objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <inlineHelpText>Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Non-critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottleneck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <description>Object to store the association between SAP Business Area, Division and Product Line</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Share_of_Wallet__c.object
<CustomObject>
    <description>Contains the Share Of Wallet (SoW) on the Account Object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Share of Wallets</relationshipLabel>
        <relationshipName>Share_of_Wallets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CY_Incremental_TO__c</fullName>
        <description>Defines the additional (incremental) turnover that Danfoss can earn on this customer in the CY (Current Year) compared to Last Year (LY)</description>
        <inlineHelpText>Defines the additional (incremental) turnover that Danfoss can earn on this customer in the CY (Current Year) compared to Last Year (LY)</inlineHelpText>
        <label>CY incremental Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CY_Non_Address_TO__c</fullName>
        <description>Defines the turnover that Danfoss cannot address because of missing product/capabilities, or does not want to address because of strategic reason</description>
        <inlineHelpText>Defines the turnover that Danfoss cannot address because of missing product/capabilities, or does not want to address because of strategic reason</inlineHelpText>
        <label>CY Non-Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Future_Addressable_TO__c</fullName>
        <label>Future Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Future_Addressable_Turnover__c</fullName>
        <description>Displays the turnover that can be earned in the future ((Total Potential TO-(Target TO CY - CY Non-Addressable TO))</description>
        <formula>Total_Potential_TO__c -(Targer_Turnover_Current_Year__c + CY_Non_Address_TO__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the turnover that can be earned in the future ((Total Potential TO-(Target TO CY - CY Non-Addressable TO))</inlineHelpText>
        <label>Future Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LY_TO_Baseline__c</fullName>
        <description>What has Danfoss or Supplier earned on this customer in the Last Year</description>
        <inlineHelpText>What has Danfoss or Supplier earned on this customer in the Last Year</inlineHelpText>
        <label>LY Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Product Line</description>
        <inlineHelpText>Product Line</inlineHelpText>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>PL01 Automatic Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪02‪ ‪Burner Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪03‪ ‪Residential Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪04‪ ‪Industrial Automation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪06‪ ‪Household Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪07‪ ‪Appliance Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪08‪ ‪District Energy Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪09‪ ‪VLT Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪10‪ ‪Venture Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪14‪ ‪High-Pressure Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪15‪ ‪Non Danfoss business areas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪16‪ ‪Water valves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪17‪ ‪Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪18‪ ‪Gearmotors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪20‪ ‪Heat Recovery Ventilation &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪21‪ ‪Electric Heating Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪22‪ ‪Heat Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪23‪ ‪Danfoss Silicon Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪24‪ ‪Heat Exchangers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪25‪ ‪Electronic Controllers &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪26‪ ‪Solar Inverters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪28‪ ‪Hydronic Balancing &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪30‪ ‪Customised Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪31‪ ‪District Energy Heat Exchangers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪32‪ ‪District Energy Heavy Duty Stations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪33‪ ‪District Energy Light Duty Stations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪34‪ ‪Floor Heating Hydronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪35‪ ‪Energy Metering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪36‪ ‪Power Stacks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪37‪ ‪Danfoss Turbocor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SoW_Total_Addressable_Turnover__c</fullName>
        <description>Displays the existing SoW (%) in the addresable customer basket, excluding the Non-Addresable TO ((Last year TO /(Total Potential TO -Current Non-Addresable TO))*100</description>
        <formula>IF(
(Total_Potential_TO__c - CY_Non_Address_TO__c) &gt;0,
LY_TO_Baseline__c /(Total_Potential_TO__c - CY_Non_Address_TO__c),
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the existing SoW (%) in the addresable customer basket, excluding the Non-Addresable TO ((Last year TO /(Total Potential TO -Current Non-Addresable TO))*100</inlineHelpText>
        <label>SoW Total Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SoW_Total_Pot_TO__c</fullName>
        <description>Displays the existing SoW (%) of the total customer basket, including the Non-addresable TO (Last year TO /Total Potential TO)*100</description>
        <formula>IF(
    Total_Potential_TO__c &gt; 0, 
    (LY_TO_Baseline__c  /  Total_Potential_TO__c),
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the existing SoW (%) of the total customer basket, including the Non-addresable TO (Last year TO /Total Potential TO)*100</inlineHelpText>
        <label>SoW Total Potential Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SoW_for__c</fullName>
        <description>Share of Wallet for...Danfoss or Supplier.</description>
        <formula>IF( ISPICKVAL(Type__c, &quot;Competitor&quot;)   ,  Competitor_Name__c ,  IF( ISPICKVAL(Type__c, &quot;Danfoss&quot;) , &quot;Danfoss&quot;, &quot;&quot;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Share of Wallet for...Danfoss or Supplier.</inlineHelpText>
        <label>SoW for</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Position__c</fullName>
        <description>The costs for changing the supplier and the suppliers position.</description>
        <inlineHelpText>The costs for changing the supplier and the suppliers position.</inlineHelpText>
        <label>Supplier Position</label>
        <picklist>
            <picklistValues>
                <fullName>1.  High Switching Cost and Entrenched Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. High Switching Cost but Competition Vulnerable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Low Switching Cost and Competition Vulnerable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Low Switching Cost and Competition Disliked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Targer_Turnover_Current_Year__c</fullName>
        <description>Displays the turnover that Danfoss aims to earn in the current year on this specific account for this specific PL (Last Year TO + CY Incremental TO)</description>
        <formula>LY_TO_Baseline__c +  CY_Incremental_TO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the turnover that Danfoss aims to earn in the current year on this specific account for this specific PL (Last Year TO + CY Incremental TO)</inlineHelpText>
        <label>CY Target Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_TO_CY__c</fullName>
        <description>Targer Turnover Current Year</description>
        <inlineHelpText>Targer Turnover Current Year</inlineHelpText>
        <label>CY Target Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Potential_TO__c</fullName>
        <description>Total Potential in terms of Turnover</description>
        <inlineHelpText>Defines the total basket of the customer (for all customer’s suppliers /all products*/all technologies)</inlineHelpText>
        <label>Total Potential Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Share Of Wallet Type</description>
        <inlineHelpText>Share Of Wallet Type</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Total</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Share of Wallet</label>
    <nameField>
        <displayFormat>SoW-{00000}</displayFormat>
        <label>Share of Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share of Wallet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountPlanShareOfWalletExtension.cls
public class AccountPlanShareOfWalletExtension {
    
    private Account_Plan__c ap;
    public ApexPages.StandardSetController setCon {get;set;}
    public ApexPages.StandardSetController setConComp {get;set;}
    public share_of_wallet__c SoWSum {get;set;}
    public share_of_wallet__c SoWSumComp {get;set;}
    
    public AccountPlanShareOfWalletExtension(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'Account__c'});
        }
        ap = (Account_Plan__c) stdController.getRecord();
        
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator([
            select Account__c, CY_Incremental_TO__c, Total_Potential_TO__c, Future_Addressable_TO__c, Future_Addressable_Turnover__c, Target_TO_CY__c, Targer_Turnover_Current_Year__c, SoW_for__c, SoW_Total_Pot_TO__c, Product_Line__c, LY_TO_Baseline__c, CY_Non_Address_TO__c, SoW_Total_Addressable_Turnover__c
            from share_of_wallet__c
            where Account__c = :ap.Account__c and SoW_for__c = 'Danfoss'
            order by Product_Line__c
        ]));
        setCon.setPageSize(3);
        setConComp = new ApexPages.StandardSetController(Database.getQueryLocator([
            select Account__c, CY_Incremental_TO__c, Total_Potential_TO__c, Future_Addressable_TO__c, Future_Addressable_Turnover__c, 
            Target_TO_CY__c, Targer_Turnover_Current_Year__c, SoW_for__c, SoW_Total_Pot_TO__c, 
            Product_Line__c, LY_TO_Baseline__c, CY_Non_Address_TO__c, SoW_Total_Addressable_Turnover__c,
            Supplier_Position__c
            from share_of_wallet__c
            where Account__c = :ap.Account__c 
            //and Type__c ='Competitor'
            order by Product_Line__c
        ]));
        setConComp.setPageSize(setConComp.getResultSize());
    }
    
    public void init() {
        calculateSum(); // Uses DML, so cannot be in constructor
    }
    
    private void calculateSum() {
        // Calculate the sums. SOQL will return them in the corporate currency
        AggregateResult arDanfossSum = [
            select sum(Total_Potential_TO__c) Total_Potential_TO__c, sum(CY_Incremental_TO__c) CY_Incremental_TO__c, sum(LY_TO_Baseline__c) LY_TO_Baseline__c, sum(CY_Non_Address_TO__c) CY_Non_Address_TO__c
            from share_of_wallet__c
            where Account__c = :ap.Account__c and SoW_for__c = 'Danfoss'
        ];
        AggregateResult arCompetitorSum = [
            select sum(Total_Potential_TO__c) Total_Potential_TO__c, sum(CY_Incremental_TO__c) CY_Incremental_TO__c, sum(LY_TO_Baseline__c) LY_TO_Baseline__c, sum(CY_Non_Address_TO__c) CY_Non_Address_TO__c
            from share_of_wallet__c
            where Account__c = :ap.Account__c 
            //and Type__c ='Competitor'
        ];
        // Store the sums in a dummy Sobject. This is required in order to use the standard currency display functionality in Visualforce.
        SoWSum = new share_of_wallet__c(
            Account__c = ap.Account__c,
            CurrencyIsoCode = [select IsoCode from CurrencyType where IsCorporate = true].IsoCode,
            Total_Potential_TO__c = (Decimal) arDanfossSum.get('Total_Potential_TO__c'),
            CY_Incremental_TO__c = (Decimal) arDanfossSum.get('CY_Incremental_TO__c'),
            LY_TO_Baseline__c = (Decimal) arDanfossSum.get('LY_TO_Baseline__c'),
            CY_Non_Address_TO__c = (Decimal) arDanfossSum.get('CY_Non_Address_TO__c'),
            //6th Feb Added to allow uniqueness field on SoW
            Type__c = 'SoWSum'
        );
        SoWSumComp = new share_of_wallet__c(
            Account__c = ap.Account__c,
            CurrencyIsoCode = [select IsoCode from CurrencyType where IsCorporate = true].IsoCode,
            Total_Potential_TO__c = (Decimal) arCompetitorSum.get('Total_Potential_TO__c'),
            CY_Incremental_TO__c = (Decimal) arCompetitorSum.get('CY_Incremental_TO__c'),
            LY_TO_Baseline__c = (Decimal) arCompetitorSum.get('LY_TO_Baseline__c'),
            CY_Non_Address_TO__c = (Decimal) arCompetitorSum.get('CY_Non_Address_TO__c'),
            //6th Feb Added to allow uniqueness field on SoW
            Type__c = 'SoWSumComp'
        );
        
        // Temporarly save the dummy Sobject, retrieve it and delete it. This ensures that formula fields are calculated.
        Savepoint sp = Database.setSavepoint();
        insert SoWSum;
        insert SoWSumComp;
        SoWSum     = [select Total_Potential_TO__c, CY_Incremental_TO__c, LY_TO_Baseline__c, Targer_Turnover_Current_Year__c, CY_Non_Address_TO__c, Future_Addressable_Turnover__c, SoW_Total_Pot_TO__c, SoW_Total_Addressable_Turnover__c from share_of_wallet__c where Id = :SoWSum.Id];
        SoWSumComp = [select Total_Potential_TO__c, CY_Incremental_TO__c, LY_TO_Baseline__c, Targer_Turnover_Current_Year__c, CY_Non_Address_TO__c, Future_Addressable_Turnover__c, SoW_Total_Pot_TO__c, SoW_Total_Addressable_Turnover__c from share_of_wallet__c where Id = :SoWSumComp.Id];
        Database.rollback(sp);
        
        //3rd Feb - UAT defect - added warning 
                if (SoWSum.Total_Potential_TO__c < SoWSum.Targer_Turnover_Current_Year__c) {                     
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Total Potential less than Target.');
            ApexPages.addMessage(myMsg);  
        } 


    }
    
    public List<share_of_wallet__c> getSoW() {
        return setCon.getRecords();
    }
    
    public List<share_of_wallet__c> getSoWComp() {
        return setConComp.getRecords();
    }
    
}