objects/Account_Division_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Division_Data_Config__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Division Data Config</label>
        <referenceTo>Account_Division_Data_Config__c</referenceTo>
        <relationshipName>Account_Attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Attributes</relationshipLabel>
        <relationshipName>Account_Division_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attribute_Set_lkp__c</fullName>
        <formula>text(Account_Division_Data_Config__r.Attribute_Set__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Set</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_lkp__c</fullName>
        <formula>Account_Division_Data_Config__r.Attribute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Marketing Attributes</relationshipLabel>
        <relationshipName>Marketing_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_lkp__c</fullName>
        <formula>Text( Account_Division_Data_Config__r.Division__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValueAgg__c</fullName>
        <formula>if (LEN(Value__c)=0,Text( ValueNumber__c ),Value__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValueNumber__c</fullName>
        <label>ValueNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Account_Division_Data_Config__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing Attribute Setup</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Account Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Attribute Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/ShowMarketingAttributesExtension.cls
public class ShowMarketingAttributesExtension {

    private final Id objId;
    private final String type;
    public List<SelectOption> statusOptions { get; set; }
    public String selectedValue { get; set; }
    public ApexPages.StandardSetController setCon { get; set; }
    public Id selectedADD { get; set; }
    
    public ShowMarketingAttributesExtension(ApexPages.StandardController stdController) {
        SObject record = stdController.getRecord();
        objId = stdController.getId();
        if (record instanceof Account) {
            type = 'Account';
        } else if (record instanceof Contact) {
            type = 'Contact';
        } else {
            System.assert(false);
        }

        statusOptions = new List<SelectOption>();
        Set<String> divisions = new Set<String>();
        for (AggregateResult ar : [select Division__c from Account_Division_Data_config__c where Division__c != null group by Division__c order by Division__c]) {
            String division = (String) ar.get('Division__c');
            statusOptions.add(new SelectOption(division, division));
            divisions.add(division);
        }
        
        selectedValue = System.currentPagereference().getParameters().get('division');
        if (selectedValue == null) {
            id uid = UserInfo.getUserId(); 
            selectedValue = [select Division__c from User where Id = :uid].Division__c;
        }
        if (!divisions.contains(selectedValue)) {
            // Invalid value, pick some valid value
            selectedValue = 'All';
        }
        
        initSetCon();
    }
    
    private void initSetCon() {
        id uid = UserInfo.getUserId(); 
        string division = selectedValue;
        if (type == 'Account') {
            if (division == 'All') {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([SELECT Id,Account__c,Attribute_lkp__c,Attribute_Set_lkp__c, name, division_lkp__c, Value__c, ValueNumber__c, ValueAgg__c FROM Account_Division_Data__c where account__c =:objId  ORDER BY division_lkp__c,Attribute_Set_lkp__c,Attribute_lkp__c]));
            } else {                    
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([SELECT Id,Account__c,Attribute_lkp__c,Attribute_Set_lkp__c, name, division_lkp__c, Value__c, ValueNumber__c, ValueAgg__c FROM Account_Division_Data__c where account__c =:objId and (division_lkp__c =:division or division_lkp__c ='All') ORDER BY division_lkp__c,Attribute_Set_lkp__c,Attribute_lkp__c]));
            }
        } else if (type == 'Contact') {
            if (division == 'All') {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([SELECT Id,Account__c,Attribute_lkp__c,Attribute_Set_lkp__c, name, division_lkp__c, Value__c, ValueNumber__c, ValueAgg__c FROM Account_Division_Data__c where contact__c =:objId ORDER BY division_lkp__c,Attribute_Set_lkp__c,Attribute_lkp__c]));
            } else {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([SELECT Id,Account__c,Attribute_lkp__c,Attribute_Set_lkp__c, name, division_lkp__c, Value__c, ValueNumber__c, ValueAgg__c FROM Account_Division_Data__c where contact__c =:objId and (division_lkp__c =:division or division_lkp__c ='All') ORDER BY division_lkp__c,Attribute_Set_lkp__c,Attribute_lkp__c]));
            }
        } else {
            System.assert(false);
        }
        setCon.setPageSize(8);
    }
    
    public List<Account_Division_Data__c> getADDs() {
        return (List<Account_Division_Data__c>) setCon.getRecords();
    }
    
    public void filterADDs() {
        initSetCon();
    }
    
    public PageReference CreateADD() {
        PageReference pr = Page.MarketingAttribute;
        pr.getParameters().put('objid', objId);
        pr.getParameters().put('type', type);
        pr.getParameters().put('retURL', getRetURL());
        return pr;
    }
    
    public PageReference EditADD() {
        PageReference pr = Page.MarketingAttribute;
        pr.getParameters().put('objid', objId);
        pr.getParameters().put('type', type);
        pr.getParameters().put('Id', selectedADD);
        pr.getParameters().put('retURL', getRetURL());
        return pr;
    }
    
    private String getRetURL() {
        if (type == 'Account') {
            return '/apex/showAccountAttributes?Id=' + objId + '&division=' + selectedValue;
        } else {
            return '/apex/showContactAttributes?Id=' + objId + '&division=' + selectedValue;
        }
    }
    
    public void DeleteADD() {
        delete new Account_Division_Data__c(Id = selectedADD);
        initSetCon();
    }
    
    public showMarketingAttributesExtension getThis() {
        return this;
    }
    
}