objects/Account_Division_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Division_Data_Config__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Division Data Config</label>
        <referenceTo>Account_Division_Data_Config__c</referenceTo>
        <relationshipName>Account_Attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Attributes</relationshipLabel>
        <relationshipName>Account_Division_Data</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Account_Division_Data_Config__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing Attribute Setup</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Account Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Attribute Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ShowMarketingAttributesExtension.cls
@isTest
public class Test_ShowMarketingAttributesExtension {
    
    static testMethod void test() {
        Account_Division_Data_config__c cfg1 = new Account_Division_Data_config__c(Division__c = 'All');
        Account_Division_Data_config__c cfg2 = new Account_Division_Data_config__c(Division__c = 'abc');
        Account_Division_Data_config__c cfg3 = new Account_Division_Data_config__c(Division__c = 'def');
        insert new List<Account_Division_Data_config__c> {cfg1, cfg2, cfg3};
        
        Account account = Test_Utility.createAccount(0);
        insert account;
        Account_Division_Data__c attr1 = new Account_Division_Data__c(Account__c = account.Id, Account_Division_Data_Config__c = cfg1.Id);
        Account_Division_Data__c attr2 = new Account_Division_Data__c(Account__c = account.Id, Account_Division_Data_Config__c = cfg2.Id);
        Account_Division_Data__c attr3 = new Account_Division_Data__c(Account__c = account.Id, Account_Division_Data_Config__c = cfg3.Id);
        insert new List<Account_Division_Data__c> {attr1, attr2, attr3};
        
        Test.startTest();
        
        ShowMarketingAttributesExtension c = new ShowMarketingAttributesExtension(new ApexPages.StandardController(account));
        System.assertEquals(3, c.getADDs().size());
        
        c.selectedValue = 'abc';
        c.filterADDs();
        System.assertEquals(2, c.getADDs().size());
        
       	System.assertNotEquals(null, c.CreateADD());
        
        c.selectedADD = attr2.Id;
        System.assertNotEquals(null, c.EditADD());
        
        c.selectedADD = attr2.Id;
        c.DeleteADD();
        System.assertEquals(2, [select Id from Account_Division_Data__c].size());
    }
    
}