objects/Account_Division_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Division_Data_Config__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Division Data Config</label>
        <referenceTo>Account_Division_Data_Config__c</referenceTo>
        <relationshipName>Account_Attributes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketing Attributes</relationshipLabel>
        <relationshipName>Account_Division_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Account_Division_Data_Config__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Set__c</fullName>
        <label>Attribute Set</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Picklist_Values__c</fullName>
        <label>Picklist Values</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>multivalue picklist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Marketing Attribute Setup</label>
    <nameField>
        <displayFormat>AA-{000000}</displayFormat>
        <label>Account Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Attribute Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_MarketingAttributeExtension.cls
@isTest
public class Test_MarketingAttributeExtension {
    
    static testMethod void test() {
        Account_Division_Data_config__c cfg1 = new Account_Division_Data_config__c(Object_Type__c = 'Account', Division__c = 'All', Attribute_Set__c = 'x', Attribute__c = '1', Type__c = 'text');
        Account_Division_Data_config__c cfg2 = new Account_Division_Data_config__c(Object_Type__c = 'Account', Division__c = 'abc', Attribute_Set__c = 'y', Attribute__c = '2', Type__c = 'picklist', Picklist_Values__c = 'i\r\nj\r\nk');
        Account_Division_Data_config__c cfg3 = new Account_Division_Data_config__c(Object_Type__c = 'Account', Division__c = 'abc', Attribute_Set__c = 'y', Attribute__c = '3', Type__c = 'text');
        Account_Division_Data_config__c cfg4 = new Account_Division_Data_config__c(Object_Type__c = 'Account', Division__c = 'def', Attribute_Set__c = 'z', Attribute__c = '4', Type__c = 'text');
        insert new List<Account_Division_Data_config__c> {cfg1, cfg2, cfg3, cfg4};
        
        Account account = Test_Utility.createAccount(0);
        insert account;
        Account_Division_Data__c attr0 = new Account_Division_Data__c(Account__c = account.Id, Account_Division_Data_Config__c = cfg3.Id);
        insert new List<Account_Division_Data__c> {attr0};
        
        Test.startTest();
        
        Account_Division_Data__c attr1 = new Account_Division_Data__c(Account__c = account.Id);
        //System.currentPagereference().getParameters().put('division', 'abc');
        System.currentPagereference().getParameters().put('objid', account.Id);
        System.currentPagereference().getParameters().put('type', 'Account');
        System.currentPagereference().getParameters().put('retURL', '/abc');
        MarketingAttributeExtension c = new MarketingAttributeExtension(new ApexPages.StandardController(attr1));
        System.assertEquals(true, c.isCreate);
        System.assertEquals(4, c.attribSetOptions.size(), c.attribSetOptions); // blank + "x" + "y" + "z"
        System.assertEquals('y', c.attribSetOptions[2].getValue());
        c.attribSetValue = 'y';
        c.getAttribValues();
        System.assertEquals(2, c.attribOptions.size()); // blank + "2" ("3" should not be available since the account already has this attribute)
        System.assertEquals('2', c.attribOptions[1].getValue());
        c.attribValue = '2';
        c.getPicklistValues();
        System.assertEquals(3, c.valueOptions.size(), c.valueOptions); // "i" + "j" + "k"
        System.assert(c.isPicklist);
        attr1.Value__c = 'test';
        PageReference pr = c.save();
        
        Test.stopTest();
        
        System.assert(ApexPages.getMessages().isEmpty());
        System.assertNotEquals(null, pr);
        
        /*System.assertEquals(3, c.getADDs().size());
        
        c.selectedValue = 'abc';
        c.filterADDs();
        System.assertEquals(2, c.getADDs().size());
        
       	System.assertNotEquals(null, c.CreateADD());
        
        c.selectedADD = attr2.Id;
        System.assertNotEquals(null, c.EditADD());
        
        c.selectedADD = attr2.Id;
        c.DeleteADD();
        System.assertEquals(2, [select Id from Account_Division_Data__c].size());*/
    }
    
}