objects/Account_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account</description>
        <inlineHelpText>Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <description>Object to store the association between SAP Business Area, Division and Product Line</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Share_of_Wallet__c.object
<CustomObject>
    <description>Contains the Share Of Wallet (SoW) on the Account Object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Share of Wallets</relationshipLabel>
        <relationshipName>Share_of_Wallets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CY_Incremental_TO__c</fullName>
        <description>Defines the additional (incremental) turnover that Danfoss can earn on this customer in the CY (Current Year) compared to Last Year (LY)</description>
        <inlineHelpText>Defines the additional (incremental) turnover that Danfoss can earn on this customer in the CY (Current Year) compared to Last Year (LY)</inlineHelpText>
        <label>CY incremental Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CY_Non_Address_TO__c</fullName>
        <description>Defines the turnover that Danfoss cannot address because of missing product/capabilities, or does not want to address because of strategic reason</description>
        <inlineHelpText>Defines the turnover that Danfoss cannot address because of missing product/capabilities, or does not want to address because of strategic reason</inlineHelpText>
        <label>CY Non-Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Future_Addressable_TO__c</fullName>
        <label>Future Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Future_Addressable_Turnover__c</fullName>
        <description>Displays the turnover that can be earned in the future ((Total Potential TO-(Target TO CY - CY Non-Addressable TO))</description>
        <formula>Total_Potential_TO__c -(Targer_Turnover_Current_Year__c + CY_Non_Address_TO__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the turnover that can be earned in the future ((Total Potential TO-(Target TO CY - CY Non-Addressable TO))</inlineHelpText>
        <label>Future Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LY_TO_Baseline__c</fullName>
        <description>What has Danfoss or Supplier earned on this customer in the Last Year</description>
        <inlineHelpText>What has Danfoss or Supplier earned on this customer in the Last Year</inlineHelpText>
        <label>LY Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Product Line</description>
        <inlineHelpText>Product Line</inlineHelpText>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>PL01 Automatic Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪02‪ ‪Burner Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪03‪ ‪Residential Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪04‪ ‪Industrial Automation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪06‪ ‪Household Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪07‪ ‪Appliance Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪08‪ ‪District Energy Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪09‪ ‪VLT Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪10‪ ‪Venture Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪14‪ ‪High-Pressure Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪15‪ ‪Non Danfoss business areas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪16‪ ‪Water valves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪17‪ ‪Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪18‪ ‪Gearmotors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪20‪ ‪Heat Recovery Ventilation &amp; Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪21‪ ‪Electric Heating Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪22‪ ‪Heat Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪23‪ ‪Danfoss Silicon Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪24‪ ‪Heat Exchangers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪25‪ ‪Electronic Controllers &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪26‪ ‪Solar Inverters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪28‪ ‪Hydronic Balancing &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪30‪ ‪Customised Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪31‪ ‪District Energy Heat Exchangers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪32‪ ‪District Energy Heavy Duty Stations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪33‪ ‪District Energy Light Duty Stations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪34‪ ‪Floor Heating Hydronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪35‪ ‪Energy Metering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪36‪ ‪Power Stacks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL‪37‪ ‪Danfoss Turbocor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SoW_Total_Addressable_Turnover__c</fullName>
        <description>Displays the existing SoW (%) in the addresable customer basket, excluding the Non-Addresable TO ((Last year TO /(Total Potential TO -Current Non-Addresable TO))*100</description>
        <formula>IF(
(Total_Potential_TO__c - CY_Non_Address_TO__c) &gt;0,
LY_TO_Baseline__c /(Total_Potential_TO__c - CY_Non_Address_TO__c),
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the existing SoW (%) in the addresable customer basket, excluding the Non-Addresable TO ((Last year TO /(Total Potential TO -Current Non-Addresable TO))*100</inlineHelpText>
        <label>SoW Total Addressable Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SoW_Total_Pot_TO__c</fullName>
        <description>Displays the existing SoW (%) of the total customer basket, including the Non-addresable TO (Last year TO /Total Potential TO)*100</description>
        <formula>IF(
    Total_Potential_TO__c &gt; 0, 
    (LY_TO_Baseline__c  /  Total_Potential_TO__c),
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the existing SoW (%) of the total customer basket, including the Non-addresable TO (Last year TO /Total Potential TO)*100</inlineHelpText>
        <label>SoW Total Potential Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SoW_for__c</fullName>
        <description>Share of Wallet for...Danfoss or Supplier.</description>
        <formula>IF( ISPICKVAL(Type__c, &quot;Competitor&quot;)   ,  Competitor_Name__c ,  IF( ISPICKVAL(Type__c, &quot;Danfoss&quot;) , &quot;Danfoss&quot;, &quot;&quot;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Share of Wallet for...Danfoss or Supplier.</inlineHelpText>
        <label>SoW for</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Position__c</fullName>
        <description>The costs for changing the supplier and the suppliers position.</description>
        <inlineHelpText>The costs for changing the supplier and the suppliers position.</inlineHelpText>
        <label>Supplier Position</label>
        <picklist>
            <picklistValues>
                <fullName>1.  High Switching Cost and Entrenched Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. High Switching Cost but Competition Vulnerable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Low Switching Cost and Competition Vulnerable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Low Switching Cost and Competition Disliked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Targer_Turnover_Current_Year__c</fullName>
        <description>Displays the turnover that Danfoss aims to earn in the current year on this specific account for this specific PL (Last Year TO + CY Incremental TO)</description>
        <formula>LY_TO_Baseline__c +  CY_Incremental_TO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the turnover that Danfoss aims to earn in the current year on this specific account for this specific PL (Last Year TO + CY Incremental TO)</inlineHelpText>
        <label>CY Target Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_TO_CY__c</fullName>
        <description>Targer Turnover Current Year</description>
        <inlineHelpText>Targer Turnover Current Year</inlineHelpText>
        <label>CY Target Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Potential_TO__c</fullName>
        <description>Total Potential in terms of Turnover</description>
        <inlineHelpText>Defines the total basket of the customer (for all customer’s suppliers /all products*/all technologies)</inlineHelpText>
        <label>Total Potential Turnover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Share of Wallet</label>
    <nameField>
        <displayFormat>SoW-{00000}</displayFormat>
        <label>Share of Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share of Wallet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountPlanShareOfWalletSupExtension.cls
public class AccountPlanShareOfWalletSupExtension {
    
    private Account_Plan__c ap;
    public ApexPages.StandardSetController setConComp {get;set;}

    public share_of_wallet__c SoWSumComp {get;set;}
    public List<ShareOfWalletProductLineWrapper> sowSums { get; set; }
    
    public AccountPlanShareOfWalletSupExtension(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'Account__c'});
        }
        ap = (Account_Plan__c) stdController.getRecord();
        
        setConComp = new ApexPages.StandardSetController(Database.getQueryLocator([
            select Account__c, CY_Incremental_TO__c, Total_Potential_TO__c, Future_Addressable_TO__c, Future_Addressable_Turnover__c, 
            Target_TO_CY__c, Targer_Turnover_Current_Year__c, SoW_for__c, SoW_Total_Pot_TO__c, 
            Product_Line__c, LY_TO_Baseline__c, CY_Non_Address_TO__c, SoW_Total_Addressable_Turnover__c,
            Supplier_Position__c
            from share_of_wallet__c
            where Account__c = :ap.Account__c 
            order by Product_Line__c
        ]));
        setConComp.setPageSize(setConComp.getResultSize());
    }
    
    public void init() {
        calculateSum(); // Uses DML, so cannot be in constructor
    }
    
    /**
     * Creates a map of SoW summary records to be used for calculation.
     */
    private Map<String, ShareOfWalletSummary> createSummaryMap(){
        Map<String, ShareOfWalletSummary> summaryMap = new Map<String, ShareOfWalletSummary>();
    
        // Extract summaries by product line
        AggregateResult[] arSum = [
            select product_line__c, sum(Total_Potential_TO__c) Total_Potential_TO__c, sum(CY_Incremental_TO__c) CY_Incremental_TO__c, sum(LY_TO_Baseline__c) LY_TO_Baseline__c, sum(CY_Non_Address_TO__c) CY_Non_Address_TO__c
            from share_of_wallet__c
            where Account__c = :ap.Account__c 
            group by product_line__c
        ];
        
        for (AggregateResult ar : arSum ) {
            ShareOfWalletSummary summary = new ShareOfWalletSummary(
                    (String) ar.get('Product_Line__c'),
                    (Decimal) ar.get('Total_Potential_TO__c'),
                    (Decimal) ar.get('CY_Non_Address_TO__c'));
            if (ar.get('Product_Line__c') != null) {
                summaryMap.put((String) ar.get('Product_Line__c'), summary); 
                System.debug(LoggingLevel.INFO, summary + ' added to map for ' + ar.get('Product_Line__c'));   
            }
            else {
                System.debug(LoggingLevel.ERROR, ' Product Line key is null: ' + ar.get('Product_Line__c'));   
            }
        }        
        return summaryMap;
    }

    
    private void calculateSum() {
        sowSums  = new List<ShareOfWalletProductLineWrapper>();
        List<Share_of_Wallet__c> sows = getSowComp();
        Map<String, ShareOfWalletSummary> summaryMap = createSummaryMap();
        
        for(Share_of_Wallet__c sow : sows) {
            ShareOfWalletProductLineWrapper wrapper = null;
            
            ShareOfWalletSummary sowSummary = summaryMap.get(sow.Product_Line__c);
            if (sowSummary != null) {
                wrapper = new ShareOfWalletProductLineWrapper(sow, sowSummary);
                sowSums.add(wrapper);
                System.debug(LoggingLevel.INFO, 'Share Of Wallet wrapper created: ' + wrapper);
            }
        }
        System.debug(LoggingLevel.INFO, 'List of Share Of Wallet wrappers: ' + sowSums);  

        //3rd Feb - UAT defect - added warning 
        /*if (SoWSum.Total_Potential_TO__c < SoWSum.Targer_Turnover_Current_Year__c) {                     
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Total Potential less than Target.');
            ApexPages.addMessage(myMsg);  
        }*/ 

    }
    
    public List<share_of_wallet__c> getSoWComp() {
        return setConComp.getRecords();
    }

    public class ShareOfWalletProductLineWrapper {
        public Share_of_Wallet__c sow { get; set; }
        public ShareOfWalletSummary summary { get; set; }
        
        ShareOfWalletProductLineWrapper(Share_of_Wallet__c sow, ShareOfWalletSummary summary) {
            this.sow = sow;
            this.summary = summary;
        }
        
        public Decimal getTotalPotentialTurnoverFraction() {
            return summary.sumTotalPotentialTurnover > 0 ?
               ((sow.LY_TO_Baseline__c / summary.sumTotalPotentialTurnover)*100).setScale(2, RoundingMode.HALF_UP) : 0;
        }
        
        public Decimal getTotalAddressableTurnoverFraction() {
            return (summary.sumTotalPotentialTurnover - summary.sumTotalAdressableTurnover) > 0 ?
                ((sow.LY_TO_Baseline__c / (summary.sumTotalPotentialTurnover - summary.sumTotalAdressableTurnover))*100).setScale(2, RoundingMode.HALF_UP) : 0;
        }
    }
    
    public class ShareOfWalletSummary {
        String productLine {get; set; }
        public Decimal sumTotalPotentialTurnover { get; set; }
        public Decimal sumTotalAdressableTurnover { get; set; }
        
        ShareOfWalletSummary(String pl, Decimal tpt, Decimal tat) {
            productLine = pl;
            sumTotalPotentialTurnover = tpt != null ? tpt : 0;
            sumTotalAdressableTurnover = tat != null ? tat : 0;
        }
    }

}