objects/Account_Merge_Request__c.object
<CustomObject>
    <fields>
        <fullName>Master_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Merge Requests</relationshipLabel>
        <relationshipName>Account_Merge_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Merged_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merged Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Merge Requests (Merged Account)</relationshipLabel>
        <relationshipName>Account_Merge_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/AccountMergeRunController.cls
public class AccountMergeRunController {
	private final Account_Merge_Request__c AMR;
    
    public AccountMergeRunController(ApexPages.StandardController controller) 
    {        
        controller.addFields(new List<String> {'Master_Account__c', 'Merged_Account__c', 'Master_Account__r.recordtype.developername'});
        this.AMR = (Account_Merge_Request__c)controller.getRecord();
    }
    
    public void runBatch() {
    	//AccountMergeRequestBatch batch = new AccountMergeRequestBatch();
    	//database.executeBatch(batch);
        if (AMR.Master_Account__c != AMR.Merged_Account__c) {
            try {
    			Account master = new Account(Id=AMR.Master_Account__c);
    			AccountMergeRequestBatch.doMerge(master, AMR.Merged_Account__c, AMR.Master_Account__r.recordtype.developername);            

            	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Accounts successfully merged'));            
            } catch (exception ex) {
                ApexPages.addmessages(ex);
            }
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Merge not possible - must be two different accounts'));                        
        }          
	}
}