objects/Account_Plan__c.object
<CustomObject>
</CustomObject>

objects/Danfoss_Tactics__c.object
<CustomObject>
    <description>Used for adding Strategies, Tactics and Actions to Account Plans</description>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Strategy and Tactics</relationshipLabel>
        <relationshipName>Strategy_and_Tactics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Strategy and Tactics</label>
    <nameField>
        <label>Danfoss Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategy and Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountPlanStrategyActionsController.cls
public with sharing class AccountPlanStrategyActionsController {
    
    public List<Task> actions {get;set;}
    
    public AccountPlanStrategyActionsController(ApexPages.StandardController controller) {
        actions = [SELECT Id, Subject, Status, ActivityDate, OwnerId, WhatId FROM Task WHERE IsClosed = False AND WhatId IN (SELECT Id From Danfoss_Tactics__c WHERE Account_Plan__c = :controller.getId()) order by WhatId];
    }
    
}