objects/Application__c.object
<CustomObject>
    <description>Cross Reference object to associate application to Market Segment (from SAP)</description>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Application_Code__c</fullName>
        <label>SAP Application Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>populated via integration</description>
        <label>SAP Application Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>populated via Sales Org trigger from Application object</description>
        <label>Market Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org__c</fullName>
        <description>SAP KNVH integration field</description>
        <externalId>true</externalId>
        <label>SAP Sales Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/Test_SalesOrgTrigger.cls
@isTest
private class Test_SalesOrgTrigger {
	static testMethod void myUnitTest() {
		Account mockAcct = Test_Utility.createAccount(1);
		insert mockAcct;
		List<Application__c> lstApplications = new List<Application__c>();
		Application__c mockAppl = new Application__c(SAP_Application_Code__c = 'ABA', Market_Segment__c = 'Agricultural Machine', Name = 'Tractors', CurrencyIsoCode = 'USD');		
		lstApplications.add(mockAppl);
		Application__c mockAppl2 = new Application__c(SAP_Application_Code__c = 'CCB', Market_Segment__c = 'Construction Machine', Name = 'Dozers', CurrencyIsoCode = 'USD');
		lstApplications.add(mockAppl2);
		if(!lstApplications.isEmpty())
			insert lstApplications;
		List<Sales_Org__c> lstSOs = new List<Sales_Org__c>();
		Sales_Org__c c1 = new Sales_Org__c (Account__c = mockAcct.Id, CurrencyIsoCode = 'USD', SAP_Sales_Org__c = '1500', Application__c = 'ABA');
		lstSOs.add(c1);
		Sales_Org__c c2 = new Sales_Org__c (Account__c = mockAcct.Id, CurrencyIsoCode = 'USD', SAP_Sales_Org__c = '1200', Application__c = 'CCB');
		lstSOs.add(c2);
		Sales_Org__c c3 = new Sales_Org__c (Account__c = mockAcct.Id, CurrencyIsoCode = 'USD', SAP_Sales_Org__c = '1200', Application__c = 'BBB');
		lstSOs.add(c3);
		if(!lstSOs.isEmpty())
			insert lstSOs;
	}
}