objects/ApprovalEmailTemplateMapping__c.object
<CustomObject>
    <fields>
        <fullName>Email_Template_ID__c</fullName>
        <defaultValue>&quot;00X&quot;</defaultValue>
        <label>Email Template ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <description>CE Competitors for header level</description>
        <inlineHelpText>Choose the main competitor you are competing against</inlineHelpText>
        <label>Main Competitor</label>
        <picklist>
            <controllingField>CE_Division__c</controllingField>
            <picklistValues>
                <fullName>(APA) Haesung</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(APA) KAORI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(APA) Meiyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Castle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Dhiren</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Dry-all</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Flowcon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Freze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) L&amp;T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Manik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Meidensha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Schaffner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Subzero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Super</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Toshiba Mitsubishsi Electric Industrial Systems Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AALBERTS (COMAP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC&amp;R-Henry Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACCOTEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC Tech (Lenze)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adlee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alfa Laval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen Bradley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Innotec</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Laval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alre</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <formula>IF( 
OR(
AND (Text(CE_Sales_model__c)=&quot;OEM&quot;,  
  OR((TODAY()-LastActivityDate)&gt;90,  
  (TODAY()-DATEVALUE(LastModifiedDate))&gt;90)),
OR((TODAY()-LastActivityDate)&gt;30,  (TODAY()-DATEVALUE(LastModifiedDate))&gt;30)),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Inactive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OLInumbers__c</fullName>
        <label>OLInumbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <label>Reason Won/Lost</label>
        <picklist>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Approx_Competitor_Price__c</fullName>
        <label>Approx Competitor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Easy Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eaton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIA Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elobau</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_Price__c</fullName>
        <description>Field to hold original Sales Price that was proposed for Replacement Business</description>
        <label>Proposed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <picklist>
            <picklistValues>
                <fullName>1010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1350</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1410</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1420</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1430</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1450</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1470</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1480</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1550</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1710</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2050</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2070</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6320</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/OpportunityManagement.cls
/******************************************************
* Author        :  Shailendra Singh (Appirio Offshore)
* Name          :  OpportunityManagement
* Date          :  09/08/2012
* Related Task  :  T-68281
* Description   :  Util Methods for functionality around opportunity
*******************************************************/
public without sharing class OpportunityManagement {
    
    public static User u = [select Id, Sales_Org__c, IsPortalEnabled from User where Id = :UserInfo.getUserId()]; 
       
    public static void getSalesOrg(List<Opportunity> lstOpptys)  //BEFORE INSERT
    {
        Set<String> setAcctIds = new Set<String>();
        for(Opportunity oppty :lstOpptys){ 
            setAcctIds.add(oppty.AccountId);
        }
        List<Account> lstAccts = [select SAP_Account_ID__c From Account where Id IN :setAcctIds];  
		Map<Id, String> mapAcctIdandSAPId = new Map<Id, String>();
        for(Account acct :lstAccts)
        { 
			if(!mapAcctIdandSAPId.containsKey(acct.Id)){
                mapAcctIdandSAPId.put(acct.Id, acct.SAP_Account_ID__c);		//it's a text field
            }         
        }
        List<Sales_Org__c> lstSO = [select Id, SAP_Account_Id__c, Name From Sales_Org__c where SAP_Account_Id__c IN :mapAcctIdandSAPId.values() and SAP_Account_Id__c != '' and SAP_Account_Id__c != null and Inactive__c = false];
		Map<String, Sales_Org__c> mapSO = new Map<String, Sales_Org__c>();
		for(Sales_Org__c so :lstSO){
			if(!mapSO.containsKey(so.SAP_Account_Id__c + u.Sales_Org__c)){
                mapSO.put(so.SAP_Account_Id__c + u.Sales_Org__c, so);
            }         
		}			
        for(Opportunity oppty : lstOpptys){
            if (!lstSO.isEmpty() && lstSO.size() == 1)  {
                for (Sales_Org__c s :lstSO)
                    oppty.Sales_Org__c = s.Id;
            }
            else if (!lstSO.isEmpty() && lstSO.size() > 1 && u.Sales_Org__c != '' && u.Sales_Org__c != null) {
				oppty.Sales_Org__c = mapSO.get(mapAcctIdandSAPId.get(oppty.AccountId)+u.Sales_Org__c).Id;
            }
            else if (!lstSO.isEmpty() && oppty.Sales_Org__c == null)
                oppty.addError('You must select a Sales Org.');
        }
    }
    
    public static void checkForCompetitorPrice(List<Opportunity> lstOpptys)  //BEFORE INSERT, BEFORE UPDATE
    {
        List <OpportunityLineItem> lstOLIs = new List <OpportunityLineItem>();
        Set<Id> setOpptyIds = new set<Id>();
        for (Opportunity oppty :lstOpptys){
            if ((oppty.StageName == 'Closed Won' || oppty.StageName == 'Closed Lost') && oppty.Reason_Won_Lost__c == 'Price'){
                setOpptyIds.add(oppty.Id); 
            }
        }
        lstOLIs = [Select OpportunityId, Competitor__c, Approx_Competitor_Price__c From OpportunityLineItem Where OpportunityId IN :setOpptyIds and (Approx_Competitor_Price__c = null or Competitor__c = null)];
        setOpptyIds.clear();
        if (!lstOLIs.isEmpty()) {
            for (OpportunityLineItem oli :lstOLIs){
                setOpptyIds.add(oli.OpportunityId);
            }
        }
        if (!setOpptyIds.isEmpty()){
            List<Opportunity> lstOpps = [select Id From Opportunity where Id IN :setOpptyIds];
            for (Opportunity oppty :lstOpptys) {
            	oppty.addError('All products for this opportunity must have an approximate competitor price and competitor entered before the opportunity can be saved in a closed stage with a reason of "Price"');
            }   
        }
    }
    
    public static void CompilePartNumbersFromOLI(List<Opportunity> lstOpptys)  //BEFORE UPDATE
    {
        List <OpportunityLineItem> lstOLIs = new List <OpportunityLineItem>();
        Map<Id, List <string>> mapOLIs = new Map<Id, List <string>>(); 
        for (Opportunity oppty :lstOpptys){
            if(!mapOLIs.containsKey(oppty.Id)){
                mapOLIs.put(oppty.Id, new List<string>());
            }         
        }
        lstOLIs = [select OpportunityId, PricebookEntry.ProductCode, Customer_Material_Number__c From OpportunityLineItem where OpportunityId IN :mapOLIs.keySet()];
		if (!lstOLIs.isEmpty()){
	    	for (OpportunityLineItem oli :lstOLIs){
				mapOLIs.get(oli.OpportunityId).add(oli.PricebookEntry.ProductCode);
				if(oli.Customer_Material_Number__c != '' && oli.Customer_Material_Number__c != null)
					mapOLIs.get(oli.OpportunityId).add(oli.Customer_Material_Number__c);
			}
			if (!mapOLIs.values().isEmpty()){
				for(Opportunity oppty :lstOpptys){
					oppty.OLInumbers__c = '';
					List<String> lstStrMaterials = mapOLIs.get(oppty.Id);
	                for (string s :lstStrMaterials){
						if(s != null){
		                    if (oppty.OLInumbers__c == '' || oppty.OLInumbers__c == null)
								oppty.OLInumbers__c = s + ', ';
		                    else if(!oppty.OLInumbers__c.contains(s))
								oppty.OLInumbers__c += s + ', ';
						}
					}
				}	
			}
		}		
		else
			for (Opportunity oppty :lstOpptys)
				if(mapOLIs.get(oppty.Id).isEmpty())
					oppty.OLInumbers__c = '';
    }
    
    public static void notifyOpportunityAccountTeam(Set<ID> opptyIds)  //AFTER INSERT (only if a portal user)
    {
        Map<ID,Contact> userContactMap = new Map<ID,Contact>();
        if(!u.isPortalEnabled){ // Opportunity is not created By an portal User
            return;
        }
		Id templateId = ApprovalEmailTemplateMapping__c.getInstance('New Opportunity from PartnerLink').Email_Template_ID__c;
        List<Opportunity> oppList = [Select ID,AccountID,Account.OwnerID,Account.Owner.Name,Account.Owner.FirstName,Account.Owner.LastName,Account.Owner.Email From Opportunity Where ID IN :opptyIds];
        for(Opportunity opp : oppList){
            if(opp.AccountId != null){ 
                Contact contact = new Contact(FirstName = opp.Account.Owner.FirstName,LastName = opp.Account.Owner.LastName,Email = opp.Account.Owner.Email);
                userContactMap.put(opp.Account.OwnerID,contact);                        
            }
            
            if(!userContactMap.isempty()){
                insert userContactMap.values();
            }
        }
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(Opportunity opp : oppList){
            if(opp.AccountId != null){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTargetObjectId(userContactMap.get(opp.Account.OwnerId).Id);
				mail.setSaveAsActivity(false);
                mail.setWhatId(opp.Id);
                mail.setTemplateId(templateId);    
                emails.add(mail);
            }
        }
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails,false);
        }
        // After sending Email delete Contact records;
        if(!userContactMap.isempty()){
            delete userContactMap.values();
        }           
    }
    
    public static void handleReplacementBusiness(List<Opportunity> lstOpptys, map<Id, Opportunity> mapOpptys)  //AFTER UPDATE
    {
        Set<Id> setOpptyIds = new Set<Id>();
        for (Opportunity oppty : lstOpptys){
            Opportunity opptyOld = mapOpptys.get(oppty.Id);
            if (opptyOld.Type == 'Replacement Business' && oppty.Type == 'Existing Business'){
                setOpptyIds.add(oppty.Id);
            }
        }
        List<OpportunityLineItem> OLIs = [select UnitPrice, Proposed_Price__c from OpportunityLineItem where OpportunityId IN :setOpptyIds];        
        for(OpportunityLineItem oli :OLIs){           
            oli.Proposed_Price__c = oli.UnitPrice;
            oli.UnitPrice = 0.00;
        }
        update OLIs;
    }
    
    @future
    public static void updateOpptyOwner(Set<Id> setOpptyIDs)  //AFTER INSERT
    {
        if (u.isPortalEnabled) {
            List<Opportunity> oppList = [Select ID, AccountId, Account.OwnerID From Opportunity Where ID IN :setOpptyIDs];
            for(Opportunity oppty :oppList){                
                oppty.ownerId = oppty.Account.OwnerId;
                //Create Account Team Member for Partner Portal User
                List<AccountTeamMember> members = new List<AccountTeamMember>();
                AccountTeamMember member = new AccountTeamMember();
                member.AccountId = oppty.AccountId;
                member.TeamMemberRole = 'Partner';
                member.UserId = Userinfo.getUserId();
                members.add(member);
                
                if (!members.isEmpty()) {
                    insert members;
                }
                List<AccountShare> shares = [select Id, OpportunityAccessLevel, RowCause, UserOrGroupId from AccountShare 
                                            where AccountId = :oppty.AccountId and UserOrGroupId = :Userinfo.getUserId()];
                // set Partner team members access as follows: ACCOUNT: Read (default), CONTACT: Read (preferrably Read/Write for Prospect Accounts - if only one option is available default to Read/Write),                           OPPORTUNITY Read/Write, CASE: Private (default)
                for (AccountShare share : shares)  {
                    share.OpportunityAccessLevel = 'Edit';
                    share.ContactAccessLevel = 'Edit';
                }
                update shares;  
            }
            if(!oppList.isEmpty())
                update oppList; 
        }   
    }   
}