objects/Associated_Account__c.object
<CustomObject>
    <description>Junction Object to Relate Project Opps to Many Accounts</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select an Account and press save to add contact person in the next page. Use field :Set Contacts</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Associated_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stakeholder Mapping</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholder Mapping</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>false</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CE_Division__c</fullName>
        <description>Used to make Picklists Divisional dependent</description>
        <inlineHelpText>Used to make Picklists Divisional dependent</inlineHelpText>
        <label>Danfoss Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Sales_model__c</fullName>
        <description>Sales model is used to identify which of the DBS sales models the Opportunity belongs to.</description>
        <inlineHelpText>Sales model is used to identify which of the DBS sales models the Opportunity belongs to.</inlineHelpText>
        <label>Sales model</label>
        <picklist>
            <picklistValues>
                <fullName>End user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>CE used for Project site adress</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <formula>IF( 
OR(
AND (Text(CE_Sales_model__c)=&quot;OEM&quot;,  
  OR((TODAY()-LastActivityDate)&gt;90,  
  (TODAY()-DATEVALUE(LastModifiedDate))&gt;90)),
OR((TODAY()-LastActivityDate)&gt;30,  (TODAY()-DATEVALUE(LastModifiedDate))&gt;30)),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Inactive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project_Opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Sub_Account__c</field>
                <operation>equals</operation>
                <valueField>Sales_Area__c.Sub_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CE_Opportunity</fullName>
        <active>true</active>
        <businessProcess>C%26E Sales Process</businessProcess>
        <label>Climate and Energy Open Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project_Opportunity</fullName>
        <active>true</active>
        <businessProcess>C%26E Sales Process</businessProcess>
        <label>Project Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>TEXT(Sub_Account__r.Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Area_Master__r.Sales_Area__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration Controls</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/SearchOpportunityExtension.cls
public without sharing class SearchOpportunityExtension {
    /*
     *	      
     *  2016.06.09 - (AHO) 
     *   - Changed class to run without sharing to prevent creation of duplicates across regions
     *   - additional criterias on search SOQL account.business_org__c='Climate and Energy'
     *      
     */
    
    public String newProject {get;set;}
    public boolean isProjectOpp {get;set;}
    private Opportunity opp;
    public string myOpportunities {get;set;}
    public string myTeamOpportunities {get;set;}
    private final string division;
    public Id selectedOpportunity { get; set; }
    public ApexPages.StandardSetController setCon {get;set;}
    public Boolean navigateToEditOpp {get;set;}
    public ApexPages.StandardSetController contactsCon {get;set;}
    public Id selectedContactId {get;set;}
    public List<Sales_Area__c> AvailableSalesAreas {get;set;}
    public ID selectedSalesArea {get;set;}
    
    public SearchOpportunityExtension(ApexPages.StandardController stdController) {
        newProject = '';
        navigateToEditOpp = false;
        //get the page parameters        
        string retURL = ApexPages.currentPage().getParameters().get('retURL');
        ID accID = ApexPages.currentPage().getParameters().get('accID');
        String projOpp = ApexPages.currentPage().getParameters().get('projOpp');
        ID projID = ApexPages.currentPage().getParameters().get('projID');
        //determine if this is a project opportunity or not
        isProjectOpp = projOpp == 'TRUE';
        //get the opportunity & set the AccountID 
        opp = (Opportunity) stdController.getRecord();
        opp.Name = '';
        opp.Project_Opportunity__c = projID;
        opp.AccountId = accID;
        
        // Aded July 2 - 2015 - Allan Hoybye @Salesforce.com
        // Get user currency - for defaulting
        if (opp.AccountId != null) {
            opp.CurrencyIsoCode = [select CurrencyIsoCode from Account where Id = :opp.AccountId].CurrencyIsoCode;
        }
        //get the user division & if it is Heating Solutions, default to a Project
        division = [Select division__c from User where Id = :Userinfo.getuserId()].division__c;
        // if (division == 'Heating Solutions'){isProjectOpp=true;}
        
        //display the enhanced lists.....
        Database.QueryLocator ql = Database.getQueryLocator([select Id from Opportunity where Id = :opp.id]);
        ApexPages.StandardSetController setController = new ApexPages.StandardSetController(ql);
        System.SelectOption[] listViews = setController.getListViewOptions();
        for (System.SelectOption listView : listViews) {
            if (listView.getLabel() == 'My Opportunity (team)') {
                myTeamOpportunities = listView.getValue();
                myTeamOpportunities = myTeamOpportunities.left(15);
            }
        }
        for (System.SelectOption listView : listViews) {
            if (listView.getLabel() == 'My Opportunities...') {
                myOpportunities = listView.getValue();
                myOpportunities = myOpportunities.left(15);
            } 
        }
    }
    
    public void showProjectFields() {
        // don't change anything, just rerender
    }
    
    //if the user hasn't searched then they can't create a new Opportunity
    public boolean getcreatepossible() {
        return opp.Name != '';
    }
    
    public pagereference GoToAccount() {
        //provide navigation for the searched records
        PageReference pageRef = new PageReference('/'+selectedOpportunity);
        return pageRef;
    }
    
    public void CreateNew() {
        goToContactSelection();
    }
    
    public void search() {
        
        //make sure that the users have filled in what they need to 
        if (opp.Name == '') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, 'Please enter Name '));
            return;
        }
        
        //do the query & get the list of matching opps
        String term = '%' + opp.Name + '%';
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator([select id, Project_Opportunity__c, name, Account.name ,Amount, stagename, CE_division__c, closedate, owner.name, City__c, Country__c from opportunity where Account.Business_Org__c='Climate and Energy' AND Account.Inactive__c=false AND name like :term limit 20]));
        setCon.setPageSize(8);
        
        //if there are no matches, create the opportunity & project
        if (!setCon.getRecords().isEmpty()) {
            return;
        }
        
        goToContactSelection();
    }
    
    private void goToContactSelection() {
        String fields = 'Id';
        for (FieldSetMember field : SObjectType.Contact.FieldSets.CreateOpportunityFields.getFields()) {
            fields += ', ' + field.getFieldPath();
        }
        String accId = opp.AccountId;
        //contactsCon = new ApexPAges.StandardSetController(Database.getQueryLocator('select ' + fields + ' from Contact where AccountId = :accId and Inactive_Contact__c = false order by CreatedDate desc'));
		contactsCon = new ApexPAges.StandardSetController(Database.getQueryLocator('select ' + fields + ' from Contact where AccountId = :accId and Inactive_Contact__c = false order by name'));
        contactsCon.setPageSize(50);
    }
    
    public List<Contact> getContactsList() {
        return (List<Contact>) contactsCon.getRecords();
    }
    
    public List<opportunity> getResults() {
        return (List<opportunity>) setCon.getRecords();
    }
    
    public void selectSalesArea() {
        String soqlFields = 'Id';
        for (FieldSetMember field : SObjectType.Sales_Area__c.FieldSets.PricesForOpportunityColumns.getFields()) {
            soqlFields += ', ' + field.getFieldPath();
        }
        ID accountId = opp.AccountId;
        AvailableSalesAreas = Database.query('select ' + soqlFields + ' from Sales_Area__c where Sub_Account__r.Account__c = :accountId');
        if (AvailableSalesAreas.isEmpty()) {
            selectedSalesArea = null;
            AvailableSalesAreas = null;
            contactsCon=null;
            createOppandProject();
            return;
        }
        if (AvailableSalesAreas.size() == 1) {
            selectedSalesArea = AvailableSalesAreas[0].Id;
            AvailableSalesAreas = null;
            contactsCon=null;
            createOppandProject();
            return;
        }
    }
    
    public void createOppandProject() {
        Savepoint sp = Database.setSavepoint();
        if (isProjectOpp) {
            //if it's a project they need to create a new one or select a pre-existing one
            if (opp.Project_Opportunity__c == null) {
                if (newProject == '') {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'For Project Opportunities select an existing Project, or create a new one'));
                    return;
                }
                Project_opportunity__c p = new Project_opportunity__c(
                    Name = newProject
                );
                try {
                    insert p;
                } catch (DMLException ex) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Failed to Create Project...' + ex));       
                    Database.rollback(sp);
                    return;
                }
                opp.Project_Opportunity__c = p.id;
            }
        } else {
            opp.Project_Opportunity__c = null;
        }
        //next get the record Type 
        String recTypeDevName = isProjectOpp ? 'Project_Opportunity' : 'CE_Opportunity';
        String recType = [select Id from RecordType where DeveloperName = :recTypeDevName and SobjectType = 'Opportunity'].Id;
        //check that the user is from Heating Solutions & set salesmodel to Project  
        if (division == 'Heating Solutions') {
            opp.CE_Sales_model__c = 'Project';
        }
        //complete the rest of the required values 
        // JPK 05-02-2015 - UAT #59     
        //opp.Amount = 0;
        opp.CE_Status__c = 'Open';
        opp.CE_Phase__c = 'Identification';
        opp.RecordTypeId = recType;
        opp.StageName = 'Open';
        opp.CE_Division__c = division;
        opp.Type = 'New Business';
        opp.Contact__c = selectedContactId;
        // Removed July 2 - 2015 - Allan Hoybye @Salesforce.com
        //if (opp.AccountId != null) {
        //    opp.CurrencyIsoCode = [select CurrencyIsoCode from Account where Id = :opp.AccountId].CurrencyIsoCode;
        //}
        opp.Sales_Area__c = selectedSalesArea;
        if (opp.Sales_Area__c != null) {
            opp.Sub_Account__c = [select Sub_Account__c from Sales_Area__c where Id = :opp.Sales_Area__c].Sub_Account__c;
        }
        //try to insert the opportunity   
        try {
            insert opp;
        } catch (DMLException ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Failed to Create Opportunity...' + ex));
            Database.rollback(sp);
            return;
        }
        
        Associated_Account__c aa = new Associated_Account__c(
            Associated_Account__c = opp.AccountId,
            Contact__c = selectedContactId,
            Project_Opportunity__c = opp.Id,
            Type_of_Association__c = 'Main Account'
        );
        
        try {
            insert aa;
        } catch (DMLException ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Failed to Create Opportunity...' + ex));
            Database.rollback(sp);
            return;
        }
        
        navigateToEditOpp = true;
    }
    
}