objects/Associated_Account__c.object
<CustomObject>
    <description>Junction Object to Relate Project Opps to Many Accounts</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select an Account and press save to add contact person in the next page. Use field :Set Contacts</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Associated_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stakeholder Mapping</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholder Mapping</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>false</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ConfigitQuoteSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ServerHost__c</fullName>
        <defaultValue>&quot;10.3.29.212&quot;</defaultValue>
        <label>Server Host</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ServerProtocol__c</fullName>
        <defaultValue>&quot;http&quot;</defaultValue>
        <label>ServerProtocol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Configit Quote Settings</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Originating_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Originating Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project_Opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Opportunity__c.object
<CustomObject>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Originating_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Case</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/InitQuoteController.cls
public class InitQuoteController {

    private Case c;
    public string url {get; set;}
    public string objectType {get; set;}
    public string objectId {get; set;}
    
    public  InitQuoteController ()
    {
        objectType = ApexPages.currentPage().getParameters().get('type');  
        objectId = ApexPages.currentPage().getParameters().get('oid');  
        url='';
    }
   
    @RemoteAction  
    public static String createOpptyAndRedirect (string otype, string oid)
    {
        Id pb2Id= null; 
        string returnUrl='';
        pb2Id=[SELECT Id FROM Pricebook2 WHERE Name='Climate and Energy'].Id;
        Opportunity o = new Opportunity();
        o = new Opportunity();                
        if (otype.equalsIgnoreCase('CONTACT')) {
            Contact contact = [SELECT id, accountid, account.CurrencyIsoCode, CurrencyIsoCode FROM Contact WHERE id=:oid limit 1];
            if (contact.accountid!=null) {
                o = QuoteBusiness.createShadowOpportunity('Price Request', contact.accountid, contact.account.CurrencyIsoCode, null, pb2Id);
            	o.Contact__c = contact.id;
            } 
                                    
        } else if (otype.equalsIgnoreCase('CASE')) {
            Case c = [SELECT id, accountid, account.CurrencyIsoCode, Subject, ContactId, CurrencyIsoCode FROM Case WHERE id=:oid limit 1];
            
            if (c.accountid!=null) {
                o = QuoteBusiness.createShadowOpportunity(c.Subject, c.accountid, c.account.CurrencyIsoCode, null, pb2Id);                              
            } else {
                o = QuoteBusiness.createShadowOpportunity(c.Subject, null, c.CurrencyIsoCode, null, pb2Id);
            }
            o.Contact__c = c.ContactId; 
            o.Originating_Case__c = c.Id;            	                      	                        
        } /* else if (otype.equalsIgnoreCase('STAKEHOLDER')) {
            Associated_Account__c sh = [SELECT id, Associated_Account__c, Contact__c, CurrencyIsoCode, Project_Opportunity__r.name FROM Associated_Account__c WHERE id=:oid limit 1];
            o.AccountId = sh.Associated_Account__c;
            o.Contact__c = sh.contact__c;
            o.name = sh.Project_Opportunity__r.name;
            o.CurrencyIsoCode = sh.CurrencyIsoCode;
        } */
                
        insert o;
        
        ConfigitQuoteSettings__c mc = ConfigitQuoteSettings__c.getOrgDefaults();
        //ConfigitQuoteSettings__c mc = ConfigitQuoteSettings__c.getInstance(UserInfo.getProfileId());
        returnUrl = mc.ServerProtocol__c + '://' + mc.ServerHost__c + '/Configit/Quote/api/ext/Opportunity/create/' + UserInfo.getUserId() +  '/' + o.AccountId + '/' + o.Id; 
        //PageReference pageRef = new PageReference(url);		
		//pageref.setRedirect(true);		
        return returnUrl;
        
    }
    
    

    
}