objects/Associated_Account__c.object
<CustomObject>
    <description>Junction Object to Relate Project Opps to Many Accounts</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_of_Association__c</fullName>
        <description>&quot;Main Account&quot; and &quot;Previous Main Account&quot; - are values used by business logic and cannot be removed or changed</description>
        <label>Type of Association</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultancy company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor/Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner/Investor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Building company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Main Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System integrator company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical inspection</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stakeholder Mapping</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholder Mapping</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project_Opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Opportunity__c.object
<CustomObject>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/Test_SetAsMainAccountExtension.cls
@isTest
public class Test_SetAsMainAccountExtension {
    
    static testMethod void test() {
        Account account1 = Test_Utility.createAccount(1);
        Account account2 = Test_Utility.createAccount(2);
        insert new List<Account> {account1, account2};
        Opportunity opportunity = Test_Utility.createOpportunity(account1.Id, 0);
        opportunity.Sales_Org__c = null;
        insert opportunity;
        Associated_Account__c aa = new Associated_Account__c(Associated_Account__c = account2.Id, Project_Opportunity__c = opportunity.Id);
        insert aa;
        
        Test.startTest();
        
        SetAsMainAccountExtension c = new SetAsMainAccountExtension(new ApexPages.StandardController(aa));
        c.gotoOpp();
        
        Test.stopTest();
        
        System.assertEquals(account2.Id, [select AccountId from Opportunity].AccountId);
        System.assertEquals('Main Account', [select Type_of_Association__c from Associated_Account__c where Id = :aa.Id].Type_of_Association__c);
    }
    
}