objects/Associated_Account__c.object
<CustomObject>
    <description>Junction Object to Relate Project Opps to Many Accounts</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select an Account and press save to add contact person in the next page. Use field :Set Contacts</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Associated_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Associated_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Association__c</fullName>
        <description>&quot;Main Account&quot; and &quot;Previous Main Account&quot; - are values used by business logic and cannot be removed or changed</description>
        <label>Type of Association</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultancy company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor/Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner/Investor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Building company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Main Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System integrator company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical inspection</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stakeholder Mapping</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholder Mapping</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project_Opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Sub_Account__c</field>
                <operation>equals</operation>
                <valueField>Sales_Area__c.Sub_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Opportunity__c.object
<CustomObject>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Area_Master__r.Sales_Area__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
</CustomObject>

classes/SetAsMainAccountExtension.cls
public class SetAsMainAccountExtension {
    
    private ID aaid; 
    
    public SetAsMainAccountExtension(ApexPages.StandardController controller) {
        aaid = controller.getId();
    }
    
    public PageReference gotoOpp() {
        // Associated_Account__c assoc_acc = (Associated_Account__c)controller.getRecord();
        //get the associated account fields - aa is the account you want to make the account on the opp
        Associated_Account__c aa = [select Associated_Account__c, SubAccount__c, Contact__c, Project_Opportunity__c, Name, Id from Associated_Account__c where Id = :aaid];
        //the parent opp is the parent opportunity
        Opportunity parentopp = [select Id, name, Sub_Account__c, Contact__c, AccountId from Opportunity where Id = :aa.Project_Opportunity__c];
        
        
        List<Associated_Account__c> preExistingAA = [
            select Associated_Account__c, SubAccount__c, Contact__c, Type_of_Association__c
            from Associated_Account__c
            where Associated_Account__c = :parentopp.AccountId and Project_Opportunity__c = :aa.Project_Opportunity__c
        ];       
        if (preExistingAA.isEmpty()) {
            Associated_Account__c newAA = new Associated_Account__c();
            newAA.Project_Opportunity__c = aa.Project_Opportunity__c;
            newAA.Associated_Account__c = parentopp.AccountId;
            newAA.Contact__c = parentopp.Contact__c;
            newAA.SubAccount__c = parentopp.Sub_Account__c;
            newAA.Type_of_Association__c = 'Previous Main Account';
            insert newAA;
        } else {
            preExistingAA[0].Type_of_Association__c = 'Previous Main Account';
            preExistingAA[0].Contact__c = parentopp.Contact__c;
            preExistingAA[0].SubAccount__c = parentopp.Sub_Account__c;
            update preExistingAA[0];
        }
        
        parentopp.AccountId = aa.Associated_Account__c;
        parentopp.Sub_Account__c = aa.SubAccount__c;
        parentopp.Contact__c = aa.Contact__c;
       
        //Added Feb 11th - auto set the Sales Area if available from Associated Account
        if (aa.SubAccount__c != null)
        {
            List<Sales_Area__c> listSA =[select id from Sales_Area__c where Sub_Account__c =:aa.SubAccount__c limit 1];
            if(listSA.size() == 1){parentopp.Sales_Area__c = listSA[0].id;}
            else
            {parentopp.Sales_Area__c = null;}
        }
        else{parentopp.Sales_Area__c = null;}
                
        update parentopp;
        
        aa.Type_of_Association__c = 'Main Account';
        update aa;
        
        return new PageReference('/' + parentopp.id);
    }
    
}