objects/Associated_Account__c.object
<CustomObject>
    <description>Junction Object to Relate Project Opps to Many Accounts</description>
    <fields>
        <fullName>Associated_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select an Account and press save to add contact person in the next page. Use field :Set Contacts</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Associated_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Stakeholder Mapping</relationshipLabel>
        <relationshipName>Associated_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stakeholder Mapping</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stakeholder Mapping</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>false</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/setContactonStakeholderMappingExtension.cls
public class setContactonStakeholderMappingExtension {

    public Associated_Account__c aa;
    public ApexPages.StandardSetController setCon {get;set;}
    public Id selectedContactId {get;set;}
    public Boolean navigateToAA {get;set;}
        
    public setContactonStakeholderMappingExtension(ApexPages.StandardController stdController) {
        aa = (Associated_Account__c) stdController.getRecord();
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator([select account.name, email, firstname, lastname , accountid from contact where accountid in (select Associated_Account__c from Associated_Account__c where id =:aa.id)]));
        setCon.setPageSize(15);
        if(setCon.getResultSize() == 0) {
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'No Contacts for the selected Account');
        ApexPages.addMessage(myMsg);  
            }
    }
  
  public List<contact> getResults() {
        return (List<contact>) setCon.getRecords();
    }
    
    public void updatewithContact() {
        aa.Contact__c = selectedContactId;
        update aa;
        navigateToAA = true;
       
    }
        public void navigatewithoutContact() {
        navigateToAA = true;
       
    }
                                                                               }