objects/Authorized_Product__c.object
<CustomObject>
    <description>Products authorized by distributor</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Products_Authorized</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>IF(
 ISPICKVAL( Account__r.Channel__c , &quot;Distributor&quot;), &quot;Distributor&quot;,
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <label>Authorized Product</label>
    <nameField>
        <displayFormat>APR-{0000000}</displayFormat>
        <label>Authorized Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Exclusive_Material__c.object
<CustomObject>
    <description>This will serve as a junction object between Account and Product2.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exclusive Material</label>
    <nameField>
        <displayFormat>EPR-{0000000}</displayFormat>
        <label>Exclusive Material Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <formula>IF( 
OR(
AND (Text(CE_Sales_model__c)=&quot;OEM&quot;,  
  OR((TODAY()-LastActivityDate)&gt;90,  
  (TODAY()-DATEVALUE(LastModifiedDate))&gt;90)),
OR((TODAY()-LastActivityDate)&gt;30,  (TODAY()-DATEVALUE(LastModifiedDate))&gt;30)),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Inactive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <description>This field shows the customer machine model number.</description>
        <inlineHelpText>Enter the customer&apos;s machine model.  Example: 820C, 810C, etc.</inlineHelpText>
        <label>Machine Model Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <description>Object to store the association between SAP Business Area, Division and Product Line</description>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydro Gear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schwarzmueller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <formula>Opportunity.Sales_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <picklist>
            <picklistValues>
                <fullName>1010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1350</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1410</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1420</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1430</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1450</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1470</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1480</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1550</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1710</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2050</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2070</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6320</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/AddProducts.cls
/**************************************************************************************
Class          : 
Developed by   : Jacqueline Ison
Description    : Product picker VF page extension controller to populate Opportunity Pricebook
Related Task   : 
****************************************************************************************/
public without sharing class AddProducts
{
    public Opportunity opportunity{get;set;}
    public Quote quote{get;set;}
    public Machine_Model__c machine{get;set;}
    
    public Authorized_Product__c[] ap = new List<Authorized_Product__c>();
    public PricebookEntry pbe;
    public Id accountId;
    public String sObjectId;
	public String subsystem;
    public Boolean isOpportunity{get;set;}
    public Boolean isMachine{get;set;}
    public Boolean isPortalUser;
    List<String> lstPLCode = new List<String>(); 
    List<Id> lstExclusiveProducts = new List<Id>();
    Boolean pageLoad;
    public Boolean limitExceeded{get;set;}
    public Boolean validExclusive{get;set;}
    Final Integer RECORD_LIMIT = 100;
    User curuser = getCurrentUserData();   
	public String salesorg {get;set;}
   	public List<Sales_Org__c> lstSOs = new List<Sales_Org__c>();
    public String Name{get;set;}
    public String ProductCode{get;set;}
    public String Model_Code{get;set;}
    public String Family{get;set;}
    public String ProductSet{get;set;}
    public String ProductLine{get;set;}	
    public Decimal SAPPrice;
    public String SAPCurrency;	
    public Boolean isSAPError{get;set;}
    public String sapErrMsg{get;set;}
	public Boolean priceretrieved{get;set;}
    public String materialNum;  
   
    public AddProducts() {
      initializePage();                  
    } 
     
     public void initializePage() {
       isOpportunity = false;
       isMachine = false;
       limitExceeded = false;
       validExclusive = true;
       pageLoad = true;
	   isSAPError = false;
       sObjectId = ApexPages.currentPage().getParameters().get('id');
	   subsystem = ApexPages.currentPage().getParameters().get('subsystem');
		 if(sObjectId.startsWith('006') ) {
         isOpportunity = true;
         opportunity = [Select Id, Account.RecordType.Name, Account.Account_Group__c, Account.Channel__c, Account.SAP_Account_ID__c, Account.Parent.SAP_Account_ID__c, PriceBook2Id,CurrencyIsoCode,Name,Pricebook2.Name,AccountId FROM Opportunity Where Id = :sObjectId];
         accountId = opportunity.AccountId;
       } 
       else if(sObjectId.startsWith('0Q0') ) {
         quote = [SELECT Id, Opportunity.Account.RecordType.Name, Opportunity.Account.Account_Group__c, Opportunity.Account.Channel__c, Opportunity.Account.Parent.SAP_Account_ID__c, Opportunity.Account.SAP_Account_ID__c, PriceBook2Id,CurrencyIsoCode,Name,Pricebook2.Name,Opportunity.AccountId FROM Quote Where Id = :sObjectId];
         accountId = quote.Opportunity.AccountId;
       }
       else if(sObjectId.startsWith('a0Q')) {
		 isMachine = true;
       	 machine = [Select Id, Account__r.RecordType.Name, Account__r.Account_Group__c, Account__r.SAP_Account_ID__c, Account__r.Channel__c, Account__r.Parent.SAP_Account_ID__c, CurrencyIsoCode, Name, Account__c FROM Machine_Model__c Where Id = :sObjectId];  
         accountId = machine.Account__c;
	     lstSOs = [select Id, Name from Sales_Org__c where Account__c = :accountId and Inactive__c = false];
	    }
       this.isPortalUser = false;
       this.isAscending = false;
       this.sortField = 'Product2.Name';    
       searchProduct = new Product2();
       lstPriceBookEntry = new List<PriceBookEntry>();
     }
     
     public void autorun() {   
        // set the pricebook in opportunity and quote
       if((isOpportunity && opportunity.Pricebook2Id==null) || (!isOpportunity && !isMachine && quote.Pricebook2Id==null)) {
         String businessOrg = curuser.Business_Org__c;
         if(businessOrg == 'Integrated') {
           businessOrg = 'Danfoss';
         } 
         Pricebook2 pb;            
         List<PriceBook2> lstPriceBook = [Select Id,Name from PriceBook2 where Name = :businessOrg];
         if(!lstPriceBook.isEmpty()) {
           pb = lstPriceBook[0];
         }
         try{
           if(isOpportunity) {
             opportunity.Pricebook2Id = pb.Id;           
             update opportunity;           
           }
           else {
             quote.Pricebook2Id = pb.Id;
             update quote; 
           }
         }    
         catch (DmlException e){
           ApexPages.addMessages(e);
         }        
       }                        
    }
  
   private void getAuthorizedProducts() {
     if(curuser.UserType == 'Portal'|| curuser.UserType == 'PowerPartner') { 
       this.isPortalUser = true;
       for(Authorized_Product__c ap : [select Product_Line__r.PL_Code__c from Authorized_Product__c where Account__c =: curuser.Contact.AccountId]) {
         if(ap.Product_Line__r.PL_Code__c != null) {
           lstPLCode.add(ap.Product_Line__r.PL_Code__c);
         }
       }
     }
   } 
   
   private void getExclusiveMaterials() {    
     for(Exclusive_Material__c exProd : [select Product__c from Exclusive_Material__c WHERE isDeleted__c = false and Account__c =: accountId]) {
       if(exProd.Product__c != null) {
         lstExclusiveProducts.add(exProd.Product__c);
       }
     }
   }
  
   private User getCurrentUserData() {
     return [Select Contact.AccountId, Business_Org__c, UserType from User where Id = :UserInfo.getUserId()];
   }
  //-----------------------------------------------------------------------------------//
    
  private List<PriceBookEntry> lstPriceBookEntry;  
  
  public String selectedProducts {get;set;}
  
  public Product2 searchProduct {get;set;}
  
  public List<PriceBookEntry> getAllEntries() {
    return this.lstPriceBookEntry;
  }
  
  /****************************************************Sorting******************************************************/
  
  //----------------Sorting variables---------------------//
  private String previousSortField = 'Name';
  
  public string sortField {
    get;
    set {
      this.previousSortField = sortField;
      this.sortField = value;
      setAscendingStatus();
    }
  } 
  
  private void setAscendingStatus() {
    if(previousSortField == sortField) {
      isAscending = !isAscending;
      return;
    }
    this.isAscending = true;  
  }
  
  public Boolean isAscending {get;set;}
  
  public PageReference doSort() {
    LoadPriceBookEntry();
    return null;
  }
  
  //======================================================================//
  //Method called internally to query and load products
  //======================================================================//    
  private PageReference LoadPriceBookEntry() {
    limitExceeded = false;
    string sortingOrder = ' ASC';
    List<PriceBookEntry> templstPBEntry = new List<PriceBookEntry>();
    
    if(isAscending == false){
      sortingOrder = ' DESC';
    }    
    
    if(pageLoad){
      return null;
    }
    
    list<Product2> lstProduct2 = getProductsList();
    lstPriceBookEntry = new List<PriceBookEntry>();
    validExclusive = checkValidExclusive();   
        
    if(lstPLCode.size()==0 && isPortalUser){
       return null;
    }
    
    if(lstProduct2.size() > 99) {
       limitExceeded = true;
      // return null;
    }    
    
    if(lstProduct2.isEmpty()) {
      return null;
    }
    
    if (!validExclusive){
        return null;
    }
    
    String currencyIsoCode;
    Id priceBookId;
	if(isMachine) {
	  priceBookId = [SELECT Id FROM PriceBook2 WHERE IsStandard=True].Id;
      currencyIsoCode = machine.CurrencyIsoCode;
	}
    else if(isOpportunity) { 
      priceBookId = opportunity.Pricebook2Id;
      currencyIsoCode = opportunity.CurrencyIsoCode;
    }
    else {
      priceBookId = quote.Pricebook2Id;
      currencyIsoCode = quote.CurrencyIsoCode;
    }
          
    String query = 'SELECT UnitPrice, IsActive, Pricebook2Id, Product2.Id, product2.productcode,'+
                   'product2.product_line__c, product2.SAP_Product_Line_Code__c, product2.model_code__c,' + 
                   'Product2.Name, Product2.Description, Product2.Family, Product2.Product_Set__c, Product2.SAP_Material_Code__c ' + 
                   'FROM PricebookEntry Where IsActive = true AND Product2.IsActive = true AND ' +
                   ' CurrencyIsoCode =  :currencyIsoCode';
    
    if(lstProduct2.size() > 0) {
      query += ' AND Product2.Id IN :lstProduct2';
    }
                
    query += ' ORDER BY ' + this.sortField + sortingOrder + ' LIMIT '+RECORD_LIMIT; 
    
    templstPBEntry = (List<PriceBookEntry>)Database.query(query);
    
    for (PriceBookEntry addPbe : templstPBEntry){
        if (addPbe.Pricebook2Id == priceBookId){
            this.lstPriceBookEntry.add(addPbe);
        }
    }    
    return null;
  }
  
  //======================================================================//
  //Get list of all the product that matches the criteria
  //======================================================================//  
  private list<Product2> getProductsList() {
    Product2[] plist;
    String query = getquerystring();
    try {
      plist = Database.query(query);
    } catch (Exception e) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
    }
    return plist; 
  }
  
 private Boolean checkValidExclusive(){
    Boolean ret = true;
    list<Id> exclAccnt = new list<Id>();
    if (ProductCode != null && ProductCode != ''){
        for(Exclusive_Material__c exAccount : [select Account__c from Exclusive_Material__c WHERE isDeleted__c = false and Product__r.ProductCode =: ProductCode]) {
            if(exAccount.Account__c != null) {
             exclAccnt.add(exAccount.Account__c);
            }
        }
        if (!exclAccnt.isEmpty()){
            ret = false;
            for(Id accId : exclAccnt){
                if (accId == accountId){
                    ret = true;
                }
            }           
        }
    }
    return ret;
 } 
  //----------------------------------------//
  // Construct Query to pull products
  //----------------------------------------//
  
  public String getquerystring() {       
    String soql = 'select Id from product2 where IsActive = true ';
    if (Name != null && Name != '') {
		String strName = Name + '%';
      	soql += ' and name LIKE \''+String.escapeSingleQuotes(strName).replace('*','%')+'\'';
		strName = Name;
    }  
    if (ProductCode != null && ProductCode != '') {
		String strProductCode = ProductCode + '%';
      	soql += ' and productcode LIKE \''+String.escapeSingleQuotes(strProductCode).replace('*','%')+'\'';
		strProductCode = ProductCode;
    }  
    if (Model_Code != NULL && Model_Code != '') {
		String strModel_Code = Model_Code + '%';
      	soql += ' and model_code__c LIKE \''+String.escapeSingleQuotes(strModel_Code).replace('*','%')+'\'';
		strModel_Code = Model_Code;
    }  
    if (ProductSet !=NULL && ProductSet != ''){
		String strProductSet = ProductSet + '%';
      	soql += ' and Product_Set__c LIKE \''+String.escapeSingleQuotes(strProductSet).replace('*','%')+'\'';
		strProductSet = ProductSet;
    }  
    soql += ' and (Proprietary__c = FALSE OR Id IN :lstExclusiveProducts)';
    system.debug('************************************************************************************* soql: ' + soql);
    if (lstPLCode.size()>0)
      soql += ' and SAP_Product_Line_Code__c in :lstPLCode ';                     
    
    
    soql += ' limit '+RECORD_LIMIT;
    
    
    return soql;
  }  

  //======================================================================//
  //Search method called from page 
  //======================================================================//  
  public PageReference Search() {	 
    if(pageLoad) {
      autorun();
      getAuthorizedProducts();
      getExclusiveMaterials();
    }   
    pageLoad = false;  
    LoadPriceBookEntry();
    return null;
  }
    
  //======================================================================//
  //Select Products and create line Items
  //======================================================================//
  public PageReference SelectProduct() {
	for(PriceBookEntry priceBookEntry :getAllEntries()){
      String selected = ApexPages.currentPage().getParameters().get(priceBookEntry.Product2.Id);
      //if the product is selected
      if(selected == '1') {
        pbe = priceBookEntry;
		materialNum = priceBookEntry.Product2.SAP_Material_Code__c;
      }
    }
    
    if(pbe == null) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'Please select at least one product'));
      return null;
    }    
	
    PageReference pg;
    if(isMachine) { 
		pg = new PageReference('/apex/AddMachineLineItems?id='+sobjectId+'&priceBookEntryId='+pbe.Id + '&subsystem=' + subsystem + '&salesorg=' + salesorg);
	    pg.setRedirect(True);
	    return pg;	
    }
    else if(isOpportunity) { 
      	pg = new PageReference('/apex/AddOpptyLineItems?id='+sobjectId+'&priceBookEntryId='+pbe.Id);   
	    pg.setRedirect(True);
	    return pg;
    }
    else {
      	pg = new PageReference('/apex/AddQuoteLineItems?id='+sobjectId+'&priceBookEntryId='+pbe.Id);   
	    pg.setRedirect(True);
	    return pg;
    } 
  }
     
  public PageReference cancel() {
    return new PageReference('/' + sObjectId);
  }
  
  public List<SelectOption> getItems() {
    List<SelectOption> options = new List<SelectOption>();
	if(lstSOs.size() > 1)
		options.add(new SelectOption('0','--Select Sales Org--'));
	for(Sales_Org__c s :lstSOs)	  
  		options.add(new SelectOption(s.Name, s.Name));
    return options;
  }
}