objects/Authorized_Product__c.object
<CustomObject>
    <description>Products authorized by distributor</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Products_Authorized</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>IF(
 ISPICKVAL( Account__r.Channel__c , &quot;Distributor&quot;), &quot;Distributor&quot;,
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Line</label>
        <referenceTo>Product_Line__c</referenceTo>
        <relationshipLabel>Authorized Products</relationshipLabel>
        <relationshipName>Authorized_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Authorized Product</label>
    <nameField>
        <displayFormat>APR-{0000000}</displayFormat>
        <label>Authorized Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorized Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <description>Object to store the association between SAP Business Area, Division and Product Line</description>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ValidateDistributer.cls
/**********************************************************************************
Created By    :    Sumit Mishra
Date          :    10/20/2011
Reason        :    Test method for trigger ValidateDistributer 
**********************************************************************************/
@isTest
private class Test_ValidateDistributer   
{
    static testMethod void unitTest1()
    {
        List<Product_Line__c> lstPL = new List<Product_Line__c>();
        Product_Line__c PL1 = new Product_Line__c(Name='PL1');lstPL.add(PL1);
        Product_Line__c PL2 = new Product_Line__c(Name='PL1');lstPL.add(PL2);
        Product_Line__c PL3 = new Product_Line__c(Name='PL1');lstPL.add(PL3);
        insert lstPL;
		
        Account actP = Test_Utility.createAccount(1);        
        actP.Channel__c ='Distributor';
        actP.Channel_Attributes__c='Partial Line';
        insert actP;
        Account actC = Test_Utility.createAccount(2);        
        actC.Channel__c ='Distributor';
        actC.Channel_Attributes__c='Partial Line';
        actC.ParentId=actP.id;
        insert actC;
        Authorized_Product__c aProd = new Authorized_Product__c(Account__c = actC.Id,Product_Line__c= PL1.id);
        dataBase.Saveresult DBRes = database.insert(aprod,false);
        system.AssertEquals(DBRes.isSuccess(),false);
        
        aProd = new Authorized_Product__c(Account__c = actP.Id,Product_Line__c= PL1.id);
        insert aProd;
        
        aProd = new Authorized_Product__c(Account__c = actC.Id,Product_Line__c= PL1.id);
        DBRes = database.insert(aprod);
        system.AssertEquals(DBRes.isSuccess(),true);
    } 
}