objects/Bulletin_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bulletin Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bulletin_Delivery_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bulletin Number</label>
        <referenceTo>Bulletin_Delivery_Job__c</referenceTo>
        <relationshipLabel>Bulletin Accounts</relationshipLabel>
        <relationshipName>Bulletin_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Generic_Attachment_ID__c</fullName>
        <formula>SUBSTITUTE(Generic_Attachment__c,  (LEFT(Generic_Attachment__c,FIND(&apos;?file=&apos;,Generic_Attachment__c)) + &apos;file=&apos;), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Generic Attachment ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <picklist>
            <picklistValues>
                <fullName>PIB Sensitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PIB Non-Sensitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does not meet criteria</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Bulletin_Delivery_Job__c.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Power CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Power OC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium Power CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium Power OC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Valves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schwarzmuller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Formula__c</fullName>
        <description>This field is used in Batch class because picklist does order by based on order defined in picklist not alphabetically.</description>
        <formula>TEXT(Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is used in Batch class because picklist does order by based on order defined in picklist not alphabetically.</inlineHelpText>
        <label>Status (Text)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/The_Bank__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Current_Actual__c</fullName>
        <label>Current Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Self_Limit__c</fullName>
        <label>Daily Self Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Limit_Reached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for check is current actual is reached to daily limit</description>
        <inlineHelpText>This field is used for check is current actual is reached to daily limit</inlineHelpText>
        <label>Is Limit Reached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Modified__c</fullName>
        <label>Last Modified</label>
        <type>DateTime</type>
    </fields>
    <label>The Bank</label>
</CustomObject>

classes/BatchSendMassEmailToContacts.cls
/*************************************************************************************************************
* @author Ankit (Appirio Ind.)
* @description  Batch class for send email to PIB and service bulletin contacts
*************************************************************************************************************/
global class BatchSendMassEmailToContacts implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
   global Boolean resetCustomSetting; 
   /**********************************************************************************************************
    * Start method of batch class.
    * @param Database.BatchableContext
    * @return database.Querylocator.
    *********************************************************************************************************/
    global database.Querylocator start(Database.BatchableContext BC) {
        if(resetCustomSetting == null) {
            resetCustomSetting = true;
        }
        setupBankObject(resetCustomSetting);
        return Database.getQueryLocator(
                [ Select Id, Generic_Attachment_ID__c, Job_Type__c, Status__c, CreatedDate,  
                  Account__c, Account__r.Sales_Manager__r.IsActive, Account__r.OwnerId, Account__r.Owner.IsActive, Account__r.Country__r.Name, 
                  Account__r.Business_Org__c, Account__r.Channel__c, Bulletin_Delivery_Job__r.Name, Bulletin_Delivery_Job__r.Business_Org__c, 
                  Bulletin_Delivery_Job__c, Bulletin_Delivery_Job__r.Comments__c, Bulletin_Delivery_Job__r.Due_Date__c, 
                  Bulletin_Delivery_Job__r.CreatedBy.IsActive, Bulletin_Delivery_Job__r.Priority__c, Bulletin_Delivery_Job__r.Business_Area__c     
                From Bulletin_Accounts__c 
                    Where Bulletin_Delivery_Job__r.Status__c IN ('Ready', 'In Progress')  
                    AND Status__c = 'Not Started'
                    Order by Bulletin_Delivery_Job__r.Status_Formula__c, CreatedDate asc limit 1]);
                    
    }
    
    /***********************************************************************************************************
    * Execute method of batch class.
    * @param Database.BatchableContext
    * @param SObject[]
    * @return void.
    *********************************************************************************************************/
    global void execute(Database.BatchableContext BC, SObject[] scope) {
        The_Bank__c bankJob;
        for(The_Bank__c obj : [Select Name, Current_Actual__c, Daily_Self_Limit__c, Is_Limit_Reached__c From The_Bank__c order by CreatedDate desc Limit 1]){
            bankJob = obj;
        }
        if(bankJob != null && bankJob.Current_Actual__c >= bankJob.Daily_Self_Limit__c ) {
            bankJob.Is_Limit_Reached__c = true;
            update bankJob; 
            return; 
        }
        PibUtility.processSendEmailToContactAndCreateTask((List<Bulletin_Accounts__c>) scope);
    }
    
    /***********************************************************************************************************
    * Finish method of batch class.
    * @param Database.BatchableContext
    * @return void.
    *********************************************************************************************************/
    global void finish(Database.BatchableContext BC) {
        The_Bank__c bankJob;
        for(The_Bank__c obj : [Select Name, Current_Actual__c, Daily_Self_Limit__c, Is_Limit_Reached__c From The_Bank__c order by CreatedDate desc Limit 1]){
            bankJob = obj;
        }
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                      FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        try {
            Messaging.reserveSingleEmailCapacity((Integer)bankJob.Current_Actual__c);
            /*FeedItem post = new FeedItem();
 
            post.ParentId = '0F9C0000000GuAM'; //Chatter Group
            post.Body = 'Under email limit: '+ bankJob.Current_Actual__c;
 
            insert post;*/
        } catch (Exception e) {
                    // This code will never be reached when going over the daily email limit
                    // Limit exceptions cannot be caught
           /* FeedItem post = new FeedItem();
 
            post.ParentId = '0F9C0000000GuAM'; //Chatter Group
            post.Body = 'Over email limit: ' + bankJob.Current_Actual__c;
 
            insert post;*/
        }       
       if (a.TotalJobItems > 0 && !bankJob.Is_Limit_Reached__c) {
        BatchSendMassEmailToContacts batchSendEmail = new BatchSendMassEmailToContacts(); 
        batchSendEmail.resetCustomSetting = false;
        database.executebatch(batchSendEmail, 1);
       }
    }
    
    /***********************************************************************************************************
    * Execute method of scheduler class.
    * @param SchedulableContext
    * @return void.
    *********************************************************************************************************/
    global void execute(SchedulableContext sc) {         
        
        BatchSendMassEmailToContacts batchSendEmail = new BatchSendMassEmailToContacts(); 
        database.executebatch(batchSendEmail, 1);
    }
    
    /***********************************************************************************************************
    * setupBankObject method for The_Bank__c custom setting.
    * @return The_Bank__c.
    *********************************************************************************************************/
    private The_Bank__c setupBankObject(Boolean setCurrentActual) {
        The_Bank__c bankObj;
        for(The_Bank__c obj : [Select Name, Current_Actual__c, Daily_Self_Limit__c, Is_Limit_Reached__c, Last_Modified__c From The_Bank__c order by CreatedDate desc Limit 1]) {
          bankObj = obj;
        }
        if (bankObj == null) {
          bankObj = new The_Bank__c(Name = 'Daily Email Limit', Daily_Self_Limit__c = 900, Current_Actual__c = 0, Last_Modified__c = DateTime.now()); 
        }
        if(setCurrentActual == null || setCurrentActual == true) {
             bankObj.Current_Actual__c = 0;
             bankObj.Is_Limit_Reached__c = false;
             bankObj.Last_Modified__c = datetime.now();
        }
        system.debug('bankObj.Current_Actual__c0: ' +bankObj.Current_Actual__c);
        system.debug('bankObj.Is_Limit_Reached__c0: ' +bankObj.Is_Limit_Reached__c);
    
        upsert bankObj;
        return bankObj;
    }
}