objects/Bulletin_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bulletin Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bulletin_Delivery_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bulletin Number</label>
        <referenceTo>Bulletin_Delivery_Job__c</referenceTo>
        <relationshipLabel>Bulletin Accounts</relationshipLabel>
        <relationshipName>Bulletin_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Generic_Attachment_ID__c</fullName>
        <formula>SUBSTITUTE(Generic_Attachment__c,  (LEFT(Generic_Attachment__c,FIND(&apos;?file=&apos;,Generic_Attachment__c)) + &apos;file=&apos;), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Generic Attachment ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <picklist>
            <picklistValues>
                <fullName>PIB Sensitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PIB Non-Sensitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does not meet criteria</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Bulletin_Delivery_Job__c.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Power CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Power OC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium Power CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium Power OC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVG Valves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schwarzmuller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Defect_Correction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defect Correction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Defective_Bulletin_Delivery_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defective Bulletin Delivery Job</label>
        <referenceTo>Bulletin_Delivery_Job__c</referenceTo>
        <relationshipLabel>Defective Bulletin Delivery Jobs</relationshipLabel>
        <relationshipName>Defective_Bulletin_Delivery_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Bulletin_Delivery_Log__c.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <label>Business Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <defaultValue>&quot;Integrated&quot;</defaultValue>
        <label>Business Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bulletin Delivery Log</label>
    <nameField>
        <displayFormat>BDL-{0000}</displayFormat>
        <label>Bulletin Delivery Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulletin Delivery Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <inlineHelpText>Business Org submitting the case request.</inlineHelpText>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Date case is requested to be completed</description>
        <inlineHelpText>Enter the date you wish this to be finalized by.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_BulletinDeliveryJobTriggerHandler.cls
/*************************************************************************************************************
* @author Neeraj (Appirio Ind.)
* @date 12/09/2013
* @Task T-213767, I-85267
* @description  Test class for BulletinDeliveryJobTrigger
*************************************************************************************************************/
@isTest
private class Test_BulletinDeliveryJobTriggerHandler {
  /***********************************************************************************************************
  Test Defect Correction Job for inserts and updates
  ***********************************************************************************************************/
  static testMethod void testDefectCorrectionPositiveCase() {
    Account acc = Test_Utility.createAccount(1);
    insert acc;
    
    //Create 200 Bulletin Delivery Jobs
    List<Bulletin_Delivery_Job__c> lstBulletinJobs = new List<Bulletin_Delivery_Job__c>();
    for (Integer i = 0; i < 10; i++) {
        Bulletin_Delivery_Job__c bdj = Test_Utility.createBulletinDeliveryJob('Test Bulletin Job ' + i, false);
        lstBulletinJobs.add(bdj);
    }
    insert lstBulletinJobs;
    
    //Create 10 bulletin Account in Each Delivery job
    List<Bulletin_Accounts__c> lstBulletinAccs = new List<Bulletin_Accounts__c>();
    for (Bulletin_Delivery_Job__c bdjJob : lstBulletinJobs) {
        for (Integer i = 0; i < 5; i++) {
            lstBulletinAccs.add(Test_Utility.createBulletinAccounts(bdjJob.Id, acc.Id, false));
        }
    }
    insert lstBulletinAccs;
    
    //Add attachments for all bulletin accounts
    List<Bulletin_Delivery_Log__c> lstBDLogs = new List<Bulletin_Delivery_Log__c>();
    List<Attachment> lstAttach = new List<Attachment>(); 
    for (Bulletin_Accounts__c ba : lstBulletinAccs) {
        lstAttach.add(Test_Utility.createAttachment(ba.Id, false));
        lstBDLogs.add(Test_Utility.createBullDelLog('Test Log 1', ba.Id, false));
    }
    insert lstBDLogs;
    insert lstAttach;
    
    //Query bulletin account with all fields
    lstBulletinAccs = 
          [Select Id, Generic_Attachment_ID__c, Job_Type__c, Status__c, CreatedDate,  
                  Account__c, Account__r.Sales_Manager__r.IsActive, Account__r.OwnerId, Account__r.Owner.IsActive, Account__r.Country__r.Name, 
                  Account__r.Business_Org__c, Account__r.Channel__c, Bulletin_Delivery_Job__r.Name, Bulletin_Delivery_Job__r.Business_Org__c, 
                  Bulletin_Delivery_Job__c, Bulletin_Delivery_Job__r.Comments__c, Bulletin_Delivery_Job__r.Due_Date__c, 
                  Bulletin_Delivery_Job__r.CreatedBy.IsActive, Bulletin_Delivery_Job__r.Priority__c, Bulletin_Delivery_Job__r.Business_Area__c
          From Bulletin_Accounts__c 
          Where Id in :lstBulletinAccs
          Order by Bulletin_Delivery_Job__r.Status__c, CreatedDate];
    
    //Execute pibUtility method to create tasks for sensitive jobs
    //Create Tasks for Sensitive Bulletin Delivery Jobs
    PibUtility.processSendEmailToContactAndCreateTask(lstBulletinAccs);
    List<Task> lstTasks = [Select id from Task Where status = 'In Progress'];
    System.assertEquals(50, lstTasks.size()); //there should be 1000 tasks created one for each BA
    System.assertEquals(50, [Select count() from Attachment  Where ParentId in :lstTasks]); //1000 attachment 1 for each BA
    
    Test.startTest();
    //CASE 1: Insert 50 bulletin Delivery job with defect correction set to true and defective job created above. 
    //This should result in 500 tasks to created.
    List<Bulletin_Delivery_Job__c> lstNewBulletinJobs = new List<Bulletin_Delivery_Job__c>();
    for (Integer i = 0; i < 10; i++) {
      Bulletin_Delivery_Job__c bdj = Test_Utility.createBulletinDeliveryJob('Test Bulletin Job ' + i, false);
        bdj.Defective_Bulletin_Delivery_Job__c = lstBulletinJobs.get(i).Id;
        bdj.Defect_Correction__c = true;
        lstNewBulletinJobs.add(bdj); 
    }
    insert lstNewBulletinJobs;
    System.assertEquals(50, [Select count() from Task  Where status = 'Cancelled']); //there should be 500 tasks with status as cancelled.
    //There should only be 500 attachments left as attachments related to cancelled tasks are deleted.
    System.assertEquals(0, [Select count() from Attachment  Where ParentId in :lstTasks]); 
    //there should be 500 tasks with status as cancelled.
    
    //CASE 2: Validate update logic (update rest 50 jobs with defective job populated)
    lstNewBulletinJobs.clear();
    for (Integer i = 5; i < 10; i++) {
      Bulletin_Delivery_Job__c bdj = Test_Utility.createBulletinDeliveryJob('Test Bulletin Job ' + i, false);
      lstNewBulletinJobs.add(bdj); 
    }
    insert lstNewBulletinJobs;
    
    Integer i = 5;
    for (Bulletin_Delivery_Job__c bdj : lstNewBulletinJobs) {
      bdj.Defective_Bulletin_Delivery_Job__c = lstBulletinJobs.get(i++).Id;
      bdj.Defect_Correction__c = true;
    }
    update lstNewBulletinJobs;
    System.assertEquals(50, [Select count() from Task  Where status = 'Cancelled']);  //All tasks should get cancelled out
    System.assertEquals(0, [Select count() from Attachment  Where ParentId in :lstTasks]);  //All attachment will be deleted
    Test.stopTest();
  }
  
  /***********************************************************************************************************
  Test Defect Correction Job for inserts and updates
  ***********************************************************************************************************/
  static testMethod void testDefectCorrectionNegativeCase() {
    Account acc = Test_Utility.createAccount(1);
    insert acc;
    
    //Create 200 Bulletin Delivery Jobs
    List<Bulletin_Delivery_Job__c> lstBulletinJobs = new List<Bulletin_Delivery_Job__c>();
    for (Integer i = 0; i < 10; i++) {
      Bulletin_Delivery_Job__c bdj = Test_Utility.createBulletinDeliveryJob('Test Bulletin Job ' + i, false);
      lstBulletinJobs.add(bdj);
    }
    insert lstBulletinJobs;
    
    //Create 10 bulletin Account in Each Delivery job
    List<Bulletin_Accounts__c> lstBulletinAccs = new List<Bulletin_Accounts__c>();
    for (Bulletin_Delivery_Job__c bdjJob : lstBulletinJobs) {
      for (Integer i = 0; i < 5; i++) {
        lstBulletinAccs.add(Test_Utility.createBulletinAccounts(bdjJob.Id, acc.Id, false));
      }
    }
    insert lstBulletinAccs;
    
    //Add attachments for all bulletin accounts
    List<Bulletin_Delivery_Log__c> lstBDLogs = new List<Bulletin_Delivery_Log__c>();
    List<Attachment> lstAttach = new List<Attachment>(); 
    for (Bulletin_Accounts__c ba : lstBulletinAccs) {
      lstAttach.add(Test_Utility.createAttachment(ba.Id, false));
      lstBDLogs.add(Test_Utility.createBullDelLog('Test Log 1', ba.Id, false));
    }
    insert lstBDLogs;
    insert lstAttach;
    
    //Query bulletin account with all fields
    lstBulletinAccs = 
          [Select Id, Generic_Attachment_ID__c, Job_Type__c, Status__c, CreatedDate,  
                  Account__c, Account__r.Sales_Manager__r.IsActive, Account__r.OwnerId, Account__r.Owner.IsActive, Account__r.Country__r.Name, 
                  Account__r.Business_Org__c, Account__r.Channel__c, Bulletin_Delivery_Job__r.Name, Bulletin_Delivery_Job__r.Business_Org__c, 
                  Bulletin_Delivery_Job__c, Bulletin_Delivery_Job__r.Comments__c, Bulletin_Delivery_Job__r.Due_Date__c, 
                  Bulletin_Delivery_Job__r.CreatedBy.IsActive, Bulletin_Delivery_Job__r.Priority__c, Bulletin_Delivery_Job__r.Business_Area__c
          From Bulletin_Accounts__c 
          Where Id in :lstBulletinAccs
          Order by Bulletin_Delivery_Job__r.Status__c, CreatedDate];
    
    //Execute pibUtility method to create tasks for sensitive jobs
    //Create Tasks for Sensitive Bulletin Delivery Jobs
    PibUtility.processSendEmailToContactAndCreateTask(lstBulletinAccs);
    List<Task> lstTasks = [Select id from Task Where status = 'In Progress'];
    System.assertEquals(50, lstTasks.size()); //there should be 1000 tasks created one for each BA
    System.assertEquals(50, [Select count() from Attachment  Where ParentId in :lstTasks]); //1000 attachment 1 for each BA
    
    Test.startTest();
    
    //  CASE 1: Defect Correction is not checked but defective job is set
    //  Expected Result: No Tasks should get created
    List<Bulletin_Delivery_Job__c> lstNewBulletinJobs = new List<Bulletin_Delivery_Job__c>();
    for (Integer i = 0; i < 10; i++) {
      Bulletin_Delivery_Job__c bdj = Test_Utility.createBulletinDeliveryJob('Test Bulletin Job ' + i, false);
      bdj.Defective_Bulletin_Delivery_Job__c = lstBulletinJobs.get(i).Id;
      bdj.Defect_Correction__c = false;
      lstNewBulletinJobs.add(bdj); 
    }
    insert lstNewBulletinJobs;
    lstTasks = [Select id from Task Where status = 'Cancelled'];
    System.assertEquals(0, lstTasks.size());
    System.assertEquals(0, [Select count() from Attachment  Where ParentId in :lstTasks]); 
    
    //  CASE 2: Defect Correction is checked but defective job is blank
    //  Expected Result: No Tasks should get created
    for (Bulletin_Delivery_Job__c bdj : lstNewBulletinJobs) {
      bdj.Defective_Bulletin_Delivery_Job__c = null;
      bdj.Defect_Correction__c = true;
    }
    try {
      update lstNewBulletinJobs;
    } catch (Dmlexception ex) {
        system.assert(ex.getMessage().contains('Please select Defective Bulletin Delivery Job.'));
    }
    System.assertEquals(0, [Select count() from Task  Where status = 'Cancelled']);
    System.assertEquals(0, [Select count() from Attachment  Where ParentId in :lstTasks]); 
    
    Test.stopTest();
  }
  
}