objects/Bulletin_Accounts__c.object
<CustomObject>
    <fields>
        <fullName>Bulletin_Delivery_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bulletin Number</label>
        <referenceTo>Bulletin_Delivery_Job__c</referenceTo>
        <relationshipLabel>Bulletin Accounts</relationshipLabel>
        <relationshipName>Bulletin_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Bulletin_Delivery_Job__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schwarzmuller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Bulletin_Delivery_Log__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <defaultValue>&quot;Integrated&quot;</defaultValue>
        <label>Business Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bulletin Delivery Log</label>
    <nameField>
        <displayFormat>BDL-{0000}</displayFormat>
        <label>Bulletin Delivery Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulletin Delivery Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_UpdateOrigBDJWithDefectBDJ.cls
@isTest
private class Test_UpdateOrigBDJWithDefectBDJ {

    static testMethod void TestUpdateOrigBDJWithDefectBDJ() {
        Account acc = Test_Utility.createAccount(1);
    	insert acc;
    	integer i = 1;
    	Bulletin_Delivery_Job__c bdj = Test_Utility.createBulletinDeliveryJob('Test Bulletin Job ' + i, false);
    	insert bdj;
    	Bulletin_Accounts__c ba = Test_Utility.createBulletinAccounts(bdj.Id, acc.Id, false);
    	insert ba;
    	Bulletin_Delivery_Log__c bdl = Test_Utility.createBullDelLog('Test Log 1', ba.Id, false);
    	insert bdl;
    	bdl.Business_Org__c = 'Integrated';
    	update bdl;
    	
    }
}