objects/BusinessWarehouseReport__c.object
<CustomObject>
    <fields>
        <fullName>Report_URL__c</fullName>
        <inlineHelpText>The URL to the BI report. {ID} will be replaced with the sub account ID.</inlineHelpText>
        <label>Report URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>BusinessWarehouseReport</label>
    <nameField>
        <label>BusinessWarehouseReport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BusinessWarehouseReports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/Test_BusinessWarehouseReportExtension.cls
@isTest
public class Test_BusinessWarehouseReportExtension {
    
    static testMethod void test() {
        insert new BusinessWarehouseReport__c(Name = 'test', Report_URL__c = 'http://sap.danfoss.net/report?accoutId={ID}');
        Sub_Account__c sa = new Sub_Account__c(SAP_Account_ID__c = '123', Name = '123');
        insert sa;
        
        Test.startTest();
        
        BusinessWarehouseReportExtension c = new BusinessWarehouseReportExtension(new ApexPages.StandardController(sa));
        System.assertEquals(1, c.getReports().size());
    }
    
}