objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <inlineHelpText>Business Org submitting the case request.</inlineHelpText>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <picklist>
            <picklistValues>
                <fullName>24 PIN Transparent Microcontrollers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50 PIN Transparent Microcontrollers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CG150 CAN/USB gateway interface communicator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS1000 Slope Sensor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Reverse Displacement Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDC20 20cm3 Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DH 80cm3 Orbital Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DS 160cm3 Orbital Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSW Orbital Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHF Electrohydraulic Boxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHPS-2 Steering Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHPS OLS320 Steering Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHPS Steering Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHSC Electrohydraulic Boxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EHS Electrohydraulic Boxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EH Steering Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMD Speed Sensor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Controller - mounted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 110cm3 Bent Axis Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 115cm3 Pump AC with wire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 115cm3 Pump with EDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 147/165cm3 Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 147/165cm3 Pump with EDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 147/165cm3 Pump with ISL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 160cm3 Bent Axis Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 250cm3 Bent Axis Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 250cm3 Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H1 45/53cm3 and 69/78cm3 Pump with EDC</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/ImageBankCtrl.cls
/***************************************************************************
// (c) 2014 Appirio, Inc. 
//
// ImageBankCtrl  
// Controller class for ImageBank Page 
//
// Dec 12, 2014     Nishant Bansal (Appirio JDC) 
// Updated by Arvind Thakur on 17th Dec T-341544, T-341545.
//**************************************************************************/
public without sharing class ImageBankCtrl {
  public list<ContentWrapper> conWrapList {get;set;}
  public list<ContentWrapper> conWrapGraphicsList {get;set;}
  public list<String> productSelectList {
    get{
      if(productSelectList == null){
        productSelectList = new list<String>();
        for(SelectOption s : Utility.getPicklistValues(New PortalBanner__c(), 'Products__c')){
          productSelectList.add(s.getValue());
        }
      }
      return productSelectList;
    }set;}

  public String imageString {get; set;}
  public String commentBox {get; set;}
  public Blob attachment {get;set;}
  public String filename {get; set;}
  public String contentType {get; set;}
  public PortalBanner__c portalBanner {get; set;}

  public User user;

  private Account account;
  private Contact contact;
  private Case newCase;
  private static Map<String,Schema.RecordTypeInfo>  recordType = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName();

  public ImageBankCtrl() {
    //productSelectList = Utility.getPicklistValues(Case, 'Products__c');

    user = [SELECT Id, Contact.AccountId, AccountId, ContactId, Contact.Account.Region__c, Contact.Account.Business_Org__c, FirstName FROM User WHERE Id=:userInfo.getuserid() LIMIT 1];
    if(user != null){
      for(Contact con : [SELECT Id, AccountId, Account.OwnerId FROM Contact WHERE Id = :user.ContactId]){
        contact = con; 
      }
      for(Account acc : [SELECT Id, OwnerId FROM Account WHERE Id =:user.AccountId]){
        account = acc;
      }  
    }

    List<ContentDocument> allLogos = [SELECT LatestPublishedVersion.Description,Title,LatestPublishedVersion.Content_Type__c,LatestPublishedVersion.PublishStatus,
                                                                      LatestPublishedVersion.FileType,LatestPublishedVersion.PathOnClient,LatestPublishedVersionId,
                                                                      LatestPublishedVersion.Content_ID__c
                                                                      FROM ContentDocument 
                                                                      WHERE LatestPublishedVersion.Content_Type__c IN ('Product Image','Product Graphic')
                                                                      ORDER BY  LatestPublishedVersion.Content_Type__c, ContentModifiedDate DESC];
    conWrapList = new list<ContentWrapper>();
    conWrapGraphicsList = new list<ContentWrapper>();
    for(ContentDocument cd : allLogos){
      ContentWrapper cw = new ContentWrapper();
      cw.title = cd.Title;
      cw.converid = cd.LatestPublishedVersionId; 
      cw.extid = cd.LatestPublishedVersion.Content_ID__c;
      cw.description = cd.LatestPublishedVersion.Description;
      if(cd.LatestPublishedVersion.Content_Type__c == 'Product Image'){
        conWrapList.add(cw);
      } else {
        conWrapGraphicsList.add(cw);
      }
    } 

    portalBanner = new PortalBanner__c();
    List<PortalBanner__c> lstPnlBanner = new List<PortalBanner__c>();
    lstPnlBanner = [SELECT Summary__c
                                FROM PortalBanner__c 
                                WHERE Region__c = :user.Contact.Account.Region__c   
                                AND Business_Org__c = :user.Contact.Account.Business_Org__c
                                AND Page__c = 'ImageBank' 
                                AND RecordTypeId = :recordType.get('Page Information').getRecordTypeId()];
    //There should only be one match for VF Page and Position (Filter: VF Page, Position, User Region, User Business Org, RecordTypeId)                           
    if (lstPnlBanner.size() == 1) {
      portalBanner = lstPnlBanner[0]; 
    }else if(lstPnlBanner.isEmpty()){
      //Query banner record again for region "Default"
      lstPnlBanner = [SELECT Summary__c
                                  FROM PortalBanner__c
                                  WHERE Region__c = 'Default' 
                                  AND Page__c = 'ImageBank'
                                  AND RecordTypeId = :recordType.get('Page Information').getRecordTypeId()];
      if(!lstPnlBanner.isEmpty()){
        PortalBanner__c defaultPortalBanner = lstPnlBanner[0];
        portalBanner = defaultPortalBanner;       
      }
    }              
  }

  public PageReference Submit(){ 
    return new PageReference('');
  }

  //Create Attachment
  public boolean createAttachment(Id objectId){
    Attachment newAttachment = new Attachment();
    newAttachment.ContentType = contentType;
    newAttachment.Body = attachment;
    newAttachment.ParentId = objectId;
    newAttachment.Name = filename;
  try{
    insert newAttachment;
    return true;
    }catch(exception ex){
      return false;
    }
  }

  //Create Case
  public void generateCase(){
    RecordType RecType = [SELECT Id FROM RecordType WHERE SobjectType = 'Case' AND Name = 'PartnerLink Case'];

    String description = 'Requested Images: ' + imageString + '\r\n\r\n' + commentBox;

    Id caseId = Utility.createPortalCase(RecType.Id, description, 'Image Request', 'PartnerLink', 'Image Bank Request'
      , 'New', account.Id, user.ContactId);

    if(caseId != null && attachment != null){
      if(createAttachment(caseId)){
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Thank you for your request!'));
      } else {
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'An error has occured. Please try again.'));
      }
    }
  }

  public class ContentWrapper {
    public String title {get;set;}
    public Blob image {get;set;}
    public String converid {get;set;}
    public String description {get;set;}
    public String extid {get;set;}

    public ContentWrapper(){
    }
  }

}