objects/Case.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Localized question and answer for FAQ</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <formula>TEXT(QuestionSet__r.SortOrder__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SortOrder</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ViewCount__c</fullName>
        <label>View Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/FAQComponentCtrl.cls
/***************************************************************************
// (c) 2014 Appirio, Inc. 
//
// FAQComponentCtrl
// Controller class for FAQ component
//
// Dec 12, 2014
// 
//**************************************************************************/
global without sharing class FAQComponentCtrl {
    
  //public ApexPages.StandardSetController setCont { get; set; }
  public String newQuestion {get;set;}
  public String questionTopic {get;set;}
  
  public List<Question__c> lstQues {
    get {
        if (lstQues == null){
        initFAQ();
        return lstQues;
        }else{
        return lstQues;
        }
    }set;
  }
  private User currentUsr;
    
  public FAQComponentCtrl(){
    currentUsr = [SELECT ContactId, Contact.AccountId, Contact.Account.OwnerId, Contact.Account.Region__c FROM User WHERE Id = :Userinfo.getUserId()];  
    initFAQ();
  }

  //Get list of questions by users region. If no region exists pull in default questions.
  public void initFAQ(){
    lstQues = new List<Question__c>();
    if(currentUsr.ContactId != null && currentUsr.Contact.Account.Region__c != null){
     lstQues = [SELECT Question__c, Answer__c, Region__c FROM Question__c 
      WHERE Region__c = :currentUsr.Contact.Account.Region__c ORDER BY SortOrder__c NULLS LAST, Question__c];
   }

   if(lstQues.size() == 0){
     lstQues = [SELECT Question__c, Answer__c, Region__c FROM Question__c 
       WHERE Region__c = 'Default' ORDER BY SortOrder__c NULLS LAST, Question__c];
   }
  }

  //Remote action to track how many clicks each question receives
  @RemoteAction
  global static void trackClicks(String questionId) {
    Question__c viewedQuestion = [SELECT ViewCount__c FROM Question__c WHERE Id = :questionId];
    if(viewedQuestion.ViewCount__c != null) {
      viewedQuestion.ViewCount__c += 1;
    } else {
      viewedQuestion.ViewCount__c = 1;
    }
    update viewedQuestion;
  }
  
  //Create Case
  public PageReference createNewCase(){
    RecordType RecType = [SELECT Id FROM RecordType WHERE SobjectType = 'Case' AND Name = 'PartnerLink Case'];

    String subject = questionTopic + ' - FAQ Question';

    Id caseId = Utility.createPortalCase(RecType.Id, newQuestion, 'Marketing Question', 'PartnerLink', subject
      , 'New', currentUsr.Contact.AccountId, currentUsr.ContactId);

    return null;
  }

}