objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pricing_Stage__c</fullName>
        <description>For Power Solutions Pricing Cases</description>
        <inlineHelpText>Current stage of Annual Pricing Adjustment. Not used for other types of pricing cases.</inlineHelpText>
        <label>Pricing Stage</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>(1) APA Negotiation Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Pricing Review and Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) CPL/MQ requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) CPL/MQ Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(5) CPL/MQ Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Pricing</fullName>
        <active>true</active>
        <businessProcess>PS Pricing</businessProcess>
        <description>This case type is for Power Solutions users to submit pricing requests to the Price Planning Teams</description>
        <label>Pricing</label>
    </recordTypes>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseTriggerHandler.cls
/**
    Author: Erin Fink
    Date: 09JUN15
    Version 1.0
**/

public with sharing class CaseTriggerHandler{

    private static Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Pricing').getRecordTypeId();
    static QueueSobject PricingAMqueue = [Select QueueId from QueueSobject where Queue.DeveloperName = 'PS_Pricing_Americas'];
    static QueueSobject PricingEUqueue = [Select QueueId from QueueSobject where Queue.DeveloperName = 'PS_Pricing_Europe'];
    static QueueSobject EUSCqueue = [Select QueueId from QueueSobject where Queue.DeveloperName = 'PS_Pricing_EUSC'];
    
    public static void assignToAccountManager(List<Case> lstCases){         
        Set<Id> setAMqueueMembers = new Set<Id>();
        for (GroupMember qUser :[Select UserOrGroupId from GroupMember WHERE GroupId = :PricingAMqueue.QueueId]){
            setAMqueueMembers.add(qUser.UserOrGroupId);
        }
        System.debug(setAMqueueMembers);
        
        set<Id> setAcctIds= new set<Id>();
        for(Case c :lstCases){
            setAcctIds.add(c.AccountId);
        }
        map<Id, List<AccountTeamMember>> mapAccountTeamMembers = new map<Id, List<AccountTeamMember>>();
        List<AccountTeamMember> lstAcctsTeam = [select Id, AccountId, TeamMemberRole, UserId from AccountTeamMember where AccountId IN :setAcctIds];
        Id PricePlanner;
        for(AccountTeamMember atm :lstAcctsTeam){
            if(!mapAccountTeamMembers.containsKey(atm.AccountId))
                mapAccountTeamMembers.put(atm.AccountId, new List<AccountTeamMember>());
            mapAccountTeamMembers.get(atm.AccountId).add(atm);
        }
        map<Id, Account> mapAccounts = new map<Id, Account>([select Id, OwnerId, Sales_Manager__c, Country__r.Region__c from Account where Id IN :setAcctIds]);

        for(Case c :lstCases){
            if(c.RecordTypeId != caseRecordTypeId)
                break;
            c.Sales_Manager__c = mapAccounts.get(c.AccountId).Sales_Manager__c;
            if(mapAccounts.get(c.AccountId).Country__r.Region__c == 'Americas'){
                c.Status = 'In Process';  //here or only when Origin is Pricing?
                if(!setAMqueueMembers.contains(UserInfo.getUserId())){                  
                    c.OwnerId = PricingAMqueue.QueueId; 
                    c.Origin = 'Sales';
                }
                else
                    c.Origin = 'Pricing';
                    if(c.Type == 'Annual Price Adjustment'){
                        c.Pricing_Stage__c = '(1) APA Negotiation Ongoing';
                        c.OwnerId = mapAccounts.get(c.AccountId).OwnerId; 
                    }
            }
            
            else if(mapAccounts.get(c.AccountId).Country__r.Region__c == 'Europe'){
                if(mapAccountTeamMembers.containsKey(c.AccountId)){
                    for(AccountTeamMember mem :mapAccountTeamMembers.get(c.AccountId)){
                        if(mem.TeamMemberRole == 'Price Planner'){
                            PricePlanner = mem.UserId;
                        }
                    }
                }           
                if(c.Type != 'Annual Price Adjustment' && c.Origin == 'Sales'){         
                    if(PricePlanner != null)
                        c.OwnerId = PricePlanner;
                    else
                        c.OwnerId = PricingEUqueue.QueueId;
                }
                else{
                    c.OwnerId = mapAccounts.get(c.AccountId).OwnerId; 
                }
                
                if(c.Type == 'Annual Price Adjustment'){
                    c.Pricing_Stage__c = '(1) APA Negotiation Ongoing';
                }
            }
        }  
    }
    
    public static void updateCaseStatus(List<Case> lstCases){
        set<Id> setAcctIds= new set<Id>();
        for(Case c :lstCases){
            setAcctIds.add(c.AccountId);
        }
        map<Id, List<AccountTeamMember>> mapAccountTeamMembers = new map<Id, List<AccountTeamMember>>();
        List<AccountTeamMember> lstAcctsTeam = [select Id, AccountId, TeamMemberRole, UserId from AccountTeamMember where AccountId IN :setAcctIds];
        Id CSR;
        Id PricePlanner;
        for(AccountTeamMember atm :lstAcctsTeam){
            if(!mapAccountTeamMembers.containsKey(atm.AccountId))
                mapAccountTeamMembers.put(atm.AccountId, new List<AccountTeamMember>());
            mapAccountTeamMembers.get(atm.AccountId).add(atm);
        }
        map<Id, Account> mapAccounts = new map<Id, Account>([select Id, OwnerId, Sales_Manager__c, Country__r.Region__c from Account where Id IN :setAcctIds]);
        for(Case c :lstCases){  
            if(c.RecordTypeId != caseRecordTypeId)
                break;      
            c.Sales_Manager__c = mapAccounts.get(c.AccountId).Sales_Manager__c;
            if(c.Type == 'Annual Price Adjustment'){
                if(mapAccountTeamMembers.containsKey(c.AccountId)){
                    for(AccountTeamMember mem :mapAccountTeamMembers.get(c.AccountId)){
                        if(mem.TeamMemberRole == 'Customer Service Rep'){
                            CSR = mem.UserId;
                        }
                        else if(mem.TeamMemberRole == 'Price Planner'){
                            PricePlanner = mem.UserId;
                        }
                    }
                }            
                if(c.Pricing_Stage__c.contains('2')){
                    if(mapAccounts.get(c.AccountId).Country__r.Region__c == 'Americas'){
                        c.OwnerId = PricingAMqueue.QueueId;
                    }
                    else if(mapAccounts.get(c.AccountId).Country__r.Region__c == 'Europe'){
                        c.Status = 'Open';
                        if(PricePlanner != null)
                            c.OwnerId = PricePlanner;
                        else
                            c.OwnerId = PricingEUqueue.QueueId;
                    }
                }           
                
                if(c.Pricing_Stage__c.contains('3') && mapAccounts.get(c.AccountId).Country__r.Region__c == 'Europe'){
                    c.Status = 'In Process';
                    c.OwnerId = EUSCqueue.QueueId;
                }            
                
                if(c.Pricing_Stage__c.contains('4') && mapAccounts.get(c.AccountId).Country__r.Region__c == 'Europe'){
                    if(PricePlanner != null)
                        c.OwnerId = PricePlanner;
                    else
                        c.OwnerId = PricingEUqueue.QueueId;
                }            
                
                if(c.Pricing_Stage__c.contains('5') && mapAccounts.get(c.AccountId).Country__r.Region__c == 'Europe'){
                    c.Status = 'Closed';
                }
            }
        }
    }
       
}