objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <formula>Account.Owner.FirstName &amp; &quot; &quot; &amp; Account.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <inlineHelpText>Business Org submitting the case request.</inlineHelpText>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts33</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Manager_of_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CNT-{000000000}</displayFormat>
        <label>Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Deviated_Lead_time_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Deviated_Lead_time_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deviated Lead-time Requests</relationshipLabel>
        <relationshipName>Deviated_Lead_time_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <label>Quote Approval Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Manager_of_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Mgr of Account</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SalesManagerofQuoteAccount</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/User_Type_Department_Match__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>User Type Department Match</label>
</CustomObject>

classes/AccountTriggerHandler.cls
public with sharing class  AccountTriggerHandler{
	public static User u = [select IsPortalEnabled, ContactId from User where Id = :UserInfo.getUserId()];
	static Id acctRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
	static Id CustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
	
	@future
	public static void PopulateAccountFields(Set<Id> setAcctIDs)	//AFTER INSERT
	{
		if (u.IsPortalEnabled)
		{
			List<Account> acctList = [Select Id, ParentId, Parent.OwnerId, Parent.Business_Org__c, Country__r.Name From Account Where Id IN :setAcctIDs];
			Contact c = [select AccountId, Account.OwnerId, Account.Business_Org__c from Contact where Id = :u.ContactId];
			
			for(Account act : acctList)
			{			
				act.Pardot_Country__c = act.Country__r.Name;
	       		act.business_org__c= c.Account.Business_Org__c;
	            act.ParentId = c.AccountId;
				act.ownerId = c.Account.OwnerId;
				//Create Account Team Member for Partner Portal User
				List<AccountTeamMember> members = new List<AccountTeamMember>();
				AccountTeamMember member = new AccountTeamMember();
				member.AccountId = act.Id;
				member.TeamMemberRole = 'Partner';
				member.UserId = u.id;
				members.add(member);
				
				if (!members.isEmpty()) {
					insert members;
				}
				List<AccountShare> shares = [select Id, OpportunityAccessLevel, RowCause, UserOrGroupId from AccountShare where AccountId = :act.Id and UserOrGroupId = :u.Id];
				// set Partner team members access as follows: ACCOUNT: Read (default), CONTACT: Read (preferrably Read/Write for Prospect Accounts - if only one option is available default to Read/Write), 							OPPORTUNITY Read/Write, CASE: Private (default)
				for (AccountShare share : shares)  {
				    share.OpportunityAccessLevel = 'Edit';
					share.ContactAccessLevel = 'Edit';
				}
				update shares; 
			}
		update acctList;
       	}		
	}

	public static void ContentDocumentSetupOnAccount(List<Account> lstAccts, Map<Id, Account> mapOldAccts, Boolean isInsert)	//AFTER INSERT and UPDATE
	{
		List<Account> accountToProceed = new List<account>();
    	set<id> accountIds = new set<id>();
		for (Account act :lstAccts)
		{
			accountIds.add(act.Id);
			boolean proceed = false;
	        if(act.RecordTypeId != acctRecordTypeId) //Not a Prospect
	        {
	            if(isInsert)
	                proceed = true;
	            else
	            {
					Account oldAcct = mapOldAccts.get(act.Id);
	                if(act.Channel__c != oldAcct.Channel__c || act.Business_Org__c != oldAcct.Business_Org__c)
	                    proceed = true;
	                if(act.Manager_Library__c != oldAcct.Manager_Library__c || act.User_Library__c != oldAcct.User_Library__c)
	                    proceed = true;
	                if(act.Country__c != oldAcct.Country__c
	                       || act.Customer_Segment__c != oldAcct.Customer_Segment__c
	                       || act.Price_Schedule__c != oldAcct.Price_Schedule__c
	                       || act.Channel_Attributes__c != oldAcct.Channel_Attributes__c)
	                    proceed = true;
	               
	            }
	        }
	        if(proceed)
	            accountToProceed.add(act);
		}
	    if(accountToProceed.size()>0)
	    {
	        if (Test.isRunningTest()&&Limits.getFutureCalls()>=Limits.getLimitFutureCalls()) {
				system.debug(LoggingLevel.Error, 'Future method limit reached. Skipping...');
			}
			else {
			        ContentUtils.ProcessforAccounts(accountIds); 
			}
		}  
	}
	
	public static void ChangeuserGroupOnLibraryChange(List<Account> lstAccts, Map<Id, Account> mapAccts, Map<Id, Account> mapOldAccts) 	//AFTER UPDATE
	{
	    Set<id> accountToOperate = new Set<id>();
	    Map<id,String> RemoveFrom = new Map<id,String>();
	    Map<id,String> AddTo = new Map<id,String>();
	    for(Account act:lstAccts)
	    {
	        account actOld = mapOldAccts.get(act.Id);
	        if(act.Manager_Library__c != actOld.Manager_Library__c || act.User_Library__c != actOld.User_Library__c)
	            accountToOperate.add(act.Id);
	    }
	    for(User usr:[Select id, Contact.department__c,ContactId, Contact.AccountId from User where Contact.AccountId in :accountToOperate])
	    {
	        Account act = mapAccts.get(usr.Contact.AccountId);
	        Account actOld = mapOldAccts.get(act.Id);
	        string uType = 'U';
	        User_Type_Department_Match__c utold=null;
	        if(usr.Contact.department__c!=null)
	        {
	            User_Type_Department_Match__c ut = User_Type_Department_Match__c.getValues(usr.Contact.department__c);
	            if(ut!=null && ut.Type__c=='Restricted') 
	                uType  = 'M';
	        }
	        if(act.Manager_Library__c != actOld.Manager_Library__c && uType=='M')
	        {
	            if(act.Manager_Library__c!=null)
	                addTo.put(usr.Id,act.Manager_Library__c);
	            if(actOld.Manager_Library__c!=null)
	                RemoveFrom.put(usr.Id,actOld.Manager_Library__c);
	        }
	        if(act.User_Library__c != actOld.User_Library__c)
	        {
	            if(act.User_Library__c!=null)
	                addTo.put(usr.Id,act.User_Library__c);
	            if(actOld.User_Library__c!=null)
	                RemoveFrom.put(usr.Id,actOld.User_Library__c);
	        }
	    }
	    if (accountToOperate.size() > 0)
		{
			if (Test.isRunningTest()&&Limits.getFutureCalls()>=Limits.getLimitFutureCalls()) {
				system.debug(LoggingLevel.Error, 'Future method limit reached. Skipping...');
			}
			else {
	    		ContentUtils.UpdateUserGroupWhenLibraryChange(accountToOperate, RemoveFrom,AddTo);
			}
		}
	}
		
	public static void UpdateNamesOnOtherRecords(List<Account> lstAccts, Map<Id, Account> mapOldAccts) 	//AFTER UPDATE
	{
		Set<Id> setAcctIds = new Set<Id>();
        for(Account act:lstAccts) {
        	if(act.RecordTypeId == CustomerRecordTypeId){
	        	Account actOld = mapOldAccts.get(act.Id);
	        	if(act.OwnerId != actOld.OwnerId || act.Sales_Manager__c != actOld.Sales_Manager__c)
	        		setAcctIds.add(act.Id);
        	}
        }
		List<Case> lstCases = new List<Case>([select Id, Sales_Manager__c from Case where AccountId IN :setAcctIds and isClosed = false]);
		List<Contract__c> lstContracts = new List<Contract__c>([select Id, Account_Manager__c, Sales_Manager_of_Account__c from Contract__c where Customer__c IN :setAcctIds]);
		List<Deviated_Lead_time_Request__c> lstDLRs = new List<Deviated_Lead_time_Request__c>([select Id, Account_Owner__c from Deviated_Lead_time_Request__c where Account__c IN :setAcctIds]);
		List<Quote> lstQuotes = new List<Quote>([select Id, Opportunity.Account.OwnerId, Opportunity.Account.Sales_Manager__c from Quote where Opportunity.AccountId IN :setAcctIds and Approval_Stage__c = 'Pending']);
		
		if(!lstCases.isEmpty())
			update lstCases;
		if(!lstContracts.isEmpty())
			update lstContracts;
		if(!lstDLRs.isEmpty())
			update lstDLRs;
		if(!lstQuotes.isEmpty())
			update lstQuotes;
	}
}