objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

objects/Portal_Business_Org_Style__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies style sheet used by portal home page based on Business Org</description>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Portal Business Org Style</label>
</CustomObject>

objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <picklist>
            <controllingField>Object__c</controllingField>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentation Archives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Signature Guidelines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Handbook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need A Logo?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Releases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing &amp; Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Items</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbooks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Type_to_Query__c</fullName>
        <label>Content Type to Query</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assembly Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Let&apos;s Torque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbook</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <description>Configure panel widgets on a portal custom visual force home page</description>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/PartnerPortalHomeComponentCtrl.cls
/*************************************************************************************************************
* @author Ankit (Appirio Ind.)
* @date 12/3/2013
* @description Controller class for PartnerPortalHomeComponent.
* @modified
* @12/5/2014 - Added check for Page name
*************************************************************************************************************/
public with sharing class PartnerPortalHomeComponentCtrl {
  public String pos{get;set;}
  public String errorMsg {get;set;}
  public User loginuser = [Select Id, Business_Org__c From User where Id =:userInfo.getUserId()];
  public Portal_Business_Org_Style__c pobu = Portal_Business_Org_Style__c.getInstance('PartnerLink Home Page');
  /***********************************************************************************************************
  /* Returns Current user with region and business org
  ***********************************************************************************************************/
  private static User m_User;
  private static User currentUser {
    get {
        if (m_User == null) {
        for (User usr: [ Select Contact.Account.Region__c, Contact.Account.Business_Org__c 
                         From User 
                         Where Id = :UserInfo.getUserId()]) {
          m_User = usr;
        }
        }
        return m_User;
    }
  }
  
  private static String userRegion = currentUser.Contact.Account.Region__c;
  private static String userBusinessOrg = currentUser.Contact.Account.Business_Org__c;
  private static String componentType = '';
  private static Map<String,Schema.RecordTypeInfo>  recordType = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName();

  /***********************************************************************************************************
  /* Returns Current user with region and business org
  ***********************************************************************************************************/
  private List<PortalBanner__c> lstPnlBanner;
  private PortalBanner__c m_portalBanner;

  public PortalBanner__c portalBanner {
    get {
      if (lstPnlBanner != null) {
        return m_portalBanner;
      }
      m_portalBanner = getPortalBannerRecord(userRegion);
      return m_portalBanner;
    }
  }
 
  /***********************************************************************************************************
  /* Returns Portal Banner Record based on region
  * @param region Region
  * @return PortalBanner__c.
  ***********************************************************************************************************/
  private PortalBanner__c getPortalBannerRecord(String region){
      PortalBanner__c portalBanner;
      //Retrieve current page name
      string pageName = EncodingUtil.urlEncode(ApexPages.currentPage().getUrl().replaceFirst('/apex/',''),'UTF-8').split('%3F',0)[0];	 
      lstPnlBanner = [Select id, Component_Type__c, Object__c, Content_Type_to_Query__c 
                         From PortalBanner__c 
                         Where Position__c = :pos 
                         And Region__c = :region   
                         AND Business_Org__c = :userBusinessOrg 
                         AND Page__c = :pageName
                         And RecordTypeId = :recordType.get('Panel').getRecordTypeId()];
      
      //There should only be one match for VF Page and Position (Filter: VF Page, Position, User Region, User Business Org, RecordTypeId)                           
      if (lstPnlBanner.size() == 1) {
        portalBanner = lstPnlBanner[0]; 
      }else if(lstPnlBanner.isEmpty()){
        //Query banner record again for region "Default"
        lstPnlBanner = [Select id, Component_Type__c, Object__c, Content_Type_to_Query__c 
                         From PortalBanner__c 
                         Where Position__c = :pos 
                         And Region__c = 'Default'   
                         AND Business_Org__c = :userBusinessOrg
                         AND Page__c = :pageName
                         And RecordTypeId = :recordType.get('Panel').getRecordTypeId()];
        if(!lstPnlBanner.isEmpty()){
            PortalBanner__c defaultPortalBanner = lstPnlBanner[0];
            //Check other portal records displayed on page to see if there is a matching component type
            List<PortalBanner__c> tempLstPnlBanner = [Select id, Component_Type__c, Object__c, Content_Type_to_Query__c 
                             From PortalBanner__c 
                             Where Position__c != null And Position__c != ''  
                             And Region__c = :region   
                             AND Business_Org__c = :userBusinessOrg
                             AND Page__c = :pageName
                             And RecordTypeId = :recordType.get('Panel').getRecordTypeId()
                             And Component_Type__c = :defaultPortalBanner.Component_Type__c
                             And Id != :defaultPortalBanner.Id];
            
          if(!tempLstPnlBanner.isEmpty()){
            componentType = defaultPortalBanner.Component_Type__c;
            addErrorMsg(Label.Error_Msg_For_Multiple_Portal_Widget_Record_Match_Found_For_Same_Component_Type);
          } else{
            portalBanner = defaultPortalBanner;
          }                 
        } else {
            componentType = '';
            addErrorMsg(Label.Error_Msg_For_No_Portal_Widget_Record_Match_Found_Portal_Home_Page);
        }
      }
    
    return portalBanner;
  }

  /***********************************************************************************************************
  /* Returns list of contents
  * @return List<ContentVersion> returns list of content versions.
  ***********************************************************************************************************/
  public List<ContentVersion> getContentList() {
    List<ContentVersion> contentList = new List<ContentVersion>();
    if (portalBanner.Content_Type_to_Query__c == null) {
      return contentList;
    }
    List<String> lstContentType = new List<String>();
    lstContentType = portalBanner.Content_Type_to_Query__c.split(';');
    
    for(ContentVersion contentVersion : [ Select c.Title, c.CreatedDate, c.Content_Type__c, c.ContentDocumentId, c.ContentURL 
                                          From ContentVersion c 
                                          Where Content_Type__c IN :lstContentType 
                                          And IsLatest = true
                                          //And Region__c = :userRegion
                                          //AND Business_Org__c = :userBusinessOrg
                                          order by CreatedDate DESC limit :(Integer)pobu.NumberOfItems__c]) {
      contentList.add(contentVersion);
    }
    return contentList;
  }

  /***********************************************************************************************************
  /* Returns top 5 ideas based on created date
  * @return List<Idea>
  ***********************************************************************************************************/
  public List<Idea> getIdeaList() {
    return [Select i.Title, i.CreatedDate From Idea i order by CreatedDate DESC limit :(Integer)pobu.NumberOfItems__c];
  }
  
  /***********************************************************************************************************
  /* Returns top 5 ideas based on created date
  * @return List<Idea>
  ***********************************************************************************************************/
  private void addErrorMsg(String msg) {
    msg = msg.replace('[Position]', pos);
    msg = msg.replace('[Region]', userRegion != null ? userRegion : '\'\'');
    msg = msg.replace('[Business Org]', userBusinessOrg != null ? userBusinessOrg : '\'\'');
    msg = msg.replace('[Component Type]', componentType != null ? componentType : '\'\'');
    
    if (portalBanner != null) {
      msg = msg.replace('[Object]', portalBanner.Object__c);
    } else {
        msg = msg.replace('[Object]', '\'\'');
    }
    if (errorMsg == null) {
      errorMsg = msg;
    } else {
      errorMsg += msg;
    }
  }

  /***********************************************************************************************************
  /* Returns content filter string
  * @return List<Idea>
  ***********************************************************************************************************/
  public String ContentFilterString {
    get {
        return PortalBannerUtil.getContentFilterString(portalBanner);
    }
  }   
  
}