objects/ContentType_Field_ID__c.object
<CustomObject>
    <fields>
        <fullName>Content_Type_ID__c</fullName>
        <label>Content Type ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assembly Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Let&apos;s Torque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Graphic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbook</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Announcement</fullName>
        <active>true</active>
        <label>Announcement</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pricebook</fullName>
        <active>true</active>
        <label>Price Book</label>
    </recordTypes>
</CustomObject>

classes/HomePageWidgetsCon.cls
/*
**************************************************************************************
Name                : HomePageWidgetsCon
Author              : Harshit Jain (Appirio offshore)
createdDate                 : 14 august,2012
Description         : This class is used for HomePageWidgets component.
Modified            : Erin Fink ~ 13 Nov 12 - changed return limit for contentVersion from 3 to 5
***************************************************************************************    
*/
public with sharing class HomePageWidgetsCon {
    /*************************************************************************************
    Getter Setter Properties
    **************************************************************************************/
    public String ContentType{get; set;}     
    
   /************************************************************************************
     get content list available in login user shared library.
    **************************************************************************************/
    public List<ContentVersion> getWidgetsList() {
        List<ContentVersion>    widgetsList = new List<ContentVersion>();
        for(ContentVersion contentVersion : [Select c.Title, c.CreatedDate, c.Content_Type__c, c.ContentDocumentId From ContentVersion c where Content_Type__c =:ContentType and IsLatest=true order by CreatedDate DESC limit 5]) {
            widgetsList.add(contentVersion);
        }
        return  widgetsList;
    }
    
    public List<ContentVersion> getPricingWidgetsList() {
    	List<String> lstContentType = new List<String>();
    	lstContentType.add('Pricebook');
    	lstContentType.add('Price File');
    	lstContentType.add('Pricing tool');
    	
        List<ContentVersion> widgetsList = new List<ContentVersion>();
        for(ContentVersion contentVersion : [Select c.Title, c.CreatedDate, c.Content_Type__c, c.ContentDocumentId From ContentVersion c where Content_Type__c IN :lstContentType and IsLatest=true order by CreatedDate DESC limit 5]) {
            widgetsList.add(contentVersion);
        }
        return  widgetsList;
    }
    
    public List<ContentVersion> getTechnicalLiteratureWidgetsList() {
    	List<String> lstContentType = new List<String>();
    	lstContentType.add('Technical Literature');
    	lstContentType.add('Service Bulletin');
    	
        List<ContentVersion> widgetsList = new List<ContentVersion>();
        for(ContentVersion contentVersion : [Select c.Title, c.CreatedDate, c.Content_Type__c, c.ContentDocumentId From ContentVersion c where Content_Type__c IN :lstContentType and IsLatest=true order by CreatedDate DESC limit 5]) {
            widgetsList.add(contentVersion);
        }
        return  widgetsList;
    }
    
    public String getContentFilterString(){
        String contentTypeFieldID = ContentType_Field_ID__c.getOrgDefaults().Content_Type_ID__c;
        contentTypeFieldID = '"'+contentTypeFieldID+'":["';
        if (ContentType.equals('Technical Literature')) {
            contentTypeFieldID = contentTypeFieldID+'9';
        }else if (ContentType.equals('Service Bulletin')) {
            contentTypeFieldID = contentTypeFieldID+'8';
        } else  if (ContentType.equals('Announcement')) {
            contentTypeFieldID = contentTypeFieldID+'1';
        } else if (ContentType.equals('Product Information Bulletin')) {
            contentTypeFieldID = contentTypeFieldID+'7';
        } else if (ContentType.equals('Pricing')) {
            contentTypeFieldID = contentTypeFieldID+'6","5","4';
        }
        contentTypeFieldID = '{'+contentTypeFieldID+'"]}';
        return contentTypeFieldID;      
    }
}