objects/Content_Viewer__c.object
<CustomObject>
    <description>When a portal user view a content, we need to keep track of that user in a custom object so that Sauer Danfoss can report on them.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Content Viewers</relationshipLabel>
        <relationshipName>Content_Viewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Id__c</fullName>
        <description>stores the content id that is being viewed</description>
        <label>Content Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Library__c</fullName>
        <description>Library name of the content</description>
        <label>Content Library</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Title__c</fullName>
        <description>stores the content title that is being viewed</description>
        <label>Content Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>logged in user id</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Viewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Viewer</label>
    <nameField>
        <label>Content Viewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Viewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Content_ID__c</fullName>
        <description>Bulletin Number, SAP Literature Number, Std Work Number</description>
        <inlineHelpText>Enter the Publication Number of the Document you are loading, if one is available.</inlineHelpText>
        <label>Content ID</label>
        <length>35</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CustomFooterComponentController.cls
/*
Class : CustomFooterComponentController 
Description :  This class is used for entering user info into Content Viewer object when user sees a content.
Created By	:	Manmeet Manethiya
Modified by : Manmeet Manethiya
Modified Date : Aug 3, 2012
*/
public with sharing class CustomFooterComponentController {
	
		private String documentId;
		private User user;
		//constructor
		public CustomFooterComponentController(){
			if(ApexPages.currentPage().getParameters().get('documentId') != null){
				documentId = ApexPages.currentPage().getParameters().get('documentId');
			}
		}
		//inserting Content_Viewer__c record
		public Pagereference insertContentViewerInfo(){
			if(isPartnerUser()){
				ContentWorkspaceDoc ctWorkSpace = new ContentWorkspaceDoc();
				for(ContentWorkspaceDoc obj : [Select c.SystemModstamp, c.IsOwner, c.IsDeleted, c.Id, c.CreatedDate, c.ContentWorkspace.name,
				 															c.ContentDocumentId, ContentDocument.title From ContentWorkspaceDoc c where c.ContentDocumentId =: documentId order by id asc limit 1]){
				 		ctWorkSpace = obj;
				 }
				 string Content_Version_Id = '';
				 for(ContentVersion verObj : [Select Id, versionnumber From ContentVersion where ContentDocumentId=:documentId order by versionnumber desc limit 1]){
				 	Content_Version_Id= verObj.id+'';
				 }
				 system.debug('***********Content_Version_Id:'+Content_Version_Id+', '+documentId);
				 Content_Viewer__c insertCnt= new Content_Viewer__c(name = UserInfo.getFirstName() + ' ' + UserInfo.getLastName(), User__c = UserInfo.getUserId(), 
																		Content_Id__c = ctWorkSpace.ContentDocumentId,
																		Content_Library__c = ctWorkSpace.ContentWorkspace.name,
																		Content_Title__c = ctWorkSpace.ContentDocument.title,
																		contact__c = user.contactID,
																		Content_Version_Id__c= Content_Version_Id);
				insert insertCnt;	
				system.debug('***********Content_Version_Id:'+Content_Version_Id+', '+documentId);
			} 
			return null; 
		}
		//checking whether the user is partner or not
		public boolean isPartnerUser(){
			user = new User();
			for(User usr : [select name, firstname, lastname, id , contactID from User where id  = : UserInfo.getUserId()]){
				user = usr;
			}
			return user.contactID != null ? true : false;
		}
}