objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assembly Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Let&apos;s Torque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Graphic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Image</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbook</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expert_Tool__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The expert tool lookup</description>
        <label>Installation Instructions</label>
        <referenceTo>Expert_Tools__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Tools</fullName>
        <active>true</active>
        <label>Tools</label>
    </recordTypes>
</CustomObject>

objects/Expert_Tools__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Expert Tool Category</description>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Performance/Life Prediction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sizing/Selection</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Expert Tool Instructions</description>
        <label>Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
</CustomObject>

objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Type_to_Query__c</fullName>
        <label>Content Type to Query</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assembly Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Let&apos;s Torque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbook</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Tools</fullName>
        <active>true</active>
        <description>Portal Banner used for the Tools VisualForce Page</description>
        <label>Tools</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_ToolsController.cls
/*************************************************************************
Name                : Test_ToolsController
Author              : Diana Losey
CreatedDate         : Jan 4 2016
Description         : This is a test class for ToolsController
*************************************************************************/
@isTest
private class Test_ToolsController {

    static User adminUser;
    static User testUser;

	@isTest static void testToolsPage() {
		createTestData();
        //String testString;
        system.runAs(testUser){
             test.startTest();
             ToolsController controller = new ToolsController();

             test.stopTest();
        }

       //system.assertEquals(testString, 'Comatrol');
    }

    private static void createTestData(){
        Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
        UserRole roles = [Select id from UserRole where Name = 'CRM_SysAdmin PS' limit 1];
        adminUser = Test_Utility.createUser(profile.Id,roles.Id, 1);
        insert adminUser;
        //List<Group> grpList =[Select g.Id From Group g where Name = '*Danfoss Power Solutions'];
        //system.assertEquals(grpList.size(), 1);
        //Assign user to intergrated group to provide access on account record
        //GroupMember groupMember = new GroupMember(UserOrGroupId = adminUser.Id,GroupId = grpList.get(0).Id);
        //insert groupMember;

        system.runAs(adminUser) {
            Profile delegatedAdminProfile = [Select Name,Id From Profile p Where Name = 'PartnerLink - Delegated Admin' Limit 1];
            Account account = Test_Utility.createAccount(1);
            insert account;
            Contact contact = Test_Utility.createContact(account.id, 1);
            insert contact;
            testUser = Test_Utility.createPortalUser(contact.id, delegatedAdminProfile.id);
            testUser.Business_Org__c = 'Integrated';
            insert testUser;


            RecordType bannerRecordType =  [select Id FROM RecordType WHERE Name='Tools' AND sObjectType = 'PortalBanner__c'];
            PortalBanner__c testBanner = test_Utility.createPortalBanner(false, 'Left');
            testBanner.RecordTypeId = bannerRecordType.Id;
            testBanner.Region__c = 'default';
            testBanner.Page__c = 'Tools';
            testBanner.Business_Org__c = 'Integrated';
            testBanner.Content_Type_to_Query__c = 'Tools';
            insert testBanner;

            RecordType ContentRT = [select Id FROM RecordType WHERE Name='Tools' AND sObjectType = 'ContentVersion'];
            ContentVersion testContentInsert =new ContentVersion();
            testContentInsert.ContentURL='www.google.com';
            testContentInsert.Title ='Google.com';
            testContentInsert.RecordTypeId = ContentRT.Id;
            insert testContentInsert;

            ContentVersion testContent = [SELECT ContentDocumentId FROM ContentVersion where Id = :testContentInsert.Id];

            ContentWorkspace testWorkspace = [SELECT Id FROM ContentWorkspace WHERE Name='*PS Public Content'];
            ContentWorkspaceDoc newWorkspaceDoc =new ContentWorkspaceDoc();
            newWorkspaceDoc.ContentWorkspaceId = testWorkspace.Id;
            newWorkspaceDoc.ContentDocumentId = testContent.ContentDocumentId;
            insert newWorkspaceDoc;

            Expert_Tools__c et = new Expert_Tools__c(Name = 'Test', Category__c = 'Pricing Tools', Description__c = 'Test, test, test');
            insert et;

            testContent.Expert_Tool__c = et.Id;
            testContent.Content_Type__c = 'Tools';
            testContent.Region__c = 'Americas';
            update testContent;

            Attachment testAttachment = test_utility.createAttachment(et.Id, true);
        }
    }

}