objects/Contact_Team__c.object
<CustomObject>
    <description>For CE - we will have a list of users associted with a contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Team Members</relationshipLabel>
        <relationshipName>Contact_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Team Member</label>
    <nameField>
        <label>Contact Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/ContactTeamDivisionsExtension.cls
public class ContactTeamDivisionsExtension {
// DANFOSS - JPK 02-12-2014 
    public String udivs { get; set; }
    
    public ContactTeamDivisionsExtension(ApexPages.StandardController stdController) {
        List<String> divisions = new List<String>();
        for (AggregateResult ar : [select User__r.Division__c div from Contact_Team__c where Contact__c = :stdController.getId() and User__r.Division__c != null group by User__r.Division__c order by User__r.Division__c]) {
            divisions.add((String) ar.get('div'));
        }
        udivs = String.join(divisions, ', ');
    }
}