objects/ContentType_Field_ID__c.object
<CustomObject>
    <fields>
        <fullName>Content_Type_ID__c</fullName>
        <label>Content Type ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <picklist>
            <controllingField>Object__c</controllingField>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentation Archives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Signature Guidelines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Handbook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need A Logo?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Releases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing &amp; Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Items</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbooks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Tools</fullName>
        <active>true</active>
        <description>Portal Banner used for the Tools VisualForce Page</description>
        <label>Tools</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalBannerUtil.cls
/*************************************************************************************************************
* @author Neeraj (Appirio Ind.)
* @date 12/3/2013
* @Story S-162787
* @description Utility class for portalbanner object related queries
*************************************************************************************************************/
public with sharing class PortalBannerUtil {
   
  /***********************************************************************************************************
  /* Returns jsonString for content Type default filter
  * @param portalBanner PortalBanner__c object
  * @return String.
  ***********************************************************************************************************/
  public static String getContentFilterString(PortalBanner__c portalBanner){
    String contentTypeFieldID = ContentType_Field_ID__c.getOrgDefaults().Content_Type_ID__c;
    
    Set<String> lstContentType = new Set<String>();
    lstContentType.add(portalBanner.Component_Type__c);
    system.debug('content type to query: ' + lstContentType);
    contentTypeFieldID = '{"'+contentTypeFieldID+'":[';
    if (lstContentType.contains('Technical Literature')) {
      contentTypeFieldID += '"9",';
    }
    if (lstContentType.contains('Service Bulletin')) {
      contentTypeFieldID += '"8",';
    } 
    if (lstContentType.contains('Announcement')) {
      contentTypeFieldID += '"1",';
    } 
    if (lstContentType.contains('Product Information Bulletin')) {
      contentTypeFieldID += '"7",';
    } 
    if (lstContentType.contains('Pricing & Tools')) {
      contentTypeFieldID += '"13","6","5","11",';
    }
    if (lstContentType.contains('Unique Selling Points Handbooks')) {
      contentTypeFieldID += '"17",';
    } 
    if (lstContentType.contains('Let\'s Torque E-Newsletters')) {
      contentTypeFieldID += '"18",';
    } 
    if (lstContentType.contains('Press Releases')) {
      contentTypeFieldID += '"19",';
    }
    if (lstContentType.contains('Customer Presentation Archives')) {
      contentTypeFieldID += '"20",';
    } 
    contentTypeFieldID = contentTypeFieldID.removeEnd(',');
    contentTypeFieldID += ']}';
	 system.debug('contentTypeFieldID: ' + contentTypeFieldID);
    return contentTypeFieldID;      
  }
}