objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <label>Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Collaboration</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>File_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <label>File Attached ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CNT-{000000000}</displayFormat>
        <label>Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Contract Attachments</relationshipLabel>
        <relationshipName>Contract_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>1. Rough Drafts/Supporting Documents</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Final Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Signed Document(s)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Attachments</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractAttachController.cls
public with sharing class ContractAttachController 
{
    public Contract_Attachment__c contAtt{get;set;}
    public Attachment attach {get;set;}
	Contract__c contract;

    public ContractAttachController(ApexPages.StandardController controller) {
        contAtt = [select Name, Contract__c, Type__c, Title__c from Contract_Attachment__c where Id = :controller.getRecord().id];
        attach = new Attachment();
		contract = [select Id, Contract_Status__c, File_Attached__c from Contract__c where Id = :contAtt.Contract__c];
    }

    public ApexPages.Pagereference upload()
    {
		ApexPages.getMessages().clear();
		if(attach.Name == null){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'You must choose a file before uploading.'));
            return null;
		}
		else{	
			attach.ParentId = contAtt.Id;
			insert attach;      
			contAtt.Title__c = attach.Name;
			update contAtt;
			contract.File_Attached__c = true;
			update contract;
			PageReference np = new PageReference('/' + contAtt.Contract__c); 
			np.setRedirect(true);
			return np;   
		}
    }
    
    public List<Attachment> getAttachments() {
        Map<Id, List<Attachment>> mapAttachments = new Map<Id, List<Attachment>>();
        List<Attachment> lstAttachments = new List<Attachment>();
        Set<Id> parentIds = new Set<Id>();
        List<Contract_Attachment__c> lstContAtt = [select Id, Name, Type__c from Contract_Attachment__c where Id=:contAtt.id ];
        lstAttachments = [Select Id, Name, body, ParentId From Attachment Where ParentId = :contAtt.Id];
        return lstAttachments;
    }
	
	public PageReference saveandReturn() {		
	    try {    
			upsert contAtt;
	    }
	    catch(DmlException ex) {
	        ApexPages.addMessages(ex);
	        return null;
	    }    
	    return new PageReference('/' + contract.Id);
  }
	
	public PageReference cancel() {
		System.debug(attach);
		if(attach.Name == null)
			delete contAtt;
    	return new PageReference('/' + contract.Id);
  }
    
}