objects/Customer_Part_Number__c.object
<CustomObject>
    <description>List of Customer specific part numbers for each Product.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Part Number</label>
    <nameField>
        <displayFormat>CPR-{0000000}</displayFormat>
        <label>Customer Part Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Part Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus3__c</fullName>
        <label>2015</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Content_per_Machine__c</fullName>
        <label>Average Content per Machine</label>
        <precision>13</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Share_of_Wallet__c</fullName>
        <label>Danfoss Share of Wallet (in %)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Machine_Potential__c</fullName>
        <inlineHelpText>Based on 2015 volume</inlineHelpText>
        <label>Total Annual Machine Potential</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Customer_Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Number__c</fullName>
        <formula>Machine_Model_Product__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Material Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <formula>TEXT(Machine_Model_Product__r.Business_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Share_of_Wallet__c.object
<CustomObject>
    <description>Contains the Share Of Wallet (SoW) on the Account Object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Share of Wallets</relationshipLabel>
        <relationshipName>Share_of_Wallets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Share of Wallet</label>
    <nameField>
        <displayFormat>SoW-{00000}</displayFormat>
        <label>Share of Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share of Wallet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MachineProductTriggerHandler.cls
/**
	Author: Erin Fink
	Date: 14MAY15
	Version 1.0
**/

public with sharing class MachineProductTriggerHandler{
	public static boolean hasTriggerExecuted = false;

	public static void UpdatePartNumbers(List<Machine_Model_Product__c> lstProducts){		//BEFORE
		List<Machine_Model_Product__c> lstmmprod = new List<Machine_Model_Product__c>();
	    Set<Id> setMMProdIds = new Set<Id>();
	    Map<Id, Id> mapMMAcct = new Map<Id, Id>();
	    for (Machine_Model_Product__c mmprod :lstProducts) {
	            lstmmprod.add(mmprod);
	            setMMProdIds.add(mmprod.Machine_Model_Product__c);
	            mapMMAcct.put(mmprod.Machine_Model__c, NULL);
	    }
	    for(Machine_Model__c machine: [SELECT Id,Account__c FROM Machine_Model__c WHERE Id IN : mapMMAcct.keySet()]) {
	        mapMMAcct.put(machine.Id,machine.Account__c);
	    }
	    map<String,Customer_Part_Number__c> mapCustomerPartNumber = new map<String,Customer_Part_Number__c>(); 
	      for(Customer_Part_Number__c part : [SELECT Material_Number__c,Id,Account__c,Product__c 
	                          FROM Customer_Part_Number__c WHERE Account__c IN :mapMMAcct.values() AND Product__c IN :setMMProdIds]) {
	        mapCustomerPartNumber.put(part.Account__c+'-'+part.Product__c,part);
	      }
	    
	    for (Machine_Model_Product__c mmprod :lstmmprod) {
	        mmprod.Name = mmprod.SAP_Material_Number__c;
	        String key = mapMMAcct.get(mmprod.Machine_Model__c) + '-' + mmprod.Machine_Model_Product__c;
	        if(mapCustomerPartNumber.containsKey(key)) {
	          mmprod.Customer_Material_Number__c = mapCustomerPartNumber.get(key).Material_Number__c;
	        }
	    }
	}
	
	public static void UpdateMachineAndAcctMetrics(List<Machine_Model_Product__c> lstProducts, List<Machine_Model_Product__c> lstProductsOLD, Boolean isDelete, Boolean isInsert){		//AFTER
		double totalAvgContentPerMachine = 0;
		double SDtotalAvgContentPerMachine = 0;
		double totalTMP = 0; 
		double totalavgContentPerAccount = 0;
		double SDtotalavgContentPerAccount = 0;
		double acctCurrency;
		double exchangeRate = 1.00;
		Map<String, Double> mapCurrency = new Map<String, Double>(); 
		List<CurrencyType> lstCurrency = [Select ConversionRate,IsoCode From CurrencyType];
		Map<Id, List<Machine_Model_Product__c>> mapMachineIdAndLstProds = new Map<Id, List<Machine_Model_Product__c>>(); 
		Map<Id, List<Machine_Model__c>> mapAcctIdAndLstMachines = new Map<Id, List<Machine_Model__c>>(); 
		List<Account> lstAccounts = new List<Account>();
		List<Machine_Model__c> lstMachines = new List<Machine_Model__c>();
		List<Machine_Model_Product__c> lstmmprod = new List<Machine_Model_Product__c>();
		set<Id> setMachineIds = new set<Id>();
		set<Id> setAcctIds = new set<Id>();

		hasTriggerExecuted = true;
		for (CurrencyType c :lstCurrency)
		    mapCurrency.put(c.IsoCode, c.ConversionRate);
		system.debug('lstProducts: ' + lstProducts);
		if (isDelete) {
		    for (Machine_Model_Product__c prod : lstProductsOLD) {
				setMachineIds.add(prod.Machine_Model__c);
				if(!mapMachineIdAndLstProds.containsKey(prod.Machine_Model__c))
					mapMachineIdAndLstProds.put(prod.Machine_Model__c, new List<Machine_Model_Product__c>());
		   }
		}
		else if (isInsert) {
		    for (Machine_Model_Product__c prod : lstProducts) {
				setMachineIds.add(prod.Machine_Model__c);
				if(!mapMachineIdAndLstProds.containsKey(prod.Machine_Model__c))
					mapMachineIdAndLstProds.put(prod.Machine_Model__c, new List<Machine_Model_Product__c>());
		   }
		}
		else {
			for (Machine_Model_Product__c prod : lstProducts) {
				setMachineIds.add(prod.Machine_Model__c);
		    }
		}	
		
		system.debug('mapMachineIdAndLstProds: ' + mapMachineIdAndLstProds);
		
		for(Machine_Model__c mach :[SELECT Account__c FROM Machine_Model__c where Id IN :setMachineIds]){
			setAcctIds.add(mach.Account__c);
		}
		lstAccounts = [SELECT Name, CurrencyIsoCode, Aggregate_Wallet_Share__c, Aggregate_Potential__c 
					   FROM Account WHERE Id IN :setAcctIds];	
		if(isDelete || isInsert){
			lstMachines = [SELECT Name, Account__c, Total_Machine_Potential__c, Annual_Production_Volume_Plus3__c, Average_Content_per_Machine__c, Share_of_Wallet__c 
					  	   FROM Machine_Model__c where Account__c IN :setAcctIds]; 	
		}
		else{
			lstMachines = [SELECT Name, Account__c, Total_Machine_Potential__c, Annual_Production_Volume_Plus3__c, Average_Content_per_Machine__c, Share_of_Wallet__c 
					  	   FROM Machine_Model__c where Total_Machine_Potential__c != NULL and Total_Machine_Potential__c != 0 and Account__c IN :setAcctIds]; 
		}
		for(Machine_Model__c machine :lstMachines){
			if(!setMachineIds.contains(machine.Id))
				setMachineIds.add(machine.Id);
		}
		lstmmprod = [SELECT Adoption_Rate__c, Price__c, CurrencyIsoCode, Number_Per_Machine__c, Supplier__c, Machine_Model__c 
					   FROM Machine_Model_Product__c where IsDeleted = false and Machine_Model__c IN :setMachineIds];
		for(Machine_Model_Product__c p :lstmmprod){
			if(!mapMachineIdAndLstProds.containsKey(p.Machine_Model__c))
				mapMachineIdAndLstProds.put(p.Machine_Model__c, new List<Machine_Model_Product__c>());
			set<Machine_Model_Product__c> setProducts = new set<Machine_Model_Product__c>(mapMachineIdAndLstProds.get(p.Machine_Model__c));
			if(!setProducts.contains(p))
				if(mapMachineIdAndLstProds.containsKey(p.Machine_Model__c))
					mapMachineIdAndLstProds.get(p.Machine_Model__c).add(p);
		}
		for(Machine_Model__c machine :lstMachines){
			if(mapMachineIdAndLstProds.containsKey(machine.Id)){
				if(!mapAcctIdAndLstMachines.containsKey(machine.Account__c)){
					mapAcctIdAndLstMachines.put(machine.Account__c, new List<Machine_Model__c>());
				}
				mapAcctIdAndLstMachines.get(machine.Account__c).add(machine);
			}
		}	
		system.debug('lstmmprod: ' + lstmmprod);
		system.debug('lstMachines: ' + lstMachines);
		if(!lstmmprod.isEmpty() && !lstMachines.isEmpty()){ 			
			system.debug('mapAcctIdAndLstMachines: ' + mapAcctIdAndLstMachines);
			system.debug('mapMachineIdAndLstProds: ' + mapMachineIdAndLstProds);			
			for(Account acct :lstAccounts){
				totalavgContentPerAccount = 0;
				acctCurrency = mapCurrency.get(acct.CurrencyIsoCode);
				for(Machine_Model__c machine :mapAcctIdAndLstMachines.get(acct.Id)){
					totalAvgContentPerMachine = 0;
					SDtotalAvgContentPerMachine = 0;
					for(Machine_Model_Product__c p :mapMachineIdAndLstProds.get(machine.id)){
						exchangeRate = mapCurrency.get(p.CurrencyIsoCode);
					    if (p.Adoption_Rate__c != null && p.Price__c != null && p.Number_Per_Machine__c != null) 
					        totalAvgContentPerMachine += ((p.Price__c / exchangeRate) * p.Number_Per_Machine__c * (p.Adoption_Rate__c/100));   
					    if (p.Adoption_Rate__c != null && p.Price__c != null && p.Number_Per_Machine__c != null && p.Supplier__c == 'Danfoss')    
					        SDtotalAvgContentPerMachine += ((p.Price__c / exchangeRate) * p.Number_Per_Machine__c * (p.Adoption_Rate__c/100));
					}
					totalavgContentPerAccount += totalAvgContentPerMachine * machine.Annual_Production_Volume_Plus3__c;
					SDtotalavgContentPerAccount += SDtotalAvgContentPerMachine * machine.Annual_Production_Volume_Plus3__c;
					//Wallet Share for machine
					if (totalAvgContentPerMachine > 0) 
					    machine.Share_of_Wallet__c = ((SDtotalAvgContentPerMachine * acctCurrency)/(totalAvgContentPerMachine * acctCurrency))*100;
					else
					    machine.Share_of_Wallet__c = 0;
					machine.Average_Content_per_Machine__c = totalAvgContentPerMachine * acctCurrency;
					if (machine.Annual_Production_Volume_Plus3__c != null)
					    machine.Total_Machine_Potential__c = machine.Annual_Production_Volume_Plus3__c * totalAvgContentPerMachine * acctCurrency;
					else
					    machine.Total_Machine_Potential__c = 0;
					if (machine.Total_Machine_Potential__c != null)
		        		totalTMP += machine.Total_Machine_Potential__c;
				}
				update mapAcctIdAndLstMachines.get(acct.Id);
				acct.Aggregate_Potential__c = totalTMP;
				//Wallet Share for acct
				if (totalavgContentPerAccount > 0) 
				    acct.Aggregate_Wallet_Share__c = ((SDtotalavgContentPerAccount * acctCurrency)/(totalavgContentPerAccount * acctCurrency))*100;
				else
				    acct.Aggregate_Wallet_Share__c = 0;
				}
			update lstAccounts;	
			}
		else{
			system.debug('lstMachines: ' + lstMachines);
			for(Account acct :lstAccounts){
				for(Machine_Model__c machine :lstMachines){
					system.debug('machine: ' + machine);
					machine.Share_of_Wallet__c = 0;
					machine.Total_Machine_Potential__c = 0;
					machine.Average_Content_per_Machine__c = 0;
				}
				update lstMachines;
				system.debug('lstMachines: ' + lstMachines);
				acct.Aggregate_Potential__c = 0;
				acct.Aggregate_Wallet_Share__c = 0;
			}
			update lstAccounts;	
		}
	}
}