objects/Customer_Part_Number__c.object
<CustomObject>
    <description>List of Customer specific part numbers for each Product.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Material_Id__c</fullName>
        <description>Unique key reference for integration.
&lt;Sales org&gt;-&lt;Account Id&gt;-&lt;Productid&gt; combination</description>
        <externalId>true</externalId>
        <label>SAP Customer Material Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Part Number</label>
    <nameField>
        <displayFormat>CPR-{0000000}</displayFormat>
        <label>Customer Part Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Part Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Exclusive_Material__c.object
<CustomObject>
    <description>This will serve as a junction object between Account and Product2.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Exclusive_Material_Id__c</fullName>
        <externalId>true</externalId>
        <label>SAP Exclusive Material Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Exclusive Material</label>
    <nameField>
        <displayFormat>EPR-{0000000}</displayFormat>
        <label>Exclusive Material Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus2__c</fullName>
        <label>2014</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus3__c</fullName>
        <label>2015</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume__c</fullName>
        <label>Production Volume - 2012</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <description>This field shows the customer machine model number.</description>
        <inlineHelpText>Enter the customer&apos;s machine model.  Example: 820C, 810C, etc.</inlineHelpText>
        <label>Machine Model Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_CustomerPartNumberTrigger.cls
@isTest
private class Test_CustomerPartNumberTrigger {
	static User adminUser;
	static Region__c usaRegion;
	static Id StdPBId;
	static PriceBookEntry stdpbe;
	static Product2 product;
	
	static testMethod void testDeleteCustomerPartNumberTriggerQuote() {
		createUsers();
		system.runAs(adminUser) {
			createTestData();
			Account account = Test_Utility.createAccount(3);
			insert account;
			Opportunity oppty = Test_Utility.createOpportunity(account.Id, 1);
			insert oppty;
			OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppty.Id,PriceBookEntryId = stdpbe.Id,UnitPrice = 10,Quantity =10);
        	insert oli;
			/*Quote quote = new Quote(OpportunityId = oppty.Id, Name = 'qli', PriceBook2Id = StdPBId, Country_Specific_Template__c = usaRegion.Id);
			insert quote;
			QuoteLineItem qli = new QuoteLineItem(QuoteId = quote.Id, PriceBookEntryId = stdpbe.Id, UnitPrice = 10, Quantity = 10);
			insert qli;*/
			Machine_Model__c machine = new Machine_Model__c(Name = 'mach', Account__c = account.Id, Annual_Production_Volume__c = 10, Annual_Production_Volume_Plus2__c = 10, Annual_Production_Volume_Plus3__c = 10);
			insert machine;
			Machine_Model_Product__c mli = new Machine_Model_Product__c(Machine_Model__c = machine.Id, Machine_Model_Product__c = product.Id);
			insert mli;
			Test.startTest();
			List<Customer_Part_Number__c> lstCPNs = new List<Customer_Part_Number__c>();
			Customer_Part_Number__c part = new Customer_Part_Number__c(Material_Number__c = '123456-ABCDE', Account__c = account.Id, Product__c = product.Id, SAP_Customer_Material_Id__c = '123477');
			lstCPNs.add(part);
			Customer_Part_Number__c part2 = new Customer_Part_Number__c(Material_Number__c = '123456-ABCDE', Account__c = account.Id, Product__c = product.Id, SAP_Customer_Material_Id__c = '123455');
			lstCPNs.add(part2);
			if(!lstCPNs.isEmpty())
				insert lstCPNs;
			part.isDeleted__c = true;
			part2.Material_Number__c = '123';
			update lstCPNs;
			/*Customer_Part_Number__c part3 = new Customer_Part_Number__c(Material_Number__c = '123456-ABCDE', Account__c = account.Id, SAP_Customer_Material_Id__c = '123453');
			insert part3;*/
			
			Exclusive_Material__c excl = new Exclusive_Material__c(Account__c = account.Id, SAP_Exclusive_Material_Id__c = '1234', Product__c = product.Id);
			insert excl;
			/*Exclusive_Material__c excl1 = new Exclusive_Material__c(Account__c = account.Id, SAP_Exclusive_Material_Id__c = '12345', Product__c = product.Id);
			insert excl1;*/
			excl.isDeleted__c = true;
			update excl;
			/*excl1.isDeleted__c = true;
			update excl1;*/
			Test.stopTest();
		}
	}

	private static void createTestData(){
    	Test_Utility.initTestData();   //create C&E pricebook
		product = Test_Utility.createProduct2();
		product.SAP_Material_Code__c = '1234';
		insert product;
		StdPBId = Test.getStandardPricebookId();
		stdpbe = new PricebookEntry(Pricebook2Id = StdPBId, Product2Id = product.Id, UnitPrice = 100, IsActive = true, CurrencyISOCode = 'DKK');
		insert stdpbe;
		usaRegion = new Region__c(Name = 'USA', Country_Code__c = 'US', Region__c = 'Americas');
		insert usaRegion;
	}
	
	private static void createUsers() {
		Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
		UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
		adminUser = Test_Utility.createUser(profile.Id, roles.Id, 1);
		adminUser.DelegatedApproverId = UserInfo.getUserId();
		insert adminUser;
	}
}