objects/Customer_Part_Number__c.object
<CustomObject>
    <description>List of Customer specific part numbers for each Product.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Material_Id__c</fullName>
        <description>Unique key reference for integration.
&lt;Sales org&gt;-&lt;Account Id&gt;-&lt;Productid&gt; combination</description>
        <externalId>true</externalId>
        <label>SAP Customer Material Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Part Number</label>
    <nameField>
        <displayFormat>CPR-{0000000}</displayFormat>
        <label>Customer Part Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Part Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Exclusive_Material__c.object
<CustomObject>
    <description>This will serve as a junction object between Account and Product2.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Exclusive_Material_Id__c</fullName>
        <externalId>true</externalId>
        <label>SAP Exclusive Material Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Exclusive Material</label>
    <nameField>
        <displayFormat>EPR-{0000000}</displayFormat>
        <label>Exclusive Material Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_AddProducts.cls
@isTest(SeeAllData=true)
private class Test_AddProducts {
    
    static testMethod void testSearchProduct() {
           Account account = Test_Utility.createAccount(1);
      insert account; 
      Pricebook2 pricebook= [SELECT Id FROM PriceBook2 WHERE IsStandard=True];
      pricebook.IsActive = true;
      update pricebook;
      Pricebook2 pricebook1 = [SELECT Id FROM PriceBook2 WHERE NAME = 'Danfoss'];        
      
      Opportunity oppty = Test_Utility.createOpportunity(account.Id, 1);
      oppty.currencyIsoCode = 'USD';
      insert oppty;  
      Product2 product = Test_Utility.insertProduct2();
      PriceBookEntry pbe = [select Id, UnitPrice from PriceBookEntry where Product2Id = :product.Id and Pricebook2Id = :pricebook.Id and CurrencyISOCode = 'USD']; 
    
      pbe = Test_Utility.createPricebookEntry(product.Id, pricebook1.Id, 'USD'); 
      insert pbe; 
      
      Region__c reg = [select Id From Region__c limit 1];
      Quote q = new Quote(name='Erin test quote', OpportunityId = Oppty.Id, Country_Specific_Template__c = reg.Id);
      insert q;
      Customer_Part_Number__c cpn = new Customer_Part_Number__c();
      cpn.Account__c = account.Id;
      cpn.Material_Number__c = '12345-ABCDE';
      cpn.Product__c = product.Id;
      cpn.SAP_Customer_Material_Id__c = 'qwerty';
      insert cpn;
      Exclusive_Material__c em = new Exclusive_Material__c();
      em.Account__c = account.Id;
      em.Product__c = product.Id;
      em.SAP_Exclusive_Material_Id__c = '1234';
      insert em;
        PageReference pg = Page.AddOpportunityProduct;
        Test.setCurrentPage(pg);
        ApexPages.currentPage().getParameters().put('id',oppty.Id);
        ApexPages.currentPage().getParameters().put(product.Id,'1'); 
        AddProducts add = new AddProducts();
        add.Name = 'TestProduct*';
        add.ProductCode = 'x';
        add.Model_Code = 'x';
        add.Family = 'x';
        add.ProductSet = 'x';
        add.ProductLine = 'x';
        add.doSort();
        add.Search();
        add.SelectProduct(); 
        add.cancel();
              PageReference pgq = Page.AddQuoteProduct;
              Test.setCurrentPage(pgq);
              ApexPages.currentPage().getParameters().put('id',q.Id);
              ApexPages.currentPage().getParameters().put(product.Id,'1'); 
              add = new AddProducts();
              add.Name = 'TestProduct*';
              add.doSort();        
              add.Search();
              add.SelectProduct();      
              add.cancel();
           /*   AddLDIProducts addldi = new AddLDIProducts();
              addldi.Name = 'TestProduct*';
              addldi.doSort();
              addldi.Search();
              addldi.SelectProduct();      
              addldi.cancel();*/
      
    }  
}