objects/Customer_Part_Number__c.object
<CustomObject>
    <description>List of Customer specific part numbers for each Product.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Customer Part Numbers</relationshipLabel>
        <relationshipName>Customer_Part_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Customer_Material_Id__c</fullName>
        <description>Unique key reference for integration.
&lt;Sales org&gt;-&lt;Account Id&gt;-&lt;Productid&gt; combination</description>
        <externalId>true</externalId>
        <label>SAP Customer Material Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Part Number</label>
    <nameField>
        <displayFormat>CPR-{0000000}</displayFormat>
        <label>Customer Part Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Part Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus1__c</fullName>
        <label>2013</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus2__c</fullName>
        <label>2014</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus3__c</fullName>
        <label>2015</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume__c</fullName>
        <label>Production Volume - 2012</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Machine_Potential__c</fullName>
        <inlineHelpText>Based on 2015 volume</inlineHelpText>
        <label>Total Annual Machine Potential</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Competitiveness__c</fullName>
        <inlineHelpText>Your perceived competitiveness of Danfoss with regards to this product in this machine model</inlineHelpText>
        <label>Danfoss Competitiveness</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subsystem__c</fullName>
        <label>Machine Function</label>
        <picklist>
            <picklistValues>
                <fullName>Steering Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HMI and Electronics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parker</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Test_MachineTrigger.cls
@isTest //(SeeAllData=true)
private class Test_MachineTrigger {

    static testMethod void myUnitTest() {
        Test_Utility.initTestData();   //create C&E pricebook
        Account acct = Test_Utility.createAccount(1);
        insert acct;
        Machine_Model__c model = new Machine_Model__c(Name = 'machine', Account__c = acct.Id, Annual_Production_Volume__c = 10, Annual_Production_Volume_Plus1__c=10, Annual_Production_Volume_Plus2__c=10, Annual_Production_Volume_Plus3__c=10,Total_Machine_Potential__c = 10.00);
        insert model;
		model.Name = 'machine2';
		update model;
        Product2 prod1 = new Product2(Name = 'prod1', Business_Org__c = 'Danfoss', SAP_Material_Code__c = '123456');
        Product2 prod2 = new Product2(Name='prod2', Business_Org__c = 'Parker', SAP_Material_Code__c = '654321');
		List<Product2> products = new List<Product2>();
		products.add(prod1);
        products.add(prod2);
		insert products;
        Machine_Model_Product__c mmprod1 = new Machine_Model_Product__c(Name = 'mmprod1', Machine_Model__c = model.Id, Machine_Model_Product__c = prod1.Id, Price__c = 2.00, Number_Per_Machine__c = 1, Adoption_Rate__c = 100, Subsystem__c = 'Steering Function', Competitiveness__c = 'High');
        Machine_Model_Product__c mmprod2 = new Machine_Model_Product__c(Name = 'mmprod2', Machine_Model__c = model.Id, Machine_Model_Product__c = prod2.Id, Price__c = 0.00, Number_Per_Machine__c = 1, Adoption_Rate__c = 100);
        Machine_Model_Product__c mmprod3 = new Machine_Model_Product__c(Name = 'mmprod3', Machine_Model__c = model.Id, Machine_Model_Product__c = prod1.Id, Price__c = 2.00, Number_Per_Machine__c = 1);
        List<Machine_Model_Product__c> lstMMProds = new List<Machine_Model_Product__c>();
        lstMMProds.add(mmprod1);
        lstMMProds.add(mmprod2);
        lstMMProds.add(mmprod3);
		System.debug('lstMMProds: ' + lstMMProds);
        insert lstMMProds;
//Start Test		
		Test.startTest();
		double avgContent = 0;
        for (Machine_Model_Product__c p : lstMMProds) {
             if (p.Adoption_Rate__c != null && p.Price__c != null && p.Number_Per_Machine__c != null) 
                avgContent += (mmprod1.Number_Per_Machine__c * mmprod1.Price__c *(mmprod1.Adoption_Rate__c/100));
        }
        system.assertEquals(4, avgContent);
        double potential = avgContent * model.Annual_Production_Volume_Plus3__c;
        model.Total_Machine_Potential__c = potential;
        update model;
		Customer_Part_Number__c cpn = new Customer_Part_Number__c(SAP_Customer_Material_Id__c = '23456', Material_Number__c = '12345', Account__c = acct.Id, Product__c = prod1.Id);
		insert cpn;
		System.debug('lstMMProds after 2nd model update: ' + lstMMProds);
        system.assertEquals(40, model.Total_Machine_Potential__c);
	//test clone
		MIDClonePageControllerExtension contClone = new MIDClonePageControllerExtension();
        Apexpages.Standardcontroller stdcont = new Apexpages.Standardcontroller(model);       
        MIDCloneUtils xclone = new MIDCloneUtils();
        contClone = new MIDClonePageControllerExtension(stdcont);
		string fieldsNames = '';
        string recId = model.Id; 
        String objAPIName= 'Machine_Model_Product__c';          
        String queryString = 'select count(id) total from Machine_Model_Product__c where Machine_Model__c=\'' + String.escapeSingleQuotes(recId) + '\'';
        SObject result = Database.query(queryString);
        if((Integer)result.get('total')>0)
            fieldsNames = fieldsNames + objAPIName + ','; 
        list<String> selectedChildObjAPINames=New list<String>();
        if(fieldsNames.length()>0) {
            for(String childObjAPIName:fieldsNames.split(',')) {
                selectedChildObjAPINames.add(childObjAPIName);
            }
        }
        MIDCloneUtils cclone = new MIDCloneUtils(model.Id, selectedChildObjAPINames);
        xclone.startsClone(model.Id, selectedChildObjAPINames);
        PageReference prClone = contClone.chainClone();
	//test VF page	
        MIDProductListingControllerExtension contPage = new MIDProductListingControllerExtension();
        contPage = new MIDProductListingControllerExtension(stdcont);
        Pagereference prPage = contPage.NewMachineProduct();
        List<Machine_Model_Product__c> lstprods= contPage.getSteeringProducts();
        lstprods = contPage.getPropelProducts();
        lstprods = contPage.getFanDriveProducts();
        lstprods = contPage.getWorkFunctionProducts();
        lstprods = contPage.getElectronicsProducts();
		contPage.prodToDel = mmprod1.Id;
		contPage.deleteProduct();
		//model.Annual_Production_Volume_Plus3__c = null;
		//update model;
/*		Machine_Model_Product__c mmprod2 = new Machine_Model_Product__c(Machine_Model__c = model.Id, Machine_Model_Product__c = prod1.Id, Name = 'machine prod2', Price__c = 10, 
        		Number_Per_Machine__c = 10, Adoption_Rate__c = 100, Subsystem__c = 'Steering Function', Competitiveness__c = 'High');
        insert mmprod2;*/
		
		delete model;
		Test.stopTest();
        }
}