objects/Distributor_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Distributor Inventory</relationshipLabel>
        <relationshipName>Distributor_Inventory</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <formula>TEXT(Account__r.Business_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_id__c</fullName>
        <description>external ID for communication with SAP. Plant + material no</description>
        <externalId>true</externalId>
        <label>SAP_id</label>
        <length>26</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Distributor Inventory</label>
    <nameField>
        <label>Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributor Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_LDIControllers.cls
@isTest (seealldata=true)
private class Test_LDIControllers {
        static Account account;
        static Contact contactPortal;
        static User portalUser;
        static User adminUser;
        
        static testMethod void myUnitTest() {
           
            createUsers();
            system.runAs(adminUser) {
                account = Test_Utility.createAccount(1);
                insert account;
                contactPortal = Test_Utility.createContact(account.Id,2);
                insert contactPortal;
                List<Profile> portalUserProfiles = [Select id from Profile where Name IN ('PartnerLink - Basic','PartnerLink - Full') limit 1];
                system.assertEquals(portalUserProfiles.size(), 1);
                portalUser = Test_Utility.createPortalUser(contactPortal.Id, portalUserProfiles.get(0).Id);
                insert portalUser;
            }
             
            system.runAs(portalUser){
                LDISearchController scont = new LDISearchController();
                LDIUploadController ucont = new LDIUploadController();
                string ds = scont.debugSoql;
                Distributor_Inventory__c di = new Distributor_Inventory__c();
                di.Account__c = account.id;
                di.SAP_id__c = 'x';
                insert di;
                List<Distributor_Inventory__c> invList = new List<Distributor_Inventory__c>();
                invList = [Select Id, SAP_id__c from Distributor_Inventory__c where SAP_id__c = 'x'];
                List<Distributor_Inventory__c> invtoupload = new List<Distributor_Inventory__c>();
                invtoupload = [Select Id, SAP_id__c from Distributor_Inventory__c where SAP_id__c = 'x'];
                contactPortal.LDI_Region__c = 'Americas';
                update contactPortal;
                scont.getLDIRegions();              
                List<string> lstdist = scont.distributors;
                Pagereference pr = scont.gotoUpload();
                Pagereference pg = Page.LDI_Search;
                Test.setCurrentPage(pg);
                pg.getParameters().put('product', '1100');
                pg.getParameters().put('model', '90');
                pg.getParameters().put('descr', 'kit');
                pg.getParameters().put('distributor', 'Comatrol');
                scont.toggleSort();
                scont.runSearch();
                scont.Cancel();
				Pricebook2 stdPb = [select Id from Pricebook2 where isStandard=true limit 1];
                stdPb.IsActive = true;
                update stdPb;   
                Product2 product2i = new Product2(Name = 'product2i', SAP_Material_Code__c='12345',Business_Org__c = 'Integrated');
                insert product2i;
        
                List<Distributor_Inventory__c> inv = ucont.getuploadedInventory();
                List<string> lstNoProdMatch;
                ucont.getNoMatches();
                lstNoProdMatch = new List<string>();
                ucont.getshowResults();
                invtoupload = [Select Id, SAP_id__c from Distributor_Inventory__c where SAP_id__c = 'x'];
                Blob content = Blob.valueOf('12345,1\n123,2'); 
                ucont.contentFile = content;
                ucont.ReadFile();  
                ucont.nameFile = content.toString();
                String[] filelines = new String[]{};
                Set<string> setPartNumbers = new Set<string>();
                Map<string, string> mapMaterialCodeAndId = new Map<string, string>();
                for (Integer i=1;i<filelines.size();i++)
                {
                    String[] inputvalues = new String[]{};
                    inputvalues = filelines[i].split(',');
                    setPartNumbers.add(inputvalues[0]);
                }
                ucont.getshowResults();
                ucont.gotoSearch(); 
                ucont.getNoMatches(); 
                ucont.getuploadedInventory();           
                ucont.ReadFile();              
                ucont.ProceedWithUpload(); 
                ucont.Cancel(); 
                content = Blob.valueOf('123,1\n123,1');
                ucont.contentFile = content;
                ucont.ReadFile();              
                ucont.ProceedWithUpload(); 
                ucont.getuploadedInventory();
                ucont.getNoMatches();
            }
        }
     
         private static void createUsers() {
              Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
              UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
              adminUser = Test_Utility.createUser(profile.Id,roles.Id, 1);
              insert adminUser; 
        }
}