objects/EDISC__c.object
<CustomObject>
    <fields>
        <fullName>Ccalculation__c</fullName>
        <formula>IF(TEXT(Q1O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q1O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q2O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q2O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q3O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q3O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q4O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q4O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q5O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q5O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q6O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q6O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q7O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q7O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q8O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q8O1__c) = &quot;Least&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Compliance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>E-DISCs</relationshipLabel>
        <relationshipName>EDISCs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dcalculation__c</fullName>
        <formula>IF(TEXT(Q1O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q1O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q2O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q2O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q3O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q3O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q4O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q4O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q5O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q5O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q6O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q6O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q7O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q7O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q8O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q8O4__c) = &quot;Least&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dominance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Icalculation__c</fullName>
        <formula>IF(TEXT(Q1O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q1O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q2O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q2O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q3O3__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q3O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q4O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q4O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q5O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q5O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q6O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q6O4__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q7O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q7O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q8O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q8O3__c) = &quot;Least&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Influence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scalculation__c</fullName>
        <formula>IF(TEXT(Q1O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q1O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q2O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q2O2__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q3O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q3O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q4O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q4O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q5O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q5O1__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q6O2__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q6O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q7O1__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q7O3__c) = &quot;Least&quot;, 1, 0) + IF(TEXT(Q8O4__c) = &quot;Most&quot;, 1, 0) + IF(TEXT(Q8O2__c) = &quot;Least&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Steadiness</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/EDISCextension.cls
/**
	Author: Erin Fink
	Date:  15APR15
	Version 1.0
**/

public with sharing class EDISCextension{
	
	private EDISC__c disc;
	SObject objDisc;
	private List<EDISC__c> lstDiscs;
	public string edID {get;set;}
	private Contact cont;
	public Integer dominance {get;set;}
	public Integer influence {get;set;}
	public Integer steadiness {get;set;}
	public Integer compliance {get;set;}
	
	public EDISCextension(ApexPages.StandardController stdcontroller) {
		if(stdcontroller.getRecord().Id != null){
			String queryString = EdiscQuery();
			disc = Database.query(queryString + ' where Id = \'' + stdcontroller.getRecord().Id + '\'');
			objDisc = disc;
			dominance = (Integer)disc.Dcalculation__c;
			influence = (Integer)disc.Icalculation__c;
			steadiness = (Integer)disc.Scalculation__c;
			compliance = (Integer)disc.Ccalculation__c;
		}
		else{
			String contId = ApexPages.currentPage().getParameters().get('cont');
        	this.disc = (EDISC__c)stdcontroller.getRecord();
			objDisc = disc;
			disc.Contact__c = contId;						
			dominance = 0;
			influence = 0;
			steadiness = 0;
			compliance = 0;
		}
	}
	
	private String EdiscQuery(){
		List<SObjectField> fieldtokens = Schema.getGlobalDescribe().get('EDISC__c').getDescribe().fields.getMap().values();
		List<string> objectFields = new List<String>();        
        for(SObjectField fieldtoken:fieldtokens) {
            DescribeFieldResult dfr = fieldtoken.getDescribe(); 
            if(dfr.isCreateable())
                objectFields.add(dfr.getLocalName());                       
        }		 
		String fields = '';
        for(string s:objectFields) {
            if(s.contains('Created') == false && s.contains('LastModified') == false)
                fields = fields + s + ','; 
        } 
		fields += 'Contact__r.Name,Dcalculation__c,Icalculation__c,Scalculation__c,Ccalculation__c';
		return 'select ' + String.escapeSingleQuotes(fields) + ' from EDISC__c';
	}
	
	public PageReference redirectToDetailPage() { //only used when creating typical EDISC from Contact
		cont = [select E_DISC__c from Contact where Id = :disc.Contact__c];
		if(cont.E_DISC__c == null){
			cont.E_DISC__c = edID;
			update cont;
		}
		return new PageReference('/'+ disc.Contact__c);
	}

}