objects/EDISC__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>E-DISCs</relationshipLabel>
        <relationshipName>EDISCs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>E-DISCs</relationshipLabel>
        <relationshipName>E_DISCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Profile__c</fullName>
        <label>Primary Profile</label>
        <picklist>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Q1O1__c</fullName>
        <label>is soft spoken</label>
        <picklist>
            <picklistValues>
                <fullName>Most</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Least</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Q1O2__c</fullName>
        <label>speaks loudly</label>
        <picklist>
            <picklistValues>
                <fullName>Most</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Least</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Secondary_Profile__c</fullName>
        <label>Secondary Profile</label>
        <picklist>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Influencer_Grid__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Look up to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Influencer Grids</relationshipLabel>
        <relationshipName>Influencer_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EDISC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>E-DISC</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>EDISC__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EDISC__c</referenceTo>
        <relationshipLabel>Influencer Grids</relationshipLabel>
        <relationshipName>Influences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Influences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_EDISCandGrids.cls
/**
	Author: Erin Fink
	Date: 12JUL15
	Version 1.0
**/

@isTest
private class Test_EDISCandGrids {
	static testMethod void myUnitTest() {
		Account account = Test_Utility.createAccount(1);
        insert account;
		Contact contact = Test_Utility.createContact(account.Id, 1);
		insert contact;
		Opportunity oppty = Test_Utility.createOpportunity(account.Id, 1);
        insert oppty;
		Test.startTest();
		Influencer_Grid__c grid = new Influencer_Grid__c(Opportunity__c = oppty.Id, Contact__c = contact.Id);
		insert grid;
		
		EDISCextension Eext = new EDISCextension(new ApexPages.StandardController(new EDISC__c()));
		EDISC__c disc = new EDISC__c(Contact__c = contact.Id, Primary_Profile__c = 'D', Q1O1__c = 'Most', Q1O2__c = 'Most');
		insert disc;
		
		InfluencerExtension Iext = new InfluencerExtension(new ApexPages.StandardController(new Influencer_Grid__c()));
		Iext.newTypicalEdisc = true;
		Iext.SaveGrid();
		
		disc = new EDISC__c(Contact__c = contact.Id, Primary_Profile__c = 'D', Secondary_Profile__c = 'D', Q1O1__c = 'Least', Q1O2__c = 'Least');
		insert disc;
		disc = new EDISC__c(Contact__c = contact.Id, Primary_Profile__c = 'D', Secondary_Profile__c = 'D', Q1O1__c = 'Least', Q1O2__c = 'Most');
		insert disc;		
		Eext = new EDISCextension(new ApexPages.StandardController(disc));
		Eext.redirectToDetailPage();
		
		Iext = new InfluencerExtension(new ApexPages.StandardController(grid));
		Iext.getItems();
		Iext.findDiscs();
		Iext.SaveGrid();
		delete grid;
		Test.stopTest();
	}
}