objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>C_E_Event</fullName>
        <active>true</active>
        <description>Record type for C&amp;E Event</description>
        <label>C&amp;E Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FieldID__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ActivityDivision__c</fullName>
        <label>ActivityDivision</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Field IDs</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/NewEventExtension.cls
/*
 * Overrides the standard new event action, and redirects to the standard new event page.
 * On desktop this page sets default field values using URL hacks.
 * On mobile these are not set, since URL hacks are not supported.
 */
public class NewEventExtension {
    
    private PageReference eventURL;
    
    public NewEventExtension(ApexPages.StandardController controller) {
        if (!Test.isRunningTest()) {
            controller.addFields(new List<String> {'WhoId', 'WhatId'});
        }
        Event event = (Event) controller.getRecord();
        
        User usr = [select Business_Org__c, Division__c from User where Id = :UserInfo.getUserId()];
        
        eventURL = new PageReference('/00U/e?nooverride=1&ent=Event');
        eventURL.getParameters().put('retURL', controller.cancel().getUrl());
        //Added branch for setting the URL for Climate & Energy, which uses Division
        eventURL.getParameters().put('what_id', event.WhatId);
        
        if (usr.Business_Org__c == 'Climate and Energy') {
            //DEFECT 230 - add in the contact from the opportunity
            if (event.WhatId != null && event.WhatId.getSObjectType() == Opportunity.sObjectType) {
                event.WhoId = [select Contact__c from Opportunity where Id = :event.WhatId].Contact__c;
            }
            eventURL.getParameters().put('RecordType', [select Id from RecordType where DeveloperName = 'C_E_Event' and SobjectType = 'Event'].Id);
            eventURL.getParameters().put(FieldID__c.getOrgDefaults().ActivityDivision__c, usr.Division__c);
        }
        
        eventURL.getParameters().put('who_id', event.WhoId);
        
    }
    
    public String geteventURL() {
        return eventURL.getUrl();
    }
    
}