objects/Exclusive_Material__c.object
<CustomObject>
    <description>This will serve as a junction object between Account and Product2.</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Exclusive_Material</relationshipLabel>
        <relationshipName>Exclusive_Material</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Exclusive Material</label>
    <nameField>
        <displayFormat>EPR-{0000000}</displayFormat>
        <label>Exclusive Material Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Proprietary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates whether this product is a proprietary product.</description>
        <label>Proprietary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/ExclusiveMaterialTriggerHandler.cls
/**
	Author: Erin Fink
	Date: 15JUL15
	Version 1.0
**/

public with sharing class ExclusiveMaterialTriggerHandler{

	public static void onUpdateDeleteEM(List<Exclusive_Material__c> lstEMs){
		List<Exclusive_Material__c> lstExclusiveMaterials = new  List<Exclusive_Material__c>();
		for(Exclusive_Material__c exc : lstEMs) {
		    if(exc.isDeleted__c) {
		       lstExclusiveMaterials.add(exc);
		    }
		  }
		if(!lstExclusiveMaterials.isEmpty())
  			delete [select id from Exclusive_Material__c where Id IN :lstExclusiveMaterials];
	}
	
	public static void onDeleteCheckProduct(List<Exclusive_Material__c> lstEMs){
		
		List<Product2> lstProducts = new List<Product2>(); 
		Set<Id> setProductIds = new Set<Id>();
		for(Exclusive_Material__c material :lstEMs ) {
			setProductIds.add(material.Product__c);
		}
		
		lstProducts = [SELECT Id,Proprietary__c, (Select Id from Exclusive_Material__r limit 1) FROM Product2 WHERE Id IN :setProductIds];
		for(Product2 prod : lstProducts) {
			if(!prod.Exclusive_Material__r.isEmpty()) {
				prod.Proprietary__c = true;
			}
			else {
				prod.Proprietary__c = false;
			}
		}	
		if(!lstProducts.isEmpty())
			update lstProducts;
	}
}