objects/FieldID__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ActivityDivision__c</fullName>
        <label>ActivityDivision</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Field IDs</label>
</CustomObject>

classes/Test_NewEventExtension.cls
@isTest
public class Test_NewEventExtension {
    
    static testMethod void test() {
        FieldID__c fieldid = FieldID__c.getOrgDefaults();
        fieldid.ActivityDivision__c = 'abc';
        insert fieldid;
        
        Test.startTest();
        
        NewEventExtension c = new NewEventExtension(new ApexPages.StandardController(new Event()));
        
        Test.stopTest();
        
        System.assertNotEquals(null, c.geteventURL());
    }
    
}