objects/FieldID__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ActivityDivision__c</fullName>
        <label>ActivityDivision</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>ActivityType</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallDivision__c</fullName>
        <label>CallDivision</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Field IDs</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>C_E_Task</fullName>
        <active>true</active>
        <description>Record type for C&amp;E Tasks</description>
        <label>C&amp;E Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/NewTaskExtension.cls
/*
 * Overrides the standard new task action, and redirects to the standard new task page.
 * On desktop this page sets default field values using URL hacks.
 * On mobile these are not set, since URL hacks are not supported.
 */
public class NewTaskExtension {
    
    private PageReference taskURL;
    Private Id recTypeId, tskRecTypeId;
        
    public NewTaskExtension(ApexPages.StandardController controller) {
        if (!Test.isRunningTest()) {
            controller.addFields(new List<String> {'WhoId', 'WhatId'});
        }
        Task task = (Task) controller.getRecord();
        
        User usr = [select Business_Org__c, Division__c from User where Id = :UserInfo.getUserId()];
        
        taskURL = new PageReference('/00T/e?nooverride=1&ent=Task');
        taskURL.getParameters().put('retURL', controller.cancel().getUrl());
        //Added branch for setting the URL for Climate & Energy, which uses Division
        taskURL.getParameters().put('what_id', task.WhatId);
        
        if (usr.Business_Org__c == 'Climate and Energy') {
            //DEFECT 230 - add in the contact from the opportunity
            if (task.WhatId != null && task.WhatId.getSObjectType() == Opportunity.sObjectType) {
                task.WhoId = [select Contact__c from Opportunity where Id = :task.WhatId].Contact__c;
            }
            
           recTypeId = [select Id from RecordType where DeveloperName = 'C_E_Task' and SobjectType = 'Task'].Id; 

            taskURL.getParameters().put('RecordType', recTypeId);
            taskURL.getParameters().put(FieldID__c.getOrgDefaults().ActivityDivision__c, usr.Division__c);
            taskURL.getParameters().put(FieldID__c.getOrgDefaults().ActivityType__c, 'Communication');
            //note 3rd Feb : added parameter to preset the diviions of the follow up task for log a call: necessary for log a call
            taskURL.getParameters().put(FieldID__c.getOrgDefaults().CallDivision__c, usr.Division__c);
        }
        
        taskURL.getParameters().put('who_id', task.WhoId);
      //note 3rd Feb : added parameters necessary for log a call
        taskURL.getParameters().put('title', ApexPages.currentPage().getParameters().get('title'));
        taskURL.getParameters().put('tsk5', ApexPages.currentPage().getParameters().get('tsk5'));
        taskURL.getParameters().put('followup', ApexPages.currentPage().getParameters().get('followup'));
        
    }
    
    public String gettaskURL() {
        return taskURL.getUrl();
    }
    
    public String getRecTypeId() {
        Schema.DescribeSObjectResult describeTask = Schema.SObjectType.Task;    
        List<Schema.RecordTypeInfo> rtInfos = describeTask.getRecordTypeInfos();
          for(Schema.RecordTypeInfo rtInfo : rtInfos) {
        if(rtInfo.isDefaultRecordTypeMapping()) {               
            tskRecTypeId = rtInfo.getRecordTypeId();
            break;
         }
       }

        return tskRecTypeId;
    }

    
}