objects/FieldID__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ActivityDivision__c</fullName>
        <label>ActivityDivision</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>ActivityType</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallDivision__c</fullName>
        <label>CallDivision</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Field IDs</label>
</CustomObject>

classes/Test_NewTaskExtension.cls
@isTest
public class Test_NewTaskExtension {
    
    static testMethod void test() {
        FieldID__c fieldid = FieldID__c.getOrgDefaults();
        fieldid.ActivityDivision__c = 'abc';
        fieldid.ActivityType__c = 'def';
        fieldid.CallDivision__c = 'ghi';
        insert fieldid;
        
        Test.startTest();
        
        Task task = new Task();
        ApexPages.StandardController controller = new ApexPages.StandardController(task);
        NewTaskExtension c = new NewTaskExtension(controller);
        c.getRecTypeId();
        
        Test.stopTest();
        
        System.assertNotEquals(null, c.gettaskURL());
    }
    
}