objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_From__c</fullName>
        <label>Postal Code From</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_To__c</fullName>
        <label>Postal Code To</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SBA_Team__c</fullName>
        <label>SBA Team</label>
        <picklist>
            <picklistValues>
                <fullName>No auto. Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_F&amp;B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_F&amp;B, other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_HVAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_HVAC_FKR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_HVAC, Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_HVAC, Refrigeration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Industry, Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Industry, Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Industry, Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Partner_HVAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Partner_Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PE_Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Account_Team_Role__c</fullName>
        <label>Account Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Employee Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Clerk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>TeamMember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/GetOpportunityTeamsExtension.cls
public class GetOpportunityTeamsExtension {
    
    public Opportunity o;    
    public ApexPages.StandardSetController setCon {get;set;}
    public Id selectedDD {get;set;} 
    public String countryList {get;set;}    
    public Id selectedOTMId {get;set;}
    public Id selectedOTId {get;set;}
    public Boolean reload {get;set;}
    public String shownTab {get;set;}
    public Boolean userInTeam {get;set;}
    public OpportunityTeamMember userTeamMember {get;set;}
    public OpportunityTeamMember anyUserTeamMember {get;set;}
    public List<OpportunityTeamMember> currentOpportunityTeamMembers {get;set;}
    
    public GetOpportunityTeamsExtension(ApexPages.StandardController stdController) {
        /*
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'Country_MainAddress__c', 'ShippingCountry'});
        }        
        */
        shownTab = ApexPages.currentPage().getParameters().get('selectedTab');
        if (shownTab=='')
            shownTab='teamsTab';
        
        o = (Opportunity) stdController.getRecord();
        /*
        Set<String> countries = new Set<String>();
        if (o.Country_MainAddress__c != null) {
            countries.add(o.Country_MainAddress__c.substring(0, 2));
        }
        if (o.ShippingCountry != null) {
            countries.add(o.ShippingCountry.substring(0, 2));
        }
        countryList = String.join(new List<String>(countries), ', ');
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator([
            select Name, Division__c, SBA_Team__c, Id
            from Team__c
            where Id in (
                select Team__c
                from Location__c
                where Postal_Code_From__c <= :a.ShippingPostalCode and Postal_Code_To__c >= :a.ShippingPostalCode and Country__c in :countries
            )
        ]));
        setCon.setPageSize(8);
        */
        
        refreshOpportunityTeamMembers();
        anyUserTeamMember = new OpportunityTeamMember();
                
    }
    
    public List<Team__c> getTeams() {       
        return setCon.getRecords();
        
    }

    public void refreshOpportunityTeamMembers() {
   		currentOpportunityTeamMembers = [SELECT Id, UserId, TeamMemberRole, OpportunityId, User.Name FROM OpportunityTeamMember WHERE OpportunityId=:o.Id LIMIT 100];
        
        userInTeam=false;
        // See if the users is already in Opportunity team
        for (OpportunityTeamMember OTM : currentOpportunityTeamMembers) {
            if (OTM.UserId == UserInfo.getUserId()) {
        		userTeamMember=OTM;        
                userInTeam=true;
                break;
            }
        }
        // If the users did not exist in the team - create a new Account Team Member
        if (userInTeam==false) {
        	userTeamMember = new OpportunityTeamMember();
        	userTeamMember.OpportunityId = o.Id;
        	userTeamMember.UserId = UserInfo.getUserId();
    	}
    }
/*    
    public pagereference AddTeam() {
        Team__c t = [select Name, SBA_Team__c from Team__c where Id = :selectedDD];
        List<AccountTeamMember> accountTeamList = new List<AccountTeamMember>();
       //Added for Team Fix 1th March 2015: only need to add Team Members that are of the "User" recordtype & where the user is actually active
        //for (TeamMember__c tm : [select User__c, user__r.isactive, Account_Team_Role__c from TeamMember__c where user__r.isactive = true and recordtype.developername='Team_Member_User' and Team__c = :selectedDD]) {
        for (TeamMember__c tm : [select User__c, user__r.isactive, Account_Team_Role__c from TeamMember__c where user__r.isactive = true and Team__c = :selectedDD]) {            
            String StrTeamRole = t.SBA_Team__c + ':' + tm.Account_Team_Role__c   ;
            if(StrTeamRole.length() > 40){StrTeamRole=StrTeamRole.substring(0,40);}
            AccountTeamMember acctTM = new AccountTeamMember(AccountId = a.Id,UserId = tm.User__c,TeamMemberRole = StrTeamRole);
            accountTeamList.add(acctTM);
        }
            
        try {
            insert accountTeamList;
            refreshAccountTeamMembers();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Added ' + accountTeamList.size() + ' user(s) to the Account Team.'));
        } catch (DMLException e) {
             ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Failed to Add Account Team... ' + e));
        }
        
        return null;
    }
*/    
    public pagereference addUser() {
        if (userTeamMember.TeamMemberRole==null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, 'Please select a team role first.'));
        } else {
        	insert userTeamMember;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Added user to the Opportunity Team.'));
            refreshOpportunityTeamMembers();
        }
               
        return null;
    }
    
    public pagereference removeUser() {                   
        if (userTeamMember!=null) {
        	delete userTeamMember;
            refreshOpportunityTeamMembers();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Removed user from the Opportunity Team.'));
    	}

        return null;     
    }

    public pagereference addTeamMember() {
        if (anyUserTeamMember.UserId==null || anyUserTeamMember.TeamMemberRole==null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.WARNING, 'Please select a user and a role.'));                        
        } else {
            anyUserTeamMember.OpportunityId=o.Id;   
        	insert anyUserTeamMember;
            
            // re-initialize for next insert
            anyUserTeamMember = new OpportunityTeamMember();
            refreshOpportunityTeamMembers();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Added user to the Opportunity Team.'));
        }
               
        return null;
    }
    
   public pagereference removeTeamMember() {
       OpportunityTeamMember delopptTM = new OpportunityTeamMember(id = selectedOTMId);
       
       try {
           delete delopptTM;
           ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Removed user from the Account Team.'));
           refreshOpportunityTeamMembers();
       } 
       catch (DMLException e) {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Failed to Delete Opportunity Team Member...' + e));       
       }                          
       return null;     
   }
}