objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus1__c</fullName>
        <label>2013</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus2__c</fullName>
        <label>2014</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus3__c</fullName>
        <label>2015</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume__c</fullName>
        <label>Production Volume - 2012</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Machine_Potential__c</fullName>
        <inlineHelpText>Based on 2015 volume</inlineHelpText>
        <label>Total Annual Machine Potential</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Competitiveness__c</fullName>
        <inlineHelpText>Your perceived competitiveness of Danfoss with regards to this product in this machine model</inlineHelpText>
        <label>Danfoss Competitiveness</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subsystem__c</fullName>
        <label>Machine Function</label>
        <picklist>
            <picklistValues>
                <fullName>Steering Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HMI and Electronics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <description>This field shows the customer machine model number.</description>
        <inlineHelpText>Enter the customer&apos;s machine model.  Example: 820C, 810C, etc.</inlineHelpText>
        <label>Machine Model Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Climate and Energy users should read CE title</inlineHelpText>
        <label>Business Unit / Product Line (CE)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Code__c</fullName>
        <label>Model Code</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_RefreshSAPPrice.cls
@isTest
private class Test_RefreshSAPPrice {
		
	static User adminUser;	
	static Region__c reg;
	static Id StdPBId;
	static PriceBookEntry stdpbe;
	static Product2 p;
	static Opportunity oppty;
	static OpportunityLineItem oli;
	static Quote quote;
	static QuoteLineItem qli;
	static Machine_Model__c model;
	static Machine_Model_Product__c mmprod;
	
    static testMethod void RefreshSAPPriceTestOppty() {
		createUsers();
		system.runAs(adminUser) {
			createTestData();
	        oli = new OpportunityLineItem(OpportunityId = oppty.Id, PriceBookEntryId = stdpbe.Id, UnitPrice = 10, Quantity =10);
	        insert oli;
		}	
		Test.startTest();
		PageReference pg = Page.RefreshOpportunitySAPPrice;
		Test.setCurrentPage(pg);
		ApexPages.currentPage().getParameters().put('id',oppty.Id);
		ApexPages.currentPage().getParameters().put('opportunityLineItemId',oli.Id);
		Test.setMock(WebServiceMock.class, new Test_QuoteWebServiceMockImpl());
		RefreshSAPPrice refreshSAP = new RefreshSAPPrice(new ApexPages.StandardController(oppty));
		refreshSAP.autorun();
		refreshSAP.saveAndReturn();
		Test.stopTest();
    }
    
    static testMethod void RefreshSAPPriceTestMachine() {
		createUsers();
		system.runAs(adminUser) {
			createTestData();
	        mmprod = new Machine_Model_Product__c(Name = 'mmprod1', Machine_Model__c = model.Id, Machine_Model_Product__c = p.Id, Price__c = 2.00, Number_Per_Machine__c = 1, Adoption_Rate__c = 100, Subsystem__c = 'Steering Function', Competitiveness__c = 'High');
	        insert mmprod;
		}	
		Test.startTest();
		PageReference pg = Page.RefreshMachineSAPPrice;
		Test.setCurrentPage(pg);
		ApexPages.currentPage().getParameters().put('id',model.Id);
		ApexPages.currentPage().getParameters().put('mmprodId',mmprod.Id);
		Test.setMock(WebServiceMock.class, new Test_QuoteWebServiceMockImpl());
		RefreshSAPPrice refreshSAP = new RefreshSAPPrice(new ApexPages.StandardController(model));
		refreshSAP.autorun();
		refreshSAP.saveAndReturn();
		Test.stopTest();
    }
    
    static testMethod void RefreshSAPPriceTestQuote() {
		createUsers();
		system.runAs(adminUser) {
			createTestData();
			quote = new Quote(OpportunityId = oppty.Id, Name='qli', PriceBook2Id = StdPBId, Country_Specific_Template__c = reg.Id);
			insert quote;      
	        qli = new QuoteLineItem(QuoteId = quote.Id, PriceBookEntryId = stdpbe.Id, UnitPrice = 10, Quantity =10);
	        insert qli;
		}
		Test.startTest();
		PageReference pg = Page.RefreshOpportunitySAPPrice;
		Test.setCurrentPage(pg);
		ApexPages.currentPage().getParameters().put('id',quote.Id);
		ApexPages.currentPage().getParameters().put('quoteLineItemId',qli.Id);
		Test.setMock(WebServiceMock.class, new Test_QuoteWebServiceMockImpl());
		RefreshSAPPrice refreshSAP = new RefreshSAPPrice(new ApexPages.StandardController(quote));
		refreshSAP.autorun();
		refreshSAP.saveAndReturn();
		Test.stopTest();
    }
	
	
	private static void createTestData(){
		Test_Utility.initTestData();   //create C&E pricebook
		p = Test_Utility.createProduct2();   
		p.Business_Unit__c = 'Motors';
		p.Model_Code__c = 'code';
		p.SAP_Material_Code__c = '1234';
		insert p;        		
		StdPBId = Test.getStandardPricebookId();
		stdpbe = new PricebookEntry(Pricebook2Id = StdPBId, Product2Id = p.Id, UnitPrice = 100, IsActive = true, CurrencyISOCode = 'DKK');
		insert stdpbe;
		reg = new Region__c(Name = 'USA', Country_Code__c = 'US', Region__c = 'Americas');
		insert reg;
		Account account = Test_Utility.createAccount(2);
		insert account; 
		oppty = Test_Utility.createOpportunity(account.Id, 1);
		insert oppty;	
		model = new Machine_Model__c(Name = 'machine', Account__c = account.Id, Annual_Production_Volume__c = 10, Annual_Production_Volume_Plus1__c=10, Annual_Production_Volume_Plus2__c=10, Annual_Production_Volume_Plus3__c=10,Total_Machine_Potential__c = 10.00);
    insert model;
	}
	
    private static void createUsers() {
		Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
		UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
		adminUser = Test_Utility.createUser(profile.Id, roles.Id, 1);
		adminUser.DelegatedApproverId = UserInfo.getUserId();
		insert adminUser;
	}
}