objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Competitiveness__c</fullName>
        <inlineHelpText>Your perceived competitiveness of Danfoss with regards to this product in this machine model</inlineHelpText>
        <label>Danfoss Competitiveness</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <controllingField>Subsystem__c</controllingField>
            <picklistValues>
                <fullName>Transmission Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydraulic Steering Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Priority Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steering Amplifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrohydraulic Steering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joystick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telematics Solution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subsystem__c</fullName>
        <label>Machine Function</label>
        <picklist>
            <picklistValues>
                <fullName>Steering Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HMI and Electronics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <formula>TEXT(Machine_Model_Product__r.Business_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Product_units__c</fullName>
        <formula>Machine_Model__r.Annual_Production_Volume_Plus3__c * Number_per_machine__c * Adoption_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Product Potential (units)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Product_value__c</fullName>
        <formula>Machine_Model__r.Annual_Production_Volume_Plus3__c * Number_per_machine__c * Price__c * Adoption_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Product Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MIDProductListingControllerExtension.cls
public with sharing class MIDProductListingControllerExtension {

    private Machine_Model__c mach;
    private Machine_Model_Product__c prod;
    public String subsystem { get; set; }
    public String mmprodName { get; set; }
    public String curr { get; set; }
	public string prodToDel{get;set;}
    private ApexPages.standardController controller {get;set;}
    public List<Machine_Model_Product__c> steeringlist;
    public List<Machine_Model_Product__c> propellist;
    public List<Machine_Model_Product__c> fanDrivelist;
    public List<Machine_Model_Product__c> workFunctionlist;
    public List<Machine_Model_Product__c> electronicslist;
    public string mmprodURL = '';
    public string mmprodescaped;
    
    public MIDProductListingControllerExtension(ApexPages.StandardController stdcontroller) {
            controller = stdController;
            this.mach = (Machine_Model__c)stdcontroller.getRecord();
    } 
    
    //Constructor
    public MIDProductListingControllerExtension(){ 
    }
      
    public PageReference NewMachineProduct(){
        /* if (!Test.isRunningTest())
         	mmprodName = mmprodName.replace('&','%26');
         mmprodURL = '/a0P/e?CF00NC0000005Mmuy=' + mmprodName + '&Name=(populated on save)&00NC0000005MmvE=' + subsystem + '&retURL=%2F'+mach.id;
         PageReference np = new PageReference(mmprodURL);*/ 
        PageReference np = new PageReference('/apex/AddMachineProduct?id=' + mach.Id + '&subsystem=' + subsystem + '&retURL=%2F'+mach.id); //00NC0000005MmvE
		np.setRedirect(true);
        return np;  
    }
	
	public pagereference deleteProduct()
    {     
        if(prodToDel!=null)
        {
			delete new Machine_Model_Product__c(Id=prodToDel);
        }
        
        return null;
    }
    
    public List<Machine_Model_Product__c> getSteeringProducts() {
            steeringlist = [SELECT Machine_Model__c, Machine_Model__r.Name, Name, Price__c, Machine_Model_Product__c, Product_Type__c, Total_Product_units__c, Total_Product_value__c, Competitiveness__c, Machine_Model_Product__r.Name, Subsystem__c, Supplier__c, Number_Per_Machine__c, Adoption_Rate__c FROM Machine_Model_Product__c Where Subsystem__c LIKE 'Steering%' AND Machine_Model__c=:mach.id];
            return steeringlist;
    }
    public List<Machine_Model_Product__c> getPropelProducts() {
            propellist = [SELECT Machine_Model__c, Machine_Model__r.Name, Name, Price__c, Machine_Model_Product__c, Product_Type__c, Total_Product_units__c, Total_Product_value__c, Competitiveness__c, Machine_Model_Product__r.Name, Subsystem__c, Supplier__c, Number_Per_Machine__c, Adoption_Rate__c FROM Machine_Model_Product__c Where Subsystem__c LIKE 'Transmission%' AND Machine_Model__c=:mach.id];
            return propellist;
    }
    public List<Machine_Model_Product__c> getFanDriveProducts() {
            fanDrivelist = [SELECT Machine_Model__c, Machine_Model__r.Name, Name, Price__c, Machine_Model_Product__c, Product_Type__c, Total_Product_units__c, Total_Product_value__c, Competitiveness__c, Machine_Model_Product__r.Name, Subsystem__c, Supplier__c, Number_Per_Machine__c, Adoption_Rate__c FROM Machine_Model_Product__c Where Subsystem__c = 'Fan Drive' AND Machine_Model__c=:mach.id];
            return fanDrivelist;
    }
    public List<Machine_Model_Product__c> getWorkFunctionProducts() {
            workFunctionlist = [SELECT Machine_Model__c, Machine_Model__r.Name, Name, Price__c, Machine_Model_Product__c, Product_Type__c, Total_Product_units__c, Total_Product_value__c, Competitiveness__c, Machine_Model_Product__r.Name, Subsystem__c, Supplier__c, Number_Per_Machine__c, Adoption_Rate__c FROM Machine_Model_Product__c Where Subsystem__c = 'Working Function' AND Machine_Model__c=:mach.id];
            return workFunctionlist;
    }
    public List<Machine_Model_Product__c> getElectronicsProducts() {
            electronicslist = [SELECT Machine_Model__c, Machine_Model__r.Name, Name, Price__c, Machine_Model_Product__c, Product_Type__c, Total_Product_units__c, Total_Product_value__c, Competitiveness__c, Machine_Model_Product__r.Name, Subsystem__c, Supplier__c, Number_Per_Machine__c, Adoption_Rate__c FROM Machine_Model_Product__c Where Subsystem__c = 'HMI and Electronics' AND Machine_Model__c=:mach.id];
            return electronicslist;
    }
}