objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus1__c</fullName>
        <label>2013</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus2__c</fullName>
        <label>2014</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus3__c</fullName>
        <label>2015</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume__c</fullName>
        <label>Production Volume - 2012</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Machine_Potential__c</fullName>
        <inlineHelpText>Based on 2015 volume</inlineHelpText>
        <label>Total Annual Machine Potential</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Competitiveness__c</fullName>
        <inlineHelpText>Your perceived competitiveness of Danfoss with regards to this product in this machine model</inlineHelpText>
        <label>Danfoss Competitiveness</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <controllingField>Subsystem__c</controllingField>
            <picklistValues>
                <fullName>Transmission Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydraulic Steering Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Priority Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steering Amplifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrohydraulic Steering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joystick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telematics Solution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <description>This field shows the customer machine model number.</description>
        <inlineHelpText>Enter the customer&apos;s machine model.  Example: 820C, 810C, etc.</inlineHelpText>
        <label>Machine Model Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cartridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Climate and Energy users should read CE title</inlineHelpText>
        <label>Business Unit / Product Line (CE)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Code__c</fullName>
        <label>Model Code</label>
        <length>240</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_AddLineItems.cls
@isTest
private class Test_AddLineItems {
	
	static Id StdPBId;
	static PriceBookEntry stdpbe;
	static Product2 product;
	static Region__c usaRegion;
	static Account account;
	static Opportunity oppty;
	static Machine_Model__c machine;
	
    static testMethod void testAddLineItem() {  
		createTestData();
		Test.startTest();
		PageReference pg = Page.AddOpptyLineItems;
		Test.setCurrentPage(pg);
		ApexPages.currentPage().getParameters().put('id',oppty.Id);
		ApexPages.currentPage().getParameters().put('priceBookEntryId',stdpbe.Id);
		Test.setMock(WebServiceMock.class, new Test_QuoteWebServiceMockImpl());

		AddLineItems ext = new AddLineItems();
		ext.quote = new Quote(); 
		ext.SaveLineItems();
		List<OpportunityLineItem> lstLineItem = ext.getOpportunityLineItems();
		lstLineItem[0].UnitPrice = 12;
		lstLineItem[0].Quantity = 21;    
		ext.SaveAndMore();
		ext.GetSAPPrice();
		AddLineItems.getTotalPrice('2', '2');
		AddLineItems.getThousandSeparator();
		Test.stopTest();
    }
	
    static testMethod void testAddLineItemMachine() {  
		createTestData();
		Test.startTest();
		PageReference pg = Page.AddMachineLineItems;
		Test.setCurrentPage(pg);
		ApexPages.currentPage().getParameters().put('id',Machine.Id);
		ApexPages.currentPage().getParameters().put('priceBookEntryId',stdpbe.Id);
		ApexPages.currentPage().getParameters().put('salesorg','1500');
		ApexPages.currentPage().getParameters().put('subsystem','Transmission');
		Test.setMock(WebServiceMock.class, new Test_QuoteWebServiceMockImpl());

		AddLineItems ext = new AddLineItems();	
		ext.machine = new Machine_Model__c();
		ext.SaveLineItems();
		List<Machine_Model_Product__c> lstLineItem = ext.getMachineLineItems();
		lstLineItem[0].Product_Type__c = 'Transmission Pump';
		lstLineItem[0].Competitiveness__c = 'High';
		lstLineItem[0].Adoption_Rate__c = 100;
		lstLineItem[0].Number_per_machine__c = 1;
		ext.SaveAndMore();
		ext.GetSAPPrice(); 
		AddLineItems.getTotalPrice('2', '2');
		AddLineItems.getThousandSeparator();
		ext.cancel();
		Test.stopTest();
    }
  
    static testMethod void testAddLineItemQuote() { 
		createTestData();
		Quote quote = new Quote(OpportunityId = oppty.Id,Name='qli',PriceBook2Id = StdPBId, Country_Specific_Template__c = usaRegion.Id);
		insert quote;
		
		Test.startTest();
		PageReference pg = Page.AddOpptyLineItems;
		Test.setCurrentPage(pg);
		ApexPages.currentPage().getParameters().put('id',quote.Id);
		ApexPages.currentPage().getParameters().put('priceBookEntryId',stdpbe.Id);
		Test.setMock(WebServiceMock.class, new Test_QuoteWebServiceMockImpl());

		AddLineItems ext = new AddLineItems();
		ext.quote = new Quote(); 
		ext.SaveLineItems();
		List<QuoteLineItem> lstQuoteLineItem = ext.getQuoteLineItems();
		lstQuoteLineItem[0].UnitPrice = 12;
		lstQuoteLineItem[0].Quantity = 21;    
		ext.SaveAndMore();
		//ext.GetSAPPrice();
		AddLineItems.getTotalPrice('2', '2');
		AddLineItems.getThousandSeparator();
		Test.stopTest();
  }
	
	static void createTestData(){
    	Test_Utility.initTestData();   //create C&E pricebook
		product = Test_Utility.createProduct2();
		product.Business_Unit__c = 'Motors';
		product.ProductCode = '11111';
		product.Model_Code__c = 'modelcodetext';
		product.Business_Org__c = 'Danfoss';
		insert product;
		StdPBId = Test.getStandardPricebookId();
		stdpbe = new PricebookEntry(Pricebook2Id = StdPBId, Product2Id = product.Id, UnitPrice = 100, IsActive = true, CurrencyISOCode = 'DKK');
		insert stdpbe;
		usaRegion = new Region__c(Name = 'USA', Country_Code__c = 'US', Region__c = 'Americas');
		insert usaRegion;
		account = Test_Utility.createAccount(1);
		insert account;
		machine = new Machine_Model__c(Name = 'machine', Account__c = account.Id, Annual_Production_Volume__c = 10, Annual_Production_Volume_Plus1__c=10, Annual_Production_Volume_Plus2__c=10, Annual_Production_Volume_Plus3__c=10,Total_Machine_Potential__c = 10.00);
        insert machine;
		oppty = Test_Utility.createOpportunity(account.Id, 1);
		insert oppty;  
	}	
}