objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Annual_Production_Volume_Plus3__c</fullName>
        <label>2015</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Content_per_Machine__c</fullName>
        <label>Average Content per Machine</label>
        <precision>13</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Share_of_Wallet__c</fullName>
        <label>Danfoss Share of Wallet (in %)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Machine_Potential__c</fullName>
        <inlineHelpText>Based on 2015 volume</inlineHelpText>
        <label>Total Annual Machine Potential</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <formula>TEXT(Machine_Model_Product__r.Business_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Product_value__c</fullName>
        <formula>Machine_Model__r.Annual_Production_Volume_Plus3__c * Number_per_machine__c * Price__c * Adoption_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Product Potential</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Share_of_Wallet__c.object
<CustomObject>
    <description>Contains the Share Of Wallet (SoW) on the Account Object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Share of Wallets</relationshipLabel>
        <relationshipName>Share_of_Wallets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Share of Wallet</label>
    <nameField>
        <displayFormat>SoW-{00000}</displayFormat>
        <label>Share of Wallet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Share of Wallet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MachineTriggerHandler.cls
/**
	* MachineTriggerHandler - Rolls up values
	* @author: Erin Fink
	* @date: 13MAY15
	* @version: 1.0
*/

public with sharing class MachineTriggerHandler{
	
	public static void GetAccountCurrency(List<Machine_Model__c> lstMachines){		//BEFORE INSERT
		for (Machine_Model__c machine : lstMachines) {
	        Account acct = [select currencyisocode from Account where id = :machine.Account__c];
			machine.CurrencyIsoCode = acct.CurrencyIsoCode;
		}
	}
	
	public static void CalculateTotalMachinePotential(List<Machine_Model__c> lstMachines){		//BEFORE UPDATE
		for (Machine_Model__c machine : lstMachines) {
	        if (machine.Average_Content_per_Machine__c != null)
	            machine.Total_Machine_Potential__c = machine.Annual_Production_Volume_Plus3__c * machine.Average_Content_per_Machine__c;
	        }
	}
	
	public static void UpdateAcctMetrics(List<Machine_Model__c> lstMachinesIN){		//AFTER UPDATE and AFTER DELETE
		double totalMachinePotential = 0;
	    double SDtotalMachinePotential = 0;
		double exchangeRate = 1.00;
	    Map<String, Double> mapCurrency = new Map<String, Double>(); 
	    List<CurrencyType> lstCurrency = [Select ConversionRate,IsoCode From CurrencyType];
		Map<Id, List<Machine_Model_Product__c>> mapMachineIdAndLstProds = new Map<Id, List<Machine_Model_Product__c>>(); 
		Map<Id, List<Machine_Model__c>> mapAcctIdAndLstMachines = new Map<Id, List<Machine_Model__c>>();
		List<Account> lstAccounts = new List<Account>();    
		List<Machine_Model__c> lstMachines = new List<Machine_Model__c>();
		List<Machine_Model_Product__c> lstProducts = new List<Machine_Model_Product__c>();
	    
	    for (CurrencyType c :lstCurrency)
	        mapCurrency.put(c.IsoCode, c.ConversionRate);
	        
	    for (Machine_Model__c machine : lstMachinesIN) {
			if(!mapAcctIdAndLstMachines.containsKey(machine.Account__c))
				mapAcctIdAndLstMachines.put(machine.Account__c, new List<Machine_Model__c>());
	    }
		
		lstMachines = [SELECT Name, Account__c, Total_Machine_Potential__c, Annual_Production_Volume_Plus3__c, Average_Content_per_Machine__c, Share_of_Wallet__c 
					   FROM Machine_Model__c where Account__c IN :mapAcctIdAndLstMachines.keySet()];	
		for(Machine_Model__c machine :lstMachines){
			if(!mapMachineIdAndLstProds.containsKey(machine.Id))
				mapMachineIdAndLstProds.put(machine.Id, new List<Machine_Model_Product__c>());
			set<Machine_Model__c> setMachines = new set<Machine_Model__c>(mapAcctIdAndLstMachines.get(machine.Account__c));
			if(!setMachines.contains(machine))
				mapAcctIdAndLstMachines.get(machine.Account__c).add(machine);	
		}
		
		lstProducts = [SELECT Adoption_Rate__c, Price__c, CurrencyIsoCode, Total_Product_value__c, Number_Per_Machine__c, Supplier__c, Machine_Model__c 
					   FROM Machine_Model_Product__c where IsDeleted = false and Machine_Model__c IN :mapMachineIdAndLstProds.keySet()];
		for(Machine_Model_Product__c p :lstProducts){
			set<Machine_Model_Product__c> setProducts = new set<Machine_Model_Product__c>(mapMachineIdAndLstProds.get(p.Machine_Model__c));
			if(!setProducts.contains(p))
				mapMachineIdAndLstProds.get(p.Machine_Model__c).add(p);
		}	
		
	    lstAccounts = [SELECT Name, CurrencyIsoCode, Aggregate_Wallet_Share__c, Aggregate_Potential__c 
					   FROM Account WHERE Id IN :mapAcctIdAndLstMachines.keySet()];
		for(Account acct :lstAccounts){
			for (Machine_Model__c machine :mapAcctIdAndLstMachines.get(acct.Id)) {
				for (Machine_Model_Product__c p : mapMachineIdAndLstProds.get(machine.Id)) {
					exchangeRate = mapCurrency.get(p.CurrencyIsoCode);				
		        	totalMachinePotential += (p.Total_Product_value__c / exchangeRate);		
				    if (p.Supplier__c == 'Danfoss')    
				        SDtotalMachinePotential += (p.Total_Product_value__c / exchangeRate);
				    }
				}			
			acct.Aggregate_Potential__c = totalMachinePotential * mapCurrency.get(acct.CurrencyIsoCode);
		    if (totalMachinePotential > 0)
		        acct.Aggregate_Wallet_Share__c = ((SDtotalMachinePotential * mapCurrency.get(acct.CurrencyIsoCode))/(totalMachinePotential * mapCurrency.get(acct.CurrencyIsoCode)))*100;
		    else
		        acct.Aggregate_Wallet_Share__c = 0;
		}
		update lstAccounts;	
	}
}