objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Adoption_Rate__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>How many % of this machine model utilize this product?</inlineHelpText>
        <label>Adoption Rate %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Competitiveness__c</fullName>
        <inlineHelpText>Your perceived competitiveness of Danfoss with regards to this product in this machine model</inlineHelpText>
        <label>Danfoss Competitiveness</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Number_per_machine__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units per machine</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <controllingField>Subsystem__c</controllingField>
            <picklistValues>
                <fullName>Transmission Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydraulic Steering Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Priority Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steering Amplifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrohydraulic Steering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function Pump</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function Motor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joystick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telematics Solution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsystem__c</fullName>
        <label>Machine Function</label>
        <picklist>
            <picklistValues>
                <fullName>Steering Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fan Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HMI and Electronics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <description>This field shows the customer machine model number.</description>
        <inlineHelpText>Enter the customer&apos;s machine model.  Example: 820C, 810C, etc.</inlineHelpText>
        <label>Machine Model Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cartridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Distributor_Price__c</fullName>
        <label>Distributor Sell Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SAP_Currency__c</fullName>
        <label>SAP Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_List_Price__c</fullName>
        <inlineHelpText>Please note - This may not be a list Price - If this price and the Current SAP Price are the same then this is not a list price but a special net price.</inlineHelpText>
        <label>SAP List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Price__c</fullName>
        <inlineHelpText>Current SAP price for this customer is shown if a list and discount is in place.</inlineHelpText>
        <label>SAP Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <formula>Opportunity.Sales_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org__c</fullName>
        <description>SAP KNVH integration field</description>
        <externalId>true</externalId>
        <label>SAP Sales Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <picklist>
            <picklistValues>
                <fullName>1010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1350</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1410</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1420</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1430</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1450</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1470</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1480</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1550</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1710</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2050</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2070</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6320</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/AddLineItems.cls
global without sharing class AddLineItems {

    public Opportunity opportunity{get;set;}
    public Quote quote{get;set;}
    public Machine_Model__c machine{get;set;}
    
    public String sObjectId;
    public String objName{get;set;}
    public String priceBookEntryId;
    public Boolean isOpportunity{get;set;}
    public Boolean isMachine{get;set;}
    public Boolean priceretrieved{get;set;}
    public Decimal SAPPrice;
    public Decimal SAPListPrice;
    public String SAPCurrency;
    public String materialNum;    
    public Boolean isSAPError{get;set;}
    public String iscloned;
    public String sapErrMsg{get;set;}
    public String salesorg;
    public String subsystem;
    public AddLineItems() {
      initializePage();                  
    } 
     
     public PageReference initializePage() {
        isOpportunity = false;
        isMachine = false;
        isSAPError = false;
        sObjectId = ApexPages.currentPage().getParameters().get('id');
        priceBookEntryId = ApexPages.currentPage().getParameters().get('priceBookEntryId');      
        iscloned = ApexPages.currentPage().getParameters().get('iscloned');
        salesorg = ApexPages.currentPage().getParameters().get('salesorg');          
        subsystem = ApexPages.currentPage().getParameters().get('subsystem');
        if (sObjectId.startsWith('a0Q')) {
            isMachine = true;
            List <Machine_Model__c> lstMachine = [Select Id, Account__r.RecordType.Name, Account__r.Account_Group__c, Account__r.Channel__c, Account__r.Parent.SAP_Account_ID__c,CurrencyIsoCode,Name, Account__r.SAP_Account_ID__c FROM Machine_Model__c Where Id = :sObjectId];
            if (lstMachine.isEmpty()) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, 'You have been redirected to incorrect link'));
                return null;
            }
            else {
                machine = lstMachine [0];
                objName = machine.Name;
            }
       } 
       else if(sObjectId.startsWith('006') ) {
         isOpportunity = true;
         List<opportunity> lstOppty = [Select Id, Account.RecordType.Name, Account.Account_Group__c, Account.Channel__c, Account.Parent.SAP_Account_ID__c,PriceBook2Id,CurrencyIsoCode,Name,Pricebook2.Name, Account.SAP_Account_ID__c, Sales_Org__r.SAP_Sales_Org__c FROM Opportunity Where Id = :sObjectId];
         if(lstOppty.isEmpty()) {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'You have been redirected to incorrect link'));
           return null;
         }
         else {
           opportunity = lstOppty[0];
             objName = opportunity.Name;
         }
       } 
       else {
         List<quote> lstQuote = [SELECT Id, Opportunity.Account.RecordType.Name, Opportunity.Account.Account_Group__c, Opportunity.Account.Channel__c, Opportunity.Account.Parent.SAP_Account_ID__c,PriceBook2Id,CurrencyIsoCode,Name,Pricebook2.Name, Opportunity.Sales_Org__r.SAP_Sales_Org__c,Opportunity.Account.SAP_Account_ID__c FROM Quote Where Id = :sObjectId];
         if(lstQuote.isEmpty()){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'You have been redirected to incorrect link'));
             return null;
         }
         else {
          quote = lstQuote[0];
             objName = quote.Name;
         } 
       }
       lstLineItem = new List<OpportunityLineItem>();    
       lstQuoteLineItem = new List<QuoteLineItem>();  
       lstMachineLineItem = new List<Machine_Model_Product__c>();
       
        if (iscloned=='1') {
            lstQuoteLineItem = [select Id, ClonedFlag__c, priceBookEntry.Product2.Name, priceBookEntry.Product2.SAP_Material_Code__c, Quantity, UnitPrice, Distributor_Price__c, SAP_Price__c, SAP_List_Price__c, SAP_Currency__c, Description, PS_Customer_Product_Category__c From QuoteLineItem where QuoteId = :sObjectId];
            for(QuoteLineItem qli :lstQuoteLineItem)
                qli.ClonedFlag__c = 'true2';
        }
        else
            SelectProduct();
       return null;
     }
     
  //-----------------------------------------------------------------------------------//
    
  private List<OpportunityLineItem> lstLineItem;
  private List<QuoteLineItem> lstQuoteLineItem;
  private List<Machine_Model_Product__c> lstMachineLineItem;
  
  public String selectedProducts {get;set;}
  
  public Product2 searchProduct {get;set;}
  
  public List<OpportunityLineItem> getOpportunityLineItems() {
    return this.lstLineItem;
  }
  
   public List<QuoteLineItem> getQuoteLineItems() {
    return this.lstQuoteLineItem;
  }
   
   public List<Machine_Model_Product__c> getMachineLineItems() {
    return this.lstMachineLineItem;
  }
  //================================================================//
  //Save Line Items and return back to Opportunity
  //===============================================================//
  public PageReference SaveLineItems() {
    try {
      if(isMachine) {
        if (!checkForMissingRequiredFields(this.lstMachineLineItem))
            upsert this.lstMachineLineItem;
          else 
          {
              machine.adderror('Fields with red heading are required.');
              return null;
          }
      } 
      else if(isOpportunity) {
        upsert this.lstLineItem;
      } 
      else {
        upsert this.lstQuoteLineItem;
      }
    }
    catch(DmlException ex) {
      ApexPages.addMessages(ex);
      return null;
    }
    
    return new PageReference('/' + sObjectId);
  }
  
  //================================================================//
  //Save Line Items and return back to for product selection
  //===============================================================//  
  public PageReference SaveAndMore() {
    try {
       if(isMachine) {
       if (!checkForMissingRequiredFields(this.lstMachineLineItem))
            upsert this.lstMachineLineItem;
          else 
          {
              machine.adderror('Fields with red heading are required.');
              return null;
          }
      } 
      else if(isOpportunity) {
        upsert this.lstLineItem;
      } 
      else {
        upsert this.lstQuoteLineItem;
      }
    }
    catch(DmlException ex) {
      ApexPages.addMessages(ex);
      return null;
    }
    PageReference pg;
     if(isMachine) {
        pg = new PageReference('/apex/AddMachineProduct?id='+sobjectId);
      } 
      else if(isOpportunity) { 
      pg = new PageReference('/apex/AddOpportunityProduct?id='+sobjectId);
    }
    else {
      pg = new PageReference('/apex/AddQuoteProduct?id='+sobjectId);
    }
    pg.setRedirect(true);    
    return pg;
  }
  
  private Boolean checkForMissingRequiredFields(List<Machine_Model_Product__c> lstMMPROD)  //true = a required field is missing
  {
      Boolean missingfields = false;
      for (Machine_Model_Product__c mmp :lstMMPROD)
      {
          if(mmp.Subsystem__c == null || mmp.Product_Type__c == null || mmp.Competitiveness__c == null || mmp.Adoption_Rate__c == null || mmp.Number_per_machine__c <= 0)
            missingfields = true;
      }
      return missingfields;
  }
  
  public PageReference GetSAPPrice()
  {
        if (isMachine && salesorg == '0') {
          machine.addError('You must select a Sales Org to retrieve SAP Price');
          return null;
        }
        else{
            SAP_PriceService pr = new SAP_PriceService();
            SAP_PriceService.SAPPriceInput params = new SAP_PriceService.SAPPriceInput();
            
          if(isMachine){ 
             params.SalesOrgId = salesorg;
             params.AccountId = machine.Account__r.SAP_Account_ID__c;           
             params.AccountGroup = machine.Account__r.Account_Group__c;
             params.Channel = machine.Account__r.Channel__c;
             params.ParentAccountId = machine.Account__r.Parent.SAP_Account_ID__c;           
             params.acctRecType = machine.Account__r.RecordType.Name;
             params.ProductCode = materialNum;
          } else if(isOpportunity){ 
             params.SalesOrgId = opportunity.Sales_Org__r.SAP_Sales_Org__c;
             params.AccountId = opportunity.Account.SAP_Account_ID__c;           
             params.AccountGroup = opportunity.Account.Account_Group__c;
             params.Channel = opportunity.Account.Channel__c;
             params.ParentAccountId = opportunity.Account.Parent.SAP_Account_ID__c;          
             params.acctRecType = opportunity.Account.RecordType.Name;
             params.ProductCode = materialNum;
          } else {
             params.SalesOrgId = quote.Opportunity.Sales_Org__r.SAP_Sales_Org__c;
             params.AccountId = quote.Opportunity.Account.SAP_Account_ID__c;           
             params.AccountGroup = quote.Opportunity.Account.Account_Group__c;
             params.Channel = quote.Opportunity.Account.Channel__c;          
             params.acctRecType = quote.Opportunity.Account.RecordType.Name;
             params.ParentAccountId = quote.Opportunity.Account.Parent.SAP_Account_ID__c;         
             params.ProductCode = materialNum;          
          }
          SAP_PriceService.SAPPriceOutput outprice;
          try{
              outprice = pr.InvokeSAPPricing(params);
              SAPPrice = outprice.SAPPrice;
              SAPCurrency = outprice.SAPCurrency; 
              SAPListPrice = outprice.SAPListPrice;
              if(outprice.RetCode!='' && outprice.RetCode!=null){
                isSAPError = true;
                sapErrMsg = outprice.RetMessage;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,sapErrMsg));
              }
              if(outprice.SAPPrice != null && outprice.SAPPrice > 0)
                priceretrieved = true;
              else
                priceretrieved = false;
          }catch (Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,pr.translateSAPError(e.getTypeName())));
          }           
          return null;
        }
  }
    
  //======================================================================//
  //Select Products and create Opportunity line Items
  //======================================================================//
  public PageReference SelectProduct() { 
        List <PriceBookEntry >lstPriceBookEntry = [Select Id,Product2Id, Product2.Name,Product2.SAP_Material_Code__c, UnitPrice FROM PriceBookEntry WHERE Id = :priceBookEntryId];
        if (lstPriceBookEntry.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, 'You have been redirected to incorrect link'));
            return null;
        }
        for (PriceBookEntry priceBookEntry :lstPriceBookEntry) {
            materialNum = priceBookEntry.Product2.SAP_Material_Code__c;
            String prodId = priceBookEntry.Product2Id;
            if (isMachine && salesorg != '0') {
                GetSAPPrice();
            }
            if (isMachine) {
                lstMachineLineItem.add(CreateMachineLineItem(priceBookEntry));
            }
            else if (isOpportunity) {
                GetSAPPrice();
                lstLineItem.add(CreateOpportunityLineItem(priceBookEntry));
            }
            else {
                GetSAPPrice();
                lstQuoteLineItem.add(CreateQuoteLineItem(priceBookEntry));
            }
        }
//  }
    return null;
}

  //==============================================================================//
 //Create Machine Line Items
 //===============================================================================// 
private Machine_Model_Product__c CreateMachineLineItem(PriceBookEntry priceBookEntry) {
    Machine_Model_Product__c lineItem = new Machine_Model_Product__c(Machine_Model__c = this.machine.Id);
    lineItem.Machine_Model_Product__c = priceBookEntry.Product2Id;
    lineItem.Name = priceBookEntry.Product2.SAP_Material_Code__c;
    lineItem.Subsystem__c = subsystem;
    lineItem.Sales_Org__c = salesorg;
    lineItem.Adoption_Rate__c = 100;
    lineItem.Number_per_machine__c = 0;
    if (!isSAPError)
    {
        lineItem.Price__c = SAPPrice;
        lineItem.CurrencyIsoCode = SAPCurrency;
        lineItem.IsSAPPrice__c = true;
        lineItem.SAP_Price_Retrieved_Date__c = Datetime.now();
    }
    return lineItem;
  }
  
 //==============================================================================//
 //Create Opportunity Line Items
 //===============================================================================// 
  private OpportunityLineItem CreateOpportunityLineItem(PriceBookEntry priceBookEntry){
    OpportunityLineItem lineItem = new OpportunityLineItem(OpportunityId = this.opportunity.Id);
    
    lineItem.UnitPrice = priceBookEntry.UnitPrice;
    lineItem.PricebookEntryId = priceBookEntry.Id;
    lineItem.PriceBookEntry = priceBookEntry;
    lineItem.Quantity = 0;
   // if (Opportunity.Sales_Org__c != '' && Opportunity.Sales_Org__c != null) {
        lineItem.SAP_Price__c = SAPPrice;
        lineItem.SAP_Currency__c = SAPCurrency;
        lineItem.SAP_List_Price__c = SAPListPrice;
   // }
   
    return lineItem;
  }
  
  //==============================================================================//
 //Create Opportunity Line Items
 //===============================================================================// 
  public QuoteLineItem CreateQuoteLineItem(PriceBookEntry priceBookEntry){
    QuoteLineItem lineItem = new QuoteLineItem(QuoteId = this.quote.Id);
    
    lineItem.UnitPrice = priceBookEntry.UnitPrice;
    lineItem.PricebookEntryId = priceBookEntry.Id;
    lineItem.PriceBookEntry = priceBookEntry;
    lineItem.Quantity = 0;
    lineItem.SAP_Price__c = SAPPrice;
    lineItem.SAP_Currency__c = SAPCurrency;
    lineItem.SAP_List_Price__c = SAPListPrice;
     
    return lineItem;
  }
  
  public PageReference cancel() {
      try {
        return new PageReference('/' + sObjectId);
      }
      catch(DmlException ex) {
        return new PageReference('/' + sObjectId);
      }
  }
   
  //================================================Currency Formatting==========================================/
  @RemoteAction
  global static String getTotalPrice(String quantity,String unitPrice) {
    String decimalSeparator = getDecimalSeparator();
    try {
      Decimal result = Decimal.valueOf(quantity) * Decimal.valueOf(unitPrice);
      result = result.setScale(2,System.RoundingMode.HALF_UP);  
     
      String formattedResult = result.format();     
      if(formattedResult.indexOf(decimalSeparator) == -1) {
       formattedResult += decimalSeparator + '00';
      }
      return formattedResult; 
    }
    catch(TypeException ex) {
       //GIGO garbage in,Garbage out
    }
    
    return '0'+ decimalSeparator + '00';
  } 
  
  /*
  *Returns the decimal separator for the current user locale to be used in js for number parsing
  */
  global static String getDecimalSeparator() {
    Decimal d = 0.25;
    return d.format().subString(1,2);
  }
  global static String getThousandSeparator() {
    Decimal d = 1000;
    return d.format().subString(1,2);
  }
  
}