objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MIDClonePageControllerExtension.cls
public with sharing class MIDClonePageControllerExtension {
    
    public MIDClonePageControllerExtension(ApexPages.StandardController controller) {
        this.mach = (Machine_Model__c)Controller.getRecord();
    }
    
    private MIDCloneUtils cc=new MIDCloneUtils();
    
    private Machine_Model__c mach;
    private ApexPages.StandardController controller;
    private string newParentRecordID; //New Parent Record ID for API call 
    public Integer numberOfItems {get;private set;}
    public Boolean hasChildRecords {get;private set;}
    private Map<String,String> chidlObjAPIName_FieldAPIName {get;private set;}
    private string fieldsNames{get;private set;}
    private string recordId;  //Parent record id
    private string objName;  //Parent object API name
     
    //Constructor
    public MIDClonePageControllerExtension(){ 
    }
      
    //Clone parent and selected child objects, redirect to the new parent record page after cloning
    public pagereference chainClone() {
        fieldsNames = '';
        string recId = mach.Id; //apexpages.currentPage().getParameters().get('id');
        String objAPIName= 'Machine_Model_Product__c'; //cc.getAllChildObjNames(objname, this.recordid).get(s);            
        String queryString = 'select count(id) total from Machine_Model_Product__c where Machine_Model__c=\'' + String.escapeSingleQuotes(recId) + '\'';
        SObject result = Database.query(queryString);
        if((Integer)result.get('total')>0)
            fieldsNames = fieldsNames + objAPIName + ','; 
        list<String> selectedChildObjAPINames=New list<String>();
        if(fieldsNames.length()>0) {
            for(String childObjAPIName:fieldsNames.split(',')) {
                selectedChildObjAPINames.add(childObjAPIName);
            }
        }
        string newParentRecordId = cc.startsClone(recId,selectedChildObjAPINames);
        PageReference pr = new PageReference('/'+newParentRecordId+'/e?retURL=%2F' + newParentRecordId);             
        return pr;
    }
}