objects/Machine_Model__c.object
<CustomObject>
    <description>Account Machine Models</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Models</relationshipLabel>
        <relationshipName>Machine_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Machine Model</label>
    <nameField>
        <label>Machine Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Machine_Model_Product__c.object
<CustomObject>
    <description>Machine Model Products</description>
    <fields>
        <fullName>IsSAPPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>set by Product Picker code (AddLineItems class) if an SAP price is returned</description>
        <label>IsSAPPrice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Machine_Model_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.SAP_Material_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <label>Machine Model</label>
        <referenceTo>Machine_Model__c</referenceTo>
        <relationshipLabel>Machine Model Products</relationshipLabel>
        <relationshipName>Machine_Model_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price per unit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SAP_Price_Retrieved_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>SAP Price Retrieved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Machine Model Product</label>
    <nameField>
        <label>Machine Model Material</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machine Model Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Machine_Model__c</fullName>
        <description>This field shows the customer machine model number.</description>
        <inlineHelpText>Enter the customer&apos;s machine model.  Example: 820C, 810C, etc.</inlineHelpText>
        <label>Machine Model Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SAP_Currency__c</fullName>
        <label>SAP Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_List_Price__c</fullName>
        <inlineHelpText>Please note - This may not be a list Price - If this price and the Current SAP Price are the same then this is not a list price but a special net price.</inlineHelpText>
        <label>SAP List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Price__c</fullName>
        <inlineHelpText>Current SAP price for this customer is shown if a list and discount is in place.</inlineHelpText>
        <label>SAP Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <formula>Opportunity.Sales_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org__c</fullName>
        <description>SAP KNVH integration field</description>
        <externalId>true</externalId>
        <label>SAP Sales Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Org_Master__c.object
<CustomObject>
    <description>Sales Org Master</description>
    <label>Sales Org Master</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RefreshSAPPrice.cls
public class RefreshSAPPrice{
   public String sObjectId;
   public String lineItemId;
   public Boolean isOpportunity;
   public Boolean isMachine;
   public Opportunitylineitem oli;
   public Quotelineitem qli;
   public Machine_Model_Product__c mmprod;
   
   private ApexPages.StandardController controller;
    
   public RefreshSAPPrice(ApexPages.StandardController controller){
    this.controller = controller;
    isOpportunity=false;
    isMachine=false;
    sObjectId = ApexPages.currentPage().getParameters().get('id');
    if (sObjectId.startsWith('a0Q')) {
        isMachine = true;
        lineItemId = ApexPages.currentPage().getParameters().get('mmprodId');
    }
    else if(sObjectId.startsWith('006') ) {
        isOpportunity = true;
        lineItemId = ApexPages.currentPage().getParameters().get('opportunityLineItemId');
    }
    else {
        lineItemId = ApexPages.currentPage().getParameters().get('quoteLineItemId');
    }
   }
   
   public PageReference autorun(){
    String errMsg;
    
    SAP_PriceService pr = new SAP_PriceService();
    SAP_PriceService.SAPPriceInput params = new SAP_PriceService.SAPPriceInput();
    SAP_PriceService.SAPPriceOutput outprice;   
    
    if(isMachine){ 
         mmprod = [Select Id, Machine_Model__r.Account__r.RecordType.Name, Machine_Model__r.Account__r.Account_Group__c, Machine_Model__r.Account__r.SAP_Account_ID__c, Machine_Model__r.Account__r.Channel__c, Machine_Model__r.Account__r.Parent.SAP_Account_ID__c, CurrencyIsoCode, Name, Machine_Model__r.Account__c, Sales_Org__c, Machine_Model_Product__r.SAP_Material_Code__c FROM Machine_Model_Product__c Where Id = :lineItemId];
         params.SalesOrgId = mmprod.Sales_Org__c;
         params.AccountId = mmprod.Machine_Model__r.Account__r.SAP_Account_ID__c;           
         params.AccountGroup = mmprod.Machine_Model__r.Account__r.Account_Group__c;
         params.Channel = mmprod.Machine_Model__r.Account__r.Channel__c;
         params.ParentAccountId = mmprod.Machine_Model__r.Account__r.Parent.SAP_Account_ID__c;           
         params.acctRecType = mmprod.Machine_Model__r.Account__r.RecordType.Name;
         params.ProductCode = mmprod.Machine_Model_Product__r.SAP_Material_Code__c;
        
        system.debug(params);
        try{
            outprice = pr.InvokeSAPPricing(params);  
            mmprod.Price__c = outprice.SAPPrice;
            mmprod.IsSAPPrice__c = true;
            mmprod.CurrencyISOCode = outprice.SAPCurrency;  
            mmprod.SAP_Price_Retrieved_Date__c = Datetime.now();        
            update mmprod;  
        } catch (Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,pr.translateSAPError(e.getTypeName())));
            return null;
        }
    }
    else if(isOpportunity){ 
        oli = [select Id, Opportunity.Account.Account_Group__c, Opportunity.Account.Channel__c, Opportunity.Account.Parent.SAP_Account_ID__c, Opportunity.Sales_Org__r.SAP_Sales_Org__c,Opportunity.Account.SAP_Account_ID__c,PricebookEntry.Product2.SAP_Material_Code__c, SAP_Price__c, SAP_Currency__c, SAP_List_Price__c from Opportunitylineitem where Id =: lineItemId];
        system.debug(oli);
        params.SalesOrgId = oli.Opportunity.Sales_Org__r.SAP_Sales_Org__c;
        params.AccountGroup = oli.Opportunity.Account.Account_Group__c;
        params.Channel = oli.Opportunity.Account.Channel__c;
        params.AccountId = oli.Opportunity.Account.SAP_Account_ID__c;
        params.ParentAccountId = oli.Opportunity.Account.Parent.SAP_Account_ID__c;
        params.ProductCode = oli.PricebookEntry.Product2.SAP_Material_Code__c;
        
        system.debug(params);
        try{
            outprice = pr.InvokeSAPPricing(params);  
            oli.SAP_Price__c = outprice.SAPPrice;
            oli.SAP_List_Price__c = outprice.SAPListPrice;
            oli.SAP_Currency__c = outprice.SAPCurrency;         
            update oli;  
        } catch (Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,pr.translateSAPError(e.getTypeName())));
            return null;
        }
    }else{
        qli = [select Id, Quote.Opportunity.Account.Account_Group__c, Quote.Opportunity.Account.Channel__c, Quote.Opportunity.Account.Parent.SAP_Account_ID__c, Quote.Opportunity.Sales_Org__r.SAP_Sales_Org__c, Quote.Opportunity.Account.SAP_Account_ID__c, PricebookEntry.Product2.SAP_Material_Code__c, SAP_Price__c, SAP_Currency__c, SAP_List_Price__c from Quotelineitem where Id =: lineItemId];
        params.SalesOrgId = qli.Quote.Opportunity.Sales_Org__r.SAP_Sales_Org__c;
        params.AccountGroup = qli.Quote.Opportunity.Account.Account_Group__c;
        params.Channel = qli.Quote.Opportunity.Account.Channel__c;
        params.AccountId = qli.Quote.Opportunity.Account.SAP_Account_ID__c;
        params.ParentAccountId = qli.Quote.Opportunity.Account.Parent.SAP_Account_ID__c;
        params.ProductCode = qli.PricebookEntry.Product2.SAP_Material_Code__c;

        try{
        outprice = pr.InvokeSAPPricing(params);
        qli.SAP_Price__c = outprice.SAPPrice;
        qli.SAP_List_Price__c = outprice.SAPListPrice;
        qli.SAP_Currency__c = outprice.SAPCurrency;
        update qli;         
        } catch (Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,pr.translateSAPError(e.getTypeName())));
            return null;            
        }
    }
    if(outprice.RetCode!=null && outprice.RetCode!=''){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,outprice.RetMessage));
        return null;
    } else  
        return saveAndReturn();
   }
   
    public PageReference saveAndReturn()
    {
         /*   PageReference cancel = controller.cancel();
            controller.save();
            return cancel;
         */
         PageReference liPage;
        if(isMachine){
            liPage = new ApexPages.StandardController(mmprod).view();         
        }
        else if (isOpportunity){
            liPage = new ApexPages.StandardController(oli).view();              
         }else{
            liPage = new ApexPages.StandardController(qli).view();      
         }
         liPage.setRedirect(true);
         return liPage;
    }
}