objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_At_Risk__c</fullName>
        <formula>IF ( Low_Quality_Opportunity__c ,  Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount At Risk</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <formula>IF( 
OR(
AND (Text(CE_Sales_model__c)=&quot;OEM&quot;,  
  OR((TODAY()-LastActivityDate)&gt;90,  
  (TODAY()-DATEVALUE(LastModifiedDate))&gt;90)),
OR((TODAY()-LastActivityDate)&gt;30,  (TODAY()-DATEVALUE(LastModifiedDate))&gt;30)),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Inactive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overdue__c</fullName>
        <formula>IF( 
AND(
NOT(
ISPICKVAL(StageName,&quot;Identified Opportunity (CE)&quot;) || ISPICKVAL(StageName,&quot;Identification (CE)&quot;) ),
CloseDate &lt; TODAY()), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Overdue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Extra_Large_Amount__c</fullName>
        <formula>IF(   Q_Extra_Large__c  =1, Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Extra Large Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Extra_Large__c</fullName>
        <formula>IF( Amount &gt; 3 * $User.Average_Opportunity_Amount__c &amp;&amp; $User.Average_Opportunity_Amount__c &gt; 0 ,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Extra Large</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Inactive_Amount__c</fullName>
        <formula>IF( Inactive__c=1, Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Inactive Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Over_Aged_Amount__c</fullName>
        <formula>IF(   Q_Over_Aged__c  =1, Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Over Aged Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Over_Aged__c</fullName>
        <formula>IF( 
    $User.Opportunity_Average_Age_Won__c &gt; 0 
    &amp;&amp; (Opp_Age__c &gt;  $User.Opportunity_Average_Age_Won__c *3),
    1,
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Over Aged</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Overdue_Amount__c</fullName>
        <formula>IF ( Overdue__c=1,Amount,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Size_Change_Amount__c</fullName>
        <formula>IF ( Q_Size_Change__c = 1, Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Size Change Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Size_Change__c</fullName>
        <formula>IF( Amount_Changes__c &gt; 0.3,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Size Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Stalled_in_Stage_Amount__c</fullName>
        <formula>IF(  Q_Stalled_in_Stage__c =1, Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Stalled in Stage Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Stalled_in_Stage__c</fullName>
        <formula>IF(ISBLANK( CE_Stage_Change_Date__c ),0,IF((TODAY()-CE_Stage_Change_Date__c)&gt;  $User.Opportunity_Average_Age_Lost__c ,1,0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Stalled in Stage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Time_Slippage_Amount__c</fullName>
        <formula>IF( Q_Time_Slippage__c = 1, Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Time Slippage Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q_Time_Slippage__c</fullName>
        <formula>IF(CloseDate_Changes__c &gt; 2,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q - Time Slippage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OTAggregateResultIterator.cls
global class OTAggregateResultIterator Implements Iterator<AggregateResult>{ 
 
    AggregateResult [] results {get;set;} 
    Integer index {get;set;} 
 
    global OTAggregateResultIterator(){ 
        index=0;
        String query = 'Select owner.division__c segment, '
            + 'owner.Region__c, '
            + 'owner.User_Country__c country, ' 
            + 'owner.Business_Segment__c team, '
            + 'OwnerId, '
            + 'StageName, '
            + 'sum(overdue__c) count_overdue, '
            + 'sum(Q_Overdue_Amount__c) overdue_amount, '
            + 'sum(inactive__c) count_inactive, '
            + 'sum(Q_Inactive_Amount__c) inactive_amount, '
            + 'sum(Q_Over_Aged__c) count_overaged, '
            + 'sum(Q_Over_Aged_Amount__c) overaged_amount ,'
            + 'sum(Q_Stalled_in_Stage__c) count_stalled, '
            + 'sum(Q_Stalled_in_Stage_Amount__c) stalled_amount,'
            + 'sum(Q_Time_Slippage__c) count_timeslip, ' 
            + 'sum(Q_Time_Slippage_Amount__c) timeslip_amount, '
            + 'sum(Q_Size_Change__c) count_sizechange, '
            + 'sum(Q_Size_Change_Amount__c) sizechange_amount,'
            + 'sum(Q_Extra_Large__c) count_extralarge, '
            + 'sum(Q_Extra_Large_Amount__c) extralarge_amount, '
            + 'count(Id) cnt, '
            + 'avg(Probability) avg_probability, '
            + 'sum(amount) sum_amount, '
            + 'avg(amount) avg_amount, '
            + 'sum(Amount_At_Risk__c) risk_amount '
            + 'FROM opportunity  '
            + 'WHERE account.business_org__c=\'Climate and Energy\' '
            + 'AND IsClosed = False '
            + 'GROUP BY owner.division__c, owner.Region__c, owner.User_Country__c, '
            + 'owner.Business_Segment__c,OwnerId, StageName';
        
        system.debug(LoggingLevel.INFO, '@@ Opportunity query: ' + query);
        results = Database.query(query); 
        system.debug(LoggingLevel.INFO, '@@ Opportunity query results: (' + results.size() + ') ' + results);
    } 
     
    global boolean hasNext(){ 
        return results !=null && !results.isEmpty() && index < results.size(); 
    } 
     
    global AggregateResult next(){ 
        return results[index++]; 
    } 
}