objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Climate and Energy users should read CE title</inlineHelpText>
        <label>Business Unit / Product Line (CE)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Code__c</fullName>
        <label>Model Code</label>
        <length>240</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Footer_Comments__c</fullName>
        <label>Footer Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_QuoteTriggers.cls
@isTest
private class Test_QuoteTriggers {
	
	static Id acctRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
	static User adminUser;	
	static Region__c usaRegion;
	static Id StdPBId;
	static PriceBookEntry stdpbe;
	static List<Account> lstAccounts;
	static List<Opportunity> lstOpptys;
	static List<Quote> lstQuotes;
	static List<QuoteLineItem> lstQLIs;
	static Account account1;
	static Account account2;
	static Account account3;
	static Opportunity oppty1;
	static Opportunity oppty2;
	
    static testMethod void testTriggers () {
		createUsers();
		system.runAs(adminUser) {
			createTestData();
			lstQuotes = new List<Quote>();
			lstQLIs = new List<QuoteLineItem>();		
			
			Test.startTest();
			Quote quote1 = new Quote(OpportunityId = oppty1.Id, Name = 'quote1', PriceBook2Id = StdPBId, Country_Specific_Template__c = usaRegion.Id, Description = 'abc', Footer_Comments__c = 'xyz');
			lstQuotes.add(quote1);
			Quote quote2 = new Quote(OpportunityId = oppty2.Id, Name = 'quote2', PriceBook2Id = StdPBId, Country_Specific_Template__c = usaRegion.Id, Description = 'abc', Footer_Comments__c = 'xyz', Approval_Date__c = null);
			lstQuotes.add(quote2);
			
			if(!lstQuotes.isEmpty())
				insert lstQuotes;
						
			QuoteLineItem qli = new QuoteLineItem(QuoteId = quote2.Id, PricebookEntryId = stdpbe.id, SAP_Price__c = 1, UnitPrice = 10, Quantity = 1, SAP_Currency__c  = 'DKK', Business_Area_Email__c = 'abc@xyz.com');	
			qli.Line_Item_Approval_Stage__c = 'Business Unit - Requires Review';
			qli.ClonedFlag__c = 'true';
			lstQLIs.add(qli);
			QuoteLineItem qli2 = new QuoteLineItem(QuoteId = quote2.Id, PricebookEntryId = stdpbe.id, SAP_Price__c = 2, UnitPrice = 20, Quantity = 2, SAP_Currency__c  = 'DKK', Business_Area_Email__c = 'abc@xyz.com');
			qli2.Line_Item_Approval_Stage__c = 'Auto-Approved';
			lstQLIs.add(qli2);
			QuoteLineItem qli3 = new QuoteLineItem(QuoteId = quote2.Id, PricebookEntryId = stdpbe.id, SAP_Price__c = 3, UnitPrice = 30, Quantity = 3, SAP_Currency__c  = 'DKK', Business_Area_Email__c = 'abc@xyz.com');
			lstQLIs.add(qli3);
			
			if(!lstQLIs.isEmpty())
				insert lstQLIs;
			
			/*qli.ClonedFlag__c = '';		
			qli.Business_Area_Email__c = 'def@xyz.com';*/
			//qli.Line_Item_Approval_Stage__c = 'Business Unit - Requires Review';
			//qli.Published_Customer_Comments__c = 'blah';
			qli3.Line_Item_Approval_Stage__c = 'Account Owner - Approved';
			update qli3;
			/*update lstQLIs;*/
			
			delete qli;
			Test.stopTest();
		}
    }
	
	/*static testMethod void testCloneController () {
		createUsers();
		system.runAs(adminUser) {
			createTestData();
			lstQuotes = new List<Quote>();
			lstQLIs = new List<QuoteLineItem>();
			Quote quote1 = new Quote(OpportunityId = oppty1.Id, Name = 'quote1', PriceBook2Id = StdPBId, Country_Specific_Template__c = usaRegion.Id, Description = 'abc', Footer_Comments__c = 'xyz');
			lstQuotes.add(quote1);
			if(!lstQuotes.isEmpty())
				insert lstQuotes;
			QuoteLineItem qli1 = new QuoteLineItem(QuoteId = quote1.Id, PricebookEntryId = stdpbe.id, SAP_Price__c = 3, UnitPrice = 30, Quantity = 3, SAP_Currency__c  = 'DKK', Business_Area_Email__c = 'abc@xyz.com');
			lstQLIs.add(qli1);
			
			if(!lstQLIs.isEmpty())
				insert lstQLIs;
			
			Test.startTest();
			PageReference pg = Page.QuoteClonePage;
			Test.setCurrentPage(pg);		
	        Apexpages.Standardcontroller stdcont = new Apexpages.Standardcontroller(quote1);
			QuoteClonePageControllerExtension cont = new QuoteClonePageControllerExtension(stdcont);
	        PageReference pr = cont.chainClone();
			Test.stopTest();
		}
	}*/
	
    static void createTestData() {
		Test_Utility.initTestData();   //create C&E pricebook
		Product2 p = Test_Utility.createProduct2();        
		p.Business_Unit__c = 'Motors';
		p.Model_Code__c = 'code';
		p.SAP_Material_Code__c = '1234';
		insert p;        		
		StdPBId = Test.getStandardPricebookId();
		stdpbe = new PricebookEntry(Pricebook2Id = StdPBId, Product2Id = p.Id, UnitPrice = 100, IsActive = true, CurrencyISOCode = 'DKK');
		insert stdpbe;
		usaRegion = new Region__c(Name = 'USA', Country_Code__c = 'US', Region__c = 'Americas');
		insert usaRegion;
		lstAccounts = new List<Account>();			
		account1 = createAccount(1, 'Integrated', 'Distributor');
		account1.SAP_Account_ID__c = '80000000';
		account1.Account_Group__c = '0001';
		lstAccounts.add(account1);
		
		account2 = createAccount(2, 'Integrated', 'Distributor');
		account2.SAP_Account_ID__c = '70000000';
		account2.Account_Group__c = '0002';
		lstAccounts.add(account2);
		
		account3 = createAccount(3, 'Integrated', 'Distributor');
		account3.Sales_Manager__c = adminUser.Id;
		account3.OwnerId = UserInfo.getUserId();
		lstAccounts.add(account3);
		if(!lstAccounts.isEmpty())
		insert lstAccounts;
		lstOpptys = new List<Opportunity>();
		oppty1 = Test_Utility.createOpportunity(account3.Id, 1);
		lstOpptys.add(oppty1);
		oppty2 = Test_Utility.createOpportunity(account2.Id, 2);
		lstOpptys.add(oppty2);
		if(!lstOpptys.isEmpty())
		insert lstOpptys;
		account1.SAP_Account_ID__c = '710000';
		account2.ParentId = account1.Id;
		account2.SAP_Account_ID__c = '810000';
		account3.ParentId = account2.Id;
		update lstAccounts;
	}
	
	private static Account createAccount(Integer i, String busorg, String channel){
		usaRegion = [select Id from Region__c where Name = 'USA'];
        Account account = new Account(
                                Name='Test Account Name' + i,
                                Business_Org__c = busorg,
								Channel__c = channel,
                                Country__c = usaRegion.Id,
                                RecordTypeId = acctRecordTypeId);
        account.OwnerId = UserInfo.getUserId();
        return account;
    }
	
    private static void createUsers() {
		Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
		UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
		adminUser = Test_Utility.createUser(profile.Id, roles.Id, 1);
		adminUser.DelegatedApproverId = UserInfo.getUserId();
		insert adminUser;
	}
}