objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Customer_Material_Number__c</fullName>
        <label>Customer Material Number</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Currency__c</fullName>
        <label>SAP Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_List_Price__c</fullName>
        <inlineHelpText>Please note - This may not be a list Price - If this price and the Current SAP Price are the same then this is not a list price but a special net price.</inlineHelpText>
        <label>SAP List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAP_Price__c</fullName>
        <inlineHelpText>Current SAP price for this customer is shown if a list and discount is in place.</inlineHelpText>
        <label>SAP Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SAP_Material_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Material Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/PS_Customer_Request__c.object
<CustomObject>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <formula>Opportunity.Sales_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org__c</fullName>
        <description>SAP KNVH integration field</description>
        <externalId>true</externalId>
        <label>SAP Sales Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Org_Master__c.object
<CustomObject>
    <description>Sales Org Master</description>
    <label>Sales Org Master</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PriceManagement.cls
global without sharing class PriceManagement {
            
    @future (callout = true)
    public static void GetSAPPrice(string sObjectId) {
        SAP_PriceService pr = new SAP_PriceService();
        SAP_PriceService.SAPPriceInput params = new SAP_PriceService.SAPPriceInput();
        QuoteLineItem lineitem = new QuoteLineItem();
        if (sObjectId.startsWith('0QL'))
        {
            lineitem = [select  Quote.Opportunity.Sales_Org__r.SAP_Sales_Org__c, Quote.Opportunity.Account.SAP_Account_ID__c, Quote.Opportunity.Account.Account_Group__c, Quote.Opportunity.Account.Channel__c, Quote.Opportunity.Account.Parent.SAP_Account_ID__c, Quote.Opportunity.Account.RecordType.Name, PricebookEntry.Product2.SAP_Material_Code__c, SAP_Price__c,  SAP_Currency__c, SAP_List_Price__c, UnitPrice From QuoteLineItem  where Id = :sObjectId];
            params.SalesOrgId = lineitem.Quote.Opportunity.Sales_Org__r.SAP_Sales_Org__c;
            params.AccountId = lineitem.Quote.Opportunity.Account.SAP_Account_ID__c;
            params.AccountGroup = lineitem.Quote.Opportunity.Account.Account_Group__c;
            params.Channel = lineitem.Quote.Opportunity.Account.Channel__c;
            params.acctRecType = lineitem.Quote.Opportunity.Account.RecordType.Name;
            params.ParentAccountId = lineitem.Quote.Opportunity.Account.Parent.SAP_Account_ID__c;
            params.ProductCode = lineitem.PricebookEntry.Product2.SAP_Material_Code__c;
        }
        
        SAP_PriceService.SAPPriceOutput outprice;
        outprice = pr.InvokeSAPPricing(params);
        lineitem.SAP_Price__c = outprice.SAPPrice;
        lineitem.SAP_Currency__c = outprice.SAPCurrency;
        lineitem.SAP_List_Price__c = outprice.SAPListPrice;
        update lineitem;
    }
    
    @future (callout = true)
    public static void GetSAPPriceOLI(string sObjectId, Id CRprod) {
        List<PS_Customer_Request__c> lstCustReqs = new List<PS_Customer_Request__c>([select Id, OpptyLineItemID__c from PS_Customer_Request__c where OpptyLineItemID__c = :sObjectId]);
        SAP_PriceService pr = new SAP_PriceService();
        SAP_PriceService.SAPPriceInput params = new SAP_PriceService.SAPPriceInput();
        OpportunityLineItem oli = [select Id, OpportunityId, Customer_Material_Number__c, CurrencyIsoCode, PricebookEntryId, PricebookEntry.Pricebook2Id, Opportunity.Account.Account_Group__c, Opportunity.Account.Channel__c, Opportunity.Account.Parent.SAP_Account_ID__c, Opportunity.Sales_Org__r.SAP_Sales_Org__c, Opportunity.Account.SAP_Account_ID__c, opportunity.Account.RecordType.Name, PricebookEntry.Product2.SAP_Material_Code__c, SAP_Price__c, SAP_Currency__c, SAP_List_Price__c from Opportunitylineitem where Id = :sObjectId];
        PricebookEntry pbe = [select Id from PricebookEntry where Product2Id = :CRprod and Pricebook2Id = :oli.PricebookEntry.Pricebook2Id and CurrencyIsoCode = :oli.CurrencyIsoCode limit 1];
        params.SalesOrgId = oli.Opportunity.Sales_Org__r.SAP_Sales_Org__c;
        params.AccountGroup = oli.Opportunity.Account.Account_Group__c;
        params.Channel = oli.Opportunity.Account.Channel__c;
        params.AccountId = oli.Opportunity.Account.SAP_Account_ID__c; 
        params.acctRecType = oli.opportunity.Account.RecordType.Name;
        params.ParentAccountId = oli.Opportunity.Account.Parent.SAP_Account_ID__c;
        params.ProductCode = oli.PricebookEntry.Product2.SAP_Material_Code__c;
        
        SAP_PriceService.SAPPriceOutput outprice;
        outprice = pr.InvokeSAPPricing(params);
        QuoteCloneUtility qcu = new QuoteCloneUtility(oli.Id);
        OpportunityLineItem oliClone = (OpportunityLineItem)qcu.newRecord;
        oliClone.put('SAP_Currency__c', outprice.SAPCurrency);
        oliClone.put('SAP_List_Price__c', outprice.SAPListPrice);
        oliClone.put('SAP_Price__c', outprice.SAPPrice);
        oliClone.put('PricebookEntryId', pbe.Id);
        insert oliClone;
        delete oli; 
        for(PS_Customer_Request__c cr : lstCustReqs){
            cr.OpptyLineItemID__c = oliClone.Id;
        }
        update lstCustReqs;
    }
}