objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <formula>Opportunity.Sales_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Comatrol_Distributor_Quote_Footer__c</fullName>
        <label>Comatrol Distributor Quote Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Comatrol_OEM_Quote_Footer__c</fullName>
        <label>Comatrol OEM Quote Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Distributor_Quote_Footer__c</fullName>
        <description>for use in Quote PDF</description>
        <label>PS Distributor Quote Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>OEM_Quote_Footer__c</fullName>
        <description>for use in the Quote PDF</description>
        <label>PS OEM Quote Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Turolla_Distributor_Quote_Footer__c</fullName>
        <label>Turolla Distributor Quote Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Turolla_OEM_Quote_Footer__c</fullName>
        <label>Turolla OEM Quote Footer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Sales_Org__r.Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Org_Master__c.object
<CustomObject>
    <description>Sales Org Master</description>
    <label>Sales Org Master</label>
    <nameField>
        <label>Sales Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <picklist>
            <picklistValues>
                <fullName>1010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1160</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1350</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1410</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1420</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1430</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1450</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1470</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1480</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1550</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1710</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2050</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2070</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6320</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/QuotePDFExtension.cls
public with sharing class QuotePDFExtension {
    
    private QuoteLineItem QLI;
    private Quote quote;
    private Opportunity oppty;
    private Account acct;
	private static Id acctRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
    public Boolean isDistributor{get;set;}
    public Boolean isIndirect{get;set;}
    public Boolean isDirect{get;set;}
    public string footertext{get;set;}
    //public string size {get;set;}
    public String imageURL{get;set;}
    public String acctAddress{get;set;}
	public Boolean showWatermark{get;set;}	
    //public String FooterSize{get;set;}
    //public Integer countEnterHeader{get;set;}
    //public Integer countEnterFooter{get;set;} 
    public string qId;
	
 	public string getDocumentLogoUrl()
    {
        //FooterSize='258px';
        imageURL='/servlet/servlet.FileDownload?file=';
        List<Document> lstDocument = new List<Document>();
		//Region__c japan = [SELECT id, Name from Region__c where Name = 'Japan'];
		if (acct.Business_Org__c == 'Comatrol')
		{
			lstDocument = [Select Id,DeveloperName from Document where DeveloperName = 'Comatrol_Logo' limit 1];
		}
		else if (acct.Business_Org__c == 'Turolla')
		{
			lstDocument = [Select Id,DeveloperName from Document where DeveloperName = 'Turolla_200_px_wide' limit 1];
		}
        //else if (quote.Country_Specific_Template__c == japan.Id)
         //   lstDocument = [Select Id,DeveloperName from Document where DeveloperName = 'Daikin' limit 1];
        else
            lstDocument = [Select Id,DeveloperName from Document where DeveloperName = 'DanfossLogoForPDF' limit 1];
        if(lstDocument.size()>0)
        {
            imageURL=imageURL+lstDocument[0].id;
        }
		//size = '2.0';
        return imageURL;
    }
    
    public QuotePDFExtension(ApexPages.StandardController controller) {
        this.quote = (Quote)controller.getRecord();
        //size = '2.0';
        oppty = [select AccountId, Sales_Org__r.Name from Opportunity where Id = :quote.OpportunityId];
        acct = [select Channel__c, SAP_Account_ID__c, Account_Group__c, Formatted_Address__c, Name, ShippingCity, ShippingCountry, ShippingPostalCode, ShippingState, ShippingStreet, ParentId, Country__r.Country_Code__c, RecordTypeId, Business_Org__c from Account where Id = :oppty.AccountId];
		if (acct.Business_Org__c == 'Comatrol' || acct.Business_Org__c == 'Turolla')	{
			showWatermark = true;
		}
		else{
			showWatermark = false;
		}
        if (acct.Channel__c == 'Distributor') {
            isDistributor = true;
            isDirect = false;
            isIndirect = false;
            if (acct.Business_Org__c == 'Turolla')
				footertext = quote.Country_Specific_Template__r.Turolla_Distributor_Quote_Footer__c;
			else if (acct.Business_Org__c == 'Comatrol')
				footertext = quote.Country_Specific_Template__r.Comatrol_Distributor_Quote_Footer__c;
			else
				footertext = quote.Country_Specific_Template__r.Distributor_Quote_Footer__c;
        }
        else if (acct.Channel__c == 'Indirect') {
            isDistributor = false;
            isDirect = false;
            isIndirect = true;
            if (acct.Business_Org__c == 'Turolla')
				footertext = quote.Country_Specific_Template__r.Turolla_Distributor_Quote_Footer__c;
			else if (acct.Business_Org__c == 'Comatrol')
				footertext = quote.Country_Specific_Template__r.Comatrol_Distributor_Quote_Footer__c;
			else
				footertext = quote.Country_Specific_Template__r.Distributor_Quote_Footer__c;			
        }
        else { //Direct or Global
            isDistributor = false;
            isDirect = true;
            isIndirect = false; 
            if (acct.Business_Org__c == 'Turolla')
				footertext = quote.Country_Specific_Template__r.Turolla_OEM_Quote_Footer__c;
			else if (acct.Business_Org__c == 'Comatrol')
				footertext = quote.Country_Specific_Template__r.Comatrol_OEM_Quote_Footer__c;
			else
            	footertext = quote.Country_Specific_Template__r.OEM_Quote_Footer__c;
        }
		Account acctForAddress;
		if(isIndirect && acct.ParentId != null)
			acctForAddress = [select Formatted_Address__c, Name, ShippingCity, ShippingCountry, ShippingPostalCode, ShippingState, ShippingStreet from Account where Id = :acct.ParentId];
		else	
			acctForAddress = acct;
		
		if(acct.RecordTypeId == acctRecordTypeId){ //is prospect			
			acctAddress = acctForAddress.Name + '<br/>' + acctForAddress.ShippingStreet + '<br/>' + acctForAddress.ShippingCity + ', ' + acctForAddress.ShippingState + '  ' + acctForAddress.ShippingPostalCode + '<br/>' + acctForAddress.ShippingCountry;
		}
		else
			acctAddress = acctForAddress.Formatted_Address__c;
    }
    
    public User getcurUser() {
        return [select CompanyName,Street, City, State, PostalCode, Country from User where Id = :UserInfo.getUserId()];
    }
}