objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Production_Start_Date__c</fullName>
        <description>Field used by both C&amp;E and PS. For PS the former name was production start date. 
The main purpose is to identify when the first delivery to an Opportunity will take place.</description>
        <inlineHelpText>Add the date of the first delivery of the Opportunity</inlineHelpText>
        <label>Date of first delivery</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org__c</fullName>
        <description>SAP KNVH integration field</description>
        <externalId>true</externalId>
        <label>SAP Sales Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/Test_CaptureOpportunityController.cls
/**************************************************************************************
Class           : CaptureOpportunityController_Test 
Developed by    : Shailendra Singh(Appirio Offshore)
Created Date    : 28 Aug 2012
Description     : Test class for CaptureOpportunityController 
Related Task    : T-77780
****************************************************************************************/
@isTest
private class Test_CaptureOpportunityController {

    static testMethod void myUnitTest() {
        Account acc = Test_Utility.createAccount(1);
        insert acc;
        Contact contact = Test_Utility.createContact(acc.id,1);
        insert contact;
        
        Campaign campaign = new Campaign();
        campaign.Name = 'Demo';
        insert campaign;
        Sales_Org__c so = new Sales_Org__c(Name = '1500', SAP_Sales_Org__c = '1500', Account__c = acc.Id);
        insert so;
        System.currentPageReference().getParameters().put('campaignID',campaign.id);
        System.currentPageReference().getParameters().put('contactID',contact.id);
        Test.startTest();
            CaptureOpportunityController controller = new CaptureOpportunityController();
            controller.opportunity.StageName = 'Evaluating Need';
            controller.opportunity.CurrencyIsoCode = 'USD';
        	controller.opportunity.Sales_Org__c = so.Id;
            controller.opportunity.Name = 'Unit Test';
            controller.opportunity.Production_Start_Date__c = System.today();
             controller.opportunity.CloseDate = System.today().addDays(-5);
            controller.save();
        Test.stopTest();
        // validate that campaign has opportunity related to it.
        
        List<Opportunity> oppList = [Select ID from Opportunity Where CampaignID = :campaign.Id];
        
        System.assertEquals(oppList.size(),1);
        
    }
}