objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>CE used for Project site adress</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State_Province__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Test_AfterLeadConvert.cls
/*---------------------------------------------------------------------
  Author        :   Appirio Offshore(Nikita Jain)
  Date          :   July 25, 2012
  Description   :   Test class for AfterLeadConvert trigger
                    (Trigger on Lead maps custom address fields of lead to
                     Shipping address field of account and mailing address of contact)
  Related Task  :   Task T-65155    
//---------------------------------------------------------------------*/
@isTest
private class Test_AfterLeadConvert {
 
    static Lead lead;
    @isTest 
    static void testLeadConvert() {
        createData();
        
        //Converting lead
        Database.LeadConvert lc = new database.LeadConvert();
        
        lc.setLeadId(lead.Id);
        LeadStatus convertstatus = [select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setDoNotCreateOpportunity(true);
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult results = Database.convertLead(lc);
        
        lead ld = [Select l.ConvertedAccount.ShippingCountry, l.ConvertedAccount.ShippingPostalCode,
                     l.ConvertedAccount.ShippingState, l.ConvertedAccount.ShippingCity,
                     l.ConvertedAccount.ShippingStreet, l.ConvertedAccountId , City__c , Country__r.name ,
                     State_Province__r.name, Zip_Code__c, Street__c, l.ConvertedContact.MailingCountry,
                     l.ConvertedContact.MailingPostalCode, l.ConvertedContact.MailingState,Business_Org__c,
                     Channel__c, l.ConvertedAccount.Channel__c, 
                     l.ConvertedContact.MailingCity, l.ConvertedContact.MailingStreet, l.ConvertedContactId,
                     ConvertedAccount.Business_Org__c From Lead l where id = :lead.Id];
                     
        /*system.assertEquals(ld.ConvertedAccount.ShippingCountry , ld.Country__r.name);
        system.assertEquals(ld.ConvertedAccount.ShippingState , ld.State_Province__r.name); 
        system.assertEquals(ld.ConvertedAccount.ShippingCity , ld.City__c); 
        system.assertEquals(ld.ConvertedAccount.ShippingStreet , ld.Street__c); 
        system.assertEquals(ld.ConvertedAccount.ShippingPostalCode , ld.Zip_Code__c);
        system.assertEquals(ld.ConvertedAccount.Business_Org__c , ld.Business_Org__c);  
        system.assertEquals(ld.ConvertedAccount.Channel__c , ld.Channel__c);         
        
        
        system.assertEquals(ld.ConvertedContact.MailingCountry , ld.Country__r.name);
        system.assertEquals(ld.ConvertedContact.MailingState , ld.State_Province__r.name);  
        system.assertEquals(ld.ConvertedContact.MailingCity , ld.City__c);  
        system.assertEquals(ld.ConvertedContact.MailingStreet , ld.Street__c);  
        system.assertEquals(ld.ConvertedContact.MailingPostalCode , ld.Zip_Code__c);  */               
        
    }
    
    //Method to create dummy data 
    static void createData(){
        Region__c reg = new Region__c();
        reg.Country_Code__c = 'TC';
        reg.Name = 'test Country';
        insert reg;
        
        State_Province__c state = new State_Province__c();
        state.Name = 'test state';
        insert state;
        
        Account acct = Test_Utility.createAccount(1);
        insert acct;
        
        Opportunity oppty = Test_Utility.createOpportunity(acct.Id, 1);
        insert oppty;
        
        lead = new Lead();
        lead.City = 'test City';
        lead.Country = 'test Country';
        lead.State = 'test state';
        lead.PostalCode = '1234';
        lead.Street = 'test street';
        lead.LastName = 'test lastname'+'i';
        lead.Company = 'test company';
        //lead.ConvertedOpportunityId = oppty.Id;
        lead.Account_Manager__c = system.Userinfo.getUserId();
        lead.Distributor__c = system.Userinfo.getUserId();
        insert lead;
        
        
    }
    
}