objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Sub_Account__c</field>
                <operation>equals</operation>
                <valueField>Sales_Area__c.Sub_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CE_Opportunity</fullName>
        <active>true</active>
        <businessProcess>C%26E Sales Process</businessProcess>
        <label>Climate and Energy Open Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>ConfigitQuoteId__c</fullName>
        <description>The quote id/number assigned by Configit</description>
        <externalId>true</externalId>
        <label>Configit Quote Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ConfigitQuoteRev__c</fullName>
        <label>Configit Revision Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Account_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup relationship is created to make Quotes visible in a related list on Account. This field is to be populated by configit.</description>
        <label>Account (Quote)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes_Visible_On_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>My_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Sub Account must belong to the selected account</errorMessage>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Custom_Account_Lookup__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CE_Quote</fullName>
        <active>true</active>
        <label>CE Quote</label>
    </recordTypes>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Area Master</label>
        <referenceTo>Sales_Area_Master__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Area_Master__r.Sales_Area__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Area_Master__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Org__c + &quot;-&quot; +  Channel__c + &quot;-&quot; +  Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
</CustomObject>

classes/QuoteTabController_Test.cls
@isTest
public class QuoteTabController_Test {

    public static testMethod void test_QuoteTab() {
		Quote q = createTestData();
        
        Task t = new Task();        
        t.Subject = 'My Follow-up task';
        t.ActivityDate = Date.today();        
        t.WhatId = q.Id;
        insert t;
        
        QuoteTabController qtc = new QuoteTabController();
        
        for (SelectOption o : qtc.listViewOptions) {
        	qtc.selectedListView = o.getValue();
        	qtc.getQuotes();    
        }        
        
    }
    
    public static quote createTestData () {
        /* Price Book */
        Pricebook2 pb = Test_DataFactory.create_CE_PriceBook();        
        insert pb;
        
        /* Create CE Customer */        
        Account account = Test_DataFactory.create_CE_Customer('Danfoss', 'USD', 'DK', 'CER');
        account.ShippingCountry = 'DK';
        account.ShippingPostalCode = '6430';
        account.ShippingCity = 'Nordborg';
        account.ShippingStreet = 'Nordborgvej 81';        
        insert account;
                
        Sales_Area_Master__c sam = Test_DataFactory.create_SalesAreaMaster('2300','00','00');
        insert sam;
                        
        Sub_Account__c sa = Test_DataFactory.create_SubAccount(account.name, '23456789', account);
        insert sa;
        
        Sales_Area__c sao = Test_DataFactory.create_salesArea(sa, sam);
        insert sao;               
        
        Test_DataFactory.setMaster(account, sa);        
        update account;
        
        contact c = new contact();        
        c.Academic_Title__c = 'Professor';
        c.AccountId = account.Id;
        c.FirstName = 'Anders';
        c.LastName = 'Breinholt';
        c.Phone = '+45 12345678';
        c.Email = 'ab=danfoss.com@example.com';
        insert c;
        
        Opportunity opp = new Opportunity();
        opp.accountId = account.Id;
        opp.Name = 'My Test Opportunity';
        opp.Sub_Account__c = sa.Id;
        opp.Sales_Area__c = sao.Id;
        opp.RecordTypeId = [SELECT Id FROM recordtype WHERE sObjectType='Opportunity' and DeveloperName = 'CE_Opportunity' and IsActive=true LIMIT 1].Id;
        opp.CurrencyIsoCode = 'USD';
        opp.Amount  = 5000;
        opp.Contact__c = c.id;
        opp.CloseDate = Date.today();
        opp.StageName = 'Initiated';        
        insert opp;
        
        Quote q = new Quote(ConfigitQuoteId__c = '012345678', OpportunityId=opp.Id, Status='In Progress');
        q.RecordTypeId = [SELECT Id FROM recordtype WHERE sObjectType='Quote' and DeveloperName = 'CE_Quote' and IsActive=true LIMIT 1].Id;
		q.ConfigitQuoteRev__c = 'R1';
		q.ExpirationDate = Date.today(); 
        q.Name= 'My Test Quote';
        q.Status = 'In Progress';
		q.ContactId=c.Id;
        q.Custom_Account_Lookup__c=account.Id;
        q.Sub_Account__c = sa.Id;
		q.Pricebook2Id = pb.Id;
        q.Responsible__c = UserInfo.getUserId();
		insert q;
               
        
        return q;
    }
}