objects/Opportunity_Lost_Product__c.object
<CustomObject>
    <description>C&amp;E Object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Lost Products</relationshipLabel>
        <relationshipName>Lost_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Lost Products</relationshipLabel>
        <relationshipName>Lost_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lost Product</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lost Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lost Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MarkOliAsLostExtension.cls
public class MarkOliAsLostExtension {
    
    private ApexPages.StandardController controller;
    
    public MarkOliAsLostExtension(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference moveToLost() {
        ID oliId = controller.getId();
        OpportunityLineItem opptLineItem = [select OpportunityId, Product2Id, Quantity, UnitPrice, CurrencyIsoCode from OpportunityLineItem where Id = :oliId];
        
        Opportunity_Lost_Product__c opptLostItem = new Opportunity_Lost_Product__c(
            Opportunity__c = opptLineItem.OpportunityId,
            Product__c = opptLineItem.Product2Id,
            Quantity__c = opptLineItem.Quantity,
            Price__c = opptLineItem.UnitPrice,
            CurrencyIsoCode = opptLineItem.CurrencyIsoCode
        );
        
        insert opptLostItem;
        delete opptLineItem;
        
        return controller.cancel();
    }
    
}