objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chosen_Sub_Segment__c</fullName>
        <label>Chosen Sub Segment</label>
        <picklist>
            <picklistValues>
                <fullName>AC - Commercial AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC - Heat Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC - Residential AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Refrigeration Subsystem Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Speciality Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR - Products &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Oil &amp; Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Reverse Osmosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Ultra Pure Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Air Compressor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Industrial Engines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Industrial Hydraulics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Marine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Mobile Hydraulics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Water Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Wind Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Air Conditioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Commercial Refrigeration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Direct Served - Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Direct Served - Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Direct Served - Premium Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Food Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Indirect Served - Independent Retailers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Indirect Served - Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Industrial Automation</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Application__c</fullName>
        <description>C&amp;E Application related to Account Sub Segment - Only relevant for RC and CC</description>
        <label>Main Application</label>
        <picklist>
            <controllingField>Chosen_Sub_Segment__c</controllingField>
            <picklistValues>
                <fullName>Agricultural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Dryers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air to Water Heat Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoclaves/ Sterilizers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Bar Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bakery Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beer &amp; Wine Cellar Coolers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage Dispensers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blast Freezers &amp; Chillers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boiler Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brewery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bus &amp; Train Air Conditioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Washing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chillers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close Control Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Ice Making Machines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Refrigerators &amp; Freezers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condensing Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dairy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dishwashing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Heating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Secondary_Segment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Secondary Segment?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <description>C&amp;E Sub segment - Mainly used for RC and CC for segmentation purpose</description>
        <inlineHelpText>Choose the relevant sub segment - Only relevant for RC and CC - otherwise select &quot;Not available&quot;</inlineHelpText>
        <label>Sub Segment</label>
        <picklist>
            <picklistValues>
                <fullName>RC CC Sub Segment 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RC CC Sub Segment 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available -PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available -HS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunitySubSegmentExtension.cls
public class OpportunitySubSegmentExtension {
    
    private Opportunity opp;
    public boolean renderdirect { get; set; }
    
    public OpportunitySubSegmentExtension(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'Account.Sub_Segment__c', 'Account.Secondary_Sub_Segment__c', 'Secondary_Segment__c'});
        }
        renderdirect = false;
        opp = (Opportunity) stdController.getRecord();
    }
    
    public void SecondarySubSegment() {
        opp.Chosen_Sub_Segment__c = opp.Account.Secondary_Sub_Segment__c;
        if (opp.Secondary_Segment__c == false) {
            opp.Main_Application__c = null;
        }
        opp.Secondary_Segment__c = true;
        update opp;
        renderdirect = true;
    }
    
    public void PrimarySubSegment() {
        opp.Chosen_Sub_Segment__c = opp.Account.Sub_Segment__c;
        if (opp.Secondary_Segment__c == true) {
            opp.Main_Application__c = null;
        }
        opp.Secondary_Segment__c = false;
        update opp;
        renderdirect = true;
    }    
}