objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Sub_Account__c</field>
                <operation>equals</operation>
                <valueField>Sales_Area__c.Sub_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <inlineHelpText>Climate and Energy users should read CE title</inlineHelpText>
        <label>Business Unit / Product Line (CE)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isProductGroupOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProductGroupOnly</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Product_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Code__c</fullName>
        <label>Group Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Product Groups</label>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>TEXT(Sub_Account__r.Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Sub_Account__r.SAP_Account_ID__c</formula>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Area Master</label>
        <referenceTo>Sales_Area_Master__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Area_Master__r.Sales_Area__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Area_Master__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Org__c + &quot;-&quot; +  Channel__c + &quot;-&quot; +  Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SAP_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SAP_Integration</label>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration Controls</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/Test_OpportunityProductEntryExtension.cls
@isTest
public class Test_OpportunityProductEntryExtension {

    private static void initProductGroups() {
        Test_Utility.initTestData();
        insert new List<Product_Groups__c> {
            new Product_Groups__c(Name = 'PL06', Group_Code__c = 'PL06', Division__c = 'Commercial Compressors'),
            new Product_Groups__c(Name = 'PL12', Group_Code__c = 'PL12', Division__c = 'Refrigeration Controls'),
            new Product_Groups__c(Name = 'PL08', Group_Code__c = 'PL08', Division__c = 'District Energy'),
            new Product_Groups__c(Name = 'PL34', Group_Code__c = 'PL34', Division__c = 'Heating Solutions'),
            new Product_Groups__c(Name = 'PL09', Group_Code__c = 'PL09', Division__c = 'Danfoss Drives'),
            new Product_Groups__c(Name = 'PL99', Group_Code__c = 'PL09', Division__c = 'Heating Solutions')                
        };
    }
    
    public static testMethod void testAddProduct() {
        initProductGroups();
        Product2 product = Test_Utility.createProduct2();
        product.Business_Unit__c = 'xyzBU';
        product.isProductGroupOnly__c=true;        
        insert product;
        ID pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = Test_Utility.createPricebookEntry(product.Id, pricebookId, 'USD');
        insert pbe;
        Account account = Test_Utility.createAccount(0);
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.Pricebook2Id = pricebookId;
        opportunity.CurrencyIsoCode = 'USD';
        insert opportunity;
        
        Test.startTest();
        
        // Load the page
        OpportunityProductEntryExtension c = new OpportunityProductEntryExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(null, c.init());
        System.assert(ApexPages.getMessages().isEmpty());
        System.assertEquals(0, c.Total);
        System.assertEquals(0, c.shoppingCart.size());
        System.assertEquals(5, c.getDivisions().size());
        //System.assertEquals(2, c.getProductLines().size());
        
        // Search for products
        
        c.ProductLine = 'xyz*';
        c.search();
        //System.assertEquals(1, c.getAvailableProducts().size());
        
        c.ProductLine = 'xyzBU';
        c.search();
        System.assertEquals(1, c.getAvailableProducts().size());
        
        
        
        
        // Add product
        c.toSelect = c.getAvailableProducts()[0].Id;
        c.addToShoppingCart();
        System.assertEquals(0, c.getAvailableProducts().size());
        System.assertEquals(1, c.shoppingCart.size());
        System.assertEquals(0, c.Total);

        // Set quantity and price
        c.shoppingCart[0].oppLine.Quantity = 2;
        c.shoppingCart[0].oppLine.UnitPrice = 2;
        c.refreshTotals();
        System.assertEquals(4, c.Total);
        
        PageReference pr1 = c.changepricebook();
        PageReference pr2 = c.goToProductSelector();
        PageReference pr3 = c.goToProductGroupSelector();
        
        // Save changes
        PageReference pr = c.onSave();
        System.assert(ApexPages.getMessages().isEmpty());
        
        
        
        Test.stopTest();
        
        System.assertNotEquals(null, pr);
        System.assertEquals(1, [select Id from OpportunityLineItem].size());
    }
    
    public static testMethod void testRemoveProduct() {
        initProductGroups();
        Product2 product = Test_Utility.createProduct2();
        product.Business_Unit__c = 'xyzBU';
        insert product;
        ID pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = Test_Utility.createPricebookEntry(product.Id, pricebookId, 'USD');
        insert pbe;
        Account account = Test_Utility.createAccount(0);
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.Pricebook2Id = pricebookId;
        opportunity.CurrencyIsoCode = 'USD';
        insert opportunity;
        OpportunityLineItem oli = Test_Utility.createOpportunityLineItem(opportunity.Id, pbe.Id, 0);
        oli.Quantity = 2;
        oli.TotalPrice = 4;
        insert oli;
        
        Test.startTest();
        
        // Load the page
        OpportunityProductEntryExtension c = new OpportunityProductEntryExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(null, c.init());
        System.assert(ApexPages.getMessages().isEmpty());
        System.assertEquals(4, c.Total);
        System.assertEquals(1, c.shoppingCart.size());
        c.getDivisions();
        c.getProductLines();
        
        // Remove product
        c.toUnselect = c.shoppingCart[0].oppLine.PriceBookEntryId;
        c.removeFromShoppingCart();
        System.assertEquals(0, c.shoppingCart.size());
        System.assertEquals(0, c.Total);
        
        // Save changes
        PageReference pr = c.onSave();
        System.assert(ApexPages.getMessages().isEmpty());
        
        Test.stopTest();
        
        System.assertNotEquals(null, pr);
        System.assertEquals(0, [select Id from OpportunityLineItem].size());
    }
    
    public static testMethod void testSelectPricebook() {
        initProductGroups();
        Pricebook2 pb = [select Id from Pricebook2 where Name = 'Climate and Energy'];
        Account account = Test_Utility.createAccount(0);
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.CurrencyIsoCode = 'USD';
        insert opportunity;
        
        Test.startTest();
        
        // Load the page
        OpportunityProductEntryExtension c = new OpportunityProductEntryExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(null, c.init());
        System.assert(ApexPages.getMessages().isEmpty());
        
        Test.stopTest();
        
        System.assertEquals(pb.Id, opportunity.Pricebook2Id);
        System.assertEquals(pb.Id, [select Pricebook2Id from Opportunity].Pricebook2Id);
    }
    
    public static testMethod void testFetchPrices() {
        initProductGroups();
        insert new List<SAP_Integration__c> {
            new SAP_Integration__c(Name = 'CE_User', Value__c = 'test'),
            new SAP_Integration__c(Name = 'CE_Password', Value__c = 'test'),
            new SAP_Integration__c(Name = 'CE_URL', Value__c = 'test')
        };
        Product2 product = Test_Utility.createProduct2();
        product.Business_Unit__c = 'xyzBU';
        insert product;
        ID pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = Test_Utility.createPricebookEntry(product.Id, pricebookId, 'USD');
        insert pbe;
        Sales_Area_Master__c salesAreaMaster = new Sales_Area_Master__c(
            Sales_Org__c = 'a',
            Channel__c = 'b',
            Division__c = 'c'
        );
        insert salesAreaMaster;
        Account account = Test_Utility.createAccount(0);
        insert account;
        Sub_Account__c subAccount = new Sub_Account__c(
            Account__c = account.Id,
            SAP_Account_ID__c = 'SAP1234'
        );
        insert subAccount;
        Sales_Area__c salesArea = new Sales_Area__c(
            Sales_Area_Master__c = salesAreaMaster.Id,
            Sales_Area_Master__r = salesAreaMaster,
            Sub_Account__c = subAccount.Id,
            Sub_Account__r = subAccount
        );
        insert salesArea;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.Pricebook2Id = pricebookId;
        opportunity.CurrencyIsoCode = 'USD';
        //opportunity.Sub_Account__c = subAccount.Id;
        //opportunity.Sales_Area__c = salesArea.Id;
        //opportunity.Sales_Area__r = salesArea;
        insert opportunity;
        OpportunityLineItem oli = Test_Utility.createOpportunityLineItem(opportunity.Id, pbe.Id, 0);
        oli.Quantity = 2;
        oli.TotalPrice = 4;
        insert oli;
        
        Test.setMock(WebServiceMock.class, new Test_SAP_CEPriceWsdlMock());
        
        Test.startTest();
        
        // Load the page
        OpportunityProductEntryExtension c = new OpportunityProductEntryExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(null, c.init());
        System.assert(ApexPages.getMessages().isEmpty());
        System.assertEquals(4, c.Total);
        System.assertEquals(1, c.shoppingCart.size());
        c.getDivisions();
        c.getProductLines();
        
        // Fetch prices
        c.fetchPrices();
        
        Test.stopTest();
        
        System.assert(!ApexPages.hasMessages(), ApexPages.getMessages());
        System.assertEquals(1, c.shoppingCart.size());
        System.assertEquals(33, c.shoppingCart[0].oppLine.UnitPrice);
        System.assertEquals(66, c.Total);
        System.assertEquals(salesArea.Id, opportunity.Sales_Area__c); // Only one available sales area, should be selected automatically
    }
}