objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opp_Age__c</fullName>
        <description>To calculate the age of the opportunity - Hidden field in opportunity
https://success.salesforce.com/answers?id=90630000000gmm1AAA</description>
        <formula>IF(IsClosed,( 
CloseDate - DATEVALUE(CreatedDate)), 
NOW() - CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UserOpportunitiesIterator.cls
/**
 * Retrieves the average amount and average age of won/lost opportunities.
 * 
 * Created by: rmohr@salesforce.com
 */
global class UserOpportunitiesIterator implements Iterator<AggregateResult> { 
 
    AggregateResult [] results {get;set;} 
    Integer index {get;set;}
 
    global UserOpportunitiesIterator(){ 
        index=0;
        String query = 'SELECT OwnerId, IsWon, '
            + 'AVG(Opp_Age__c) avg_age, '
            + 'AVG(Amount) avg_amount '
            + 'FROM Opportunity '
            + 'WHERE Account.business_org__c=\'Climate and Energy\' '
            + 'AND (IsWon = true '
            + 'OR (IsClosed = true AND IsWon = false)) '
            + 'GROUP BY OwnerID, IsWon';
                  
        system.debug(LoggingLevel.INFO, '@@ Run query: ' + query);
        results = Database.query(query); 
        system.debug(LoggingLevel.INFO, '@@ Query size: ' + results.size());
    } 
    
    global boolean hasNext(){ 
        return results !=null && !results.isEmpty() && index < results.size(); 
    } 
     
    global AggregateResult next(){ 
        return results[index++]; 
    } 
}