objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Country_Specific_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>country used to determine the footer text on the PDF</description>
        <label>Country Specific Footer</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_AttachmentGenerator.cls
@isTest (seealldata=true)
private class Test_AttachmentGenerator {

    static testMethod void myUnitTest() {
        AttachmentGenerator ag = new AttachmentGenerator();
        Account account = Test_Utility.createAccount(1);
		  account.Sales_Manager__c = UserInfo.getUserId();
		  insert account;
		  Opportunity oppty = Test_Utility.createOpportunity(account.Id, 1);
		  oppty.currencyIsoCode = 'USD';
		  insert oppty;     
		  Pricebook2 pricebook1 = [SELECT Id FROM PriceBook2 WHERE NAME = 'Danfoss'];
		  Region__c reg = [select Id From Region__c limit 1];
		  Quote quote = new Quote(OpportunityId = oppty.Id,Name='qli',PriceBook2Id = pricebook1.Id, Country_Specific_Template__c = reg.Id);
		  insert quote; 
        
        PageReference pageRef = new PageReference('/apex/QuotePDF?Id='+quote.Id);
        Blob content = blob.valueof('p');
        AttachmentGenerator.AttachPDFToQuote(quote.Id);
        AttachmentGenerator.SaveAndEmail(quote.Id);
    }
}