objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CE_Division__c</fullName>
        <description>Used to make Picklists Divisional dependent</description>
        <inlineHelpText>Used to make Picklists Divisional dependent</inlineHelpText>
        <label>Danfoss Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_HS_Sub_reason__c</fullName>
        <label>Sub Reason (DHS)</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>Our product does not match customer specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Better Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service terms</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_reason__c</fullName>
        <description>CE sub reason for closed Opportunities. This is CE specific as it is uncertain if the PS field &quot;Detailed reason&quot; can be reused.
Linked with Reason</description>
        <inlineHelpText>Use the Close Opportunity button to close your Opportunity and add a sub reason.
Please note that the sub reason is not available for all reasons.</inlineHelpText>
        <label>Close sub reason</label>
        <picklist>
            <picklistValues>
                <fullName>Competitor has strong value proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor has superior Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor is preferred supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor offers full System/Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer has long relationship with Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss does not have the needed product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divisional specific feature we are currently missing in portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Our product does not physically fit in application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_OpportunityCloseExtension.cls
@isTest
public class Test_OpportunityCloseExtension {
    
    static testMethod void test() {
        Account account = Test_Utility.createAccount(0);
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.CE_Division__c = 'Heating';
        insert opportunity;
        
        Test.startTest();
        
        OpportunityCloseExtension c = new OpportunityCloseExtension(new ApexPages.StandardController(opportunity));
        opportunity.CE_HS_Sub_reason__c = 'xyz';
        PageReference pr = c.closeOpp();
        
        Test.stopTest();
        
        System.assert(ApexPages.getMessages().isEmpty());
        System.assertNotEquals(null, pr);
        System.assertEquals('xyz', [select Sub_reason__c from Opportunity].Sub_reason__c);
    }
    
}