objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project_Opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Sub_Account__c</field>
                <operation>equals</operation>
                <valueField>Sales_Area__c.Sub_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Opportunity__c.object
<CustomObject>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Area Master</label>
        <referenceTo>Sales_Area_Master__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Area_Master__r.Sales_Area__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Area_Master__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Org__c + &quot;-&quot; +  Channel__c + &quot;-&quot; +  Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Test_SearchOpportunityExtension.cls
@isTest
public class Test_SearchOpportunityExtension {

    public static testMethod void testNoMatchFound() {
        Account account = Test_Utility.createAccount(0);
        insert account;
        Opportunity opportunity1 = Test_Utility.createOpportunity(account.Id, 0);
        opportunity1.Name = 'NoMatchOpportunity';
        insert opportunity1;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accID', account.Id);
        Opportunity opportunity = new Opportunity();
        SearchOpportunityExtension c = new SearchOpportunityExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(false, c.getcreatepossible());
        opportunity.Name = 'MyTestOpportunity';
        c.search();
        opportunity.CloseDate = Date.today();
        c.selectedContactId = null;
        c.selectSalesArea();
        
        Test.stopTest();
        
        System.assertEquals(true, c.navigateToEditOpp);
        System.assertEquals(0, [select Id from Project_opportunity__c].size());
        System.assertEquals(2, [select Id from Opportunity].size());
    }

    public static testMethod void testMatchFound() {
        Account account = Test_Utility.createAccount(0);
        account.Business_Org__c='Climate and Energy';
        insert account;
        Opportunity opportunity1 = Test_Utility.createOpportunity(account.Id, 0);
        opportunity1.Name = 'NoMatchOpportunity';
        insert opportunity1;
        Opportunity opportunity2 = Test_Utility.createOpportunity(account.Id, 0);
        opportunity2.Name = 'MyTestOpportunity';
        insert opportunity2;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accID', account.Id);
        Opportunity opportunity = new Opportunity();
        SearchOpportunityExtension c = new SearchOpportunityExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(false, c.getcreatepossible());
        opportunity.Name = 'MyTestOpportunity';
        c.search();
        System.assertEquals(true, c.getcreatepossible());
        System.assertEquals(false, c.navigateToEditOpp);
        System.assertEquals(1, c.getResults().size());
        c.CreateNew();
        opportunity.CloseDate = Date.today();
        c.selectedContactId = null;
        c.selectSalesArea();
        
        Test.stopTest();
        
        System.assertEquals(true, c.navigateToEditOpp);
        System.assertEquals(0, [select Id from Project_opportunity__c].size());
        System.assertEquals(3, [select Id from Opportunity].size());
    }

    public static testMethod void testProjectOpp() {
        Account account = Test_Utility.createAccount(0);
        account.Business_Org__c='Climate and Energy';
        insert account;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accID', account.Id);
        Opportunity opportunity = new Opportunity();
        SearchOpportunityExtension c = new SearchOpportunityExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(false, c.getcreatepossible());
        opportunity.Name = 'MyTestOpportunity';
        c.isProjectOpp = true;
        c.showProjectFields();
        c.newProject = 'MyTestProject';
        c.search();
        opportunity.CloseDate = Date.today();
        c.selectedContactId = null;
        c.selectSalesArea();
        
        Test.stopTest();
        
        System.assertEquals(true, c.navigateToEditOpp);
        System.assertEquals(1, [select Id from Project_opportunity__c].size());
        System.assertEquals(1, [select Id from Opportunity].size());
    }

    public static testMethod void testOneSalesArea() {
        Account account = Test_Utility.createAccount(0);
        account.Business_Org__c='Climate and Energy';
        insert account;
        Sub_Account__c subAcc = new Sub_Account__c(Account__c = account.Id);
        insert subAcc;
        Sales_Area_Master__c sam = new Sales_Area_Master__c();
        insert sam;
        Sales_Area__c sa = new Sales_Area__c(Sub_Account__c = subAcc.Id, Sales_Area_Master__c = sam.Id);
        insert sa;
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accID', account.Id);
        Opportunity opportunity = new Opportunity();
        SearchOpportunityExtension c = new SearchOpportunityExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(false, c.getcreatepossible());
        opportunity.Name = 'MyTestOpportunity';
        c.search();
        opportunity.CloseDate = Date.today();
        c.selectedContactId = null;
        c.selectSalesArea();
        
        Test.stopTest();
        
        System.assertEquals(true, c.navigateToEditOpp);
        System.assertEquals(0, [select Id from Project_opportunity__c].size());
        System.assertEquals(1, [select Id from Opportunity].size());
        System.assertEquals(sa.Id, opportunity.Sales_Area__c);
    }

    public static testMethod void testManySalesArea() {
        Account account = Test_Utility.createAccount(0);
        account.Business_Org__c='Climate and Energy';
        insert account;
        Sub_Account__c subAcc = new Sub_Account__c(Account__c = account.Id);
        insert subAcc;
        Sales_Area_Master__c sam1 = new Sales_Area_Master__c();
        Sales_Area_Master__c sam2 = new Sales_Area_Master__c();
        insert new List<Sales_Area_Master__c> {sam1, sam2};
        Sales_Area__c sa1 = new Sales_Area__c(Sub_Account__c = subAcc.Id, Sales_Area_Master__c = sam1.Id);
        Sales_Area__c sa2 = new Sales_Area__c(Sub_Account__c = subAcc.Id, Sales_Area_Master__c = sam2.Id);
        insert new List<Sales_Area__c> {sa1, sa2};
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('accID', account.Id);
        Opportunity opportunity = new Opportunity();
        SearchOpportunityExtension c = new SearchOpportunityExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(false, c.getcreatepossible());
        opportunity.Name = 'MyTestOpportunity';
        c.search();
        opportunity.CloseDate = Date.today();
        c.selectedContactId = null;
        c.selectSalesArea();
        System.assertEquals(false, c.navigateToEditOpp);
        c.selectedSalesArea = sa1.Id;
        c.createOppandProject();
        
        Test.stopTest();
        
        System.assertEquals(true, c.navigateToEditOpp);
        System.assertEquals(0, [select Id from Project_opportunity__c].size());
        System.assertEquals(1, [select Id from Opportunity].size());
        System.assertEquals(sa1.Id, opportunity.Sales_Area__c);
    }

}