objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SAP_URLs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>URLs for deep-linking into SAP</description>
    <fields>
        <fullName>Create_SAP_CRM_Quote_URL__c</fullName>
        <inlineHelpText>The deep link into SAP CRM to create a quote, where {SAPID} is used as the SAP account ID</inlineHelpText>
        <label>Create SAP CRM Quote URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SAP URLs</label>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>REGIO</description>
        <label>Region</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/Test_SapQuoteOpportunityExtension.cls
@isTest
public class Test_SapQuoteOpportunityExtension {
    
    static testMethod void testBlankSubAccount() {
        insert new SAP_URLs__c(SetupOwnerId = UserInfo.getOrganizationId(), Create_SAP_CRM_Quote_URL__c = 'test={SAPID}');
        insert new Region__c(Name = 'Germany', Country_Code__c = 'DE');
        Account account = Test_Utility.createAccount(0);
        insert account;
        Sub_Account__c s1 = new Sub_Account__c(Account__c = account.Id, SAP_Account_ID__c = '123');
        insert s1;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        insert opportunity;
        
        Test.startTest();
        
        SapQuoteOpportunityExtension c = new SapQuoteOpportunityExtension(new ApexPages.StandardController(opportunity));
        System.assertEquals(null, c.init());
        System.assertEquals(1,c.getDiv().size());
        c.selectedDD = c.getDiv()[0].Id;
        PageReference pr = c.CreateQuote();
        
        Test.stopTest();
        
        System.assertNotEquals(null, pr);
        System.assertEquals(s1.Id, [select Sub_Account__c from Opportunity].Sub_Account__c);
    }
    
    static testMethod void testNotBlankSubAccount() {
        insert new SAP_URLs__c(SetupOwnerId = UserInfo.getOrganizationId(), Create_SAP_CRM_Quote_URL__c = 'test={SAPID}');
        insert new Region__c(Name = 'Germany', Country_Code__c = 'DE');
        Account account = Test_Utility.createAccount(0);
        insert account;
        Sub_Account__c s1 = new Sub_Account__c(Account__c = account.Id, SAP_Account_ID__c = '123');
        insert s1;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.Sub_Account__c = s1.Id;
        insert opportunity;
        
        Test.startTest();
        
        SapQuoteOpportunityExtension c = new SapQuoteOpportunityExtension(new ApexPages.StandardController(opportunity));
        PageReference pr = c.init();
        
        Test.stopTest();
        
        System.assertNotEquals(null, pr);
    }
    
    static testMethod void testWithoutSubAccount() {
        insert new SAP_URLs__c(SetupOwnerId = UserInfo.getOrganizationId(), Create_SAP_CRM_Quote_URL__c = 'test={SAPID}');
        insert new Region__c(Name = 'Germany', Country_Code__c = 'DE');
        Account account = Test_Utility.createAccount(0);
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        insert opportunity;
        
        Test.startTest();
        
        SapQuoteOpportunityExtension c = new SapQuoteOpportunityExtension(new ApexPages.StandardController(opportunity));
        PageReference pr = c.init();
        
        Test.stopTest();
        
        System.assertNotEquals(null, pr);
    }
    
}