objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Account.SAP_Account_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Sub Account must belong to the selected account</errorMessage>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Custom_Account_Lookup__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/SAP_URLs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>URLs for deep-linking into SAP</description>
    <fields>
        <fullName>Create_SAP_CRM_Quote_URL__c</fullName>
        <inlineHelpText>The deep link into SAP CRM to create a quote, where {SAPID} is used as the SAP account ID</inlineHelpText>
        <label>Create SAP CRM Quote URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SAP URLs</label>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/SapQuoteOpportunityExtension.cls
/**
 * Deep links into SAP to create a quote for the sub account associated with the given opportunity.
 * If no sub account is associated with the opportunity, the page first asks the user to select one, and then saves the choice on the opportunity.
 */
public class SapQuoteOpportunityExtension {
    
    public ApexPages.StandardSetController setCon {get;set;}
    public Id selectedDD {get;set;}
    private Opportunity o;
    
    public SapQuoteOpportunityExtension(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'AccountId', 'Sub_Account__c', 'Account.CE_SAP_Account_ID__c'});
        }
        o = (Opportunity) stdController.getRecord();
        if (o.Sub_Account__c == null) {
            String soqlFields = 'Id';
            for (FieldSetMember field : SObjectType.Sub_Account__c.FieldSets.SapQuoteFields.getFields()) {
                soqlFields += ', ' + field.getFieldPath();
            }
            ID accId = o.AccountId;
            setCon = new ApexPages.StandardSetController(Database.getQueryLocator('select ' + soqlFields + ' from Sub_Account__c where Account__c = :accId'));
            setCon.setPageSize(8);
        } else {
            selectedDD = o.Sub_Account__c;
        }
    }
    
    public PageReference init() {
        if (selectedDD == null) {
            if (setCon.getRecords().isEmpty()) {
            	return new PageReference(SAP_URLs__c.getInstance().Create_SAP_CRM_Quote_URL__c.replace('{SAPID}', '' + o.Account.CE_SAP_Account_ID__c));
            }
            return null;
        } else {
            return doCreateQuote();
        }
    }
    
    public List<Sub_Account__c> getDiv() {
        return setCon.getRecords();
    }
    
    public PageReference CreateQuote() {
        o.Sub_Account__c = selectedDD;
        try {
            update o;
        } catch (DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        return doCreateQuote();
    }
    
    public PageReference doCreateQuote() {
        Sub_Account__c sap_cust = [select SAP_Account_ID__c from Sub_Account__c where Id = :selectedDD];
        PageReference pageRef = new PageReference(SAP_URLs__c.getInstance().Create_SAP_CRM_Quote_URL__c.replace('{SAPID}', '' + sap_cust.SAP_Account_ID__c));
        return pageRef;
    }
    
}