objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Area</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Sub_Account__c</field>
                <operation>equals</operation>
                <valueField>Sales_Area__c.Sub_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Area__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a Sub Account (SAP customer)</description>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Shadow_Opportunity</fullName>
        <active>true</active>
        <businessProcess>C%26E Sales Process</businessProcess>
        <description>This record type is for shadow opportunities that should not be part of a salesprocess nor be included in reporting and forecasting</description>
        <label>Shadow Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>ConfigitQuoteId__c</fullName>
        <description>The quote id/number assigned by Configit</description>
        <externalId>true</externalId>
        <label>Configit Quote Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ConfigitQuoteRef__c</fullName>
        <label>Quick Reference Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfigitQuoteRev__c</fullName>
        <label>Configit Revision Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfigitSyncMessage__c</fullName>
        <defaultValue>&quot;OK&quot;</defaultValue>
        <label>Configit Sync Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Request_Date__c</fullName>
        <inlineHelpText>If left blank will default to +5 days</inlineHelpText>
        <label>Customer Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_Valid_From__c</fullName>
        <label>Price Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_Valid_To__c</fullName>
        <label>Price Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Sub Account must belong to the selected account</errorMessage>
            <filterItems>
                <field>Sub_Account__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Custom_Account_Lookup__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Quote Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Quote Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manual assigned opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You cannot only select Climate and Energy opportunities 
- which are not shadow opportunities</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Shadow_Opportunity</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.Account.Business_Org__c</field>
                <operation>equals</operation>
                <value>Climate and Energy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Manual Re-assigned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CE_Quote</fullName>
        <active>true</active>
        <label>CE Quote</label>
    </recordTypes>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Area Master</label>
        <referenceTo>Sales_Area_Master__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Area_Master__r.Sales_Area__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Area_Master__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>Sales_Org__c + &quot;-&quot; +  Channel__c + &quot;-&quot; +  Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
</CustomObject>

classes/QuoteBusiness_Test.cls
@isTest
public class QuoteBusiness_Test {
    @TestSetup
    private static void setup() {
        /* Price Book */
        Pricebook2 pb = Test_DataFactory.create_CE_PriceBook();        
        insert pb;
        
        Product2 p = Test_DataFactory.create_CE_Product( 'My Product 0001', 'SMC-0001');
        p.Description = 'My Product 0001 - Description';
        insert p;
        
        /* Create CE Customer */        
        Account account = Test_DataFactory.create_CE_Customer('Danfoss', 'USD', 'DK', 'CER');
        account.ShippingCountry = 'DK';
        account.ShippingPostalCode = '6430';
        account.ShippingCity = 'Nordborg';
        account.ShippingStreet = 'Nordborgvej 81';        
        insert account;
                
        Sales_Area_Master__c sam = Test_DataFactory.create_SalesAreaMaster('2300','00','00');
        insert sam;
                        
        Sub_Account__c sa = Test_DataFactory.create_SubAccount(account.name, '23456789', account);
        insert sa;
        
        Sales_Area__c sao = Test_DataFactory.create_salesArea(sa, sam);
        insert sao;               
        
        contact c = new contact();        
        c.Academic_Title__c = 'Jedi';
        c.AccountId = account.Id;
        c.FirstName = 'Luke';
        c.LastName = 'Skywalker';
        c.Phone = '+45 12345678';
        c.Email = 'ls=danfoss.com@example.com';
        insert c;
    }
    
    public static testMethod void test_shadow_opportunity() {
        
        account a = [SELECT id, name, CurrencyIsoCode FROM account WHERE name='Danfoss'];
        
        Id pb2Id=[SELECT Id FROM Pricebook2 WHERE Name='Climate and Energy'].Id;
        
        Test.startTest();
        insert QuoteBusiness.createShadowOpportunity('Shadow Opportunity',a.Id, a.CurrencyIsoCode, UserInfo.getUserId(), pb2Id);
        Test.stopTest();
        
        opportunity o = [SELECT id, name from opportunity WHERE name='Shadow Opportunity' and recordtype.developername='Shadow_Opportunity'];
        
        System.assertEquals('Shadow Opportunity', o.name);        
         
    }
    
    
    public static testMethod void clone_quote() {
        
        account a = [SELECT id, name, CurrencyIsoCode FROM account WHERE name='Danfoss'];        
        Id pb2Id=[SELECT Id FROM Pricebook2 WHERE Name='Climate and Energy'].Id;        
        opportunity o = QuoteBusiness.createShadowOpportunity('Shadow Opportunity',a.Id, a.CurrencyIsoCode, UserInfo.getUserId(), pb2Id);
        insert o;
        
        string configitQuoteId='9876543210';
        quote q = new Quote(ConfigitQuoteId__c = configitQuoteId, OpportunityId=o.Id, Status='In Progress');
        q.name = 'QUOTE ABC';
        q.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType='Quote' AND developername='CE_Quote' LIMIT 1].Id;        
        q.ConfigitQuoteRev__c = 'R0';
        q.ConfigitQuoteRef__c = 'QWERTY';
        q.Valid_From__c = date.today();
        q.Valid_To__c = date.today();
        q.ExpirationDate = date.today();
        q.Price_Valid_From__c = date.today();
        q.Price_Valid_To__c = date.today();  
        q.Customer_Request_Date__c = date.today();
        q.ConfigitSyncMessage__c = 'OK';   
        q.OpportunityId = o.Id;        
        insert q;
        
        Opportunity o_target = new Opportunity();
        o_target.AccountId = a.Id;
        o_target.name ='new opportunity';   
        o_target.StageName='Open';
        o_target.CloseDate=date.today();
        insert o_target;
        q.opportunity__c=o_target.Id;   
        
        Test.startTest();
        QuoteBusiness.deepCloneQuote(q, true);
        Test.stopTest();
        
        q=[SELECT Id, ConfigitQuoteId__c, opportunityId, status, ConfigitQuoteRev__c FROM quote WHERE ConfigitQuoteId__c=:configitQuoteId];
        System.assertEquals(q.OpportunityId, o_target.Id);        
        
    }

}