objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <description>CE Competitors for header level</description>
        <inlineHelpText>Choose the main competitor you are competing against</inlineHelpText>
        <label>Main Competitor</label>
        <picklist>
            <controllingField>CE_Division__c</controllingField>
            <picklistValues>
                <fullName>(APA) Haesung</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(APA) KAORI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(APA) Meiyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Castle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Dhiren</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Dry-all</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Flowcon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Freze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) L&amp;T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Manik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Meidensha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Schaffner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Subzero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Super</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(IN) Toshiba Mitsubishsi Electric Industrial Systems Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AALBERTS (COMAP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC&amp;R-Henry Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACCOTEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC Tech (Lenze)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adlee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AEG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alfa Laval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen Bradley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Innotec</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpha Laval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alre</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Production_Start_Date__c</fullName>
        <description>Field used by both C&amp;E and PS. For PS the former name was production start date. 
The main purpose is to identify when the first delivery to an Opportunity will take place.</description>
        <inlineHelpText>Add the date of the first delivery of the Opportunity</inlineHelpText>
        <label>Date of first delivery</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <label>Reason Won/Lost</label>
        <picklist>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Leave Sales Org blank for opportunities on a prospect account</inlineHelpText>
        <label>Sales Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sales_Org__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Sales_Org__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sales_Org__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Easy Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eaton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIA Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elobau</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>Argo Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic Fluidpress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eaton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyde</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydraforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HydroControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydrocontrols</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated Hydraulics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iskra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kawasaki</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayaba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kersen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lifan</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org__c</fullName>
        <description>SAP KNVH integration field</description>
        <externalId>true</externalId>
        <label>SAP Sales Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/Test_CheckOpptyProductCompTrigger.cls
//@isTest
public with sharing class Test_CheckOpptyProductCompTrigger {
 /*public static testMethod void testInit() {
        Account acct = Test_Utility.createAccount(1);
        insert acct;
        
        Product2 p1 = new Product2(
        name='tstprod',
        IsActive=true,
        Description='My Product',
        ProductCode='0723',
        CurrencyIsoCode='USD'
        );
        
        insert p1;       
      
        Pricebook2 stdPb = [select Id from Pricebook2 where isStandard=true limit 1];
        stdPb.IsActive = true;
        update stdPb;       
        PriceBookEntry pbe = [select Id, UnitPrice from PriceBookEntry where Product2Id = :p1.Id and Pricebook2Id = :stdPb.Id and CurrencyISOCode = 'USD'];//Test_Utility.createPricebookEntry(p.Id, stdPb.Id, 'USD'); 
        
	 	Sales_Org__c so = new Sales_Org__c(Name = '1500', SAP_Sales_Org__c = '1500', Account__c = acct.Id);  
        insert so;
        Test.StartTest();
        Opportunity oppty = new Opportunity(AccountId = acct.Id, name = 'tstoppty2', Sales_Org__c = so.Id, Production_Start_Date__c = Date.Today(), stagename = 'Evaluating Need', CloseDate = Date.Today().addDays(-5), CurrencyIsoCode='USD');
        insert oppty;
        
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppty.Id, TotalPrice = 1, Quantity = 23,PricebookEntryId=pbe.id);
        insert oli;


        oli = new OpportunityLineItem(OpportunityId = oppty.Id, TotalPrice = 1, Quantity = 23,PricebookEntryId=pbe.id, Competitor__c = '');
        insert oli;
        
        oppty = new Opportunity(AccountId = acct.Id, name = 'tstoppty3', Sales_Org__c = so.Id, Production_Start_Date__c = Date.Today(), stagename = 'Evaluating Need', Reason_Won_Lost__c = 'Price',Reason_Description__c ='Competition', CloseDate = Date.Today().addDays(-5), CurrencyIsoCode = 'USD');
        insert oppty;
        oli = new OpportunityLineItem(OpportunityId = oppty.Id, TotalPrice = 1, Quantity = 23,PricebookEntryId=pbe.id, Competitor__c = 'Bosch Rexroth', Approx_Competitor_Price__c = 1);
        insert oli;
        oppty.StageName='Closed Won';
        update oppty;
        Test.StopTest();
 }*/
}