objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CE_Phase__c</fullName>
        <description>C&amp;E Phases for the Pipeline</description>
        <inlineHelpText>Phase indicates where you are in the sales process with your Opportunity</inlineHelpText>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Identification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Status__c</fullName>
        <description>Status is used to indicate if an Opportunity is Open or Closed.</description>
        <inlineHelpText>Status is used to indicate if an Opportunity is Open or Closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>CE_Phase__c</controllingField>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>CE Reason for closed Opportunities. This is CE specific as it is uncertain if the PS field can be reused.</description>
        <inlineHelpText>Use the Close Opportunity button to close your Opportunity and add a reason.</inlineHelpText>
        <label>Close reason</label>
        <picklist>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by third party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>CE_Opportunity</fullName>
        <active>true</active>
        <businessProcess>C%26E Sales Process</businessProcess>
        <label>Climate and Energy Open Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Shadow_Opportunity</fullName>
        <active>true</active>
        <businessProcess>C%26E Sales Process</businessProcess>
        <description>This record type is for shadow opportunities that should not be part of a salesprocess nor be included in reporting and forecasting</description>
        <label>Shadow Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Cloned_Quote_Number__c</fullName>
        <label>Cloned Quote Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfigitQuoteId__c</fullName>
        <description>The quote id/number assigned by Configit</description>
        <externalId>true</externalId>
        <label>Configit Quote Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by third party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Quote_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP Quote ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manual assigned opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You cannot only select Climate and Energy opportunities 
- which are not shadow opportunities</errorMessage>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Shadow_Opportunity</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.Account.Business_Org__c</field>
                <operation>equals</operation>
                <value>Climate and Energy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Manual Re-assigned Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/QuoteBusiness.cls
public class QuoteBusiness {

    
    public static Opportunity createShadowOpportunity (string name, Id accountId, string currencyCode, string currentUserid, id pb2Id) {
        Opportunity o = new Opportunity();                
        o.AccountId = accountId;  
		if (currentUserid!=null) {
        	o.ownerId = currentUserid;
			//o.CreatedById = currentUserid;
		}
                    
        o.name = name.left(120);
        o.CE_Phase__c = 'Qualification';
        o.CE_Status__c = 'Lost';
        o.Reason__c = 'No Follow-up';
        o.StageName='Closed-Lost';
        o.CloseDate=Date.today();
        o.CurrencyIsoCode=currencyCode;
		// CE_Opportunity
		o.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType='Opportunity' AND developername='Shadow_Opportunity' LIMIT 1].Id;
                    
                    
        //o.RecordTypeId = RestQuoteController.getRecordTypeId(Opportunity.SObjectType, 'CE_Opportunity');
        o.Pricebook2Id=pb2Id;
        o.Amount=0;
        
        return o;
    }
    
    public static quote deepCloneQuote (quote q, boolean deleteOriginalQuote) {
		// build query string for all quote fields
        string query = getSelectAllQuery('Quote');           	
        query = (query + ' WHERE id=\'' + q.id + '\'');             
        Quote sourceQ = Database.query(query);
        //clone(Boolean preserveId, Boolean isDeepClone, Boolean preserveReadonlyTimestamps, Boolean preserveAutonumber)
        Quote targetQ = sourceQ.clone(false, true, true, true);
        targetQ.opportunityId=q.opportunity__c;
        targetQ.opportunity__c=null;        
        if (sourceQ.Cloned_Quote_Number__c!=null)  {
        	targetQ.Cloned_Quote_Number__c=sourceQ.Cloned_Quote_Number__c;    
		} else {
        	targetQ.Cloned_Quote_Number__c=sourceQ.QuoteNumber;
		}            
            
        sourceQ.configitQuoteId__c=null;
        sourceQ.opportunity__c =null;
        sourceQ.SAP_Quote_ID__c=null;
        update sourceQ;
            
        targetQ.name = targetQ.name;
        insert targetQ;
            
            
        // clone related data (quotelineitems)
        query = getSelectAllQuery('QuoteLineItem');
        //query=('SELECT id' + query);
        query = (query + ' WHERE quoteid=\'' + q.id + '\''); 
            
        List<quotelineitem> newItems = new List<quotelineitem>();
        List<quotelineitem> existingItems = Database.query(query);
        for (quotelineitem qli : existingItems) {
       		quotelineitem newqli = qli.clone(false);
            qli.ConfigitQuoteLineId__c=null;
            
			newqli.QuoteId = targetQ.id;
            newItems.add(newqli);
        }
        update existingItems;
        insert newItems;
            
        // insert quote attachments
        List<attachment> la = new List<attachment>();
        for (attachment a: [SELECT id, name, description, body, ContentType, bodyLength, LastModifiedDate, CreatedDate, parentid from attachment where parentid=:q.Id limit 50]) {
        	attachment na = a.clone();
            na.parentId=targetQ.Id;
            la.add(na);
        }
        insert la;
            
        if (deleteOriginalQuote) {
        	// cleanup and delete the original quote
        	delete sourceQ;            
        }
        
        return  targetQ;
        
    }
    
    public static String getSelectAllQuery(string sObjectName) {
    	// get all quote fields
        string qfields='SELECT id';
        //List<string> lstQuoteFields = new List<string>();
        Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
       	Map <String, Schema.SObjectField> fieldMap = schemaMap.get(sObjectName).getDescribe().fields.getMap();
		for(Schema.SObjectField sfield : fieldMap.Values())
		{
			schema.describefieldresult dfield = sfield.getDescribe();
			
			string fieldname = dfield.getname();
            if (!fieldname.equalsIgnoreCase('id')) {
                qfields = (qfields + ',' + fieldname);                                	
            }
            //lstQuoteFields.add(fieldname);			
		}
        qfields = (qfields + ' FROM ' + sObjectName);
        return qfields;
    }     
}