objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CE_Phase__c</fullName>
        <description>C&amp;E Phases for the Pipeline</description>
        <inlineHelpText>Phase indicates where you are in the sales process with your Opportunity</inlineHelpText>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Identification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Sales_model__c</fullName>
        <description>Sales model is used to identify which of the DBS sales models the Opportunity belongs to.</description>
        <inlineHelpText>Sales model is used to identify which of the DBS sales models the Opportunity belongs to.</inlineHelpText>
        <label>Sales model</label>
        <picklist>
            <picklistValues>
                <fullName>End user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Status__c</fullName>
        <description>Status is used to indicate if an Opportunity is Open or Closed.</description>
        <inlineHelpText>Status is used to indicate if an Opportunity is Open or Closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <controllingField>CE_Phase__c</controllingField>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>CE Reason for closed Opportunities. This is CE specific as it is uncertain if the PS field can be reused.</description>
        <inlineHelpText>Use the Close Opportunity button to close your Opportunity and add a reason.</inlineHelpText>
        <label>Close reason</label>
        <picklist>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped by third party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/BatchUpdateOpportunityStages_TEST.cls
// Test class for the Batch class BatchUpdateOpportunityStages
// Changelog:
// October 01, 2015: Madhav Kakani - Fluido Denmark - Initial implementation
@isTest
private class BatchUpdateOpportunityStages_TEST {
    static testMethod void runTest() {   
        Account acct = new Account();
        acct.Name = 'Test Account';
        acct.Division__c = 'Cooling';
        insert acct;
        
        system.assert(acct.Id != null);
        
       /* List<String> sPhases = new List<String> {'Identification', 'Value Proposition', 'Quotation', 'Follow-up'};
        List<Opportunity> lstOpp = new List<Opportunity>();
        for(Integer i= 0; i < 4; i++) {
            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opp'+ String.valueof(i);
            opp.AccountId = acct.Id;
            opp.Amount = 100000;
            opp.CE_Sales_model__c = 'End user';
            opp.CE_Phase__c = sPhases[i];
            opp.CE_Status__c = 'In Progress';
            opp.CloseDate = Date.today() + 30;      
            opp.StageName = 'Open';
            lstOpp.add(opp);
        }
        
        // Lost opportunity
        for(Integer i= 0; i < 4; i++) {
            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opp'+ String.valueof(i);
            opp.AccountId = acct.Id;
            opp.Amount = 100000;
            opp.CE_Sales_model__c = 'End user';
            opp.CE_Phase__c = sPhases[i];
            opp.CE_Status__c = 'Lost';
            opp.Reason__c = 'Test';
            opp.CloseDate = Date.today() + 30;      
            opp.StageName = 'Open';
            lstOpp.add(opp);
        }
        
        insert lstOpp;
            */                                
        Test.startTest();

        BatchUpdateOpportunityStages batch = new BatchUpdateOpportunityStages();
        Id batchId = Database.executeBatch(batch, 8);
            
        Test.stopTest();
    }
}