objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_At_Risk__c</fullName>
        <formula>IF ( Low_Quality_Opportunity__c ,  Amount, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount At Risk</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>AD: Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE: Unit. Arab Emir.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF: Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG: Antigua/Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI: Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL: Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM: Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN: Dutch Antilles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO: Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ: Antarica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR: Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS: Samoa American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT: Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU: Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW: Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ: Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA: Bosnia-Herz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB: Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD: Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE: Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF: Burkina-Faso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG: Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH: Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI: Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ: Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL: BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM: Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN: Brunei-Daruessa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO: Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR: Brazil</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CE used for Project site adress</description>
        <label>Region - for reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>CE Segment is used to segment the Opportunity Pipeline</description>
        <inlineHelpText>Choose the relevant segement for your Opportunity</inlineHelpText>
        <label>Opportunity Segment</label>
        <picklist>
            <controllingField>CE_Division__c</controllingField>
            <picklistValues>
                <fullName>DD - Air comp &amp; vac pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Automotive &amp; other transport equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Basic Metal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Cement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Cranes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Distributors not assigned to SBA’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Electric &amp; Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - HVAC exc. Pump OEM’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - HVAC Pump OEM’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Lifts and escalators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Machinery not elsewhere included</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Machine Tools &amp; Robotics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Marine &amp; Off Shore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Material Handling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Metal Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Mining &amp; Mineral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Oil &amp; Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Other renewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Pharmaceutical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Plastics &amp; Rubber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Power Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Pulp &amp; Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Recycle &amp; waste Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Refining/petrochem</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity_Trending__c.object
<CustomObject>
    <description>My Pipeline dashboard summary data component</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Sum of the amount for all open opportunities</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_at_Risk__c</fullName>
        <label>Amount at Risk</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExtraLarge_Amount__c</fullName>
        <label>Extra Large Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ExtraLarge_count__c</fullName>
        <label>ExtraLarge count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inactive_Amount__c</fullName>
        <label>Inactive Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Inactive_count__c</fullName>
        <label>Inactive count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_count__c</fullName>
        <label>Opportunity count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overaged_Amount__c</fullName>
        <label>Overaged Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overaged_count__c</fullName>
        <label>Overaged count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overdue_Amount__c</fullName>
        <label>Overdue Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overdue_count__c</fullName>
        <label>Overdue count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Trendings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stalled_count__c</fullName>
        <label>Stalled count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stalled_in_Stage_Amount__c</fullName>
        <label>Stalled in Stage Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeSlip_count__c</fullName>
        <label>TimeSlip count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Trending</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Opportunity TRending Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Trendings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/OTAggregateResultRunQuery.cls
global class OTAggregateResultRunQuery implements Database.Batchable<AggregateResult> { 
// AggregateResultRunQuery batchquery = new AggregateResultRunQuery();        
//Database.executeBatch(batchquery, 200);

    global OTAggregateResultRunQuery () {
        system.debug(LoggingLevel.INFO, '@@ Initializing OTAggregateResultRunQuery');
        removeCurrentPeriodData();
    }
    
    global Iterable<AggregateResult> start(Database.BatchableContext BC){
        System.debug(LoggingLevel.INFO, '@@ OTAggregateResultRunQuery start - Job ID: ' + BC.getJobId());
        return new OTAggregateResultIterable(); 
    } 
     
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        List<Opportunity_Trending__c> OppTrendList = new List<Opportunity_Trending__c>();
        
        System.debug(LoggingLevel.INFO, '@@ Starting batch update for Opportunity Trending');
        
        for(sObject s : scope){ 
            AggregateResult ar = (AggregateResult) s;
            System.debug(LoggingLevel.INFO, '@@ AggregateResult: ' + ar);       
            Opportunity_Trending__c OppTrend = new Opportunity_Trending__c();
            OppTrend.OwnerId__c= (String)ar.get('OwnerId');
            OppTrend.Team__c = (String) ar.get('team');
            OppTrend.Period__c= Date.today();
            OppTrend.Segment__c= (String)ar.get('Segment');
            OppTrend.Region__c= (String)ar.get('Region__c');
            OppTrend.Country__c= (String)ar.get('country');

            OppTrend.Stage__c= (String)ar.get('StageName');
            OppTrend.Amount__c= ((Decimal)ar.get('sum_amount'));            
            OppTrend.Amount_at_Risk__c=((Decimal)ar.get('risk_amount'));
            
            OppTrend.Opportunity_count__c= ((Decimal)ar.get('cnt'));            
            OppTrend.Overdue_count__c= ((Decimal)ar.get('count_overdue'));
            OppTrend.Overdue_Amount__c = (Decimal) ar.get('overdue_amount');
            OppTrend.Inactive_count__c= ((Decimal)ar.get('count_inactive'));
            OppTrend.Inactive_Amount__c = ((Decimal)ar.get('inactive_amount'));
            OppTrend.Stalled_count__c= ((Decimal)ar.get('count_stalled'));
            OppTrend.Stalled_in_Stage_Amount__c = (Decimal) ar.get('stalled_amount');
            OppTrend.ExtraLarge_count__c= ((Decimal)ar.get('count_extralarge'));
            OppTrend.ExtraLarge_Amount__c = ((Decimal)ar.get('extralarge_amount'));
            OppTrend.Overaged_count__c= ((Decimal)ar.get('count_overaged'));
            OppTrend.Overaged_Amount__c = (Decimal) ar.get('overaged_amount');
            OppTrend.TimeSlip_count__c= ((Decimal)ar.get('count_timeslip'));
            OppTrend.TimeSlip_Amount__c = ((Decimal)ar.get('timeslip_amount'));
            OppTrend.SizeChange_count__c= ((Decimal)ar.get('count_sizechange'));
            OppTrend.SizeChange_Amount__c = ((Decimal)ar.get('sizechange_amount'));
            OppTrend.Average_Probability__c = ((Decimal)ar.get('avg_probability'));
            // Insert weighted score - this should be divided by the selected number of opportunities
            // E.g. If user A has a score of 200 and user B 180 and the is 22 the end weighted probability
            // will be 380/22
            OppTrend.Average_Probability_Weighted__c = OppTrend.Average_Probability__c * OppTrend.Opportunity_count__c;
            
            OppTrendList.add(OppTrend);
            System.debug(LoggingLevel.INFO, '@@ Added Opportunity Trending record: ' + OppTrend);
            
        } 
        insert OppTrendList;
        System.debug(LoggingLevel.INFO, '@@ Inserted ' + oppTrendList.size() + ' Opportunity Trending entries');
        
        // Debugging only
        for (Opportunity_Trending__c ot : OppTrendList) {
            System.debug(LoggingLevel.INFO, '@@ OT: ' + ot.ownerId__c + ', ' + ot);
        }
    } 
     
    global void finish(Database.BatchableContext BC){ 
        AsyncApexJob a = 
            [Select Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems,CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
        System.debug(LoggingLevel.INFO, '@@ Finished batch job ********: ' + a.Id);
    }
    
    /**
     * Removes previously inserted summary data for the current reporting period.
     */
    private void removeCurrentPeriodData() {
        try {
            System.debug(LoggingLevel.INFO, '@@ Removing existing data from current reporting period');
            delete [SELECT Id FROM Opportunity_Trending__c WHERE Period__c = THIS_MONTH];    
        }
        catch(DMLException e) {
            System.debug(LoggingLevel.ERROR, '@@ Failed to remove previous data: ' + e.getMessage());
        }
    }
}