objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chosen_Sub_Segment__c</fullName>
        <label>Chosen Sub Segment</label>
        <picklist>
            <picklistValues>
                <fullName>AC - Commercial AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC - Heat Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC - Residential AC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Refrigeration Subsystem Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Speciality Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR - Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR - Products &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Oil &amp; Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Reverse Osmosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP - Ultra Pure Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Air Compressor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Industrial Engines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Industrial Hydraulics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Marine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Mobile Hydraulics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Water Pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA - Wind Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Air Conditioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Commercial Refrigeration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Direct Served - Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Direct Served - Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Direct Served - Premium Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Food Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Indirect Served - Independent Retailers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Indirect Served - Wholesaler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IC - Industrial Automation</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Secondary_Segment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Secondary Segment?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>CE Segment is used to segment the Opportunity Pipeline</description>
        <inlineHelpText>Choose the relevant segement for your Opportunity</inlineHelpText>
        <label>Opportunity Segment</label>
        <picklist>
            <controllingField>CE_Division__c</controllingField>
            <picklistValues>
                <fullName>DD - Air comp &amp; vac pumps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Automotive &amp; other transport equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Basic Metal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Cement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Cranes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Distributors not assigned to SBA’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Electric &amp; Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - HVAC exc. Pump OEM’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - HVAC Pump OEM’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Lifts and escalators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Machinery not elsewhere included</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Machine Tools &amp; Robotics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Marine &amp; Off Shore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Material Handling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Metal Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Mining &amp; Mineral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Oil &amp; Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Other renewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Packaging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Pharmaceutical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Plastics &amp; Rubber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Power Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Pulp &amp; Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Recycle &amp; waste Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD - Refining/petrochem</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <description>C&amp;E Sub segment - Mainly used for RC and CC for segmentation purpose</description>
        <inlineHelpText>Choose the relevant sub segment - Only relevant for RC and CC - otherwise select &quot;Not available&quot;</inlineHelpText>
        <label>Sub Segment</label>
        <picklist>
            <picklistValues>
                <fullName>RC CC Sub Segment 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RC CC Sub Segment 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available -PE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available -HS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_OpportunitySubSegmentExtension.cls
@isTest
public class Test_OpportunitySubSegmentExtension {
    
    static testMethod void testSecondarySubSegment() {
        Account account = Test_Utility.createAccount(0);
        account.Segment__c = 'prim-seg';
        account.Sub_Segment__c = 'prim-subseg';
        account.Secondary_Segment__c = 'sec-seg';
        account.Secondary_Sub_Segment__c = 'sec-subseg';
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.Account = account;
        insert opportunity;
        
        Test.startTest();
        
        OpportunitySubSegmentExtension c = new OpportunitySubSegmentExtension(new ApexPages.StandardController(opportunity));
        c.SecondarySubSegment();
        
        Test.stopTest();
        
        System.assertEquals(true, c.renderdirect);
        Opportunity opp2 = [select Chosen_Sub_Segment__c, Secondary_Segment__c from Opportunity where Id = :opportunity.Id];
        System.assertEquals('sec-subseg', opp2.Chosen_Sub_Segment__c);
        System.assertEquals(true, opp2.Secondary_Segment__c);
    }
    
    static testMethod void testPrimarySubSegment() {
        Account account = Test_Utility.createAccount(0);
        account.Segment__c = 'prim-seg';
        account.Sub_Segment__c = 'prim-subseg';
        account.Secondary_Segment__c = 'sec-seg';
        account.Secondary_Sub_Segment__c = 'sec-subseg';
        insert account;
        Opportunity opportunity = Test_Utility.createOpportunity(account.Id, 0);
        opportunity.Account = account;
        insert opportunity;
        
        Test.startTest();
        
        OpportunitySubSegmentExtension c = new OpportunitySubSegmentExtension(new ApexPages.StandardController(opportunity));
        c.PrimarySubSegment();
        
        Test.stopTest();
        
        System.assertEquals(true, c.renderdirect);
        Opportunity opp2 = [select Chosen_Sub_Segment__c, Secondary_Segment__c from Opportunity where Id = :opportunity.Id];
        System.assertEquals('prim-subseg', opp2.Chosen_Sub_Segment__c);
        System.assertEquals(false, opp2.Secondary_Segment__c);
    }
    
}