objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CE_CC_Sub_reason__c</fullName>
        <label>Sub Reason (CC)</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>Compressor valve does not fit to customer application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Better Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service terms</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_DE_Sub_reason__c</fullName>
        <label>Sub Reason (DE)</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>Our product does not match customer specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Better Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_Division__c</fullName>
        <description>Used to make Picklists Divisional dependent</description>
        <inlineHelpText>Used to make Picklists Divisional dependent</inlineHelpText>
        <label>Danfoss Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_HS_Sub_reason__c</fullName>
        <label>Sub Reason (DHS)</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>Our product does not match customer specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Better Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service terms</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_PE_Sub_reason__c</fullName>
        <label>Sub Reason (DDS)</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>Customer application requires Liquid cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Better Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquid cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Front End</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harmonic solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overload capability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC technique</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System supplier/Package deals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CE_RC_Sub_reason__c</fullName>
        <label>Sub Reason (DCS)</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>Our product is too large for the customer application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compressor valve does not fit to customer application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Better Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_reason__c</fullName>
        <description>CE sub reason for closed Opportunities. This is CE specific as it is uncertain if the PS field &quot;Detailed reason&quot; can be reused.
Linked with Reason</description>
        <inlineHelpText>Use the Close Opportunity button to close your Opportunity and add a sub reason.
Please note that the sub reason is not available for all reasons.</inlineHelpText>
        <label>Close sub reason</label>
        <picklist>
            <picklistValues>
                <fullName>Competitor has strong value proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor has superior Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor is preferred supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor offers full System/Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer has long relationship with Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss does not have the needed product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divisional specific feature we are currently missing in portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Our product does not physically fit in application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityCloseExtension.cls
public class OpportunityCloseExtension {
    
    private ApexPages.StandardController stdController;
    private Opportunity opp;
    //public Boolean cc {get;set;}
    //public Boolean de {get;set;}
    public Boolean rc {get;set;}
    public Boolean hs {get;set;}
    public Boolean pe {get;set;}    
    private string division;
    
    public OpportunityCloseExtension(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'CE_Division__c'});
        }
        opp = (Opportunity) stdController.getRecord();
        division = opp.CE_Division__c;
        hs = division == 'Heating';
        //de = division == 'NA - District Energy';
        rc = division == 'Cooling';
        pe = division == 'Drives';
        //cc = division == 'NA - Commercial Compressors';
    }
    
    public PageReference closeOpp() {
        if (division == 'Heating') { opp.Sub_reason__c=opp.CE_HS_Sub_reason__c; }
        //if (division == 'NA - District Energy') { opp.Sub_reason__c=opp.CE_DE_Sub_reason__c; }
        if (division == 'Cooling') { opp.Sub_reason__c=opp.CE_RC_Sub_reason__c; }
        if (division == 'Drives') { opp.Sub_reason__c=opp.CE_PE_Sub_reason__c; }
        //if (division == 'NA - Commercial Compressors') { opp.Sub_reason__c=opp.CE_CC_Sub_reason__c; }
        return stdController.save();
    }
    
}