objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <picklist>
            <controllingField>Object__c</controllingField>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentation Archives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Signature Guidelines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Handbook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need A Logo?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Releases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing &amp; Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Items</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbooks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Type_to_Query__c</fullName>
        <label>Content Type to Query</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assembly Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Let&apos;s Torque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbook</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <description>Configure panel widgets on a portal custom visual force home page</description>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_PortalBannerTrigger.cls
/*************************************************************************************************************
* @author Ankit (Appirio Ind.)
* @date 12/3/2013
* @description Test class for PortalBannerTrigger.
*************************************************************************************************************/
@isTest
private class Test_PortalBannerTrigger {
  private static Id panelRecordTypeId = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName().get('Panel').getRecordTypeId();
  
  /***********************************************************************************************************
  /* Test method for testBulkBeforeInsertAndBeforeUpdate
  ***********************************************************************************************************/
  public static testMethod void testBulkBeforeInsertAndBeforeUpdate() {
    List<PortalBanner__c> lstPortalbanner = createTestData();
    //Test for insert success and failure
    Test.startTest();
    List<Database.Saveresult> lstResult = Database.insert(lstPortalbanner, false);
    Integer successResultCount = 0;
    for(Database.Saveresult result : lstResult) {
      if(result.isSuccess()) {
        successResultCount++;
      }
    }
    Test.stopTest();
    System.assertEquals(52, successResultCount);
    
    //Test for update for failure
    List<PortalBanner__c> lstPortalBannerForUpdate = [Select Id From PortalBanner__c Where 
                                                        Business_Org__c = 'Test Org' 
                                                        And Position__c = '' 
                                                        And Region__c = 'Americas']; 
    for(PortalBanner__c pb : lstPortalBannerForUpdate) {
        pb.Position__c = 'Top Left';
    }
    successResultCount = 0;
    lstResult.clear();
    lstResult = Database.update(lstPortalBannerForUpdate, false);
    for(Database.Saveresult result : lstResult) {
      if(result.isSuccess()) {
        successResultCount++;
      }
    }
    System.assertEquals(0, successResultCount);
    
    //Test for update for success
    for(PortalBanner__c pb : lstPortalBannerForUpdate) {
      pb.Position__c = 'Top Right';
      pb.Component_Type__c = 'Test Component2';
    }
    successResultCount = 0;
    lstResult.clear();
    lstResult = Database.update(lstPortalBannerForUpdate, false);
    for(Database.Saveresult result : lstResult) {
      if(result.isSuccess()) {
        successResultCount++;
      }
    }
    System.assertEquals(1, successResultCount);
      
  }
  
  /***********************************************************************************************************
  /* Test method for testValidationAndConstraints
  ***********************************************************************************************************/
  public static testMethod void testValidationAndConstraints() {
    //Test for validation (Must Select one or more values for 'Content Type to Query' if 'Object' = Content)
    //Test for failure for validation rule
    Boolean isInsert = true;
    PortalBanner__c objPortalBanner;
    try{
      objPortalBanner = new PortalBanner__c(Component_Type__c = 'Test Component', Name = 'Test Banner', Object__c = 'Content', Position__c = 'Top Left', Region__c = 'Americas', RecordTypeId = panelRecordTypeId);
      insert objPortalBanner;
    } catch(Exception e) {
      isInsert = false;
    }
    System.assertEquals(false, isInsert);
    
    //Test for success for validation rule
    objPortalBanner.Content_Type_to_Query__c = 'Test Content1;Test Content2';
    insert objPortalBanner;
    isInsert = true;
    System.assertEquals(true, isInsert);
    
    delete [Select Id From PortalBanner__c];
    //Test for Constraints
    
    //#1. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = Default, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    // and a user attempted to create a record with 
    //Position = ‘Top Left’, Business Org = ‘Integrated’, Region = ‘Default’, Component Type = ‘Announcement’, Record Type = ‘Panel’ , 
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'Default', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    insert objPortalBanner;
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Left', Business_Org__c = 'Integrated', Region__c = 'Default', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is an error condition because the component is the same for the given business org, region, record type and the positions are not none
    System.assertEquals(false, isInsert);
    
    //#2. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = Default, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = None, Business Org = ‘Integrated’, Region = ‘Default’, Component Type = ‘Announcement’, Record Type = ‘Panel’ , 
    objPortalBanner = new PortalBanner__c(Position__c = '', Business_Org__c = 'Integrated', Region__c = 'Default', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is NOT an error condition because the position = none.  Positions with no values selected are never displayed on the page.
    System.assertEquals(true, isInsert);
    
    //#2.1 For update
    objPortalBanner.Position__c = 'Top Left';
    Boolean isUpdate = true;
    try{
      update objPortalBanner;
      isUpdate = true;
    } catch(Exception e) {
      isUpdate = false;
    }
    //This is an error condition because the component is the same for the given business org, region, record type and the positions are not none
    System.assertEquals(false, isUpdate);
    
    
    //#3. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = Default, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Default’, Component Type = ‘Technical Literature’, Record Type = ‘Panel’  
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'Default', Component_Type__c = 'Technical Literature', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is an error condition because the positions are not none and they are same for the given business org, region, and record type
    System.assertEquals(false, isInsert);
    
    //#4. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = Default, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = ‘Top Right’, Business Org = ‘Comatrol’, Region = ‘Default’, Component Type = ‘Announcement’, Record Type = ‘Panel’  
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Comatrol', Region__c = 'Default', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is NOT an error condition because the Business Orgs are different.  
    System.assertEquals(true, isInsert);
    
    //#5. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = None, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ , 
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'Americas', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    insert objPortalBanner;
    objPortalBanner = new PortalBanner__c(Position__c = '', Business_Org__c = 'Integrated', Region__c = 'Americas', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is NOT an error condition because the position = none.  Positions with no values selected are never displayed on the page.
    System.assertEquals(true, isInsert);
    
    //#6. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Technical Literature’, Record Type = ‘Panel’  
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'Americas', Component_Type__c = 'Technical Literature', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is an error condition because the positions are not none, positions are both the same for the given business org, region, and record type
    System.assertEquals(false, isInsert);
    
    //#7. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = ‘Top Right’, Business Org = ‘Comatrol’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’  
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Comatrol', Region__c = 'Americas', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is NOT an error condition because the Business Orgs are different.
    System.assertEquals(true, isInsert);
    
    //#8. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Europe’, Component Type = ‘Announcement’, Record Type = ‘Panel’  
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'Europe', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is NOT an error condition because the Regions are different.
    System.assertEquals(true, isInsert);
    
    //#9. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = ‘Top Left’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ , 
    objPortalBanner = new PortalBanner__c(Position__c = 'Top Left', Business_Org__c = 'Integrated', Region__c = 'Americas', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is an error condition because the component is the same for the given business org, region, record type and the positions are not none
    System.assertEquals(false, isInsert);
    
    //#10. if there exist record with Position = ‘Top Right’, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ 
    //and a user attempted to create a record with 
    //Position = None, Business Org = ‘Integrated’, Region = ‘Americas’, Component Type = ‘Announcement’, Record Type = ‘Panel’ , 
    objPortalBanner = new PortalBanner__c(Position__c = '', Business_Org__c = 'Integrated', Region__c = 'Americas', Component_Type__c = 'Announcement', RecordTypeId = panelRecordTypeId);
    isInsert = insertPortalBanner(objPortalBanner);
    //This is NOT an error condition because the position = none.  Positions with no values selected are never displayed on the page.
    System.assertEquals(true, isInsert);
    
  }
  
  /***********************************************************************************************************
  /* Returns true or false based on insert success
  * @param objPortalBanner PortalBanner__c
  * @return Boolean
  ***********************************************************************************************************/
  private static Boolean insertPortalBanner(PortalBanner__c objPortalBanner){
  	Boolean isInsert;
  	try{
    	insert objPortalBanner;
    	isInsert = true;
    } catch(Exception e) {
    	isInsert = false;
    }
    return isInsert;
  }
  
  /***********************************************************************************************************
  /* Methos For Create Test Data
  * @return List<PortalBanner__c>
  ***********************************************************************************************************/
  private static List<PortalBanner__c> createTestData(){
    List<PortalBanner__c> lstPortalbanner = new List<PortalBanner__c>();
    
    // It will insert only one record and rest of 99 will get failure
    for(Integer i = 0 ; i < 100 ; i++){
      PortalBanner__c objPortalBanner = new PortalBanner__c();
      objPortalBanner.Business_Org__c = 'Test Org';
      objPortalBanner.Component_Type__c = 'Test Component';
      objPortalBanner.Name = 'Test Banner ' + i;
      objPortalBanner.Object__c = 'Idea';
      objPortalBanner.Position__c = 'Top Left';
      objPortalBanner.Region__c = 'Americas';
      objPortalBanner.RecordTypeId = panelRecordTypeId;
      lstPortalbanner.add(objPortalBanner);
    }
    
    // It will insert only one record and rest of 49 will get failure
    for(Integer i = 100 ; i < 150 ; i++){
      PortalBanner__c objPortalBanner = new PortalBanner__c();
      objPortalBanner.Business_Org__c = 'Test Org';
      objPortalBanner.Component_Type__c = 'Test Component';
      objPortalBanner.Name = 'Test Banner ' + i;
      objPortalBanner.Object__c = 'Idea';
      objPortalBanner.Position__c = 'Top Left';
      objPortalBanner.Region__c = 'Default';
      objPortalBanner.RecordTypeId = panelRecordTypeId;
      lstPortalbanner.add(objPortalBanner);
    }
    
    // It will insert all 50 records and no one will get failure
    for(Integer i = 150 ; i < 200 ; i++){
      PortalBanner__c objPortalBanner = new PortalBanner__c();
      objPortalBanner.Business_Org__c = 'Test Org';
      objPortalBanner.Component_Type__c = 'Test Component';
      objPortalBanner.Name = 'Test Banner ' + i;
      objPortalBanner.Object__c = 'Idea';
      objPortalBanner.Position__c = '';
      objPortalBanner.Region__c = 'Americas';
      objPortalBanner.RecordTypeId = panelRecordTypeId;
      lstPortalbanner.add(objPortalBanner);
    }
    return lstPortalbanner;
  }
}