objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Spots</fullName>
        <active>true</active>
        <description>Spots - Marketing call outs</description>
        <label>Spots</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_PartnerPortalHomeCtrl.cls
/*************************************************************************************************************
Name                : Test_PartnerPortalHomeCtrl
Author              : Ankit Goyal (Appirio offshore)
createdDate         : 7 Dec,2013    
Description         : This class is used for verify all functionality of PartnerPortalHomeCtrl class.
*************************************************************************************************************/
@isTest
private class Test_PartnerPortalHomeCtrl {
  static Account account;
  static Contact contactPortal;
  static User portalUser;
  static User adminUser;
        
  static testMethod void unitTestWithTopBanner() { 
    PortalBanner__c portalBanner;
    List<Idea> ideaList;
    createUsers();
    update PortalUser;
    //Run as admin user to create dummy data(As setup or non setup data conn't be created in one context)
    system.runAs(adminUser){
    ideaList = new List<Idea>();
    for(Community community : [Select c.Id From Community c where IsActive = true limit 1]) {
      for(Integer i=0; i<5; i++) {
          Idea idea = new Idea(Title = 'Test idea'+i, CommunityId = community.Id);
          ideaList.add(idea);
      }       
    }
    if(!ideaList.IsEmpty()) {
      insert ideaList;
    } 
    //Create portal Banner record of TopBanner record Type
    portalBanner = Test_Utility.createPortalBanner(true, 'Middle');
    portalBanner.Business_Org__c = 'Integrated';
    portalBanner.Region__c = 'default';
    update portalBanner;
  // Add test attacment file to portal banner record      
    Attachment attach = new Attachment();     
          attach.Name = 'Unit Test Attachment';
          Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
          attach.body = bodyBlob;
      attach.parentId = portalBanner.id;
      insert attach;        
    }
    //login as portal user
    //verify that controller fetch latest 3 ideas
    //verify portalBanner is fetched against the region of portal user account  
    System.runAs(portalUser) {
      Test.startTest();
      PartnerPortalHomeCtrl portalHomePageCon = new PartnerPortalHomeCtrl();
      system.assertNotEquals(portalHomePageCon.loginUser, null);
      portalBanner.Position__c = 'Right';
      update portalBanner;
      portalHomePageCon = new PartnerPortalHomeCtrl();
      portalBanner.Position__c = 'Left';
      update portalBanner;
      portalHomePageCon = new PartnerPortalHomeCtrl();
      system.assertNotEquals(portalHomePageCon.marCommLeft, null); 
      Test.stopTest();
    }
  }
    
  static testMethod void unitTestWithSpotsBanner() { 
    PortalBanner__c portalBanner;
    createUsers();
    //Run as admin user to create dummy data(As setup or non setup data cann't be created in one context)     
    system.runAs(adminUser){
      Map<String,Schema.RecordTypeInfo> recordType = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName();
      //Create portal Banner record of sports record type
      portalBanner = Test_Utility.createPortalBanner(false, 'Middle');
      portalBanner.RecordTypeId = recordType.get('Spots').getRecordTypeId(); 
      insert portalBanner;
      // Add test attacment file to portal banner record      
      Attachment attach = new Attachment();     
      attach.Name = 'Unit Test Attachment';
      Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
      attach.body = bodyBlob;
      attach.parentId = portalBanner.id;
      insert attach;        
    }
    //Login as portal user
    //verify portalBanner is fetched against the region of portal user account    
    System.runAs(portalUser) {
      Test.startTest();
      PartnerPortalHomeCtrl portalHomePageCon = new PartnerPortalHomeCtrl();
      portalBanner.Position__c = 'Right';
      update portalBanner;
      portalHomePageCon = new PartnerPortalHomeCtrl();
      portalBanner.Position__c = 'Left';
      update portalBanner;
      portalHomePageCon = new PartnerPortalHomeCtrl();
      system.assertEquals(portalHomePageCon.portalBanner, null); 
      Test.stopTest();
    }
  }
    
  private static void createUsers() {
    Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
    UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
    adminUser = Test_Utility.createUser(profile.Id,roles.Id, 1);
    insert adminUser;
    List<Group> grpList =[Select g.Id From Group g where Name = '*Danfoss Power Solutions'];
    system.assertEquals(grpList.size(), 1);
    //Assign user to intergrated group to provide access on account record
    GroupMember groupMember = new GroupMember(UserOrGroupId = adminUser.Id,GroupId = grpList.get(0).Id);
    insert groupMember;
    
    system.runAs(adminUser) {
      account = new Account(Name='Test Account Name', Business_Org__c='Integrated');//Test_Utility.createAccount(1);
      //Region__c region = new Region__c(Name = 'USA');//[select Id from Region__c where Name = 'USA'];
      Region__c region = new Region__c(
                              Name='USA',
                              Country_Code__c='16',
                              Region__c = 'Test region');
      insert region;
      account.Country__c = region.Id;
      insert account;
      contactPortal = Test_Utility.createContact(account.Id,2);
      insert contactPortal;
      List<Profile> portalUserProfiles = [Select id from Profile where Name IN ('PartnerLink - Full') limit 1];
      system.assertEquals(portalUserProfiles.size(), 1);
      portalUser = Test_Utility.createPortalUser(contactPortal.Id, portalUserProfiles.get(0).Id);
      insert portalUser;
      //Provide access on account record by assigning portal user to intergrated group
      GroupMember  grpMember = new GroupMember(UserOrGroupId = portalUser.Id,GroupId = grpList.get(0).Id);
      insert grpMember;
    }
  }
}