objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <description>Configure panel widgets on a portal custom visual force home page</description>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalBannerLink__c.object
<CustomObject>
    <fields>
        <fullName>PortalBanner__c</fullName>
        <label>Portal Banner</label>
        <referenceTo>PortalBanner__c</referenceTo>
        <relationshipLabel>Portal Banner Links</relationshipLabel>
        <relationshipName>Portal_Banner_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <description>Determines where the link will be opened</description>
        <label>Target</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>External</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>URL of link</description>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_PartnerPortalPanelComponentCtrl.cls
/**************************************************************************
Name            : Test_PartnerPortalPanelComponentCtrl
Description     : Test Class for PartnerPortalPanelComponentCtrl
Created By      : Arvind Thakur
Date            : 24rd Dec, 2014
Task            : T-346183
***************************************************************************/
@isTest
private class Test_PartnerPortalPanelComponentCtrl {
    
    static User adminUser;
    static User testUser;
    static PortalBanner__c testBanner;
    
    static testMethod void testPartnerPortalPanelComponentCtrl() {
    	createTestData();    	
    	system.runAs(testUser){
    		test.startTest();
    		PartnerPortalPanelComponentCtrl testPortal = new PartnerPortalPanelComponentCtrl();
    		testPortal.pos = 'Left';
            PortalBanner__c getBanner = testPortal.portalBanner;
            system.assertEquals(getBanner.Id , testBanner.Id);            
            List<PortalBannerLink__c> portalList = testPortal.getPortalLInks();
            system.assert(portalList.size() > 0);
            test.stopTest();
    	}        
       
    }
    
    private static void createTestData(){
	    Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
	    UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
	    adminUser = Test_Utility.createUser(profile.Id,roles.Id, 1);
	    insert adminUser;
	    List<Group> grpList =[Select g.Id From Group g where Name = '*Danfoss Power Solutions'];
	    system.assertEquals(grpList.size(), 1);
	    //Assign user to intergrated group to provide access on account record
	    GroupMember groupMember = new GroupMember(UserOrGroupId = adminUser.Id,GroupId = grpList.get(0).Id);
	    insert groupMember;
      
		system.runAs(adminUser) {    	
			Profile delegatedAdminProfile = [Select Name,Id From Profile p Where Name = 'PartnerLink - Delegated Admin' Limit 1];
			Account account = Test_Utility.createAccount(1);
			insert account;
			Contact contact = Test_Utility.createContact(account.id, 1);
			//contact.Email = 'athakur@appirio.com';
			insert contact; 
			testUser = Test_Utility.createPortalUser(contact.id, delegatedAdminProfile.id); 
			testUser.Business_Org__c = 'Integrated';
			insert testUser;
			
			
			RecordType bannerRecordType =  [select Id FROM RecordType WHERE Name='Marketing Panel'];
			testBanner = test_Utility.createPortalBanner(false, 'Left');
			testBanner.RecordTypeId = bannerRecordType.Id;
			testBanner.Region__c = 'default';
			testBanner.Page__c = 'MarketingToolbox';
			testBanner.Business_Org__c = 'Integrated';
			insert testBanner;
			
			Attachment testAttachment = test_utility.createAttachment(testBanner.Id, true);
			
			PortalBannerLink__c bannerLink = new PortalBannerLink__c();
			bannerLink.Target__c = 'Self';
			bannerLink.Type__c = 'External';
			bannerLink.URL__c = 'https://www.google.co.in';
			bannerLink.PortalBanner__c = testBanner.Id;
			insert bannerLink;
		}
    }
}