objects/Portal_Business_Org_Style__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies style sheet used by portal home page based on Business Org</description>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Portal Business Org Style</label>
</CustomObject>

objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Alt__c</fullName>
        <inlineHelpText>Alt text will be used for the Spots images.</inlineHelpText>
        <label>Alt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Top_Banner</fullName>
        <active>true</active>
        <description>Top Banner by Region</description>
        <label>Top Banner</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/MarketingToolboxCtrl.cls
/***************************************************************************************
Name                : PartnerPortalHomeCtrl
Author              : Matt Salpietro
CreatedDate         : 12 Dec,2014    
Description         : This class is used for Marketing Toolbox Page.
****************************************************************************************/
public with sharing class MarketingToolboxCtrl {
    /*************************************************************************************
    Getter Setter Properties
    **************************************************************************************/
    
    private static String TOP_BANNER = 'Top Banner';
    private static String DEFAULT_REGION = 'default';

    public String COMATROL_ORG {get{
        return 'Comatrol';
    }set;}
    
    public User loginUser {get;set;}
    public PortalBanner__c portalBanner {get; set;}
    public Portal_Business_Org_Style__c styleSheetRecord{get; set;}
    public String baseURL {get;set;}
    public String pageURL {get;set;}


    public MarketingToolboxCtrl() { 
        baseURL = URL.getSalesforceBaseUrl().toExternalForm();
        pageURL = ApexPages.currentPage().getUrl();

        for(User user:[Select Id, Contact.Account.Region__c, ContactId, Contact.AccountId, Business_Org__c From User where Id =:userInfo.getUserId()]) {
            loginUser = user; 
        }
        
        Map<String,Schema.RecordTypeInfo>  recordType = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName();
           
        //fetch portal banner image based on login user (account) region. 
        for(PortalBanner__c portalBannerObj:[Select Alt__c,Link__c,RecordTypeId,Region__c,Summary__c,Id,Position__c,Business_Org__c,
                                           (Select Id, LastModifiedDate From Attachments order by LastModifiedDate desc limit 1) From PortalBanner__c where 
                                           Region__c =:loginUser.Contact.Account.Region__c and Business_Org__c =:loginUser.Business_Org__c
                                           and Page__c = 'MarketingToolbox']) { 
            if (portalBannerObj.RecordTypeId == recordType.get('Top Banner').getRecordTypeId()) {
                portalBanner = portalBannerObj;
            }
        }
        // If there is no region image then fetch default images
        for(PortalBanner__c portalBannerObj:[Select Alt__c,Link__c,RecordTypeId,Region__c,Summary__c,Id,Position__c,Business_Org__c,
                                           (Select Id, LastModifiedDate From Attachments order by LastModifiedDate desc limit 1) From PortalBanner__c where 
                                           Region__c = :DEFAULT_REGION and Business_Org__c=:loginUser.Business_Org__c
                                           and Page__c = 'MarketingToolbox']){
            if (portalBanner == null && portalBannerObj.RecordTypeId == recordType.get('Top Banner').getRecordTypeId() ){
                portalBanner = portalBannerObj;
            }                                               
        }      
        //Get style sheet resource on basis of current user's business org
        styleSheetRecord = Utility.getStyleSheetResource();
    }
}