objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <picklist>
            <controllingField>Object__c</controllingField>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentation Archives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Signature Guidelines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Handbook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need A Logo?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Releases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing &amp; Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Items</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbooks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <description>Configure panel widgets on a portal custom visual force home page</description>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalBannerTriggerHandler.cls
/*************************************************************************************************************
* @author Ankit (Appirio Ind.)
* @date 12/3/2013
* @Story S-162787
* @description Handler class for PortalBannerTrigger.
*************************************************************************************************************/
public without sharing class PortalBannerTriggerHandler {
    
  public static Map<String,Schema.RecordTypeInfo> recordType = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName();
  
  /***********************************************************************************************************
  /* Actions performed before update of Portal Banner
  * @param newList List of Portal Banners
  * @param oldMap Map with old values of Portal Banners
  * @return void.
  ***********************************************************************************************************/
	public static void beforeUpdate(List<PortalBanner__c> newList, Map<Id, PortalBanner__c> oldMap) {
    checkForRecordExist(newList, oldMap);
	}
  
  /***********************************************************************************************************
  /* Actions performed before Insert of Portal Banner
  * @param newList List of Portal Banners
  * @return void.
  ***********************************************************************************************************/
  public static void beforeInsert(List<PortalBanner__c> newList) {
      checkForRecordExist(newList, null);
  }
  
  /***********************************************************************************************************
   * Method for check is record exist or not
	    #1 For panel type records, there can only be one record 
	      For each Position {Top Right, Top, Left, Bottom Right, Bottom Left} and Business Org Combination with Region = Default
	    #2 For panel type records, there can only be one record 
	      For each Position {Top Right, Top, Left, Bottom Right, Bottom Left} and Business Org and Region combination
      #3 For panel type records, there can only be one record 
        For each Component, Business Org and Region combination Where Location != None
   * @param newList List of Portal Banners
   * @param oldMap Map of old Portal Banners
   * @return void.
   *
   *Modified 12/4/2014 - Matt Salpietro - Added check for Page value
  ***********************************************************************************************************/
  private static void checkForRecordExist(List<PortalBanner__c> newList, Map<Id, PortalBanner__c> oldMap) {
    String useCase1FilterStr = 'Position__c,Business_Org__c,Region__c,Page__c'; 
    List<PortalBanner__c> lstPortalBanner = getLstPortalBanner(newList, oldMap, useCase1FilterStr);
		
		if(!lstPortalBanner.isEmpty()) {
			Set<String> keySet = new Set<String>();
			for(AggregateResult ar : [Select Position__c, Business_Org__c, Region__c, Page__c From PortalBanner__c 
                                Where RecordTypeId = :recordType.get('Panel').getRecordTypeId()  
                                group by Position__c, Business_Org__c, Region__c, Page__c]) {
        keySet.add(getKey(ar.get('Position__c') , null, ar.get('Business_Org__c'), ar.get('Region__c'), ar.get('Page__c')));
			}
			
			for(PortalBanner__c pb : lstPortalBanner) {
		    if(keySet.contains(getKey(pb.Position__c, null, pb.Business_Org__c, pb.Region__c, pb.Page__c))) {
	        pb.addError(getErrorMsg(Label.PortalBannerExistForPosition, pb));
		    } else {
	        keySet.add(getKey(pb.Position__c , null, pb.Business_Org__c, pb.Region__c, pb.Page__c));
		    }
			}   
    }
        
		useCase1FilterStr = 'Component_Type__c,Business_Org__c,Region__c,Position__c,Page__c';
		lstPortalBanner.clear();
		lstPortalBanner = getLstPortalBanner(newList, oldMap, useCase1FilterStr);
		if(!lstPortalBanner.isEmpty()) {
	    Set<String> keySet = new Set<String>();
	    for(AggregateResult ar : [Select Component_Type__c, Business_Org__c, Region__c, Page__c From PortalBanner__c 
                                Where RecordTypeId = :recordType.get('Panel').getRecordTypeId() 
                                And Position__c != '' And Position__c != null  
                                group by Component_Type__c, Business_Org__c, Region__c, Page__c]) {
	        
        keySet.add(getKey(null, ar.get('Component_Type__c'), ar.get('Business_Org__c'), ar.get('Region__c'), ar.get('Page__c')));
	    }
	    
	    for(PortalBanner__c pb : lstPortalBanner) {
		    if(keySet.contains(getKey(null, pb.Component_Type__c, pb.Business_Org__c, pb.Region__c, pb.Page__c))) {
	        pb.addError(getErrorMsg(Label.PortalBannerExistForComponentType, pb));
		    } else {
	        keySet.add(getKey(null , pb.Component_Type__c, pb.Business_Org__c, pb.Region__c, pb.Page__c));
		    }
	    }   
		}
  }
    
  /***********************************************************************************************************
   * Method for get final list of Portal Banner after check is field update and other required filters
   * @param newList List of Portal Banners
   * @param oldMap Map of old Portal Banners
   * @param changeFieldsStr string with comma separated fields api
   * @return List<Portal_Banner__c>.
  ***********************************************************************************************************/
  private static List<PortalBanner__c> getLstPortalBanner(
    List<PortalBanner__c> newList, Map<Id, PortalBanner__c> oldMap, String changeFieldsStr) {
    	
		List<PortalBanner__c> lstFinalPortalBanner = new List<PortalBanner__c>();
		List<PortalBanner__c> lstPortalBanner = new List<PortalBanner__c>();
    if(oldMap != null) {
			for(PortalBanner__c pb : newList) {
		    Boolean isRecordUpdate = false;
		    if(changeFieldsStr != '') {
	        for(String fieldApi : changeFieldsStr.split(',')) {
            isRecordUpdate = isRecordUpdate || Utility.isNewOrChanged(pb, fieldApi.trim(), oldMap);
	        }
		    }
		    if(isRecordUpdate) {
	        lstPortalBanner.add(pb);
		    }
			}
		} else {
	    lstPortalBanner.addAll(newList);
		}
        
		for(PortalBanner__c pb : lstPortalBanner) {
	    if(pb.RecordTypeId == recordType.get('Panel').getRecordTypeId() && pb.Position__c != null && pb.Position__c != '') {
        lstFinalPortalBanner.add(pb);
	    }
		}
		return lstFinalPortalBanner;
  }
    
  /***********************************************************************************************************
  * Append error message and replaces values for attributes: Position, Region, Business Org, Component Type
   * @param msg String error message
   * @param pb PortalBanner Record
   * @return String error message.
  ***********************************************************************************************************/
  private static String getErrorMsg(String msg, PortalBanner__c pb) {
		msg = msg.replace('[Position]', pb.Position__c);
		msg = msg.replace('[Region]', pb.Region__c);
		msg = msg.replace('[Business Org]', pb.Business_Org__c);
		msg = msg.replace('[Component Type]', pb.Component_Type__c);
		return msg;
  }
  
  /***********************************************************************************************************
  //Returns key for PortalBanner record constraints
   * @param position position of portalBanner
   * @param PortalBanner PortalBanner of portalBanner
   * @param bussinessOrg bussinessOrg of portalBanner
   * @param region region of portalBanner
   * @return Stirng.
  ***********************************************************************************************************/
  private static String getKey(object position, object compType, object bussinessOrg, object region, object page) {
    String key  = (position == null ? '' : String.valueOf(position) + '-')
			          + (compType == null ? '' : String.valueOf(compType) + '-')
			          + (bussinessOrg == null ? '' : String.valueOf(bussinessOrg) + '-')
			          + (region == null ? '' : String.valueOf(region) + '-')
                              + (page == null ? '' : String.valueOf(page) + '-');
    key = key.removeEnd('-');
    return key;
  }
}