objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <picklist>
            <controllingField>Object__c</controllingField>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentation Archives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Signature Guidelines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Handbook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need A Logo?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Releases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing &amp; Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Items</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbooks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <description>Configure panel widgets on a portal custom visual force home page</description>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalBannerLink__c.object
<CustomObject>
    <fields>
        <fullName>DisplayPopText__c</fullName>
        <description>Text displayed in pop-up</description>
        <label>Pop-up Text</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisplayPop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if user is presented pop-up text before browsing to URL</description>
        <label>Display Pop-up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DisplayPopupText__c</fullName>
        <label>Display Pop-up Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PortalBanner__c</fullName>
        <label>Portal Banner</label>
        <referenceTo>PortalBanner__c</referenceTo>
        <relationshipLabel>Portal Banner Links</relationshipLabel>
        <relationshipName>Portal_Banner_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Order of displayed links</description>
        <label>Sequence</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <description>Determines where the link will be opened</description>
        <label>Target</label>
        <picklist>
            <picklistValues>
                <fullName>Self</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>External</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>URL of link</description>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/PartnerPortalPanelComponentCtrl.cls
/*************************************************************************************************************
* @author Matt Salpietro
* @date 12/5/2014
* @description Controller class for PartnerPortalPanelComponent.
*************************************************************************************************************/
public with sharing class PartnerPortalPanelComponentCtrl {
  public String pos{get;set;}
  public String errorMsg {get;set;}

/***********************************************************************************************************
/* Returns Current user with region and business org
***********************************************************************************************************/
private static User m_User;
private static User currentUser {
  get {
    if (m_User == null) {
      for (User usr: [ Select Contact.Account.Region__c, Contact.Account.Business_Org__c 
        From User 
        Where Id = :UserInfo.getUserId()]) {
        m_User = usr;
      }
    }
    return m_User;
  }
}

private static String userRegion = currentUser.Contact.Account.Region__c;
private static String userBusinessOrg = currentUser.Contact.Account.Business_Org__c;
private static String componentType = '';
private static Map<String,Schema.RecordTypeInfo>  recordType = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName();

/***********************************************************************************************************
/* Returns Current user with region and business org
***********************************************************************************************************/
private List<PortalBanner__c> lstPnlBanner;
private PortalBanner__c m_portalBanner;

public PortalBanner__c portalBanner {
  get {
    if (lstPnlBanner != null) {
      return m_portalBanner;
    }
    m_portalBanner = getPortalBannerRecord(userRegion);
    return m_portalBanner;
  }
}

/***********************************************************************************************************
/* Returns Portal Banner Record based on region
* @param region Region
* @return PortalBanner__c.
***********************************************************************************************************/
private PortalBanner__c getPortalBannerRecord(String region){
  PortalBanner__c portalBanner;
  lstPnlBanner = [SELECT Id, Component_Type__c, Object__c, Summary__c, Name, (SELECT Id, Name  FROM Attachments)
                              FROM PortalBanner__c 
                              WHERE Position__c = :pos 
                              AND Region__c = :region   
                              AND Business_Org__c = :userBusinessOrg 
                              AND RecordTypeId = :recordType.get('Marketing Panel').getRecordTypeId()];
  //There should only be one match for VF Page and Position (Filter: VF Page, Position, User Region, User Business Org, RecordTypeId)                           
  if (lstPnlBanner.size() == 1) {
    portalBanner = lstPnlBanner[0]; 
    }else if(lstPnlBanner.isEmpty()){
  //Query banner record again for region "Default"
  lstPnlBanner = [SELECT Id, Component_Type__c, Object__c, Summary__c, Name, (SELECT Id, Name  FROM Attachments)
  FROM PortalBanner__c 
  WHERE Position__c = :pos 
  AND Region__c = 'Default'   
  AND RecordTypeId = :recordType.get('Marketing Panel').getRecordTypeId()];
  if(!lstPnlBanner.isEmpty()){
    PortalBanner__c defaultPortalBanner = lstPnlBanner[0];
    portalBanner = defaultPortalBanner;       
    } else {
      componentType = '';
    }
  }

  return portalBanner;
}

/***********************************************************************************************************
/* Returns list of links
* @return List<PortalBannerLink__c> returns list of portal banner links.
***********************************************************************************************************/
public List<PortalBannerLink__c> getPortalLInks() {
  String sitePrefix = '';
  if(Site.getPathPrefix() != null){
    sitePrefix = Site.getPathPrefix();
  }
  List<PortalBannerLink__c> portalLinkList = new List<PortalBannerLink__c>();

  for(PortalBannerLink__c link : [SELECT URL__c, Sequence__c, Name, Target__c, Type__c, DisplayPop__c, DisplayPopText__c, DisplayPopupText__c
                                                          FROM PortalBannerLink__c
                                                          WHERE PortalBanner__c = :portalBanner.Id
                                                          ORDER BY Sequence__c]) {
															  System.debug(link);
    if(link.Target__c == 'Self'){
      link.Target__c = '_self';
      } else {
        link.Target__c = '_blank';
      }
      if(link.Type__c == 'Internal'){
        String pageURL = ApexPages.currentPage().getUrl();
        link.URL__c = sitePrefix + '/apex/' + link.URL__c + '?' + pageURL.substring(pageURL.indexOf('sfdc.tabName'));
      } else if(link.Type__c == 'Content'){
        Id contentVersionId = [SELECT LatestPublishedVersionId FROM ContentDocument WHERE Id = :link.URL__c LIMIT 1].LatestPublishedVersionId;
        //link.URL__c = URL.getSalesforceBaseUrl().toExternalForm() + sitePrefix + '/sfc/servlet.shepherd/version/download/' + contentVersionId;
        link.URL__c = sitePrefix + '/sfc/servlet.shepherd/version/download/' + contentVersionId;
      } 
      portalLinkList.add(link);
    }
    return portalLinkList;
  }

}