objects/Portal_Business_Org_Style__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies style sheet used by portal home page based on Business Org</description>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfItems__c</fullName>
        <description>number of items to show in each panel on the home page. Used in PartnerPortalHomeComponentCtrl</description>
        <label>NumberOfItems</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Visualforce_Page__c</fullName>
        <label>Terms and Conditions Visualforce Page</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Portal Business Org Style</label>
</CustomObject>

objects/PortalBanner__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <picklist>
            <controllingField>Object__c</controllingField>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentation Archives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Kit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>e-Signature Guidelines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Handbook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need A Logo?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Releases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing &amp; Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Items</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbooks</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Type_to_Query__c</fullName>
        <label>Content Type to Query</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assembly Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Presentations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactive Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Let&apos;s Torque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Press Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price File</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Information Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Bulletin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Literature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Specification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unique Selling Points Handbook</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <picklist>
            <picklistValues>
                <fullName>Idea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Static</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <description>Page where the record will be displayed.</description>
        <label>Page</label>
        <picklist>
            <picklistValues>
                <fullName>ImageBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InformationHub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LogoBank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MarketingToolbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PartnerPortalHome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom Right</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>default</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Banner</label>
    <nameField>
        <label>Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <description>Configure panel widgets on a portal custom visual force home page</description>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Cross reference object to associate the countries (Accounts) with regions; will be used for both SAP integration as well as population for Prospect Accounts</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <externalId>true</externalId>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Country Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>C&amp;E field
Used for identifying the Region of the User</description>
        <label>Region</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS: Europe</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_PartnerPortalHomeComponentCtrl.cls
/*************************************************************************************************************
* @author Ankit (Appirio Ind.)
* @date 7 Dec,2013
* @description This class is used for verify all functionality of PartnerPortalHomeComponentCtrl class.
*************************************************************************************************************/
@isTest
public with sharing class Test_PartnerPortalHomeComponentCtrl {
    private static Id panelRecordTypeId = Schema.SObjectType.PortalBanner__c.getRecordTypeInfosByName().get('Panel').getRecordTypeId();
    static User adminUser;
    static User portalUser;
    static User comatrolUser;
    
    /***********************************************************************************************************
    /* Test method for testPortalBannerForPortalUser
    ***********************************************************************************************************/    
    static testMethod void testPortalBannerForPortalUser() { 
        createUsers();
        PortalBanner__c objPortalBanner;
        PartnerPortalHomeComponentCtrl ctrl;
		Portal_Business_Org_Style__c pobu;
        Test.setCurrentPage(Page.InformationHub);
        //#1 No Match is found neither user's region nor default region (Error condition)
        system.runAs(portalUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(null, ctrl.portalBanner);
            System.assertNotEquals(null, ctrl.errorMsg);
        }
        
        //#2 Match is found with user's region (No error condition)
        system.runAs(adminUser){
        	objPortalBanner = new PortalBanner__c(Page__c = 'InformationHub', Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'USA', Component_Type__c = 'Announcement', 
        						Content_Type_to_Query__c = 'TestContent1;TestContent2', Object__c = 'Idea', RecordTypeId = panelRecordTypeId);
            insert objPortalBanner;
			pobu = new Portal_Business_Org_Style__c(Name='PartnerLink Home Page', NumberOfItems__c = 7, Business_Org__c = 'Integrated', Terms_and_Conditions_Visualforce_Page__c='test');
			insert pobu;			
        }
        system.runAs(portalUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(objPortalBanner.Id, ctrl.portalBanner.Id);
            System.assertEquals(true, ctrl.errorMsg == null);
            System.assertEquals(0, ctrl.getContentList().size());
            System.assertEquals(0, ctrl.getIdeaList().size());
            System.assertEquals(true, ctrl.ContentFilterString != null);
        }
        
        //#3 Match is found with Default region (No error condition)
        system.runAs(adminUser){
        	objPortalBanner.Region__c = 'Default';
        	update objPortalBanner; 
        }
        system.runAs(portalUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(objPortalBanner.Id, ctrl.portalBanner.Id);
            System.assertEquals(true, ctrl.errorMsg == null);
        }
        
        //#4 Match is found with Default region for other panel records displayed on page to with matching component type (Error condition)
        system.runAs(adminUser){
        	objPortalBanner = new PortalBanner__c(Page__c = 'InformationHub', Position__c = 'Top Left', Business_Org__c = 'Integrated', Region__c = 'USA', Component_Type__c = 'Announcement', 
        						Content_Type_to_Query__c = 'TestContent1;TestContent2', Object__c = 'Idea', RecordTypeId = panelRecordTypeId);
        	insert objPortalBanner; 
        }
        system.runAs(portalUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(null, ctrl.portalBanner);
            System.assertNotEquals(null, ctrl.errorMsg);
        }
    }
    
    /***********************************************************************************************************
    /* Test method for testPortalBannerForComatrolUser
    ***********************************************************************************************************/
    static testMethod void testPortalBannerForComatrolUser() { 
        createUsers();
        PortalBanner__c objPortalBanner;
        PartnerPortalHomeComponentCtrl ctrl;
		Portal_Business_Org_Style__c pobu;
        Test.setCurrentPage(Page.InformationHub);
        
        //#1 No Match is found neither user's region nor default region (Error condition)
        system.runAs(comatrolUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(null, ctrl.portalBanner);
            System.assertNotEquals(null, ctrl.errorMsg);
        }
        
        //#2 Match is found with user's region (No error condition)
        system.runAs(adminUser){
        	objPortalBanner = new PortalBanner__c(Page__c = 'InformationHub', Position__c = 'Top Right', Business_Org__c = 'Integrated', Region__c = 'USA', Component_Type__c = 'Announcement', 
        						Content_Type_to_Query__c = 'TestContent1;TestContent2', Object__c = 'Idea', RecordTypeId = panelRecordTypeId);
            insert objPortalBanner;
			pobu = new Portal_Business_Org_Style__c(Name='PartnerLink Home Page', NumberOfItems__c = 7, Business_Org__c = 'Integrated', Terms_and_Conditions_Visualforce_Page__c='test');
			insert pobu;
        }
        system.runAs(comatrolUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(objPortalBanner.Id, ctrl.portalBanner.Id);
            System.assertEquals(true, ctrl.errorMsg == null);
            System.assertEquals(0, ctrl.getContentList().size());
            System.assertEquals(0, ctrl.getIdeaList().size());
            System.assertEquals(true, ctrl.ContentFilterString != null);
        }
        
        //#3 Match is found with Default region (No error condition)
        system.runAs(adminUser){
        	objPortalBanner.Region__c = 'Default';
        	update objPortalBanner; 
        }
        system.runAs(comatrolUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(objPortalBanner.Id, ctrl.portalBanner.Id);
            System.assertEquals(true, ctrl.errorMsg == null);
        }
        
        //#4 Match is found with Default region for other panel records displayed on page with matching component type (Error condition)
        system.runAs(adminUser){
        	objPortalBanner = new PortalBanner__c(Page__c = 'InformationHub', Position__c = 'Top Left', Business_Org__c = 'Integrated', Region__c = 'USA', Component_Type__c = 'Announcement', 
        						Content_Type_to_Query__c = 'TestContent1;TestContent2', Object__c = 'Idea', RecordTypeId = panelRecordTypeId);
        	insert objPortalBanner; 
        }
        system.runAs(comatrolUser) {
            ctrl = new PartnerPortalHomeComponentCtrl();
            ctrl.pos = 'Top Right';
            System.assertEquals(null, ctrl.portalBanner);
            System.assertNotEquals(null, ctrl.errorMsg);
        }
    }
    
    /***********************************************************************************************************
    /* Methos For Create Test users
    ***********************************************************************************************************/
    private static void createUsers() {
	    Profile profile = [Select id from Profile where Name = 'System Administrator' limit 1];
	    UserRole roles = [Select id from UserRole where Name = 'SFDC_Platform Administrator' limit 1];
	    adminUser = Test_Utility.createUser(profile.Id,roles.Id, 1);
	    insert adminUser;
	    List<Group> grpList =[Select g.Id From Group g where Name = '*Danfoss Power Solutions'];
	    system.assertEquals(grpList.size(), 1);
	    //Assign user to intergrated group to provide access on account record
	    GroupMember groupMember = new GroupMember(UserOrGroupId = adminUser.Id,GroupId = grpList.get(0).Id);
	    insert groupMember;
      
		system.runAs(adminUser) {
		    Region__c region = new Region__c(Name='USA', Country_Code__c='16', Region__c = 'USA');
		    insert region;
		    Account account = new Account(Name='Test Account Name', Business_Org__c='Integrated', Country__c = region.Id);
		    insert account;
		    //Create portal user
		    Contact contactPortal = Test_Utility.createContact(account.Id,1);
		    insert contactPortal;
		    List<Profile> userProfiles = [Select id from Profile where Name IN ('PartnerLink - Full') limit 1];
		    system.assertEquals(userProfiles.size(), 1);
		    portalUser = Test_Utility.createPortalUser(contactPortal.Id, userProfiles.get(0).Id);
		    insert portalUser;
		    //Provide access on account record by assigning portal user to intergrated group
		    GroupMember  grpMember = new GroupMember(UserOrGroupId = portalUser.Id,GroupId = grpList.get(0).Id);
		    insert grpMember;
		    
		    //Create comatrol user
		    Contact contactComatrol = Test_Utility.createContact(account.Id,2);
		    insert contactComatrol;
		    userProfiles = [Select id from Profile where Name IN ('MyComatrol - Full') limit 1];
		    system.assertEquals(userProfiles.size(), 1);
		    comatrolUser = Test_Utility.createPortalUser(contactComatrol.Id, userProfiles.get(0).Id);
		    insert comatrolUser;
		    //Provide access on account record by assigning comatrol user to intergrated group
		    grpMember = new GroupMember(UserOrGroupId = comatrolUser.Id,GroupId = grpList.get(0).Id);
		    insert grpMember;
		}
    }
}