objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Material_Code_CE__c</fullName>
        <externalId>true</externalId>
        <label>SAP_Material_Code_CE</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Area__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>TEXT(Sub_Account__r.Division__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <formula>Sub_Account__r.SAP_Account_ID__c</formula>
        <label>SAP Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sales Area Master</label>
        <referenceTo>Sales_Area_Master__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Account</label>
        <referenceTo>Sub_Account__c</referenceTo>
        <relationshipLabel>Sales Areas</relationshipLabel>
        <relationshipName>Sales_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sales_Area_Master__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sales Area ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Org_Description__c</fullName>
        <label>Sales Org Description</label>
        <picklist>
            <picklistValues>
                <fullName>1: DKRC/IC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4: MCFDGBO Sales Org.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5: MCFDDK Sales Org.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6: MCFDGBS Sales Org.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11: DIR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13: RAV-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>41: RA Sales &amp; Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55: DKAP Thermostats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>56: DKAP Surface</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>57: Pressworks A/S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>58: DKAP Plastics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>101: MX Sales Org.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>102: PLIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>103: USRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>104: CNRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>105: DEIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>107: Not used now 0101</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>109: PLCD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110: CNCD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>111: CNCC (Next Gen)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>112: CNWV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>113: CNCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>114: HKSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>116: CNDD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>117: CNSCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>118: CNSCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>119: CNIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>144: RUSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>146: KZSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150: CNCCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Sales_Org__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Account_Id__c</fullName>
        <description>Used for KNVH integration</description>
        <externalId>true</externalId>
        <label>SAP Account Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Description__c</fullName>
        <formula>Sales_Org__r.Name</formula>
        <label>Sales Org Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sales org lookup from Sales Org Master</description>
        <inlineHelpText>Sales org lookup from Sales Org Master</inlineHelpText>
        <label>Sales Org</label>
        <referenceTo>Sales_Org_Master__c</referenceTo>
        <relationshipLabel>Sales Orgs</relationshipLabel>
        <relationshipName>Sales_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration Controls</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Account_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP Account ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/Test_DataFactory.cls
public class Test_DataFactory {
        
    /* Price Book */
    public static Pricebook2 create_CE_PriceBook () {        
        Pricebook2 pb = new Pricebook2();
        pb.Name='Climate and Energy';
        pb.IsActive=true;
        return pb;
    }
    
    public static Product2 create_CE_Product(string name, string SapID) {
        Product2 p = new Product2();
        p.Name = name;
        p.SAP_Material_Code_CE__c = SapID;        
        return p;
    }
    
    public static Account create_CE_Customer (String name, String currencyIsoCode, String country, String region) {
        /* Create CE Customer */
        Account account = new Account();
        account.Name = name;
        account.Business_Org__c  = 'Climate and Energy';
        account.RecordTypeId = [SELECT Id FROM recordtype WHERE sObjectType='Account' and DeveloperName = 'Customer_CE' and IsActive=true LIMIT 1].Id;
        account.ShippingCountry=country;
        account.Country_MainAddress__c=country;
        account.CurrencyIsoCode='DKK';
        account.Danfoss_Region__c = region;        
        return account;
    }
    
    public static Sales_Area_Master__c create_SalesAreaMaster(string salesOrg, string distChannel, string division) {
        Sales_Area_Master__c sam = new Sales_Area_Master__c();        
        sam.Sales_Area_ID__c= salesOrg + '-' + distChannel + '-' + division;
        sam.Sales_Org__c = SalesOrg;
        sam.Channel__c = distChannel;        
        sam.Division__c = division;
        sam.Sales_Org_Description__c = sam.Sales_Area_ID__c;
        return sam;
    }
    
    public static Sub_Account__c create_SubAccount(string name, string SapID, Account a) {
        Sub_Account__c sa = new Sub_Account__c();
        sa.Name  = name;
        sa.SAP_Account_ID__c = SapID;
        sa.Country_Code__c = a.ShippingCountry;
        sa.City__c = a.ShippingCity;
        sa.Postal_Code__c = a.Postal_Code__c;
        sa.Street__c = a.ShippingStreet;
        sa.Account__c = a.id;
        sa.Currency__c = 'DKK: Danish krone';
        return sa;        
    }
    
    public static Sales_Area__c create_salesArea (Sub_Account__c sa, Sales_Area_Master__c sam) {
        Sales_Area__c sao = new Sales_Area__c();
        sao.Sub_Account__c = sa.Id;
        sao.Sales_Area_Master__c = sam.Id;
        sao.Sales_Area_SAP_ID__c = sa.SAP_Account_ID__c + sam.Sales_Area__c;
        return sao;
    }
    
    public static void setMaster (Account a, Sub_Account__c sa) {
        a.Master_Sub_Account__c=sa.id;
        a.CE_SAP_Account_ID__c=sa.SAP_Account_ID__c;        
    }
}