objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>3B6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Actia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argo-Hytos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axiomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bauser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bondioli &amp; Pavesi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosch Rexroth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brevini</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brosa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buchholz Hydraulik</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldaro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Captive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casappa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Command Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CrossControl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curtis Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danaher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Brown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeltaTech Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dinamic Oil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doosan Mottrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynamatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <inlineHelpText>Climate and Energy users should read CE title</inlineHelpText>
        <label>Product Line / Product Class (CE)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Product_Line_Code__c</fullName>
        <externalId>true</externalId>
        <label>SAP Product Line Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product_Line__c.object
<CustomObject>
    <description>Object to store the association between SAP Business Area, Division and Product Line</description>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hydro Gear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schwarzmueller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PL_Code__c</fullName>
        <externalId>true</externalId>
        <label>PL Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Line</label>
    <nameField>
        <label>Product Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_onProductAfterInsertCreatePBEntry.cls
/**********************************************************************************
Created By    :    Sumit Mishra
Date          :    10/14/2011
Reason        :    Test method for TestonProductAfterInsertCreatePBEntry  
**********************************************************************************/
@isTest (seealldata=true)
private class Test_onProductAfterInsertCreatePBEntry  
{
    static testMethod void unitTest1() 
    {
        List<Product_Line__c> lstPL = new List<Product_Line__c>();
        Product_Line__c PL1 = new Product_Line__c(Name='PL1',PL_Code__c='XPL1',Business_Org__c='Comatrol');
        lstPL.add(PL1);
        Product_Line__c PL2 = new Product_Line__c(Name='PL2',PL_Code__c='XPL2',Business_Org__c='Integrated');
        lstPL.add(PL2);
        Product_Line__c PL3 = new Product_Line__c(Name='PL3',PL_Code__c='XPL3',Business_Org__c='Turolla');
        lstPL.add(PL3);
        Product_Line__c PL4 = new Product_Line__c(Name='PL4',PL_Code__c='XPL4');
        lstPL.add(PL4);
        Product_Line__c PL5 = new Product_Line__c(Name='PL5',PL_Code__c='XPL5',Business_Org__c='Valmova');
        lstPL.add(PL5);
        Insert lstPL;
        List<product2> lstProduct = new List<product2>();
        product2 prod1 = new product2(Name = 'testProduct111', productCode='tp111', SAP_Product_Line_Code__c ='XPL1');
        lstProduct.add(prod1);
        product2 prod2 = new product2(Name = 'testProduct112', productCode='tp112', SAP_Product_Line_Code__c ='XPL2');
        lstProduct.add(prod2);
        product2 prod3 = new product2(Name = 'testProduct113', productCode='tp113', SAP_Product_Line_Code__c ='XPL3');
        lstProduct.add(prod3);
        product2 prod4 = new product2(Name = 'testProduct114', productCode='tp114', SAP_Product_Line_Code__c ='XPL4');
        lstProduct.add(prod4);
        product2 prod5 = new product2(Name = 'testProduct115', productCode='tp115', SAP_Product_Line_Code__c ='XPL5');
        lstProduct.add(prod5);
        product2 prod6 = new product2(Name = 'testProduct116', productCode='tp114');
        lstProduct.add(prod6);
        
        insert lstProduct;        
    }
}