objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration Controls</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Danfoss Segment</label>
        <picklist>
            <controllingField>Business_Org__c</controllingField>
            <picklistValues>
                <fullName>Cooling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/AccountFilterExtension.cls
public class AccountFilterExtension {

    private final ID objId;
    public List<SelectOption> divisionOptions { get; set; }
    public String selectedDivision { get; set; }
    public ApexPages.StandardSetController setCon { get; set; }
    
    public AccountFilterExtension(ApexPages.StandardController stdController) {
        objId = stdController.getId();
        selectedDivision = [select division__c from user where id = :UserInfo.getUserId()].division__c;
        divisionOptions = new List<SelectOption>();
  		
        Boolean foundSelectedValue = false;
        String firstValue = null;
    	for (AggregateResult ar : [select Division__c from Sub_Account__c where Account__c = :objId group by Division__c order by Division__c]) {
            String division = (String) ar.get('Division__c');
            
            if (division == null) {
                division = '';
            }
            
        	divisionOptions.add(new SelectOption(division, division));
            
            if (selectedDivision == division) {
                foundSelectedValue = true;
            }
            if (firstValue == null) {
                firstValue = division;
            }
        }
        
        if (!foundSelectedValue) {
            selectedDivision = firstValue;
        }
        
        initSetCon();
    }
    
    
    private void initSetCon() {
        List<String> fields = new List<String>();
        for (FieldSetMember field : SObjectType.Sub_Account__c.FieldSets.AccountFilterFields.getFields()) {
            fields.add(field.getFieldPath());
        }
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator('select ' + String.join(fields, ', ') + ' from Sub_Account__c where Account__c = :objId and Division__c = :selectedDivision order by Name'));
        setCon.setPageSize(3);
    }

    public List<Sub_Account__c> getSAP() {
        return setCon.getRecords();
    }
    
    public void filterSAP() {
        initSetCon();
    }

}