objects/Sub_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relation to a SFDC account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sub Accounts</relationshipLabel>
        <relationshipName>Sub_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial Compressors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heating Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss Drives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration Controls</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/Test_AccountFilterExtension.cls
@isTest
public class Test_AccountFilterExtension {
    
    public static testMethod void test() {
        Account account = Test_Utility.createAccount(0);
        insert account;
        Sub_Account__c s1 = new Sub_Account__c(Account__c = account.Id, Division__c = 'a');
        Sub_Account__c s2 = new Sub_Account__c(Account__c = account.Id, Division__c = 'a');
        Sub_Account__c s3 = new Sub_Account__c(Account__c = account.Id, Division__c = 'b');
        insert new List<Sub_Account__c> {s1, s2, s3};
        
        Test.startTest();
        
        AccountFilterExtension c = new AccountFilterExtension(new ApexPages.StandardController(account));
        System.assertEquals(2, c.divisionOptions.size());
        c.selectedDivision = 'a';
        c.filterSAP();
        System.assertEquals(2, c.getSAP().size());
    }
    
}