objects/Terms_and_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cote D&apos;Ivoire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egypt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faroe Islands</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Business_Org__c</fullName>
        <label>Business Org</label>
        <picklist>
            <picklistValues>
                <fullName>Comatrol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turolla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valmova</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Climate and Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Danfoss</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions__c</fullName>
        <description>Time when Terms And Conditions was accepted by User from Portal</description>
        <inlineHelpText>Time when Terms And Conditions was accepted by User from Portal</inlineHelpText>
        <label>Terms And Conditions</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Status__c</fullName>
        <label>Terms and Conditions Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/TermAndConditionController.cls
/**
Class : TermAndConditionController 
Description :  This class is used for displaying T&C content from T&C object based on region of that user.
Developed by : Manmeet Manethiya
Created Date : August 30, 2012

Last Modified By   : Shailendra Singh(Appirio Offshore)
Last Modified Date : 31st August 2012
Related Task	   : T-78971
Purpose			   : Display Terms & Conditions from Object based on user Country and Business org.
**/
public without sharing class TermAndConditionController {
	
	public Terms_and_Condition__c termAndCondition{get;set;}
	private User user;
	
	
	public TermAndConditionController(){
		initialize();
	}
	public Boolean hideButtons{get;set;}
	/**
	Update Terms_And_Conditions__c field of curret user with current time and Mark accepted = true
	@return PageReferance of portal home.
	*/	
	public Pagereference acceptConditions(){
			user.Terms_And_Conditions__c =  System.now();
			user.Terms_and_Conditions_Status__c = 'Accepted';
		    update user;
			return Page.PartnerPortalHome;
	}
	/**
	Update Terms_and_Conditions_Status__c = 'Declined' and Terms_And_Conditions__c with current time.
	@return send user on logout page.
	*/
	public Pagereference declineConditions(){
			user.Terms_And_Conditions__c = System.now();
			user.Terms_and_Conditions_Status__c = 'Declined';
			update user;
			return new Pagereference('/secur/logout.jsp');	
	}
	/**
		initialize page
	**/
	public void initialize(){
		Map<String,String> requestParameters = Apexpages.currentPage().getParameters();
		if(requestParameters.get('showonly') != null){
			hideButtons = true;
		}else{
			hideButtons = false;
		}
		user = [select contact.account.country__r.Name,Business_Org__c from User where id = : UserInfo.getUserId() limit 1];
		for(Terms_and_Condition__c tAndC : [select Description__c from Terms_and_Condition__c where Country__c INCLUDES  (:user.contact.account.country__r.Name) AND Business_Org__c = :user.Business_Org__c limit 1]){
			termAndCondition = tAndC;
		}		
	}
}